channel-io/bezier-react

src/components/OutlineItem/OutlineItem.stories.tsx
src/components/OutlineItem/OutlineItem.styled.ts
src/components/OutlineItem/OutlineItem.test.tsx
src/components/OutlineItem/OutlineItem.tsx
src/components/OutlineItem/OutlineItem.types.ts

setCurrentMenuItemIndex를 되살려 OutlineItem select 시 active 상태가 제대로 들어가도록 수정합니다.
[#359 issue](https://github.com/channel-io/design-system/pull/359#discussion_r631559924)에서 paul이 알려주신 버그입니다.
#359 에서 OutlineItem과 ListItem을 분리하는 과정에서, `if (isListItem(element)) {` 블럭 내의 코드가 ListItem 관련 코드라고 판단하여 지웠었습니다.
그러나 해당 코드는 OutlineItem 리스트 중 leaf(자식이 없는 Item)에 해당하는 Item에 대해 처리하는 로직이었습니다.
따라서 해당 코드 OutlineItem에 맞게 동작하도록 수정하여 되살립니다.
* OutlineItem이 leaf일 경우 setCurrentMenuItemIndex가 동작하도록 수정
* (href일 경우 동작 안함 - 기존 로직)
* 이슈 없음.

OutlineItem active 작동하게 수정

---

.storybook/main.js
babel.config.js

babel/preset-env 업데이트 및 storybook 6.2 업데이트에 따른 변경사항을 대응합니다.
* Storybook 7 부터 deprecate 되는 postcss feature 를 disable 처리 (사용하지 않음)
* babel/preset-env 업데이트에 따른 private property in class 의 loose mode 를 false 로 변경
* 이슈 없음.

Deprecation / Change 대응

---

src/components/Input/TextField/TextField.styled.ts
src/components/Input/TextField/TextField.tsx
src/components/Input/TextField/TextField.types.ts

데스크의 TagInput을 제작하며 TextField 내부 엘리먼트의 스타일을 조작/키 이벤트를 감지해야하는 상황이 생겼습니다. input 등의 스타일을 직접 수정할 수 있게 하고, keyup, keydown 이벤트 핸들러등을 추가할 수 있게 인터페이스를 수정합니다.
* 리팩토링: input active 상태를 변수로 분리 
* disableLeftWrapper, disableRightWrapper : TagInput UI가 가능해지기 위해선 LeftContent로 들어가는 Tag들과 Input이 sibling 관계에 있어야 합니다. 현재 구조에선 LeftContent가 들어가면 LeftWrapper가 무조건 감싸게 되므로, 해당 속성을 추가했습니다. (disableRightWrapper는 짝을 맞추기위해 추가. 당장 필요한 기능은 아닙니다)
* input에 className 및 interpolation 속성 추가
* 이슈 없음.

TextField 컴포넌트 확장 및 리팩토링

---

src/components/ListItem/ListItem.styled.ts
src/components/ListItem/ListItem.test.tsx
src/components/ListItem/ListItem.tsx

아래와 같은 화면에서 leftIcon이 아니라 leftContent가 와도 description이 indent 되도록 합니다.
**현재**
* CSS grid 사용하여 레이아웃 수정
* 이슈 없음.

ListItem CSS grid 사용하게 수정

---

src/components/Input/TextField/TextField.styled.ts
src/components/Input/TextField/TextField.test.tsx
src/components/Input/TextField/TextField.tsx
src/components/Input/TextField/TextFieldUtils.ts

[Figma Spec](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=6818%3A52495)
state에 따른 color 분기 처리를 수정합니다.
* state에 따른 background color 분기 처리를 수정합니다.
* text color 분기 처리를 단순화 합니다. (제이미와 싱크함)
* placeholder는 `txt-black-dark`, contents는 `txt-black-darkest`
* 이슈 없음.

TextField state에 따른 color 로직 수정

---

src/components/Button/Button.tsx
src/components/Button/Button.types.ts

다른 컴포넌트는 모두 onClick의 event type을 `React.MouseEvent`로 받고 있는데 Button 컴포넌트만 native event type으로 받고 있어 괴리가 있는 점을 수정합니다.
* Button의 onClick prop type을 `(e: MouseEvent) => void` 에서 `(e: React.MouseEvent) => void`으로 수정
(해당사항 없음)
* 이슈 없음.

Button의 onClick event parameter type 수정

---

src/components/SectionLabel/SectionLabel.test.tsx
src/components/SectionLabel/SectionLabel.tsx

버튼 컴포넌트 작성 이후 SectionLabel에서 right action에 해당하는 부분에 간략하게 prop을 던질 경우 알아서 Button으로 그리도록 로직을 변경합니다.
* `icon`, `onClick`만 줄 경우 Button 컴포넌트를 사용하여 그려냅니다. (Tertiary, Monochrome)
* `iconColor`를 사용하고 있는 경우 Button의 color variant와 일치하기 않기 때문에 기존 로직 유지
* 이슈 없음.

SectionLabel의 right action button default 렌더링을 Button으로 하도록 변경

---

src/components/Button/Button.styled.ts

Button 의 active 스타일이 focus selector 에도 걸리는 문제를 수정합니다.
https://github.com/channel-io/bezier-react/pull/89#discussion_r627929043 에서 focus 시의 스타일로 activeCSS 를 제안했는데, 이는 버튼 클릭 후 active 스타일이 빠지지 않는 문제가 있었습니다. 따라서 focus 시에는 activeCSS 를 제외하며, 추후 다른 스타일로 보강할 필요가 있습니다.
* 이슈 없음.

Button active 스타일이 focus pseudo selector 에서는 활성화되지 않도록 수정

---

src/components/KeyValueListItem/KeyValueListItem.types.ts
src/layout/Side/SidePanelContent/SidePanelContent.tsx

- SidePanelContent에 ref를 추가했습니다(UserChatSidePanel에서 사용되고 있음)
- KeyValueListITem이 HTMLAttr을 extend하게 변경했습니다
* 이슈 없음.

SidePanelContent에 ref 추가, KeyValueListItem이 HTMLArrtibutes를 extends하게 변경

---

src/components/Input/Select/__snapshots__/Select.test.tsx.snap
src/components/Text/Text.styled.ts

이전 PR에서 추가되었던 Text 컴포넌트의 `display: flex` 속성을 삭제합니다.
인라인 스타일이 블록 스타일로 변경되면서 예기치 못한 사이드 이펙트가 많아서 제거합니다.
* 변경1 세부사항
* 변경2 세부사항
* 이슈 없음.

Text의 display: flex 삭제

---

src/components/Toast/index.ts

`ToastOptions`, `ToastId type`을 export합니다.
[Toast 마이그레이션](https://github.com/channel-io/ch-desk-web/pull/7198/commits/6b85e6b485c6f3bf5d3720e5255970431a780d2e#diff-2052107ae9cf66d5cdaa0e3c37c4223a21d06d124fc9bf3983c7f15f427d58cdR20-R22) 도중 해당 type을 활용해야 하는 상황이 생겼습니다.
(지금은 아래와 같이 import 중)
```tsx
import { ToastId, ToastOptions } from '@channel.io/bezier-react/build/components/Toast/Toast.types'
```
* 이슈 없음.

ToastOptions, ToastId type export 추가

---

src/components/ListItem/ListItem.stories.tsx
src/components/ListItem/ListItem.styled.ts
src/components/ListItem/ListItem.test.tsx
src/components/ListItem/ListItem.tsx
src/components/ListItem/ListItem.types.ts
src/components/ListItem/__snapshots__/ListItem.test.tsx.snap
src/components/ListItem/index.ts

ListItem disabled 디자인 및 color props추가
colorVariant props전달시에 icon, text color가 고정이 되도록 했습니다.
**description은 active 여부와 상관없이 'txt-black-darker'로 색상이 고정됩니다.** (jamie와 싱크후 변경됨)
disabled시엔 opacity: 0.4, cursor, hover, onClick 이벤트 블락 처리를 해주었습니다.
[피그마 링크](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=10663%3A155649
)
* 이슈 없음.

ListItem disabled, color props추가

---

src/components/ListItem/ListItem.stories.tsx
src/components/ListItem/ListItem.styled.ts
src/components/ListItem/ListItem.tsx
src/components/ListItem/ListItem.types.ts
src/components/ListItem/__snapshots__/ListItem.test.tsx.snap

hover 됐을 때 뿐만 아니라, ListItem에 직접 focused 스타일을 줘야 할 필요성(키보드로 이동)이 생겨 해당 prop을 추가합니다. 
* `focused` prop 추가
* `focused={true}` 이고 포커스 가능한 상태일 경우, hover 됐을 때와 동일한 스타일을 지정
* 제대로 동작하지 않던 `href` 관련 로직을 수정
* `href` 가 빈 문자열이 아닌 문자열일 경우에만 하이퍼링크라고 판단하도록 변경 (기존엔 nil 체크)
* 하이퍼링크일 경우, active 스타일이 아이콘에만 지정되던걸 지정되지 않도록 변경
* 아이콘과 텍스트 사이의 어색한 트랜지션을 수정
* 동일한 트랜지션 옵션으로 지정하면 아이콘과 텍스트의 color가 변하는 타이밍이 약간 다르기때문에, 빠르게 변하는 아이콘의 트랜지션 duration을 한단계 높임(느리게)
* 링크로 동작하는 ListItem과 일반적인 ListItem의 공통 속성 분리 등 리팩토링 진행
* 이슈 없음.

ListItem에 focused 추가 및 개선

---

package-lock.json
package.json
rollup.config.js
src/components/Input/TextArea/TextArea.styled.ts

commonjs 의 경우 module package 대신 main package 를 우선하도록 수정합니다.
1. `react-textarea-autosize` 는 cjs, esm 빌드를 각각 제공하고 있음.
2. 두 빌드 모두 babel helper 를 포함하고 있는데, esm 은 특히 esm 버전의 helper 를 가리킴 (external deps)
3. 이때 rollup 은 esm 을 우선해서 가져오므로, `react-textarea-autosize` 또한 esm 빌드를 가져오게 됨.
4. 그러나 cjs 번들링 시 구문 자체는 cjs 형식으로 잘 감싸지만, babel helper import 문 자체까지 cjs helper import 문으로 변경하지는 않음.
5. 따라서 cjs 번들에 esm babel helper 가 들어가 있는 상황이 발생함.
6. 이것은 추후에 jest 등 esm 을 사용할 수 없는 환경에서 bezier-react 를 사용할 때 문제가 됨.
두 가지가 있습니다.
1. 사용처에서 알아서 esm 사용가능하도록 수정, 해결하는 것. 예를 들면 jest 에서 transformIgnorePatterns 옵션을 통해 babel helper 를 transpile 하도록 설정할 수 있습니다. 이는 간단하지만 실질적으로 패키지가 가지고 있는 문제점은 해결하지 않습니다.
2. cjs 빌드 시에는 cjs 로 컴파일 된 패키지를 가져오기. 이는 정확한 해결 방식이지만, `@rollup/plugin-commonjs` 의 문제로 인해 default export 를 가져올 때 버그가 발생합니다. 자세한 …

fix(rollup): commonjs bundle 방식 수정

---

src/components/Input/Select/Select.styled.ts
src/components/Input/Select/Select.test.tsx

width 100% 로 인해 children 의 너비를 존중하지 않고 있었음.

fix(select): dropdown width 100% 제거

---

package-lock.json
package.json
src/components/Avatars/Avatar/Avatar.test.tsx
src/components/Avatars/Avatar/Avatar.tsx
src/components/Avatars/Avatar/__snapshots__/Avatar.test.tsx.snap
src/hooks/useProgressiveImage.test.ts
src/hooks/useProgressiveImage.ts

Avatar 컴포넌트의 avatarUrl이 업데이트 되지 않는 문제를 수정합니다.
* 잘못된 useEffect 조건 로직을 수정했습니다. 기존 캐시된 이미지의 url과 전달받은 url이 같을 경우에만 effect 훅을 스킵하도록 변경했습니다.
* fix #497

Avatar의 avatarUrl이 업데이트 되지 않는 문제 수정

---

src/components/Input/TextArea/TextArea.styled.ts
src/components/Input/TextArea/__snapshots__/TextArea.test.tsx.snap

TextArea 스타일을 올바르게 수정합니다.
* placeholder 텍스트 사이즈 적용
* 브라우저 기본 textarea의 margin, padding을 오버라이드
* 엣지(Mac) 기준 margin은 없지만 예외 케이스를 방지하기 위해 함께 오버라이드합니다
* 이슈 없음.

TextArea 스타일을 올바르게 수정

---

src/components/Input/TextArea/TextArea.styled.ts
src/components/Input/TextArea/__snapshots__/TextArea.test.tsx.snap

TextArea 스타일이 Figma와 일치하도록 수정합니다.
* overflow시 콘테이너 꽉 차게 텍스트가 자리잡음
* 스크롤바 제거
overflow: scroll 시 padding-bottom이 무시되어 firefox에선 스타일이 깨집니다.

fix(textarea): TextArea 스타일 수정

---

src/components/Toast/Toast.stories.tsx
src/components/Toast/Toast.styled.ts
src/components/Toast/Toast.test.tsx
src/components/Toast/Toast.types.ts
src/components/Toast/ToastElement.tsx
src/components/Toast/ToastProvider.tsx

Toast가 Modal dim에 가리는 등의 문제가 있어 해결합니다.
* Toast z-index를 가능한 최대 값으로 설정
* addToast에 zIndex를 실어 표현할 수 있게 수정
* storybook에 zIndex 테스트를 할 수 있는 코드 추가
* 이슈 없음.

fix(toast): toast z-index 수정 및 관리 방식 추가

---

src/components/Input/TextField/TextField.styled.ts

~~좌측 컴포넌트(`leftComponent`) 가 없을 땐~~ 양옆 패딩이 12px 이 되도록 수정합니다.
- 패딩 수정
* 이슈 없음.

TextField 스타일을 올바르게 수정

---

src/components/Input/Select/Select.tsx
src/components/Input/Select/Select.types.ts
src/components/Input/Select/index.ts
src/components/Input/TextField/TextField.tsx

현재 드롭다운을 닫기 위해선 트리거를 클릭하거나, 드롭다운이 열렸을 때 외부를 클릭하는 방법 두 가지 방법이 있습니다. 
라디오 버튼의 동작처럼 여러가지 선택을 하는 케이스라면 문제가 없지만, 체크박스 버튼의 동작처럼 한 번의 선택만을 하는 케이스에선 UX가 그다지 좋지 않습니다. **아이템 클릭 -> 드롭다운 닫힘** 이 아니라, **아이템 클릭 -> 드롭다운 외부 클릭 -> 드롭다운 닫힘** 이 되기 때문입니다.
Select 컴포넌트에선 드롭다운 안에 들어가는 내용물에 대해선 알고 있지 않기 때문에, 사용처에서 Select 컴포넌트를 제어할 수 있도록 내부 메서드들을 `useImperativeHandle` 을 사용해서 외부로 노출했습니다.
- 참고: #511
* `useImperativeHandle` 로 `handleClickTrigger`, `handleHideDropdown`, `getDOMNode` 메서드를 외부로 노출합니다
* 사용처에서 `ref` 를 통해 DOM node를 가져올 수 없게 되었으므로, `getDOMNode` 메서드를 외부로 함께 노출하여 사용처에서 DOM node를 가져올 수 있도록 합니다
*  `SelectRef` 타입을 추가합니다
* 사용할 수 없게 된 `useMergeRef` 를 제거합니다. `useMergeRef` 의 정확한 타입 추론을 위해 사용되었던 콜백 ref 또한 `useRef` 로 변경합니다
* 이슈 없음.

Select 컴포넌트를 제어하는 메서드를 외부에서도 사용할 수 있도록 변경

---

src/components/Avatars/Avatar/Avatar.styled.ts
src/components/Avatars/Avatar/Avatar.tsx
src/components/Avatars/CheckableAvatar/CheckableAvatar.styled.ts

smooth corner 관련해서 스타일링을 위해 `z-index: 1` 이 AvatarWrapper 컴포넌트에 들어가 있었습니다. 이 부분 때문에 사용처에서 의도치않게 Avatar 컴포넌트가 위로 뜨는 현상이 발생해서 `z-index: 0` 으로 수정합니다.
`z-index: 1` 은 내부 `Wrapper` 컴포넌트를 추가로 만들고 스타일링해서, 내부에서 쌓임 맥락을 추가로 생성하는 방식으로 해결했습니다.
* 일부 스타일 컴포넌트 변수명을 변경합니다
* StyledAvatar -> AvatarImage 
* 이슈 없음.

Avatar가 사용처에서 의도치않게 위에 쌓이는 문제 수정

---

src/components/OutlineItem/OutlineItem.styled.ts
src/components/OutlineItem/OutlineItem.test.tsx

OutlineItem의 height, color를 기본 디자인에 맞게 수정합니다.
1. 현재 모든 Navigations 내부에서 쓰이는 OutlineItem는 height가 28px이어야 합니다. 32px을 쓰는 경우는 28px보다 적기에 28px이 기본 적용되도록 합니다.
2. OutlineItem에서 쓰이는 color는 txt-black-darker가 아닌 txt-black-darkest여야 합니다.

fix(outlineitem): height, color를 디자인에 맞게 수정

---

src/components/SectionLabel/SectionLabel.types.ts

SectionLabelHelpProps에 커스텀한 tooltipContent를 넣어야 할 필요가 있습니다
하지만 이 prop의 type이 Tooltip의 content prop과 달라서, 동작에 문제는 없지만 타입이 맞지 않기에 이를 수정합니다
* 이슈 없음.

fix(sectionlabel.types.ts): sectionLabelHelpProps['tooltipContent']의 타입을 Tooltip Content 타입과 맞춤

---

src/components/Avatars/CheckableAvatar/CheckableAvatar.stories.tsx
src/components/Avatars/CheckableAvatar/CheckableAvatar.styled.ts
src/components/Avatars/CheckableAvatar/CheckableAvatar.tsx
src/components/Avatars/CheckableAvatar/CheckableAvatar.types.ts

CheckableAvatar는 체크된 상태의 background color가 일반적으로 bgtxt-green-dark로 지정되지만, 일부 경우에는 다르게 지정되어야 하기에 커스텀 가능하도록 변경합니다.

fix(checkableavatar): checkableAvatar가 체크된 상태일때 background color를 커스텀 가능하도록 변경

---

src/layout/Navigations/NavigationContent/NavigationContent.tsx

Main Nav를 숨기는 chevron-double의 아이콘 색상을 darkest -> darker으로 변경
https://www.notion.so/channelio/e508731aa79f48aeb0ebfa16d3fd74e7

Main Nav를 숨기는 chevron-double의 아이콘 색상을 darkest -> darker으로 변경

---

src/components/Avatars/Avatar/Avatar.styled.ts
src/components/Avatars/Avatar/__snapshots__/Avatar.test.tsx.snap

기존에 컬러 시스템 업데이트하며 아바타 기본 배경, 보더에 투명도 있는 흰색이 지정되어서 아래 색상이 투과되어 보였습니다.
투명도가 없는 #FFF 흰색으로 변경합니다.
* 이슈 없음.

fix(avatar): 아바타의 background, border 색상을 투명도 없는 색상으로 변경

---

src/components/KeyValueListItem/KeyValueListItem.styled.ts
src/components/KeyValueListItem/KeyValueListItem.test.tsx
src/components/KeyValueListItem/KeyValueListItem.tsx
src/components/KeyValueListItem/KeyValueListItem.types.ts
src/components/KeyValueListItem/__snapshots__/KeyValueListItem.test.tsx.snap

KeyValueItem의 multine 속성은 Key와 Value를 뉴라인으로 두는 옵션입니다.
multiline일 경우에는 Value Row의 Padding bottom이 6px이어야 합니다.
multiline일 경우에는 Key Row는 multiline이 아닐때와 동일해야 합니다
이를 위해 최상단에 걸려 있던 padding을 한 단계씩 내렸습니다
* 변경1 세부사항
* 변경2 세부사항
* 이슈 없음.

fix(keyvaluelistitem): multiline일때의 padding 미세 조정

---

src/components/OutlineItem/OutlineItem.styled.ts

| AS-IS | TO-BE |
| -- | -- |
| <img width="285" alt="스크린샷 2021-06-10 오후 6 55 08" src="https://user-images.githubusercontent.com/33291896/121506603-d36e8f80-ca1e-11eb-84d4-57dc547a50ee.png"> | <img width="290" alt="스크린샷 2021-06-10 오후 6 57 36" src="https://user-images.githubusercontent.com/33291896/121506636-da959d80-ca1e-11eb-8dd6-19e8da8101d6.png"> |
(active인 `푸시 메시지 설정` 을 hover중인 상태)

fix(outlineitem): active인 OutlineItem을 hover하면 background가 덮어씌워지는 문제 수정

---

src/components/OutlineItem/OutlineItem.styled.ts
src/components/OutlineItem/OutlineItem.tsx
src/components/OutlineItem/OutlineItem.types.ts

OutlineItem의 기존 사용처에는 두 가지 종류가 있었습니다.
| chevron과 아이콘이 동시에 사용되는 경우 | chevron과 아이콘이 서로 배타적인 경우 |
| -- | -- |
| <img width="275" alt="스크린샷 2021-06-09 오후 1 48 28" src="https://user-images.githubusercontent.com/25701854/121295121-7c3ac300-c929-11eb-96cb-ed9c24007b7f.png"> | <img width="234" alt="스크린샷 2021-06-09 오후 1 48 22" src="https://user-images.githubusercontent.com/25701854/121295113-79d86900-c929-11eb-962b-61fb750e8c99.png"> |
기존 구현에는 chevron 영역을 reserve 해 놓기 때문에 2번째 케이스의 경우 올바른 스타일이 나타나지 않습니다. 기존 prop인 `chevronClassName`, `chevronInterpolation`은 reserve한 영역 안쪽의 chevron icon 자체에 적용되기 때문에 이것을 사용해서는 구현할 수 없습니다. 따라서 새로운 prop을 추가합니다.
+) prop 추가에 관한 고민: chevron은 nested될 수 있다는 특징과 이어지는, OutlineItem의 정체성을 나타내는 feature 중 하나인데 이것을 disable하는 케이스는 사실 다른 컴포넌트로 작성되어야 하는 것이 아닌가? 라는 …

OutlineItem의 chevron 영역을 제거할 수 있도록 prop 추가

---

src/components/Button/Button.styled.ts
src/components/Button/Button.tsx

기존 로직은 monochrome 버튼에 대해 styleVariant에 따라 텍스트와 아이콘 색의 분기가 이루어집니다. 이는 실제 스펙과 다릅니다.
다음과 같이 계산되어야 합니다.
기본: txt-black-darkest
- S 이하 크기 버튼에 대해: 위보다 한 단계 낮음
- 버튼이 hover되면: 기본 색으로 복원
기본: 계산된 텍스트 색보다 한 단계 낮음
* 이슈 없음.

fix(button): correct Button colors according to its size

---

package.json

CircleCI 에서 jest 가 메모리 부족으로 실패하는 경우를 해결합니다.
* maxWorkers 를 2로 제한합니다.
https://support.circleci.com/hc/en-us/articles/360038192673-NodeJS-Builds-or-Test-Suites-Fail-With-ENOMEM-or-a-Timeout

ci(jest): maxWorkers 를 제한하여 CI 메모리 부족 현상을 해결 (시도)

---

src/components/Avatars/AvatarGroup/AvatarGroup.styled.ts
src/components/Avatars/AvatarGroup/AvatarGroup.tsx

EllipsisCount의 좌측 마진이 제대로 적용되도록 변경합니다.
- 잘못된 스타일 변경
* 이슈 없음.

AvatarGroup의 EllipsisCount 잘못된 스타일 수정

---

src/components/Tooltip/Tooltip.styled.ts
src/components/Tooltip/Tooltip.tsx
src/foundation/Mixin.test.tsx
src/foundation/Mixins.ts

[Notion issue](https://www.notion.so/channelio/51466cfb272440e993448228cad3ff2a)
[관련 논의 스레드](https://desk.channel.io/root/groups/Bezier-62019/60c8574eb94d851ca4aa)
* Tooltip에 20줄 제한 ellipsis를 적용합니다.
* ellipsis 함수 타입을 재정의합니다.
* 불필요한 파라미터 unit 삭제
* 두번째 파라미터(lineHeight)를 첫 번째 파라미터(line 수)에 따라 conditional하게 받도록 수정.
|:---:|:---:|
|<img width="450" alt="스크린샷 2021-06-15 오후 5 24 45" src="https://user-images.githubusercontent.com/16368822/122021299-8153b280-ce00-11eb-9d0e-4f9dc6802d0e.png">|<img width="450" alt="스크린샷 2021-06-15 오후 5 25 01" src="https://user-images.githubusercontent.com/16368822/122021284-7dc02b80-ce00-11eb-88db-8ad44efd1ca6.png">|
* 이슈 없음.

Tooltip에 줄 수 제한 및 ellipsis 적용

---

src/components/Overlay/Overlay.stories.tsx
src/components/Overlay/Overlay.tsx

fix #515
https://user-images.githubusercontent.com/33291896/122337286-1da0c500-cf79-11eb-8498-7d6099f164da.mp4
https://user-images.githubusercontent.com/33291896/122337297-209bb580-cf79-11eb-82b2-b8a952abc892.mp4
* OverlayContainer이 현재 React.FunctionalComponent 형식인데, 이러면 OverlayContainer가 변경되어도 react에도 제대로 포착하지 못하는 것으로 보임. 따라서 unmount 후 mount가 일어나서 부작용이 발생함.
중복 코드를 최소화하는 코드였기에 기본적인 React.ReactNode를 사용하도록 변경해도 문제는 없음.
* 이슈 없음.

fix(overlay): overlay의 prop이 변하면 children이 remount되는 문제 수정

---

src/hooks/useResizingHandlers.ts
src/layout/Navigations/NavigationArea/NavigationArea.tsx
src/layout/Navigations/NavigationArea/NavigationArea.types.ts
src/layout/Navigations/NavigationContent/NavigationContent.tsx
src/layout/redux/LayoutActions.ts
src/layout/stories/LayoutPlayground/LayoutPlayGround.stories.tsx

initialKey일때만 onChangeWidth를 불리게 수정합니다.
해당 이슈를 해결합니다  - [유저챗 리스트의 최소너비 버그](https://www.notion.so/channelio/e6adaac5429b4a2ea4b0d2bf4d6eaf7a)
as-is|to-be
---|---
* 이슈 없음.

fix(useresizinghandler.ts): onChangeWidth가 인접 column 을 움직일 때에도 불리던 문제를 수정

---

src/index.ts

inputWrapperStyle을 외부에서 사용할 수 있도록 export 합니다.
아래와 같이 desk의 커스텀한 컴포넌트에서 사용합니다.
* 이슈 없음.

feat(input): inputWrapperStyle을 외부에서 사용할 수 있도록 export

---

src/components/TagBadge/TagBadgeCommon/constants/TagBadgeVariant.ts

사용처에서 정확한 타입을 사용할 수 있도록 태그, 뱃지 컬러 프리셋의 타입을 `SemanticNames` 에서 리터럴 타입으로 변경합니다.
없음
없음
* **See also**: https://github.com/channel-io/ch-desk-web/pull/7292#discussion_r639641315

feat(tag): 태그, 뱃지 프리셋의 타입을 정확하게 수정

---

src/components/ListItem/ListItem.tsx

content가 `<Title>` 안에 갇혀 TitleWrapper 영역을 모두 사용하지 못하고 있었습니다.
사용처에서 좀 더 자유로운 스타일링 가능하도록 수정합니다.
* content가 String일 때만 Title 안에 렌더링하게 수정
* 이슈 없음.

fix(listitem): content가 string이 아닐 때, TitleWrapper 영역 모두 차지하도록 수정

---

package.json
src/components/KeyValueListItem/KeyValueListItem.tsx
src/components/KeyValueListItem/KeyValueListItem.types.ts
src/components/KeyValueListItem/__snapshots__/KeyValueListItem.test.tsx.snap

아래처럼 사용해야 하는 경우가 있어 string뿐만 아니라 ReactNode도 받을 수 있게끔 prop을 확장했습니다
additional: jest snapShot 업데이트 스크립트를 추가
* 이슈 없음.

KeyValueListItem의 keyContent prop을 확장함

---

src/components/Checkbox/Checkbox.styled.ts

사용처에서 원하지 않게 체크박스의 배경색이 지정되는 경우가 생겨, 체크박스의 기본 배경색을 투명에서 흰색으로 변경합니다(시안과 동일).
없음
* 이슈 없음.

fix(checkbox): 체크박스의 기본 배경색을 투명에서 흰색으로 변경

---

src/components/KeyValueListItem/KeyValueListItem.tsx
src/components/KeyValueListItem/__snapshots__/KeyValueListItem.test.tsx.snap

isStringNumber의 의미를 잘못 파악하고 사용하여 isString으로 변경함
string or number인줄 알았는데, number인 string을 찾아내는 것이어서 isString으로 변경합니다.
#553 에서 잘못 작업된 버그 입니다
keyContent에 stirng을 넣었을때도 이제 잘 작동합니다
* 이슈 없음.

fix(keyvaluelistitem): isStringNumber의 의미를 잘못 파악하고 사용하여 isString으로 변경함

---

src/components/Avatars/CheckableAvatar/CheckableAvatar.styled.ts
src/components/Avatars/CheckableAvatar/CheckableAvatar.tsx

CheckableAvatar 컴포넌트의 디자인을 최신 버전으로 업데이트합니다.
[피그마](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=2098%3A473) 시안을 참고해주세요.
* 체크 아이콘의 크기를 비율이 아닌 상수로 지정합니다.
* 체크 시 기본 배경색상을 `bgtxt-green-dark` 에서 `bgtxt-green-normal` 로 변경합니다.
* 이슈 없음.

CheckableAvatar 컴포넌트 최신화

---

src/components/Avatars/AvatarGroup/AvatarGroup.styled.ts
src/components/Avatars/AvatarGroup/AvatarGroup.tsx

AvatarGroup 컴포넌트를 시안에 맞게 최신화하고, 수정/리팩토링을 진행합니다.
- 기존 아바타 사이즈로 고정된 width의 Count를 글자의 크기만큼 가변너비를 가지되, 사이즈별 다른 우측 패딩을 가지도록 변경
- className을 받을 수 있도록 변경
- ellipsisIcon의 색상을 투명도 없는 흰색으로 변경
- children으로 넘긴 Avatar의 key가 없을 경우에만 AvatarGroup에서 key를 지정해주도록 변경
없음
* 이슈 없음.

AvatarGroup 컴포넌트 최신화

---

src/components/Overlay/Overlay.tsx

#552 에서 ref의 접근 인터페이스가 달라져 데스크에서 Overlay에 ref로 접근하여 사용하던곳에서 문제발생함
다시 이전처럼 ref 인터페이스 되돌림
* 변경1 세부사항
* 변경2 세부사항
* 이슈 없음.

fix(overlay): 오버레이 ref가 달라져 생긴 사이드이펙트 수정

---

src/components/Avatars/Avatar/Avatar.styled.ts
src/components/Avatars/Avatar/Avatar.tsx
src/components/Avatars/Avatar/__snapshots__/Avatar.test.tsx.snap
src/components/Header/Header.styled.ts
src/components/Header/Header.tsx
src/foundation/Mixins.ts

기존 `smoothCorners` interpolation을 보면, prop에 backgroundImageUrl을 포함하고 있습니다. 이는, 사용처에서 서로 다른 avatarUrl 하나마다 classname 하나가 만들어진다는 것을 의미합니다. 실제로 profiler를 통해 유저챗 화면에서 fetch more를 할 때 측정해 보면, 새로운 유저의 아바타가 필요할 때마다 classname을 하나 만들고, CSSOM에 추가한 후 (`insertRules`), css가 업데이트되었으므로 전체 스타일을 재계산하는 연산이 실행됩니다. 매번 새로운 avatarUrl이 추가될 때마다 비싼 computation이 실행됩니다.
이를 개선하여, avatarUrl은 styled component의 prop으로 전달하지 않도록 합니다. 대신, element에 attribute로 전달하고 `var()` 함수를 통해 읽도록 합니다. (`attr()`는 대부분의 브라우저에서 지원하지 않아 동작하지 않더라구요)
**측정 1**
- 측정 방법: 유저챗 전체, 열림 목록에서 idle 상태 될 때까지 기다렸다가 측정 시작, 아래로 스크롤 하면서 fetch more 5번 수행
- 측정 조건: production server, build
| AS-IS (production) | TO-BE |
| -- | -- |
| <img width="969" alt="스크린샷 2021-07-05 오후 4 05 23" src="https://user-images.githubusercontent.com/25701854/124433784-17e714 …

perf(smoothcorners): do not generate new classname per image url

---

src/components/Toast/Toast.styled.ts
src/components/Toast/ToastController.tsx
src/foundation/Transition/index.ts

setTimeout 등에서 TransitionDuration의 값을 사용할 때 용이하게 하기 위해서 string 대신 number로 정의합니다.
* `TransitionDuration` 수정 `"300ms"` -> `300`
* `ToastController`에서 `TransitionDuration`에 따라 parsing 하던 로직 제거
close #554

TransitionDuration enum을 string 대신 number로 정의

---

src/components/Checkbox/Checkbox.styled.ts
src/components/Checkbox/Checkbox.test.tsx
src/components/Checkbox/Checkbox.tsx
src/components/Checkbox/Checkbox.types.ts

Checkbox 컴포넌트를 디자인 시안에 맞게 최신화합니다.
- 마우스 호버 시 체크 아이콘의 색상은 변하지 않도록 수정합니다.
- 수도 엘리먼트로 구현한 체크 아이콘을, Icon 컴포넌트로 구현하도록 변경합니다.
- 보더의 끝에 Radius가 있는 아이콘이라, 수도 엘리먼트의 Border로는 표현하기가 어렵습니다. 디자인 시안과 오차 없이 동일하게 만들고자 했습니다.
- border-radius를 4-> 6px 로 변경합니다.
- border의 색상을 시안과 동일하게 변경합니다.
- `*실제 크기는 18이나, margin을 1로 잡아 전체 크기가 20이 되게 합니다.` 를 적용합니다. 
- margin: 1px 을 추가합니다.
- Content와의 간격은 9 -> 8px로 변경합니다.
- 불필요한 코드 제거 & 리팩토링
* 이슈 없음.

Checkbox 컴포넌트 디자인 최신화

---

src/components/Avatars/Avatar/__snapshots__/Avatar.test.tsx.snap
src/foundation/Mixins.ts
src/worklets/smoothCorners/smoothCorners.ts

원래 아래 사진처럼 어정쩡하게 작동하고 있었습니다 😢 
#561 에서 수정되면서 어정쩡함이 해소되었습니다. 그러면서 pseudo element의 background image가 제대로 적용되지 않았습니다.
1. smoothCorners mixin에서, `hasBackgroundImage` prop이 smooth corners가 적용되었을 때 잘 존중되도록 수정
2. paint worklet에서, border-image-source attribute가 주어지지 않았을 때를 올바르게 구별하도록 수정
- 기본값이 falsy한 value가 아니라, 'none' 값을 가지는 CSSKeywordValue 이기 때문에 guard를 통과합니다. 따라서 drawImage에서 에러가 발생합니다.
- 올바른 값이 주어진다면 CSSImageValue의 instance 여야 하므로 그 조건으로 수정합니다.
* #561

CheckableAvatar 등, background image가 없는 smooth corners가 잘 작동하지 않는 문제 수정

---

src/worklets/smoothCorners/smoothCorners.ts

화면에 그려야 하는 smooth corner가 많아지면, path를 계산하는 superellipse 함수의 실행시간이 부담이 됩니다!
(위 사진에서 "points" 함수)
주어진 argument에 따라 결과를 캐싱해두어 같은 크기의 smooth corner를 paint한다면 중복 계산이 이루어지지 않도록 합니다.
- superellipse 함수 실행 결과를 argument에 따라 캐싱
위 사진은 캐싱 후.
* 이슈 없음.

perf(smoothcorners): cache smoothcorner path computation result

---

src/components/TagBadge/Badge/Badge.tsx
src/components/TagBadge/Tag/Tag.tsx
src/components/TagBadge/TagBadgeCommon/TagBadge.styled.ts
src/foundation/FoundationStyledComponent.tsx
src/types/InjectedFoundation.ts

|:---:|:---:|
다른 색상에 대해 다른 className을 generate|다른 색상도 같은 className을 generate
- foundation을 react component 내부에서 사용하기 위한 useFoundation을 작성했습니다.
styled component의 useTheme과 동일한 역할을 합니다.
- Tag
* 이슈 없음.

Tag, Badge 컴포넌트의 ClassName생성을 줄이는 작업

---

src/components/Input/Select/Select.styled.ts
src/components/Input/Select/Select.tsx
src/components/Input/Select/Select.types.ts

현재는 Select의 Dropdown에 스타일을 지정할 수 있는 방법이 없습니다.
예로 들어, 아래와 같은 NotificationSettingSelect에서 두번째 ListItem처럼 word-wrap되는 문자열이 없다면 두번째 사진과 같이 width가 줄어듭니다.
이때, Dropdown에 `width: 100%;`를 지정하게 되면 아래와 같이 됩니다.
디자인과 구현을 맞추기 위해서 해당 변경이 필요하여 변경하였습니다.

feat(select): select에 dropdown의 스타일을 지정하는 dropdownInterpolation prop 추가

---

src/components/Toast/Toast.styled.ts
src/components/Toast/ToastElement.tsx

Electron에서만 Toast의 각 line에서 말줄임표가 나타나는 현상이 있습니다.
텍스트가 overflow 되면 말줄임표가 나타나는 것인데, 일반적인 상황이라면 텍스트가 overflow 되기 전에 개행이 되기 때문에 이런 현상은 없어야 합니다.
정확하진 않지만 일렉트론에서 텍스트 element 범위를 정확히 잡지 못하는 것이 아닌가 하는 의심을 하고 있습니다.
이 수정에서는 약간의 트릭을 써서 해당 문제를 해결합니다.
Mixin의 ellipsis에서 주는 `overflow: hidden을` 무시하게 하고, 한 단계 위 부모에서 `overflow: hidden`을 줍니다.
이렇게 하면 5 줄 이상은 보이지 않으면서 (_아마_)일렉트론 버그로 인한 텍스트 오버플로우는 사라집니다.
|as-is|to-be|
|:---:|:---:|
|<img width="313" alt="스크린샷 2021-06-26 오후 2 28 42" src="https://user-images.githubusercontent.com/16368822/123503131-e07cb700-d68b-11eb-9b47-82774bb0f546.png">|<img width="313" alt="스크린샷 2021-06-26 오후 2 28 03" src="https://user-images.githubusercontent.com/16368822/123503133-e2df1100-d68b-11eb-8606-60d0ace6e09c.png">|
직접 build해서 desk `node_modules`에 넣고, `npm run …

Toast line break 관련 버그 수정

---

src/components/Button/Button.styled.ts
src/components/Button/Button.tsx
src/components/Button/Button.types.ts
src/foundation/Colors/Theme/presets/LightTheme.ts

- ButtonColorVariant 추가 (MonochromeLight, MonochromeDark, Orange, Pink, Purple)
- 기존 ButtonColorVariant.Monochrome은 deprecate
- 기존의 Monochrome variant는 이상한 예외처리가 있었습니다. (size S, XS의 경우 색을 한 단계 내려주어야 했음) 색은 color, style variant에만 의존하는 것이 자연스러웠기 때문에 Monochrome을 Light/Dark로 나누어 주는 방향으로 논의가 되었습니다.
- style 결정 과정에서 중복 코드를 줄이기 위해 구조를 변경했습니다.
* 이슈 없음.

feat(button): add new color variants

---

src/components/Input/Select/Select.styled.ts
src/components/Input/Select/Select.tsx
src/components/Input/Select/Select.types.ts
src/components/Input/Select/__snapshots__/Select.test.tsx.snap

디자인 시안에 맞게 Icon과 Text 색상을 최신화하고, 색상과 이벤트 핸들러를 외부에서 주입할 수 있도록 수정합니다
* 이슈 없음.

feat(select): select 컴포넌트에 스타일 관련 속성과 이벤트 핸들러를 주입할 수 있도록 수정

---

src/components/Input/Select/Select.tsx
src/components/Input/TextField/TextField.tsx

```typescript
useImperativeHandle(forwardedRef, () => ({ ... }))
```
위와 같은 구문을 사용하면, 매 렌더링마다 handle object가 새로 생성됩니다.
```typescript
const [handle, setHandle] = useState<SomethingHandle>()
<SomeComponent ref={setHandle} ...>
```
따라서 위와 같은 구문을 사용하면 무한루프에 빠집니다 😢 
handle object를 memoize하여 위와 같은 활용에서 무한루프가 일어나지 않도록 합니다.
* 이슈 없음.

fix: reference of imperative handle changes on every render

---

src/components/Input/TextArea/TextArea.stories.tsx
src/components/Input/TextArea/TextArea.test.tsx
src/components/Input/TextArea/TextArea.tsx
src/components/Input/TextArea/TextArea.types.ts
src/components/Input/TextArea/index.ts

TextArea의 rows설정을 기존에 숫자를 prop으로 넣어 변경해 주던 것을 TextAreaSize를 통해서 하도록 변경하였습니다.
* TextArea.tsx의 maxRows, minRows prop을 삭제, 대신 size prop을 받도록 변경
* size prop은 TextAreaSize enum만을 받아들이도록 제한
* size prop은 mapping되어 maxRow로 설정됨
* minRow는 5로 고정됨
* 이슈 없음.

TextArea의 rows설정을 TextAreaSize를 통해서 하도록 변경

---

src/layout/Main/Main.styled.ts

Main 컴포넌트의 `overflow-x: scroll` 속성을 `auto` 로 변경합니다. 
윈도우 환경의 대부분의 브라우저에서 불필요하게 가로 스크롤 바를 만드는 문제를 해결합니다.
없음
* 이슈 없음.

fix(main): 윈도우 환경에서 메인뷰 가로스크롤을 항상 표시하지 않도록 수정

---

.husky/commit-msg
commitlint.config.js
package-lock.json
package.json

현재 bezier-react의 배포는 semantic-release tool을 이용하여 이루어지고 있습니다.
semactic-release는 커밋 format을 참고하여 버저닝을 하는데, 이 때문에 cz-cli라는 툴을 이용하여 commit format을 강제하고 있습니다.
지금은 아무렇게나 커밋이 가능하기 때문에 가끔씩 실수가 나고는 합니다.
그냥 `git commit`을 통한 커밋을 불가능하게 린트를 추가합니다
- commit lint library 추가
- commit lint를 husky에 추가
https://github.com/conventional-changelog/commitlint
https://github.com/semantic-release/semantic-release#commit-message-format

commitlint를 추가하여 cz를 제외한 방법으로는 커밋하지 못하게 변경

---

src/components/Input/TextField/TextField.styled.ts
src/components/Input/TextField/TextField.tsx
src/components/Input/TextField/TextFieldUtils.ts

기존에 8px로 고정되어있던 border-radius값을 size가 XL일땐, border-radius가 12px가 될 수 있도록 변경했습니다.
* size에 따른 border-radius를 변경하기 쉽도록 util function을 만들어 추가했습니다.
* 해당 util function을 통해 border-radius css가 주입됩니다.
* border-radius는 foundation의 Rounding을 사용했습니다.
* 이슈 없음.

TextField에서 size가 XL일때, border-radius가 12px로 적용되도록 수정

---

src/components/OutlineItem/OutlineItem.styled.ts
src/components/OutlineItem/OutlineItem.test.tsx
src/components/OutlineItem/OutlineItem.tsx
src/components/OutlineItem/OutlineItem.types.ts

ListItem과 마찬가지로, 키보드 동작 관련 a11y를 보강하기 위해 focused prop을 추가합니다.
- `focused = true`로 주어진 경우, 기존의 mouse hover와 동일한 스타일이 적용됩니다.
- `focused = false`로 주어진 경우, 변화 없음
* 이슈 없음.

OutlineItem 컴포넌트에 "focused" prop 추가

---

src/layout/Main/Main.styled.ts

현재는 70px을 넘는 header가 없습니다.
하지만 더 넓은 header를 사용하는 디자인이 아래와 같이 추가되어, 70px 이상인 header를 적용할 수 있도록 수정합니다.
As-is | To-be
----- | -----

feat(header): header 크기가 70px을 넘을 수 있도록 변경

---

src/foundation/Mixins.ts

파일에서 lodash-es 가 아닌 devDependency lodash 를 임포트해 빌드에서 오작동이 됐던 버그 수정
- 베지어 사용처에서 lodash 관련 에러가 나서 화면이 로드가 되지 않는 버그 있었음.
* src/foundation/Mixin.ts 에서 lodash(devDependency) 를 import 하던 것을 lodash-es(dependency) 로 바꿨습니다.
* 이슈 없음.

fix(foundation/mixins.ts): 잘못된 lodash 모듈 임포트 수정

---

.storybook/preview.js
src/foundation/FoundationStyledComponent.tsx
src/foundation/Mixins.ts
src/index.ts

기존에 Smooth Corners 적용을 위해 EnableCSSHoudini를 bezier-react의 entry인 index.ts에서 실행시켜 주고 있었습니다. 
이것은 side effect가 유발되는 행동이기 때문에 트리 쉐이킹하면서 떨어져 나가면 안됩니다.
하지만 트리 쉐이킹을 돕기 위해 package.json의 sideEffect value를 false로 해두었기 때문에 컨슈머 모듈에서는 이 라이브러리가 side effect free 하다고 판단하게 됩니다. 그래서 EnableCSSHoudini가 실행되지 않는 문제가 있었고 이를 수정합니다.
이제 bezier-react의 entry가 아니라 FoundationProvider를 사용하게 된다면 EnableCSSHoudini가 실행됩니다.
npm pack 하여 데스크에 설치하여 잘 보이는 것 확인
https://developer.mozilla.org/en-US/docs/Web/API/PaintWorklet#use_a_paintworklet 
우리는 위 방식처럼 paintworklet을 적용하고 있는데 CSSHoudini를 적용하지 않아도 paint는 support되는 속성이라 fallback 처리가 되지 않음

fix(houdini): remove side effect of enablecsshoudini and move it to foundation provider

---

src/components/Banner/Banner.stories.tsx
src/components/Banner/Banner.styled.ts
src/components/Banner/Banner.test.tsx
src/components/Banner/Banner.tsx
src/components/Banner/Banner.types.ts

배너 컴포넌트에 데스크의 translateWithInnerHtml를 사용한 번역을 넘겨야하는 상황이 생기게 되었습니다. (번역 값에 bold태그와 같이 html을 사용하는 경우)
text prop은 string만을 받으므로 text prop을 ReactNode까지 받을 수 있도록 확장했습니다. 
@제이미 께 추후 배너 컴포넌트에 아이콘이나 텍스트외 다른 컴포넌트가 들어 갈 수 있는 상황에 대해 여쭈어보고 현재로선 딱히 생각나는 케이스가 없다고 답변주셔서 children으로 넘기지 않고 text prop을 확장시켰습니다.
* 변경1 세부사항
* 변경2 세부사항
#600

배너 컴포넌트에 text prop을 string과 ReactNode를 받을 수 있도록 확장

---

src/components/ListItem/ListItem.styled.ts

- ListItem의 RightContent가 영어가 아닐 경우 줄바꿈 되는 버그를 수정했습니다.
- 변경 전
- 변경 후
* #580

listItem의 RightContent가 강제 줄바꿈 되는 버그 수정

---

src/components/Input/TextArea/TextArea.types.ts
src/components/Input/TextField/TextField.types.ts

TextField와 TextArea는 `React.TextareaHTMLAttributes<HTMLTextAreaElement>`, `React.InputHTMLAttributes<HTMLInputElement>` 타입을 extend하고 있습니다.
HTMLInputElement, HTMLTextAreaElement 모두 readOnly와 disabled를 가지고 있지만 해당 타입 파일에 명시되어 있지 않아서 해당 프롭이 있는 것을 잘 인지하지 못하는 문제가 있어서 이를 명시하고 각 프롭의 순서를 정리했습니다
* 이슈 없음.

refactor(input.type): TextField와 TextArea 타입에서 disabled, readOnly를 명시하고 타입을 중요도 순서로 정리

---

src/components/Banner/Banner.test.tsx
src/components/Banner/Banner.tsx

배너의 링크 텍스트의 typography가 잘못 설정된 부분을 수정합니다. (15 -> 14)
| AS-IS | TO-BE |
| -- | -- |
| <img width="331" alt="스크린샷 2021-11-18 오후 1 15 01" src="https://user-images.githubusercontent.com/25701854/142351484-e3301004-236f-4d87-b46c-20f4d7e1cfe8.png"> | <img width="314" alt="스크린샷 2021-11-18 오후 1 15 45" src="https://user-images.githubusercontent.com/25701854/142351506-a210e5e1-eec2-47ff-92d5-ae968af61235.png"> |
* 이슈 없음.

fix(banner): correct Banner link text style

---

src/components/Input/TextArea/TextArea.stories.tsx
src/components/Input/TextArea/TextArea.styled.ts
src/components/Input/TextArea/TextArea.test.tsx
src/components/Input/TextArea/TextArea.tsx
src/components/Input/TextArea/TextArea.types.ts
src/components/Input/TextArea/__snapshots__/TextArea.test.tsx.snap
src/components/Input/TextArea/index.ts
src/components/Input/TextField/TextField.styled.ts

- https://desk.channel.io/root/groups/Bezier-62019/618cee9cba2ca222938a 의 논의에 따라서 minRows와 maxRows 옵션을 TextArea에 추가합니다.
- 이에 따라 size option을 삭제합니다
- TextField에는 있었고 TextArea에는 없었던 disabled 옵션을 추가합니다
- minRows, maxRows 추가
- TextAreaHeight enum 추가
- size prop 삭제
- disabled 옵션 추가
* 이슈 없음.

TextArea의 minRow, maxRow prop을 부활하고 size option 삭제, disabled 옵션 & 스타일 추가

---

src/components/SegmentedControl/SegmentedControl.styled.ts
src/components/SegmentedControl/SegmentedControl.test.tsx
src/components/SegmentedControl/SegmentedControl.tsx
src/components/SegmentedControl/__snapshots__/SegmentedControl.test.tsx.snap

SegmentedControl 컴포넌트가 disable = true prop을 받았을 때 잘못된 스타일을 수정합니다.
| AS-IS | TO-BE |
| -- | -- |
| <img width="430" alt="스크린샷 2021-11-18 오후 1 43 57" src="https://user-images.githubusercontent.com/25701854/142353304-308606af-42f3-4855-9936-a51bda63a115.png"> | <img width="433" alt="스크린샷 2021-11-18 오후 1 43 46" src="https://user-images.githubusercontent.com/25701854/142353303-9a951977-7902-4489-893f-70df838db0ea.png"> |
- 기존 구현에서 disable = true일 때 텍스트 색상을 txt-black-light로 했는데, 해당 색상이 LightTheme에 정의가 되어있지 않아 default color로 표시됨
- disable일 때 텍스트 색상만 바꾸는 것은 스펙에 맞지 않아, opacity를 조정하도록 올바르게 변경
* 이슈 없음.

fix(segmentedcontrol): correct disabled style

---

src/components/Divider/Divider.stories.tsx
src/components/Divider/Divider.styled.ts
src/components/Divider/Divider.test.tsx
src/components/Divider/Divider.tsx
src/components/Divider/Divider.types.ts
src/components/Divider/__snapshots__/Divider.test.tsx.snap
src/components/Divider/index.ts
src/index.ts

[Divider 컴포넌트](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=3263%3A0)를 추가합니다. 
Divider는 가로 혹은 세로로 그려질 수 있습니다. 기본적으로 사방에 마진을 가지나, 축 양쪽에 마진이 없을 수 있습니다.
- 스토리북 추가
- 테스트코드 추가
* Close #126

Add Divider Component

---

src/components/FormHelperText/FormHelperText.stories.tsx
src/components/FormHelperText/FormHelperText.styled.ts
src/components/FormHelperText/FormHelperText.test.tsx
src/components/FormHelperText/FormHelperText.tsx
src/components/FormHelperText/FormHelperText.types.ts
src/components/FormHelperText/__snapshots__/FormHelperText.test.tsx.snap
src/components/FormHelperText/index.ts
src/components/Text/Text.tsx
src/components/Text/Text.types.ts
src/index.ts
src/types/ComponentProps.ts
src/utils/stringUtils.ts

여러가지 폼 아래에 들어가게 되는 `FormHelperText` 컴포넌트를 만들었습니다. 
- 이어지는 PR에서 `TextField`, `TextArea` 등과 함께 손쉽게 사용처에서 사용할 수 있도록 작업할 예정입니다.
- `FormLabel` 컴포넌트 추가도 예정되어 있습니다.
|Description|Error|
|---|---|
|<img width="278" alt="스크린샷 2021-11-29 오후 8 12 17" src="https://user-images.githubusercontent.com/58209009/143858477-b3db549e-08f9-4537-b90e-8d21873690b8.png">|<img width="278" alt="스크린샷 2021-11-29 오후 8 12 13" src="https://user-images.githubusercontent.com/58209009/143858485-a3e3a3b4-ef82-41a3-a51e-1cd4dbc8aff7.png">|
- `aria-describedby` 속성을 사용하기 위해서, `FormHelperText` 는 `id` prop을 필수로 가집니다. Form과 함께 사용되어야 하는 속성이라 후속 PR에서 함께 잘 사용되도록 만들 예정입니다.
- `margin-top: 4px` 과 `padding: 0 2px` 을 가집니다.
- ~~아래와 같은 정책을 가집니다. **description, errorMessage 둘 중 하나만 존재할 수 있다는 내용이 핵심입니다.**~~
1. ~~description, …

Add FormHelperText Component

---

.circleci/config.yml

code coverage 관리를 위해 사용하는 codecov integration에 관한 수정입니다.
현재 codecov에서는 clover.xml 파일을 coverage report로 보고 있는데요, 이 report에서는 branch에 따라 coverage가 잘 판정되지 않아 fully covered line이 partially covered line으로 판정되는 오류가 있습니다. 관련 사례는 Changes Detail 섹션을 참조해주세요.
관련하여 조사해본 결과 facebook/jest#10262 에서 논의된 내용을 보면 clover가 자기쪽 진영의 라이브러리가 아니라서 잘 모르고, maintaining되지 않는 것 같다며 lcov를 사용할 것을 권장하고 있었습니다.
[관련 스레드](https://desk.channel.io/root/groups/Web-18500/6154091867fe3e9f17fe) 요약입니다.
#587 의 케이스
(테스트 추가 전 - L68의 브랜치)
truecount = 3, falsecount = 1 → fully covered로 판정됨
(테스트 추가 후 - L75의 브랜치)
truecount = 4, falsecount = 0 → partially covered로 판정됨
(테스트 추가 전 - L68 의 브랜치)
```
BRDA: 68,2,0,0 // L68의 2번 분기, if가 0번 실행
BRDA: 68,2,1,2 // L68의 2번 분기, else가 2번 실행
BRDA: 68,3,0,2 // L68의 3번 분기, if가 2번 실행
BRDA: 68,3,1,2 // L68의 3번 …
```

ci(circle): change coverage report file to lcov.info

---

src/components/Overlay/Overlay.stories.tsx
src/components/Overlay/Overlay.test.tsx
src/components/Overlay/Overlay.tsx

- rect를 계산하는 함수가 새로운 객체를 계속 리턴하여 re-render가 되는 문제 개선
- rect를 계산하는 함수의 return Object를 ref에 할당하여 객체 주소 변경 안되게 변경
- DOM에 영향을 받는 함수로서 useLayoutEffect로 변경하여 ref에 할당
- keyup과 keydown 함수이름이 혼동되어 keydown으로 변경 (리뷰에 확인바람)
- 스토리북에 overlay children이 바뀌는 스펙 추가
https://www.notion.so/channelio/Reflow-e32b87347d07496999b0fa5fe2b691ec
- `enableClickOutside`는 Click에 대한 SideEffect가 존재합니다. 코드자체로는 의도를 하신것 같은데요, outside를 눌렀을 경우 overlay가 꺼지는게 UX적으로 괜찮아보입니다. overlay가 떠있는 동안 다른 Click event를 막는것은 버그에 가깝게 느껴집니다. 
- forceReducer가 안에 존재하던데, 이 부분은 한번 더 확인이 필요해보입니다. (#552)
- Props의 container, target의 영역을 ref로 감쌀 수 있는가? (e.g. Overlay로 Dropdown을 사용하는데 Dropdown의 ref값을 알 수 있어야 함)
- 초기 설계되었던 Overlay의 기능과 Portal의 기능이 분리되는 방법도 있을것 같습니다. 현재 두가지가 혼용되어있는것 같습니다.
- forceRender를 사용하지 않고 ref를 다시 계산할 수 있는 …

Overlay에서 발생되는 reflow 개선

---

package-lock.json
package.json

rollup plugin visualizer 버전 업데이트
생략
생략

chore(rollup-visualizer): update rollup-plugin-visualizer 5.5.0 to 5.5.2

---

src/components/Forms/Inputs/InputStyle.ts
src/components/Forms/Inputs/TextArea/TextArea.styled.ts
src/components/Forms/Inputs/TextArea/__snapshots__/TextArea.test.tsx.snap
src/components/Forms/Inputs/TextField/TextField.styled.ts

https://github.com/channel-io/bezier-react/blob/612f134ad04bc33ee2df9ca6dbf1e5706be6c6aa/src/components/Forms/Inputs/TextField/TextField.styled.ts#L34-L36
해당 내용과 동일하게 color를 추가합니다. (디자인과 일치)

fix(textarea): placeholder의 color를 추가 (like TextField)

---

src/worklets/EnableCSSHoudini.ts

NextJS 같은 경우에는 페이지 전환 시에 FoundationProvider가 여러 번 불리면서
smooth corner 관련된 스크립트를 여러 번 호출하게 되는데
이 때 등록된 reigsterPaint는 그대로 남아 있어 아래 에러가 발생합니다.
위 에러를 해결합니다

CSSHoudini가 여러 번 등록되어 발생하는 에러 문구를 제거

---

src/components/Button/Button.test.tsx
src/components/Button/Button.tsx

Button 컴포넌트의 스펙을 베지어 디자인 시스템 스펙에 맞게 최신화합니다.
- 사이즈 `L` : Typo14 -> Typo15
- 사이즈 `XL` : Typo16 -> Typo18, IconSize.S -> IconSize.Normal
- [Figma - Bezier Components](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=0%3A1)

Button 컴포넌트 스펙 최신화

---

src/components/Avatars/Avatar/Avatar.styled.ts
src/components/Avatars/Avatar/Avatar.test.tsx
src/components/Avatars/Avatar/Avatar.tsx
src/components/Avatars/Avatar/__snapshots__/Avatar.test.tsx.snap
src/components/Avatars/AvatarStyle.ts
src/components/Status/Status.stories.tsx
src/components/Status/Status.styled.ts
src/components/Status/Status.tsx
src/components/Status/Status.types.ts
src/components/Status/index.ts

위 디자인을 구현합니다.
14px 크기의 Status를 추가하고, 적절한 AvatarSize에 대해 StatusSize를 자동으로 지정합니다.

feat(status): statusSize 추가, AvatarSize에 맞게 StatusSize 지정

---

src/components/Status/Status.types.ts

#675 의 누락
https://github.com/channel-io/bezier-react/blob/a47dbc5625841730182db97258a1f95b08b40e0e/src/components/Status/Status.tsx#L12-L15
해당 default value를 사용하기 위해서 undefined size를 넣어줄 수 있도록 변경

fix(status): size prop 타입을 optional으로 수정

---

src/components/Tooltip/Tooltip.styled.ts
src/components/Tooltip/Tooltip.test.tsx
src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap

styled-component 기반으로 사용시 contentClassName 를 대체할 수 있는 contentInterpolation를 추가

fix(tooltip): tooltip이 contentInterpolation prop을 받도록 수정

---

src/components/Forms/Inputs/Select/__snapshots__/Select.test.tsx.snap
src/components/Forms/Inputs/TextArea/TextArea.test.tsx
src/components/Forms/Inputs/TextArea/__snapshots__/TextArea.test.tsx.snap
src/components/Forms/Inputs/TextField/TextField.test.tsx
src/components/Forms/Inputs/mixins.ts

Input 컴포넌트의 box-shadow 색상 스펙을 베지어 디자인 시스템 최신 버전에 맞게 업데이트합니다.
없음.
없음.

Input 컴포넌트의 box-shadow 색상 스펙 최신화

---

src/foundation/ThemeVars.ts

Theme css variable에 foundation sub theme도 함께 추가합니다.
없음
없음

feat(theme-vars): add inverted theme css vars

---

src/components/Forms/FormLabel/FormLabel.tsx
src/components/Forms/FormLabel/__snapshots__/FormLabel.test.tsx.snap
src/components/Forms/SegmentedControl/SegmentedControl.styled.ts
src/components/Forms/SegmentedControl/__snapshots__/SegmentedControl.test.tsx.snap
src/components/Forms/Switch/Switch.styled.ts

컴포넌트 색상을 최신화합니다. 다크모드에서도 올바른 색상으로 보이도록 합니다.
시안에 맞게 시맨틱 네임을 주입합니다.
- FormLabel 의 텍스트
기존에 ev 믹스인으로 인해 오버라이드되고 있었던 색상을 올바르게 변경합니다.
- Switch 컨트롤러
- SegmentedControl 각 아이템
없음. 피그마 참고 부탁드립니다.

Switch, SegmendtedControl, FormLabel 컴포넌트 색상 최신화

---

src/components/Avatars/Avatar/Avatar.styled.ts
src/components/Avatars/Avatar/Avatar.test.tsx
src/components/Avatars/Avatar/Avatar.tsx
src/components/Avatars/Avatar/__snapshots__/Avatar.test.tsx.snap

`Avatar` 컴포넌트의 border color를 변경합니다.
기존의 #FFF 고정값에서, 테마에 따라 색상이 변경될 수 있도록 합니다.
- [이전 메세지](https://desk.channel.io/root/groups/Bezier-62019/6113c08672c1b7a09d60)

fix(avatar): border-color 변경

---

src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
src/foundation/Colors/Palette/index.ts
src/foundation/Colors/Theme/presets/DarkTheme.ts

Palette에 white80 색상을 추가하고, 다크 테마의 `txt-black-darkest` 색상을 white90 -> 80으로 변경합니다.
다크 테마에서 글자색이 도드라져보이는 걸 완화하기 위한 변경입니다.
- [관련 채널톡 스레드](https://desk.channel.io/root/groups/Bezier-62019/61e0f3c7ae6e52a2f046)

다크 테마의 txt-black-darkest 색상 변경

---

src/components/Forms/Inputs/Select/Select.stories.tsx
src/components/Forms/Inputs/Select/Select.styled.ts
src/components/Forms/Inputs/Select/Select.test.tsx
src/components/Forms/Inputs/Select/Select.tsx
src/components/Forms/Inputs/Select/Select.types.ts

- 인터페이스만 열려 있고 실제로 동작하지 않는 Select의 `readOnly` prop이 잘 동작하도록 합니다. [스펙](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=6810%3A0)
- Select의 chevronColor prop을 drop합니다. (스펙상 커스터마이징 불가능합니다.) read-only일 때 chevron color를 txt-black-dark로 한 단계 낮춥니다.
https://user-images.githubusercontent.com/25701854/148726265-c6276e86-784c-42b6-8f24-6ab8981d3c80.mov
- [스펙](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=6810%3A0)

Support "readOnly" prop in Select

---

src/components/Forms/Inputs/Select/Select.stories.tsx
src/components/Forms/Inputs/Select/Select.styled.ts
src/components/Forms/Inputs/Select/Select.test.tsx
src/components/Forms/Inputs/Select/Select.tsx
src/components/Forms/Inputs/Select/Select.types.ts
src/components/Forms/Inputs/Select/__snapshots__/Select.test.tsx.snap

[Select] rightContent 추가, iconComponent를 leftContent로 변경, text에 Ellipsis 적용

---

src/components/Avatars/Avatar/Avatar.styled.ts
src/components/Avatars/AvatarGroup/AvatarGroup.stories.tsx
src/components/Avatars/AvatarGroup/AvatarGroup.test.tsx
src/components/Avatars/AvatarGroup/AvatarGroup.tsx
src/components/Avatars/AvatarGroup/__mocks__/avatarList.ts
src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap

- `Avatar` 기본 배경색상을 고정 화이트에서, 다크 테마에선 검정색이 될 수 있도록 수정합니다.
- `AvatarGroup` 컴포넌트의 하위 `Avatar` 컴포넌트 보더 표시 로직을 수정합니다. 화면에 그려지는`Avatar` 컴포넌트가 하나뿐이라면, 보더를 표시하지 않도록 합니다.
- 다크 테마 적용 시, smoothCorner가 적용된 `Avatar` 의 테두리가 지글지글해지는 현상이 발생하여 색상을 수정합니다.
없음

Avatar 기본 배경색 수정, AvatarGroup 보더 표시 로직 개선

---

src/components/Avatars/AvatarGroup/AvatarGroup.styled.ts
src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap

아바타 그룹의 생략 아이콘의 배경 색상을 다크모드에서도 동일하도록 absolute 시맨틱 컬러로 변경합니다
없음

fix(avatar-group): change ellipsis icon background color

---

src/components/Forms/Checkbox/Checkbox.tsx
src/components/Forms/FormControl/FormControl.stories.tsx
src/components/Forms/FormControl/FormControl.styled.ts
src/components/Forms/FormControl/FormControl.test.tsx
src/components/Forms/FormControl/FormControl.tsx
src/components/Forms/FormControl/FormControl.types.ts
src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
src/components/Forms/FormControl/index.ts
src/components/Forms/FormGroup/FormGroup.stories.tsx
src/components/Forms/FormGroup/FormGroup.styled.ts
src/components/Forms/FormGroup/FormGroup.test.tsx
src/components/Forms/FormGroup/FormGroup.tsx
src/components/Forms/FormGroup/FormGroup.types.ts
src/components/Forms/FormGroup/__snapshots__/FormGroup.test.tsx.snap
src/components/Forms/FormGroup/index.ts
src/components/Forms/FormLabel/FormLabel.tsx
src/components/Forms/Inputs/Select/Select.tsx
src/components/Forms/Inputs/TextArea/TextArea.tsx
src/components/Forms/Inputs/TextField/TextField.tsx
src/components/Forms/Radio/Radio.tsx
src/components/Forms/SegmentedControl/SegmentedControl.tsx
src/components/Forms/Switch/Switch.tsx
src/components/Forms/useFormFieldProps.ts
src/index.ts

`FormGroup` 컴포넌트를 추가합니다. 여러 폼 필드를 묶을 때 사용하는 Wrapper Component입니다. `Checkbox`, `Radio`, `TextField` 등 다양한 필드와 함께 사용할 수 있습니다. `FormControl` 과 함께 사용 시, 접근성 속성이 여러 필드에 중복되어 지정되는걸 방지하기 위해서 각 필드로 전달되는 접근성 관련 속성들을 `FormGroup` 에서 대신 전달받습니다. 
1. FormGroup만 단독으로 사용하면 Stack 컴포넌트(flex, gap속성이 있는 div)와 똑같이 동작합니다.
```tsx
<FormGroup>
<Checkbox>Option</Checkbox>
<Checkbox>Option</Checkbox>
<Checkbox>Option</Checkbox>
<Checkbox>Option</Checkbox>
</FormGroup>
```
2. FormControl과 함께 조합해서 사용하는 케이스
```tsx
<FormControl style={{ width: 400 }} labelPosition="left" {...args}>
<FormLabel>선택 항목</FormLabel>
<FormGroup>
<FormControl {...args} hasError={false}>
<TextField placeholder="선택 항목 추가" />
<FormErrorMessage>Error!</FormErrorMessage>
</FormControl>
<FormControl {...args} hasError={false}>
<TextField …
```

FormGroup Component

---

src/components/Divider/Divider.test.tsx
src/components/SectionLabel/SectionLabel.styled.ts
src/components/SectionLabel/SectionLabel.test.tsx
src/components/SectionLabel/SectionLabel.tsx

- Divider 컴포넌트가 베지어에 생겨, 기존 스타일 컴포넌트로 적용되었던 Divider 컴포넌트를 마이그레이션 해주었습니다.

Divider 컴포넌트 마이그레이션

---

src/components/Forms/FormControl/FormControl.test.tsx
src/components/Forms/FormControl/FormControl.tsx
src/components/Forms/FormControl/FormControl.types.ts
src/components/Forms/FormControl/__mocks__/forms.tsx
src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
src/components/Forms/FormGroup/FormGroup.tsx
src/components/Forms/FormGroup/FormGroup.types.ts
src/components/Forms/FormHelperText/FormHelperText.tsx
src/components/Forms/FormLabel/FormLabel.tsx
src/components/Forms/useFormFieldProps.ts
src/index.ts

폼 컴포넌트의 잘못된 구현을 수정하고, 오버라이드할 수 있는 속성을 추가합니다.
공통 Hook을 export하여 사용처에서 사용할 수 있도록 합니다.
- FormGroup, FormLabel 컴포넌트를 FormControl 외부에서 사용했을 때 속성을 오버라이드할 수 없었던 문제 수정
- FormGroup이 존재할 때 하위 Field에 id를 전달하지 않도록 수정
- 기존엔 FormControl -> FormGroup  -> FormControl -> Fields... 구조이기때문에 상위 FormControl 컨텍스트를 하위 FormControl 컨텍스트가 오버라이드해서 정상적으로 field id가 들어가게되나, 하위 FormControl을 생략한 케이스의 경우 상위 FormControl에서 generate한 field id가 그대로 들어가므로 이를 방지하고자 했습니다
- FormGroup의 role 속성을 오버라이드할 수 있도록 수정
-  radiogroup, checkboxgroup 등의 속성으로 오버라이드할 수 있도록 합니다
- 공통 Hook을 export하여 사용처에서 사용할 수 있도록 개선
- FormControl 테스트 보강
없음

폼 컴포넌트 개선 및 공통 Hook export

---

.eslintrc.js
.storybook/preview.js
jest.config.js
src/components/Banner/Banner.test.tsx
src/components/Button/Button.test.tsx
src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
src/components/Forms/FormHelperText/__snapshots__/FormHelperText.test.tsx.snap
src/components/Forms/FormLabel/__snapshots__/FormLabel.test.tsx.snap
src/components/Forms/Inputs/Select/__snapshots__/Select.test.tsx.snap
src/components/Forms/Inputs/TextArea/__snapshots__/TextArea.test.tsx.snap
src/components/Forms/SegmentedControl/__snapshots__/SegmentedControl.test.tsx.snap
src/components/KeyValueListItem/__snapshots__/KeyValueListItem.test.tsx.snap
src/components/ListItem/__snapshots__/ListItem.test.tsx.snap
src/components/SectionLabel/SectionLabel.test.tsx
src/components/Text/Text.test.tsx
src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
src/foundation/FoundationStyledComponent.tsx
src/foundation/GlobalStyle.tsx
src/foundation/ThemeVars.ts
src/foundation/Typography.ts
src/foundation/index.ts
src/index.ts
src/providers/BezierProvider.tsx
src/utils/testUtils.tsx
tsconfig.json

지금까지의 Typography14 라는 값은 14px를 의미했습니다
이 PR에서는 Typography{Number} 라는 값이 {Number}rem을 의미하도록 변경합니다.
하지만 변수명 변경이나 각 사용처에서의 글자 사이즈 변경 등 Breaking Change를 막기 위해 html 의 font size를 62.5%(10px) 로 고정하여  사용하게끔 설정했습니다
특정 상황에서 Typo의 사이즈를 변경할 수 있게 하기 위해서(html의 font-size를 조정함으로써) GlobalStyle을 주입할 수 있게 해당 코드를 추가해주었습니다. Global style을 inject할 수 있게 foundation에 추가적인 prop을 넣는 작업을 진행했습니다
- BezierProvider 작성
- Typography를 Rem단위로 변경
- 외부에서 html font size 변경 가능하게끔 Global Style Inject를 지원
- 이에 따른 테스트 코드 업데이트

Typography를 Rem 단위로 바꾸는 작업(BezierProvider, Typography, GlobalStyle)

---

src/components/Toast/Toast.styled.ts
src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
src/foundation/Mixin.test.tsx
src/foundation/Mixins.ts

#665 이후 데스크에서 사용하는 font-size의 단위는 PX가 아니라 REM이 되었습니다.
ellipsis function은 여전히 px단위였고 데스크에서 문제가 있었습니다. 이를 수정합니다.
잘리던 모습
rem 단위로 잘 나타남.

Ellipsis 의 text size가 rem 반영이 되지 않았던 문제를 수정

---

src/components/Navigator/NavGroup/NavGroup.stories.tsx
src/components/Navigator/NavGroup/NavGroup.styled.ts
src/components/Navigator/NavGroup/NavGroup.test.tsx
src/components/Navigator/NavGroup/NavGroup.tsx
src/components/Navigator/NavGroup/NavGroup.types.ts
src/components/Navigator/NavGroup/__snapshots__/NavGroup.test.tsx.snap

아코디언 UX가 변경되면서 작동 요구사항에 navgroup에 active가 되는 기능 구현입니다.

기획 변경으로 인하여 navgroup에 active prop 추가

---

src/components/Forms/Inputs/Select/Select.styled.ts
src/components/Forms/Inputs/Select/Select.test.tsx
src/components/Forms/Inputs/Select/Select.tsx
src/components/Forms/Inputs/Select/__snapshots__/Select.test.tsx.snap
src/components/Forms/Inputs/mixins.ts

fix #700, fix #708
- `Select` 컴포넌트 구현을 `button` 엘리먼트로 변경합니다 
- 인풋 컴포넌트(`TextField`, `TextArea`, `Select`) read-only 상태의 디자인 변경사항을 적용합니다.
- `Trigger` 의 엘리먼트 타입을 `button` 으로 변경. 키보드 포커싱이 가능해져, 엔터키를 통해 드롭다운을 열고 닫을 수 있게 됩니다
- read-only 상태의 배경 색상과 텍스트 색상 변경
- 스타일링 방식을 최대한 Native Selector를 사용하도록 리팩토링
- 일관성을 가지도록 변수명 리팩토링
- [Figma](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=0%3A1)

Select 컴포넌트 구현을 button 엘리먼트로 변경 및 디자인 최신화

---

src/components/Tooltip/Tooltip.stories.tsx
src/components/Tooltip/Tooltip.styled.ts
src/components/Tooltip/Tooltip.test.tsx
src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/Tooltip.types.ts
src/components/Tooltip/TooltipContent.test.tsx
src/components/Tooltip/TooltipContent.tsx
src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap

- Tooltip 내 TooltipContent 에 대한 lazy evaluation 옵션 추가
- Tooltip 리팩토링 (Tooltip, TooltipContent 분리)
- Tooltip 컴포넌트 내에 있지 않아도 될 함수들을 모두 memoize 해서 컴포넌트 내부에서 갖고있었음.
- show 되기 전의 TooltipContent 에 대한 style, component 등 모든 객체를 initialize 한 채로 갖고 있었음.
- Tooltip 컴포넌트의 memoization 이 없음.
- Tooltip 컴포넌트 내에 있지 않아도 될 함수들은 모두 컴포넌트 바깥으로 static 한 함수로
- TooltipContent 에 대한 style, component 등 모든 객체를 TooltipContent: React.FC 라는 새로운 컴포넌트 안으로 옮김.
- Tooltip 에 lazy: boolean prop을 추가하고, lazy = true 일 때는 TooltipContent 를 필요할 때 lazy 하게 evaluate 함
[노션](https://www.notion.so/channelio/TooltipContent-lazy-evaluation-1e4b27f3d65b4910be2e43f2b36e5179)

TooltipContent lazy evaluation

---

src/components/Avatars/Avatar/Avatar.tsx

- 절대경로로 바뀐 avatar asset의 import 경로를 상대경로로 변경합니다.

잘못 import된 avatar asset의 경로 변경

---

src/components/Forms/Inputs/Select/Select.styled.ts
src/components/Forms/Inputs/Select/Select.test.tsx
src/components/Forms/Inputs/Select/Select.tsx
src/components/Forms/Inputs/Select/__snapshots__/Select.test.tsx.snap

- Select의 DefaultFocus가 true일때에 DropDown이 간헐적으로 위치를 못잡던 문제를 해결합니다.
- Select의 Trigger가 Div에서 Button으로 수정됨에 따라, Select의 Trigger가 Container의 width만큼 확장되지 않는 문제를 해결합니다.
DefaultFocus가 true일때에, 스토리북 첫번째 랜딩 화면에서 DropDown이 제대로 위치를 잡지 못합니다.

Select의 DefaultFocus의 시점 변경 및 width 변경

---

src/components/Forms/Inputs/Select/Select.test.tsx
src/components/Forms/Inputs/Select/Select.tsx
src/components/Forms/Inputs/Select/__snapshots__/Select.test.tsx.snap

Select 컴포넌트의 트리거 버튼 클릭 시, 예기치 않은 submit 이벤트가 발생하고 있었습니다.
누락된 `type="button"` 을 추가합니다.
없음

Select 컴포넌트의 트리거 버튼 type을 button으로 수정

---

src/components/Forms/FormControl/FormControl.test.tsx
src/components/Forms/FormControl/FormControl.tsx
src/components/Forms/FormControl/FormControl.types.ts
src/components/Forms/FormControl/__mocks__/forms.tsx
src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
src/components/Forms/FormLabel/FormLabel.tsx

팔로업 알림 QA중 나온 폼 라벨 기본 폰트사이즈 변경에 관환 내용입니다.
- 현재 FormLabel에서 Typo의 default가 size13으로 설정되어 있습니다.
- FormControl과 같이 사용시 LabelPosition이 left 일때는 14px로 기본값을 변경해야하는 이슈가 있습니다. (하단 레퍼런스 링크 참조)
- FormLabel의 Typo에 기본값이 지정되어 있으면 LabelPosition을 확인한 시점에는 이미 값을 가지고 있어,
지정된 Typo의 값이 default에서 온 Size13인지 사용자가 입력한 Size13인지 알 수 없는 이슈가 있습니다.
FormControl의 LabelPosition의 값이 left일때만 특정하기 위해서 다음과 같이 수정합니다.
1. FormLabel의 Typo는 props에서 기본값을 지정하지 않는다.
2. FormControl에서는 getLabelProps에 labelPosition 값을 같이 전달한다.
3. FormLabel에서는 getLabelProps에서 넘어온 LabelPosition 값이 left이고 기본값이 undefined일때만 기본 폰트를 Size14로 지정한다.
4. 그 외의 케이스는 현재 룰대로 Size13을 기본값으로 정의한다.
- [[노션 QA문서]](https://www.notion.so/channelio/f47ac1de84b14083a9bb3a560a9fc720)

폼 라벨의 폰트 기본사이즈를 폼 컨트롤의 라벨 포지션에 따라 변경

---

src/foundation/ThemeVars.ts
src/providers/BezierProvider.stories.tsx
src/providers/BezierProvider.tsx

BezierProvider가 항상 `:root`에 SCSS theme variables를 주입하는 버그를 수정하고, foundation을 바꿀 수 있는 story를 storybook에 추가합니다.
- #742
해결 방법에 대한 논의는 issue에 있습니다.
**해당 PR은 Method 1으로 진행되었으며, 다른 의견이 있으시면 코멘트 부탁드립니다.**
채널 데스크에서 미리보기 컴포넌트 구현을 새롭게 하면서, 데스크의 테마와 상관 없이 항상 LightTheme으로만 보여줘야하는 경우가 생겼습니다.
이를 구현하기 위해서 미리보기 컴포넌트에 `BezierProvider`를 감싸는 형태로 작업을 하였는데, `BezierProvider` 바깥의, Provider의 관심 밖인, SCSS theme variable을 사용하는 컴포넌트가 LightTheme color로 고정되는 버그가 발견되었습니다. 이는 `BezierProvider`가 사용 위치에 상관 없이 항상 `:root`에 주입을 하고 있기 때문입니다.
- channel-io/ch-desk-web#9454
- channel-io/ch-desk-web#9397
이제 `BezierProvider`에 prop을 넘겨주면 `:root`가 아닌 해당 scope에 SCSS theme variables가 삽입됩니다.
- #742
- channel-io/ch-desk-web#9454
- channel-io/ch-desk-web#9397

BezierProvider가 항상 :root에 theme variables를 주입하는 버그 수정

---

src/components/Button/Button.styled.ts
src/components/Button/Button.test.tsx
src/components/Button/Button.tsx
src/components/Button/__snapshots__/Button.test.tsx.snap
src/components/Forms/FormGroup/FormGroup.styled.ts
src/utils/styleUtils.ts

[피그마](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=39%3A2) 에 있는 스펙에 맞게 Button 의 padding 값 결정 로직을 업데이트했습니다.
기존의 Button 의 padding 값 결정 로직은 text prop 의 유무로 결정되었습니다.
```typescript
case ButtonSize.L:
return css`
min-width: 44px;
height: 44px;
padding: 12px ${isEmpty(text) ? 12 : 10}px;
`
```
새로운 디자인 스펙 상 버튼의 padding 은 다음과 같은 케이스마다 다릅니다.
1. 버튼에 text 가 없는 경우
2. styleVariant 가 Floating 인 경우
3. padding이 들어갈 곳 바로 옆에 텍스트가 있는 경우
4. padding이 들어갈 곳 바로 옆에 컨텐츠(ex. 아이콘)가 있는 경우
이에 따라 로직을 분리했습니다.
[피그마](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=39%3A2)

Button 의 최신 디자인 스펙 반영

---

src/components/Navigator/NavGroup/NavGroup.styled.ts
src/components/Navigator/NavGroup/__snapshots__/NavGroup.test.tsx.snap
src/components/Navigator/NavItem/NavItem.styled.ts
src/components/Navigator/NavItem/__snapshots__/NavItem.test.tsx.snap

해당 PR은 사파리에서 navItem, navGroup의 hover style이 적용되지 않는 버그를 수정합니다.
1. 기존에 `:hover, :focus-visible {...}` 와 같이 `,`를 통해 키보드 포커스와 마우스 over에 대한 스타일을 정의하고 있었음
2. safari 15.4 이전 버전에서는 `:focus-visible`을 지원하지 않기 때문에, `,`를 통해 연결해준 hover 스타일 까지 작동이 안되고 있었음
https://user-images.githubusercontent.com/14245930/161017342-cee2f2bd-71a8-44a0-a912-5d241abf5bcd.mov
https://user-images.githubusercontent.com/14245930/161017372-07f05fd7-8135-4274-a3c0-55abc57d1b44.mov
- [:focus-visible compatibility](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible#browser_compatibility)
- [Notion QA](https://www.notion.so/channelio/21dda255845a49b5a969a92f49f25ebc)

사파리에서 navItem, navGroup의 hover style이 적용되지 않는 버그 수정

---

src/components/Navigator/NavGroup/NavGroup.styled.ts
src/components/Navigator/NavGroup/__snapshots__/NavGroup.test.tsx.snap
src/components/Navigator/NavItem/NavItem.styled.ts

해당 PR은 Navigator 컴포넌트 rightContent에 여백을 추가하고, 찌그러지지 않게 flex 스타일을 수정합니다.
- 4월 릴리즈 QA 중에 버그가 제보되었습니다.
- content가 꽉 찰 경우 여백이 없고 **오른쪽 내용에 text가 있을 경우** 찌그러지는 버그입니다.
|:---:|:---:|
|:---:|:---:|

Navigator 컴포넌트 rightContent에 여백 추가

---

package-lock.json
package.json
rollup.config.js
src/foundation/FoundationStyledComponent.tsx

사용처에서 hash collision을 막기 위해, styled-components로 생성되는 className에 namespace를 추가합니다.
- `typescript-plugin-styled-components` 플러그인을 추가하여 className에 displayName을 추가합니다.
- 잘못된 `FoundationStyled` 의 구현을 수정합니다. consumer project에서 `babel-plugin-styled-components` 플러그인을 사용했을 때, 번들링된 파일에서 에러가 발생합니다. `attrs()` 메서드를 사용한 스타일 컴포넌트의 경우, 번들링 시 `attrs({ /* ... */ }).withConfig({ /* babel 플러그인이 주입하는 옵션 */})`  의 형태로 트랜스파일링 되는데, 현재 구현에선 메서드 체이닝이 불가능하여 에러가 발생합니다. 메서드 체이닝이 가능하도록 수정합니다.
- [React Rollup build with styled-components namespace issue](https://stackoverflow.com/questions/68168926/react-rollup-build-with-styled-components-namespace-issue)

styled-components로 생성되는 className에 namespace 추가, 잘못된 FoundationStyled의 구현 수정

---

src/components/Modals/Modal/Modal.test.tsx

https://github.com/channel-io/bezier-react/pull/734 머지 이후에 ci에서 test 에러가 발생하여 추가 작업을 진행합니다.
**PR에서 테스트 실패가 식별되지 않는 이슈가 있습니다.**
padding style test가 불필요하여 제거하였습니다.
테스트 코드만 제거한 것이라 추가하지 않았습니다.
https://github.com/channel-io/bezier-react/pull/734

test(modal): fix modal style test removed padding

---

src/components/Avatars/Avatar/Avatar.styled.ts
src/components/Avatars/Avatar/Avatar.test.tsx
src/components/Avatars/Avatar/Avatar.tsx
src/components/Avatars/Avatar/Avatar.types.ts
src/components/Avatars/Avatar/__snapshots__/Avatar.test.tsx.snap

**Avatar**에  **AvatarSize 72**를 추가합니다.
- 72 size는 `StatusSize.M`을 가집니다.
- Avatar와 StatusWrapper가 가지게되는 gap은 StatusSize에 따라 계산되었지만, 72 size가 StatusSize.M을 보게되면서 **gap이 달라지는 기준을** `AvatarSize.Size72`로 변경합니다.
- StatusSize 사이즈 매칭은 AvatarSize.Size90으로 기존과 동일합니다.

Avatar에  AvatarSize 72를 추가

---

src/components/Navigator/NavGroup/NavGroup.stories.tsx
src/components/Navigator/NavGroup/NavGroup.test.tsx
src/components/Navigator/NavGroup/NavGroup.tsx
src/components/Navigator/NavGroup/NavGroup.types.ts
src/components/Navigator/NavGroup/__snapshots__/NavGroup.test.tsx.snap
src/components/Navigator/NavItem/NavItem.stories.tsx
src/components/Navigator/NavItem/NavItem.test.tsx
src/components/Navigator/NavItem/NavItem.tsx
src/components/Navigator/NavItem/NavItem.types.ts
src/components/Navigator/NavItem/__snapshots__/NavItem.test.tsx.snap

- Navigator의 요소들(NavGroup, NavItem)에서 active가 true이면 item의 background와 text의 color는 blue로 바뀝니다.
- 이때, leftIcon의 색상도 blue가 되도록 수정합니다.
|NavGroup|NavItem|
|-|-|
|<img width="413" alt="스크린샷 2022-04-21 오전 11 36 03" src="https://user-images.githubusercontent.com/57767891/164360505-211db704-70ef-475d-9aa2-8286bebfa560.png">|<img width="384" alt="스크린샷 2022-04-21 오전 11 36 12" src="https://user-images.githubusercontent.com/57767891/164360542-9636c6ab-0e66-45d2-abdc-3a237d33d274.png">|
|NavGroup|NavItem|
|-|-|
|<img width="516" alt="스크린샷 2022-04-21 오전 11 34 04" src="https://user-images.githubusercontent.com/57767891/164360574-0109d5c4-0f50-4efa-b64c-bdd98357f78b.png">|<img width="587" alt="스크린샷 2022-04-21 오전 11 33 55" …

Navigator에서 active 상태일 때 LeftIcon의 색상이 blue가 되도록 수정

---

src/components/Navigator/NavGroup/NavGroup.styled.ts
src/components/Navigator/NavGroup/NavGroup.tsx
src/components/Navigator/NavGroup/__snapshots__/NavGroup.test.tsx.snap

- 기존에는 NavGroup이 close 상태일 때 hover 시에만 chevron이 보였습니다.
- NavGroup 안에 NavItem이 있는 경우라면 open 여부에 관계없이 항상 chevron이 보이도록 수정합니다.
https://user-images.githubusercontent.com/57767891/164386925-eaab755c-36f6-470f-88f2-84906bb05d00.mov
https://user-images.githubusercontent.com/57767891/164386938-db8cece0-4892-4ee7-9c43-ca6382ee27f1.mov

NavGroup에 NavItem이 있는 경우 chevron이 항상 보이도록 수정

---

src/components/Banner/Banner.test.tsx
src/components/Button/__snapshots__/Button.test.tsx.snap
src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
src/components/Forms/FormLabel/__snapshots__/FormLabel.test.tsx.snap
src/components/KeyValueListItem/__snapshots__/KeyValueListItem.test.tsx.snap
src/components/SectionLabel/SectionLabel.test.tsx
src/components/Text/Text.styled.ts
src/components/Text/Text.test.tsx

- 베지어 Text 의 스펙 상 bold: true 일 때 `font-weight: 600` 입니다. 기존의 bezier-react 에선 bold 옵션이 `font-weight: bold (700)` 이었기에 스펙에 맞게 이를 수정합니다.
- Text 컴포넌트는 베지어 안에서 여러 곳에서 사용되는 컴포넌트라 이에 따라 영향을 받는 컴포넌트들의 테스트 코드와 스냅샷을 수정합니다.

Text 의 bold 옵션 시 font-weight 수정 

---

src/components/Status/Status.styled.ts
src/components/Status/Status.tsx

Avatar에서 쓰이는 Status에서 사용되는 Legacy 아이콘을 대체하여 빌드시 번들에 다른 아이콘이 포함되지 않도록 합니다.
프론트 번들 경량화의 일환입니다.
Avatar의 bundle size가 비정상적으로 크게 잡히는 문제를 해결합니다.
- #762

Status 컴포넌트에서 Legacy Icon 제거

---

src/components/Stack/HStack/HStack.test.tsx
src/components/Stack/VStack/VStack.test.tsx
src/components/Stack/VStack/VStack.tsx

#739 의 오류 수정.
셀프리뷰와 테스트케이스 작성을 강조했으나, 나부터 지켜야 할 듯 😅 
- #739

VStack 컴포넌트 direction 오류 수정

---

src/components/Forms/SegmentedControl/SegmentedControl.const.ts
src/components/Forms/SegmentedControl/SegmentedControl.stories.tsx
src/components/Forms/SegmentedControl/SegmentedControl.styled.ts
src/components/Forms/SegmentedControl/SegmentedControl.tsx
src/components/Forms/SegmentedControl/SegmentedControl.types.ts
src/components/Forms/SegmentedControl/__snapshots__/SegmentedControl.test.tsx.snap
src/components/Forms/SegmentedControl/index.ts

Fixes #689
- `SegmentedControlSize` enum 추가
- `SegmentedControlProps`
- delete `height` prop (** BREAKING CHANGE)
- support `size` prop
- `size`에 따라 height, padding 등 조정
- item 사이에 divider 추가
#707 도 수정하려면 item에 해당하는 컴포넌트도 export하여 각 item에 대해 `name`, `value` 등을 지정할 수 있도록 해야 할 듯 싶습니다.
인터페이스 조정이 추가적으로 필요하여 PR을 분리합니다.
```tsx
<SegmentedControl ...>
<SegmetedControlItem name="???" value="???" ... />
<SegmetedControlItem name="???" value="???" ... />
<SegmetedControlItem name="???" value="???" ... />
</SegmentedControl>
```
- #689

SegmentedControl 디자인 리뉴얼

---

src/components/TagBadge/Badge/Badge.test.tsx
src/components/TagBadge/Badge/Badge.tsx
src/components/TagBadge/Badge/__snapshots__/Badge.test.tsx.snap
src/components/TagBadge/Tag/Tag.test.tsx
src/components/TagBadge/Tag/Tag.tsx
src/components/TagBadge/Tag/__snapshots__/Tag.test.tsx.snap
src/components/TagBadge/TagBadgeCommon/TagBadgeText/TagBadgeText.tsx

`Tag`, `Badge` 컴포넌트에 `children` props가 없을 경우 불필요한 여백이 생기는 오류를 수정합니다.
아래와 같이 `children`이 없는 경우에도 padding을 가진 `TagBadgeText` 컴포넌트가 랜더링 되고 있어 좌우에 여백이 생기고 있었습니다.
실제로 `children`이 없는 경우엔 `TagBadgeText` 컴포넌트는 렌더링 될 필요가 없으므로 렌더링을 차단하는 방향으로 개선합니다.
**DOM**
**code**
```jsx
<TagBadgeText
horizontalPadding={BADGE_TEXT_HORIZONTAL_PADDING}
typo={getProperTagBadgeTypo(size)}
>
{ children }
</TagBadgeText>
```
fix 후 아래와 같이 개선해 볼 수 있을 것 같습니다
**(bug-fix와 같이 있던 @quino0627 feedback)**
- https://github.com/channel-io/bezier-react/issues/755
- https://github.com/channel-io/bezier-react/issues/745

Tag, Badge 컴포넌트에 children props가 없을 경우 불필요한 여백이 생기는 오류 수정

---

src/components/Forms/SegmentedControl/__snapshots__/SegmentedControl.test.tsx.snap
src/components/Stack/StackItem/StackItem.test.tsx
src/components/Stack/StackItem/StackItem.tsx

아래와 같이 Stack을 여러 번 중첩하여 사용하는 usecase에서 하위 레벨의 stack 스타일이 깨지는 이슈를 수정합니다.
```tsx
<HStack>
<StackItem size={320}>
<VStack>
<StackItem>{ ... }</StackItem> /* <- here */
</VStack>
</StackItem>
{ ... }
</HStack>
```
원인은 StackItem의 `--main-axis-size` css variable이 undefined인 경우, 상위 element의 variable이 적용되기 때문에 의도하지 않은 값을 스타일링에 사용하기 때문입니다.
StackItem에서 사용하는 CSS Variable이 항상 overwritten 되도록 `--main-axis-size`의 fallback 값을 `undefined`가 아닌 `"initial"`로 합니다. (테스트 케이스를 통해 이를 검증합니다.)
- #739

여러 Stack을 중첩하여 사용할 때 적용되는 스타일 오류 수정

---

.releaserc
turbo.json

Fix #784 
자동 배포가 안되는 문제를 수정합니다.
- `semantic-release` 스크립트는 `apps/bezier-react/` 패키지에서 실행되므로 패키지 루트는 그대로 `.` (기본값) 이어야 합니다. 설정을 다시 되돌립니다.
- `npm run release` 스크립트의 의존성을 제거합니다. 릴리즈 스크립트에 대한 의존성은 Circle CI의 workflow에서 책임지도록 변경했습니다. (cf. https://github.com/channel-io/bezier-react/pull/781#pullrequestreview-971842528) 
없음

잘못된 배포 설정 수정

---

apps/bezier-react/scripts/build-icon.sh

`npx` 커맨드 사용 시 ci 환경에서 [`svgr@next-v1` 패키지를 찾는 에러](https://app.circleci.com/pipelines/github/channel-io/bezier-react/2107/workflows/7686826d-f958-4dfa-9b07-009e9665f89d/jobs/6805?invite=true#step-102-373)가 발생합니다. (원인 파악 필요)
로컬에 설치되어 있는 `svgr` cli를 사용하도록 설정을 변경합니다. 
없음

fix(build-icon): 빌드 스크립트에서 로컬 svgr 커맨드를 사용하도록 수정

---

apps/bezier-react/src/hooks/useId.test.ts
apps/bezier-react/src/hooks/useId.ts
apps/bezier-react/src/utils/reactUtils.ts

React 버전 하위 호환성(v16.8, v17)을 위해 `useId` 훅의 구현을 변경합니다.
- `React.useId` 훅이 없이도 동작하도록 `useId` 훅의 이전 구현을 되돌렸습니다. 
- 버전을 체크하여 v18 이전 버전일 경우 이전 구현을 사용하도록 합니다.
없음

feat(use-id): implement the useIdLegacy hook for legacy react version compatibility

---

apps/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.const.ts
apps/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.styled.ts
apps/bezier-react/src/components/Forms/SegmentedControl/__snapshots__/SegmentedControl.test.tsx.snap

#759 에서 renewal 한 style이 box-sizing: border-box 를 가지는 어플리케이션에서 올바르게 나타나지 않는 현상을 수정합니다.
컴포넌트의 box-sizing property를 명시하고 padding을 적절하게 조정합니다.
- #759

SegmentedControl이 외부 box-sizing property에 관계없이 올바른 padding을 가지도록 수정

---

apps/bezier-react/src/components/Modals/Modal/index.ts

#727 에서 ModalTitleSize가 exports 되지 않았습니다.
ModalTitleSize가 exports 되게 수정합니다.
```tsx
// AS-is
import { ModalTitleSize } from '@channel.io/bezier-react/build/src/components/Modals/Modal/Modal.types'
// To-be
import { ModalTitleSize } from '@channel.io/bezier-react'
```
#727

chore(modal): 모달 titleSize type exports index에 추가

---

apps/bezier-react/package.json
package-lock.json

`react@^18.0.0` 을 지원하도록 direct dependency 버전을 업데이트 합니다.
- `react-resize-detector`: `^6.7.4` -> `^7.1.1`
- `react-textarea-autosize`: `^8.3.3` -> `^8.3.4`
- 버전 업데이트로 인한 changelog는 체크 결과 문제 없이 마이그레이션 가능합니다.
- `@mdx-js/react`는 v2부터 react v18을 지원합니다. 현재 사용중인 Storybook 6에서는 opt-in 기능으로 지원되고, 7버전부터 기본 지원된다고 합니다. (https://github.com/storybookjs/storybook/issues/18094)
- Opt-in으로 적용해보았으나, mdx 쪽 문서에서도 breaking change를 바로잡아야 하는 부분이 많았습니다.
- 따라서 이 문제는 나중에 해결하기로 하고, `--legacy-peer-deps` 옵션을 통해 업데이트합니다.
- https://github.com/storybookjs/storybook/issues/18094

Upgrade dependencies to support React v18 as peer dependency

---

apps/bezier-react/src/components/Forms/FormControl/FormControl.tsx
apps/bezier-react/src/components/Forms/FormControl/FormControl.types.ts
apps/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
apps/bezier-react/src/components/Forms/FormFieldSize.ts
apps/bezier-react/src/components/Forms/Inputs/Select/Select.styled.ts
apps/bezier-react/src/components/Forms/Inputs/Select/Select.types.ts
apps/bezier-react/src/components/Forms/Inputs/Select/__snapshots__/Select.test.tsx.snap
apps/bezier-react/src/components/Forms/Inputs/TextField/TextField.types.ts
apps/bezier-react/src/components/Forms/index.ts

`SelectSize` , `TextFieldSize` 와 동일한 사이즈를 가진 `FormFieldSize` enum을 추가합니다.
- `FormControlProps` 의 `leftLabelWrapperHeight` 타입을 `FormFieldSize` 로 변경하고, 기존 `TextFieldSize` 를 참조하던 것을 `FormFieldSize` 를 참조하도록 변경합니다.
- Fix #728 . 상위 디렉토리의 enum을 사용하면서 해결됩니다.

refactor(forms): add FormFieldSize enum

---

packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.common.styled.ts
packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.const.ts
packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.stories.tsx
packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.test.tsx
packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.types.ts
packages/bezier-react/src/components/KeyValueListItem/KeyValueMultiLineListItem.styled.ts
packages/bezier-react/src/components/KeyValueListItem/KeyValueMultiLineListItem.tsx
packages/bezier-react/src/components/KeyValueListItem/__snapshots__/KeyValueListItem.test.tsx.snap
packages/bezier-react/src/components/KeyValueListItem/common/ItemActions/ItemAction.styled.ts
packages/bezier-react/src/components/KeyValueListItem/common/ItemActions/ItemAction.tsx
packages/bezier-react/src/components/KeyValueListItem/common/ItemActions/ItemAction.types.ts
packages/bezier-react/src/components/KeyValueListItem/common/ItemActions/index.ts
packages/bezier-react/src/components/KeyValueListItem/common/KeyItem/KeyItem.styled.ts
packages/bezier-react/src/components/KeyValueListItem/common/KeyItem/KeyItem.tsx
packages/bezier-react/src/components/KeyValueListItem/common/KeyItem/KeyItem.types.ts
packages/bezier-react/src/components/KeyValueListItem/common/KeyItem/index.ts
packages/bezier-react/src/components/KeyValueListItem/common/ValueItem/ValueItem.styled.ts
packages/bezier-react/src/components/KeyValueListItem/common/ValueItem/ValueItem.tsx
packages/bezier-react/src/components/KeyValueListItem/common/ValueItem/ValueItem.types.ts
packages/bezier-react/src/components/KeyValueListItem/common/ValueItem/index.ts
packages/bezier-react/src/components/KeyValueListItem/common/index.ts
packages/bezier-react/src/components/KeyValueListItem/index.ts

- KeyValueListItem의 공통 Component를 분리하고, RenderComponent를 Props가 아닌 Component 단위로 분리합니다.
- Key, Value, Action으로 Component를 나눕니다.
- common
- SingleLine과 MultiLine은 같은 Component를 공유하되 세부적인 Style은 Component와 styled 파일로 나눕니다.
- KeyValueListItem.common.styled
- KeyValueListItem + KeyValueListItem.styled
- KeyValueMultiLineListItem + KeyValueMultiLineListItem.styled
- onClickKey, onClickValue가 추가되고, 각 영역의 Hover/Cursor 스타일이 ClickEvent를 기반으로 동작합니다.
- KeyValueListItem.types
- SingleLine에서 min-width 100px이 추가되고, Key와 Value의 1:2 비율을 추가합니다.
- Test를 강화합니다.
- [KeyValueListItem Figma](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=1164%3A12605)

refactor(components): key-value-list-item을 single/multiLine component로 분리

---

packages/bezier-react/src/components/Status/Status.styled.ts
packages/bezier-react/src/components/Status/Status.tsx
packages/bezier-react/src/components/Status/Status.types.ts

`Status` 컴포넌트에 초승달 이미지가 표시될 수 있도록 `StatusType` enum에 두가지 값을 추가합니다.
또한 추가 된 두가지 값일 경우와 기존에 존재하던 `Lock`의 경우의 렌더링 로직을 개선합니다.
```diff
export enum StatusType {
Online = 'Online',
Offline = 'Offline',
Lock = 'Lock',
+ OnlineCrescent = 'OnlineCrescent',
+ OfflineCrescent = 'OfflineCrescent',
}
```

feat: add Do-Not-Disturb status prop to Status and Avatar component

---

packages/bezier-react/src/foundation/Rounding/Rounding.stories.tsx
packages/bezier-react/src/foundation/Rounding/index.ts

명세에 따라 `round3`을 추가합니다.
`border-radius: 3px;`에 해당하는 `round3`이 #803 에 필요하게 되어, 이를 `Rounding`에 추가합니다.
- Figma: https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=24044%3A206093

Rounding에 round3 추가

---

packages/bezier-react/src/components/Banner/Banner.stories.tsx

`Banner` 컴포넌트의 Storybook Story의 `colorVariant` args를 `variant`로 수정했습니다.
- Closes #741

Banner Story의 colorVariant를 variant로 수정

---

packages/bezier-react/src/components/Banner/Banner.const.ts

`Banner` 컴포넌트의 variant에 따른 색상 중, alt variant의 아이콘 색상이 스펙과 일치하지 않아 이를 수정합니다.
- `BannerVariant.Alt`의 올바른 icon color인 `bgtxt-red-normal` 로 수정합니다.
없음.

Correct icon color of alt variant in Banner component

---

packages/bezier-react/src/layout/components/Navigations/NavigationArea/NavigationArea.tsx

어플리케이션에서 report된 현상으로, NavigationArea 컴포넌트로부터 발생하는 "Maximum update depth exceeded" 오류를 해결합니다.
React v18은 v17과 비교했을 때 layout effect의 dispatch 시점에 차이가 있습니다. (Fiber 구현의 차이)
한 NavigationArea 컴포넌트가 unmount되고 다른 NavigationArea 컴포넌트가 mount되는 상황에서, (주로 route 이동 시 발생) fiber의 task scheduling에 의해 layout effect의 dispatch 순서가 특정하게 배열되면 trigger 조건이 꼬여버려버려 infinite loop로 떨어지는 현상을 관찰했습니다.
이를 해결하기 위해, layout effect의 trigger 조건을 더 좁힙니다. 이 수정 후 위에서 서술한 현상이 발생하지 않는 것을 관찰했습니다.
(NavigationArea는 자신의 `currentKey`에 해당하는 state에만 관심을 가지면 됩니다.)
(없음)

Suppress unnecessary layout effect in NavigationArea

---

packages/bezier-react/src/components/Status/Status.tsx

Status 컴포넌트의 배경 색상이 잘못 지정되어 있어서 다크모드로 변경 했을 때 배경이 어색한 문제를 수정합니다.

다크모드에서 Status 컴포넌트 배경 색상이 어색한 문제 수정

---

packages/bezier-react/src/components/Banner/Banner.const.ts
packages/bezier-react/src/components/Banner/Banner.stories.tsx
packages/bezier-react/src/components/Banner/Banner.styled.ts
packages/bezier-react/src/components/Banner/Banner.test.tsx
packages/bezier-react/src/components/Banner/Banner.tsx
packages/bezier-react/src/components/Banner/Banner.types.ts

배너의 우측에 X 아이콘 외에도 다른 액션을 트리거하는 버튼이 들어갈 수 있도록 컴포넌트 스펙이 변경되었습니다.
`Banner` 컴포넌트의 `dismiss`, `onDismiss` prop을 `actionIcon`, `onClickAction` prop으로 변경합니다.
```diff
- dismiss: boolean
- onDismiss: () => void
+ actionIcon: IconName /* FIXME: 추후 IconSource로 변경 */
+ onClickAction: ButtonProps['onClick']
```
> **💥 BREAKING CHANGE: `dismiss`, `onDismiss` prop이 제거됩니다!**
- `Icon` 기반의 스타일링을 `Button` 을 사용하도록 변경
- 내부적으로 `Stack` 을 사용하여 스타일링하도록 리팩토링
- 피그마 참고

feat(banner): change the dismiss prop to actionIcon

---

packages/bezier-react/src/utils/arrayUtils.test.ts
packages/bezier-react/src/utils/arrayUtils.ts

`removeItem` 함수에 배열 범위를 벗어나는 index를 넣으면 잘못 작동하는 버그를 수정합니다.
- `LayoutReducer`에서 사용하는 `removeItem` 함수에 배열 범위를 벗어나는 index를 넣으면 잘못 작동할 가능성이 있었습니다.
- `removeItem` 함수 내에서 index 범위를 체크하도록 하여 수정합니다.
- 참고: `removeItem(arr, -1)`의 결과

arrayUtils.removeItem에 out of index를 넣으면 잘못 작동하는 버그 수정

---

packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.test.tsx
packages/bezier-react/src/components/KeyValueListItem/__snapshots__/KeyValueListItem.test.tsx.snap
packages/bezier-react/src/components/KeyValueListItem/common/KeyItem/KeyItem.styled.ts

KeyValueListItem에 key min-width 제거
KeyValueListItem에 key min-width 100px이 1:2 비율을 유지하는 flex와 중첩되어 key에 ellipsis가 100px보다 작아질 때 동작하지 않는 문제가 있습니다. 이를 해결합니다.
[채널톡 그룹쳇](https://desk.channel.io/root/threads/groups/(TF)BezierReactV1-124831/62a6f5430d62c58b5534/62a6f5430d62c58b5534)

style(key-value-list=item): key-value-list-item에서 key에 min-width 스타일을 제거

---

packages/bezier-react/src/components/Banner/Banner.styled.ts
packages/bezier-react/src/components/Banner/Banner.tsx

- StackItem 사용으로 인해 height가 아이콘, 버튼보다 커져 align이 깨지던 문제를 해결합니다.
- As-is
- To-be
- StackItem의 SIze는 상위 Stack의 타입에 따라 width를 조절할지 height를 조절할지 결정됩니다. 이에 따라 Banner의 아이콘, 버튼의 Height를 별개로 조절할 수 없어서 StackItem을 오버라이드 한 후 height를 고정합니다.

Banner의 아이콘과 버튼의 align을 교정

---

packages/bezier-react/src/components/SectionLabel/SectionLabel.tsx

~~`SectionLabel` 컴포넌트의 `help` 프롭 타입에 `allowTooltipHover: boolean`을 추가하여, `SectionLabel`을 사용할 때 Help tooltip의 `allowHover` 여부를 정할 수 있게 합니다.~~
`SectionLabel` 컴포넌트의 `help` 툴팁의 `allowHover`를 항상 true로 변경합니다.
> 관련 Desk 이슈: https://github.com/channel-io/ch-desk-web/issues/10023
Help tooltip 내에 Clickable한 요소가 있는 경우 등에는 Tooltip이 호버 가능해야 하며, 이를 ~~`SectionLabel.help`의 props에 추가하여 해결합니다.~~ `SectionLabel.help`를 렌더링하는 툴팁의 `allowHover`를 true로 설정하여 해결합니다.

SectionLabel의 help Tooltip의 allowHover를 true로 설정

---

packages/bezier-react/src/components/Modals/Modal/Modal.styled.ts
packages/bezier-react/src/components/Modals/Modal/Modal.test.tsx

- Modal Title에서의 ellipsis 처리를 제거합니다.
- Modal Title에서의 줄임말 처리는 의도되지 않은 디자인이라는 피드백이 있어서 이를 제거합니다.
- [Modal Figma](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=1427%3A229)
- [팀 기능 QA 시 Modal 리포트](https://www.notion.so/channelio/f2b71cbe8781481eb62cd032c1a8548b)

fix(modal): modal title ellipsis style을 제거

---

packages/bezier-react/src/components/Tooltip/Tooltip.styled.ts
packages/bezier-react/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap

해당 PR은 Tooltip Content의 가독성을 개선합니다.
`word-break`, `word-wrap`을 수정하여 영어에서 줄 바꿈이 단어 기준으로 되도록 수정합니다.
영어가 알파벳으로 끊김, 느낌표가 화면 밖을 벗어남.

Tooltip 가독성 개선

---

.releaserc

Close #832
semantic release의 릴리즈 규칙을 개선합니다.
#832 이슈 코멘트에 작성했듯 모든 커밋 타입에 대해 릴리즈를 수행할 필요는 없다고 생각하여 일부 의미 있는 커밋만 릴리즈를 트리거하도록 개선합니다.
- `docs`, `refactor` 시에도 patch 버전 릴리즈가 이루어지도록 변경
- `no-release` scope 지정 시에는 릴리즈를 트리거하지 않도록 변경
- #832 
- https://github.com/semantic-release/commit-analyzer

build(semantic-release): enhance the release rules

---

packages/bezier-react/src/components/ProgressBar/index.ts

- `ProgressBar`에 사용되는 Size, Variant enum을 type export가 아닌, 값까지 export하도록 수정합니다.
> Closes #850
- As-is
```ts
import type { ProgressBarSize, ProgressBarVariant } from './ProgressBar.types'
export {
ProgressBar,
type ProgressBarProps,
type ProgressBarSize,
type ProgressBarVariant,
}
```
- To-be
```ts
import { ProgressBarSize, ProgressBarVariant } from './ProgressBar.types'
export {
ProgressBar,
type ProgressBarProps,
ProgressBarSize,
ProgressBarVariant,
}
```

ProgressBar에서 Size, Variant enum을 값까지 export하도록 수정

---

.circleci/config.yml
packages/bezier-react/package.json
yarn.lock

[Chromatic - bezier-react](https://www.chromatic.com/builds?appId=62bead1508281287d3c94d25)
Chromatic을 설치하고, CI pipeline에 Chromatic 배포(Storybook) 작업을 추가합니다.
- circleci project 환경변수로 프로젝트 토큰을 추가했습니다.
- push할 때마다 각 브랜치별 Storybook이 배포되도록 합니다. 주소는 아래와 같습니다.
```bash
https://<branch>--62bead1508281287d3c94d25.chromatic.com
```
- `yarn workspace @channel.io/bezier-react chromatic --exit-zero-on-changes --skip 'dependabot/**'`
- `--exit-zero-on-changes` : Chromatic에서 변경사항이 있다면 머지가 블로킹되는데, 이를 방지하는 옵션입니다. 
비슷하게 `--auto-accept-changes` 옵션의 경우 Chromatic의 변경사항을 자동으로 확인해주기도 하는데, 이 옵션을 적용할지는 더 살펴볼 예정입니다.
- `-skip 'dependabot/**'` : depandabot PR의 경우 스토리북 배포를 스킵합니다.
- 스토리북 배포 과정에서 테스트를 다시 한 번 실행합니다. `jest` 명령어와 충돌하는데, `jest` 명령어를 통해 코드 커버리지 파일을 생성하고 있고 Chromatic에서 테스트를 스킵할 수 있는 방법이 현재 없어 테스트 2번 실행은 …

Add Chromatic

---

.changeset/old-students-raise.md
packages/bezier-react/src/components/Forms/Switch/Switch.stories.tsx
packages/bezier-react/src/components/Forms/Switch/Switch.styled.ts
packages/bezier-react/src/components/Forms/Switch/Switch.test.tsx
packages/bezier-react/src/components/Forms/Switch/Switch.tsx
packages/bezier-react/src/components/Forms/Switch/Switch.types.ts
packages/bezier-react/src/components/Forms/Switch/index.ts

- Forms의 `Switch` 컴포넌트 구현이 Figma 명세를 따르도록 수정합니다.
> Closes #840
```ts
export enum SwitchSize {
M = 'm',
S = 's',
}
```
- [Figma Switch](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=3263%3A131)

Switch 컴포넌트 구현이 Figma 명세를 따르도록 수정

---

.changeset/old-olives-trade.md
packages/bezier-react/src/components/Forms/Switch/Switch.styled.ts

- handle의 bgColor를 `bgtxt-absolute-white-dark`로 옳게 지정하였으나, elevation의 css에 bgColor 속성이 override되어 absolute color가 제대로 적용되지 않고 있었습니다.
- elevation 설정을 위로 올려 해결합니다.

Switch handle의 색상이 다크모드에서 잘못 표시되는 버그 수정

---

packages/bezier-react/.storybook/preview.js

> 뷰포트 사이즈에 따라 잘 줄바꿈 됩니다.
스토리북에서 별도의 설정 없이, 라이트 테마와 다크 테마를 함께 보여주도록 개선합니다.
- 스토리북 상단의 툴바를 사용하여 테마를 전환할 수 있으나, 기본적으로 라이트 테마로 고정되어있어 작업자가 주의를 기울이지 않으면 다크 테마를 고려하지 못하고 실수를 저지르는 경우가 많았습니다. 이를 미연에 방지하고자 두 테마의 스토리를 동시에 띄우는 방식으로 개선합니다.
- Chromatic의 Snapshot diff에 어떤 영향이 있을지는 계속해서 지켜보아야 할 거 같습니다.
- `FIXME` : Layout playground 스토리가 제대로 안보이는 문제
- 가이드 문서에도 두가지 테마가 동시에 보여 어노잉할 수 있을 거 같습니다.
없음

feat(storybook): improvements to show the inverted theme as well

---

.circleci/config.yml
.github/workflows/chromatic.yml

Chromatic 배포 job을 circle ci에서 github ci로 이동합니다.
[GitHub Action for Chromatic](https://github.com/chromaui/action)을 사용하여 진행상황을 더 자세히 보여주기 위한 변경입니다.
- circleci의 workflow명을 적절하게 변경
- secret 토큰 추가
- https://storybook.js.org/tutorials/ui-testing-handbook/react/en/automate/

ci(chromatic): move deploy chromatic job to github workflow

---

.changeset/fresh-lamps-remain.md
packages/bezier-react/src/components/Forms/FormControl/FormControl.stories.tsx
packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
packages/bezier-react/src/components/Forms/FormGroup/FormGroup.stories.tsx
packages/bezier-react/src/components/Forms/FormGroup/FormGroup.styled.ts
packages/bezier-react/src/components/Forms/FormGroup/FormGroup.test.tsx
packages/bezier-react/src/components/Forms/FormGroup/FormGroup.tsx
packages/bezier-react/src/components/Forms/FormGroup/FormGroup.types.ts
packages/bezier-react/src/components/Forms/FormGroup/__snapshots__/FormGroup.test.tsx.snap
packages/bezier-react/src/components/Stack/Stack/Stack.tsx
packages/bezier-react/src/components/Stack/Stack/Stack.types.ts

`FormGroup` 의 내부 구현을 `Stack` 을 사용하는 방향으로 변경합니다. (TODO Resolve)
- `gap` 프로퍼티 명이 `Stack` 과 동일하게 `spacing` 으로 변경됩니다.
- `direction` 프로퍼티에 가능한 값이 `Stack` 과 동일하게 `'horizontal' | 'vertical'` 로 변경됩니다.
- `Stack` 이 aria attribute를 전달받지 못하는 문제가 있어, rest parameter를 추가하는 방향으로 우선 해결했습니다.
- `flex: wrap` 같은 속성의 경우 `Stack` 에서 처리하지 못하는 문제가 있어, `Stack` 상위에 `Flex` 컴포넌트가 구현되어서 이를 내부적으로 상속하는 형태가 되면 스타일 오버라이드를 더 줄일 수 있겠다는 생각이 들었습니다. 
(ex: https://ui.docs.amplify.aws/react/components/flex, https://chakra-ui.com/docs/components/flex/usage)
없음

refactor(form-group): change implementation to use Stack internally

---

.github/workflows/chromatic.yml

- Reverts channel-io/bezier-react#885
- https://github.com/channel-io/bezier-react/actions/runs/2712576956
- Chromatic 액션은 `repository_dispatch` 액션을 지원하지 않아 리버트합니다.

Revert "ci(chromatic): change trigger event to repository_dispatch"

---

.github/comment_template.md
.github/workflows/chromatic-report.yml
.github/workflows/chromatic.yml
packages/bezier-react/package.json

- Close #877
- 크로마틱 워크플로우가 올바르게 작동하도록 수정하고, 개선합니다.
- 크로마틱 배포가 마무리되면 해당 PR에 배포 정보에 대한 코멘트를 남기는 워크플로우를 추가합니다.
기존 `Chromatic` 워크플로우는 `push` 이벤트가 발생할 때만 트리거되도록 설정되어 있었습니다. 하지만 Fork된 레포지토리의 브랜치에 커밋을 푸시하는 거로는 트리거되지 않아서, origin(upstream)의 `next-v1` 브랜치에 푸시하는 경우에만 동작하고 있었습니다. 
항상 최신 상태의 스토리북을 배포하고자 하는 목적도 있었으나, 작업자들의 개별 PR에서 자동 배포가 이루어져서 리뷰 과정을 원활하게 하고자 하는 이유도 있었기때문에 이전 CircleCI에서 동작하던 방식처럼 되돌릴 필요가 있었습니다.
트리거 이벤트의 목록에 `push` 이벤트는 그대로 둔 채, `pull_request` 이벤트를 추가했습니다. 
```yml
on:
push:
pull_request:
types: [opened, reopened, synchronize]
paths:
- packages/bezier-react/src/**.jsx?
- packages/bezier-react/src/**.tsx?
- packages/bezier-react/.storybook/**
```
PR이 열릴 때(`opened`), 다시 열릴 때(`reopend`), 그리고 PR의 head branch가 업데이트될 때(`synchronize`) 워크플로우가 트리거 되도록 했습니다. 아래 설명에 따르면, 커밋이 푸시되거나 base branch가 …

ci: enhance the chromatic workflow

---

packages/bezier-react/.storybook/main.js
packages/bezier-react/package.json
packages/bezier-react/src/components/ButtonGroup/ButtonGroup.stories.mdx
yarn.lock

`@channel.io/bezier-react` package의 storybook이 webpack 5 builder를 사용하도록 합니다.
Migration에 관해서는 [Guide](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#webpack-5) 참고 바랍니다.
Storybook의 docs add-on (`@storybook/addon-docs`) 이 typescript와 jsdoc으로부터 컴포넌트 prop의 description 등 메타데이터를 읽어내도록 하는 작업 중입니다.
이 작업에서 사용하는 [`react-docgen-typescript-plugin`](https://github.com/hipstersmoothie/react-docgen-typescript-plugin) 은 webpack 5를 기본으로 하고 있습니다. (webpack 4에서도 사용 가능하나, **HMR이 적용되지 않는 등** 사용에 있어 불편함이 있습니다.) 따라서 먼저 `@channel.io/bezier-react`의 storybook bundler를 webpack 5로 opt-in하는 업데이트를 진행합니다.
- **Storybook이 webpack 5를 bundler로 사용하도록 opt-in 합니다.**
- bezier-react에서는 scss 파일을 사용하지 않으므로, 불필요한 loader를 제거합니다.
- `deploy:storybook` script를 제거합니다. (스토리북 배포는 chromatic 사용 중)
-  [Storybook - Webpack 5 …

Opt-in webpack5 builder for bezier-react storybook

---

.github/workflows/chromatic-report.yml

Chromatic report 워크플로우가 작동하지 않던 부분을 수정합니다.
- [예제](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run)에서 예상하던 동작과 다르게 run id가 제대로 전달되지 않아 동작하지 않던 오류를 수정합니다.
- [이전 워크플로우](https://github.com/channel-io/bezier-react/runs/7456067119?check_suite_focus=true)에선 이 PR의 내용으로 Download artifact 스탭이 잘 실행되었기에 이 PR이 적용되면 문제가 수정될 거로 생각합니다.
없음

ci(chromatic-report): fix download artifact step script

---

packages/bezier-react/src/components/Banner/Banner.mdx
packages/bezier-react/src/components/Banner/Banner.stories.tsx
packages/bezier-react/src/components/Button/Button.mdx
packages/bezier-react/src/components/Button/Button.stories.tsx
packages/bezier-react/src/components/ButtonGroup/ButtonGroup.mdx
packages/bezier-react/src/components/ButtonGroup/ButtonGroup.stories.tsx
packages/bezier-react/src/components/Stack/Stack.mdx
packages/bezier-react/src/components/Stack/Stack.stories.tsx
packages/bezier-react/src/stories/mdx.d.ts

TSX, MDX 파일에서 동일 컴포넌트에 대한 스토리를 모두 export하고 있어, mdx documentation이 가려지는 현상이 발생합니다.
이를 수정하여, Docs tab에서 mdx documentation이 올바르게 표시되도록 합니다.
- mdx documentation 파일에서 metadata를 export하지 않고, tsx 파일에서 mdx 파일을 import하여 docs page로 지정합니다. 이로 인해 중복 export 문제가 해소됩니다.
```ts
// [Component].stories.tsx
import mdx from './[Component].mdx'
export default {
...
parameters: {
docs: {
page: mdx,
},
},
}
```
- 스토리에 name을 더 적절하게 지정합니다.
- Carbon design system의 스토리 구현을 참고했습니다.

Ensure mdx documentation is shown instead of canvas

---

.changeset/thick-dryers-deliver.md
packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.common.styled.ts
packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.stories.tsx
packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.styled.ts
packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.test.tsx
packages/bezier-react/src/components/KeyValueListItem/__snapshots__/KeyValueListItem.test.tsx.snap
packages/bezier-react/src/components/KeyValueListItem/common/ValueItem/ValueItem.styled.ts

- remove fixed height(28px) styles 
- add default color to value component
- add color(txt/black/darkest) style to value component
- remove fixed height(28px) style
- change align-items "center" to "flex-start"
- [KeyValueListItem Figma](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=1164%3A12605)
- [ChannelTalk - GroupChat Bug](https://desk.channel.io/root/groups/Bug-10/62d6c137ad052a374c4a)

refactor(key-value-list-item): change key and value component styles removed fixed height and given default color

---

.changeset/witty-bananas-return.md
packages/bezier-react/src/components/Toast/Toast.stories.tsx
packages/bezier-react/src/components/Toast/Toast.styled.ts
packages/bezier-react/src/components/Toast/Toast.test.tsx
packages/bezier-react/src/components/Toast/Toast.types.ts
packages/bezier-react/src/components/Toast/ToastController.test.tsx
packages/bezier-react/src/components/Toast/ToastController.tsx
packages/bezier-react/src/components/Toast/ToastElement.tsx
packages/bezier-react/src/components/Toast/ToastProvider.tsx
packages/bezier-react/src/components/Toast/ToastService.ts
packages/bezier-react/src/components/Toast/index.ts

- change the toast component content props from string to react-node
- Replace the line breaking "\n" to div element in string content.
- Changed from string to ReactNode to build a custom content toast.
- Since ReactNode is string compatible, there is no breaking-changes.
- Fixed a problem broader than the Close area than the Content area. (flex-shrink)
- actionContent props is deprecated. It is used one place only in the desk application.
- Add a CustomContent(ReactNode) storybook.
https://user-images.githubusercontent.com/16330024/180923853-adb35cf9-c7eb-4801-9ccc-496b45d6de9c.mov
https://github.com/channel-io/ch-desk-web/issues/10597
- [Figma](https://www.figma.com/file/82ho83cCj4n1FbD9ErU825/Contacts?node-id=4210%3A150677)
- [Notion - Contacts Bulk …

change the toast component content props from string to react-node

---

.changeset/cold-jars-clap.md
packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
packages/bezier-react/src/components/Forms/FormGroup/FormGroup.tsx
packages/bezier-react/src/components/Forms/FormGroup/__snapshots__/FormGroup.test.tsx.snap

없음
`FormGroup` 컴포넌트의 동작을 #866 이전과 동일하게 맞추기 위해, CSS Flex 프로퍼티 기본 값과 동일하게 세팅합니다.
[What are the default values for justify-content & align content?](https://stackoverflow.com/questions/62350959/what-are-the-default-values-for-justify-content-align-content)
> The [first one related to flexbox](https://drafts.csswg.org/css-flexbox-1/#propdef-justify-content) (the one you have to follow) gives the initial value as flex-start for justify-content and stretch for align-items. This is the Flexbox Level 1 specification and it's widely supported.
>
> The second one is related [to future alignment techniques](https://drafts.csswg.org/css-align-3/#propdef-justify-content). This specification is still in Draft …

fix(form-group): apply default value of justify-content, align-items property

---

.changeset/heavy-jars-behave.md
packages/bezier-react/src/components/Button/Button.mdx
packages/bezier-react/src/components/Button/Button.styled.ts
packages/bezier-react/src/components/Button/Button.test.tsx
packages/bezier-react/src/components/Button/Button.types.ts
packages/bezier-react/src/components/Button/__snapshots__/Button.test.tsx.snap

Fixes #0000 
This PR adds a `floating-alt` style variant in Button element.
No

Add floating-alt style variant in Button element

---

.changeset/strong-ducks-complain.md
packages/bezier-react/package.json
packages/bezier-react/src/components/Toast/Toast.stories.tsx
packages/bezier-react/src/components/Toast/Toast.types.ts
packages/bezier-react/src/components/Toast/ToastContext.ts
packages/bezier-react/src/components/Toast/ToastController.test.tsx
packages/bezier-react/src/components/Toast/ToastController.tsx
packages/bezier-react/src/components/Toast/ToastProvider.tsx
packages/bezier-react/src/components/Toast/ToastService.test.ts
packages/bezier-react/src/components/Toast/ToastService.ts
packages/bezier-react/src/components/Toast/useToast.ts
packages/bezier-react/src/components/Toast/useToastContextValues.test.tsx
packages/bezier-react/src/components/Toast/useToastContextValues.ts
yarn.lock

#894 
- add toast update feature for past toasts
- add version type in ToastType
- add update functions in ToastService
- add ToastService test
- migration ToastProvider functions to useToastContextValues hooks
- add useToastContextValues test, but this is deprecated.
https://user-images.githubusercontent.com/16330024/182978176-26b53b7b-9e19-4681-a1d1-1ef7d43fecb7.mov
No
#894 
https://github.com/channel-io/ch-desk-web/issues/10597
- [Figma](https://www.figma.com/file/82ho83cCj4n1FbD9ErU825/Contacts?node-id=4210%3A150677)
- [Notion - Contacts Bulk Action](https://www.notion.so/channelio/DB-BulkAction-1668569383ae412abf2b3e2cd479f73d)

add toast update feature for past toasts

---

.changeset/cuddly-eagles-serve.md
.changeset/seven-planes-serve.md
packages/bezier-react/src/foundation/Typography.ts

Fixes #912  
This PR adds `Size17` option to Typography
No
[Figma](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=1161%3A1)

feat(text): add size17 option to Text typography

---

.changeset/shy-sloths-collect.md
packages/bezier-react/src/components/Icon/Icon.types.ts

- 피그마 상의 icon size와 실제 구현이 일치하도록 수정합니다.
- IconSize.L: 34 => 36
- icon size가 변경됨에 따라 사용처의 레이아웃이 영향을 받게 됩니다. 따라서 각 사용처마다 확인이 필요합니다.
[피그마](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=966%3A4)

Update icon size L from 34px to 36px

---

packages/bezier-react/src/components/Avatars/Avatars.mdx
packages/bezier-react/src/components/Avatars/Avatars.stories.tsx
packages/bezier-react/src/stories/mdx.d.ts

`Components/Avatars` 에 속하는 Avatar 컴포넌트군 (`Avatar`, `CheckableAvatar`, `AvatarGroup`) 에 대한 documentation을 작성합니다.
- API 명세의 경우, `react-docgen-typescript-plugin` 적용 이후에 다시 살펴보도록 합니다.
스토리 확인 후 첨삭 부탁드립니다!
없음.

Add mdx documentation for Avatars component group

---

.changeset/rich-starfishes-notice.md
packages/bezier-react/src/components/Modals/Modal/Modal.styled.ts

Fixes #922 
- Change word-break property to `break-word` in Modal component
- No

Change word-break style of Modal content from break-all to break-word

---

.changeset/shiny-ears-end.md
packages/bezier-react/jest.setup.ts
packages/bezier-react/package.json
yarn.lock

None.
- Bump `@radix-ui/react-separator` to 1.0.0
- Add `ResizeObserver` jest mock to `jest.setup.ts`
- This is needed by `@radix-ui/react-use-size` hook, which Radix primitives internally use.
- Some commits are cherry-picked from #871: 559b45a5e7c53b7cd083d19f6627d4f66fcf786f c58d3688fa97a9010c3a55ea1f940901feba8bd5
No.
- https://www.npmjs.com/package/@radix-ui/react-separator
- https://www.radix-ui.com/docs/primitives/components/separator
- `ResizeObserver` mock implementation from: https://github.com/radix-ui/primitives/blob/83a8c13bf66f3d9f17d77caeb187a69eb146930b/scripts/setup-tests.ts

Bump @radix-ui/react-separator to 1.0.0, Add ResizeObserver jest mock

---

.changeset/flat-ghosts-poke.md
.changeset/strange-readers-grab.md
packages/bezier-react/src/components/Forms/FormControl/FormControl.styled.ts
packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
packages/bezier-react/src/components/Forms/FormLabel/FormLabel.styled.ts
packages/bezier-react/src/components/Forms/FormLabel/FormLabel.tsx
packages/bezier-react/src/components/Forms/FormLabel/__snapshots__/FormLabel.test.tsx.snap

- Windows: Chrome, Edge, (Optional) Firefox ❌
- macOS: Chrome, Edge, Safari, (Optional) Firefox ✅
없음
- 폼 유즈 케이스에서 라벨 컴포넌트의 영역이 150px로 고정되어있는걸 확인했습니다. `FormControl` 의 불필요한 `minmax` 스타일을 제거하고 고정 너비로 변경합니다.
- `FormLabel` 컴포넌트의 text-overflow를 방지하기 위해 `word-break: break-word` 스타일을 추가하고, Help 컴포넌트와 함께 사용될 경우도 마찬가지로 `flex-shrink` 속성을 추가합니다.
라벨이 길 경우 아래와 같이 줄넘김 처리가 됩니다.
No
- [Bezier Figma](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=1164%3A14992)

Enhance FormControl and FormLabel style to avoid text-overflow

---

.github/dependabot.yml

Fixes #854
dependabot이 잘 동작하도록 설정을 최신화합니다.
Github Docs를 참고하여 root, 개별 package, Github action에 대한 설정 및 관련 주석을 추가했습니다.
No
- [Configuring Dependabot version updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates)
- [Configuration options for the dependabot.yml file](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#vendor)
- [Dependabot can now generate security and version updates for Yarn v2 and v3](https://github.blog/changelog/2022-10-20-dependabot-can-now-generate-security-and-version-updates-for-yarn-v2-and-v3/)

chore(github): update dependabot config

---

.github/dependabot.yml

없음
```
The property '#/updates/0/' contains additional properties ["vendor"] outside of the schema when none are allowed
```
dependabot의 위 에러를 해결합니다.
[vendor](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#vendor) 옵션의 Package manager에 `npm` 은 없으나, [package-ecosystem](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem) 옵션의 표로 미루어보건데 yarn v2는 지원을 하는 것으로 판단하여 옵션을 추가했는데, 지원하지 않는 거 같아 제거합니다.
No
없음

chore(github): fix dependabot yml parsing error

---

.github/dependabot.yml

- https://github.com/dependabot/dependabot-core/issues/4993
- https://github.com/dependabot/dependabot-core/issues/5226
Fix dependabot config to update yarn.lock file and support monorepo structure
See also: [comment](https://github.com/dependabot/dependabot-core/issues/4993#issuecomment-1289133027)
> For those still looking for a solution: The solution is described here: #5226
> 
> Short version:
> 
> * Do not set up the `dependabot.yml` as described above (by listing each package individually) but by just listing the npm root like so:
> 
> ```
> version: 2
> updates:
>   - package-ecosystem: "npm"
>     directory: "/"
> ```
> 
> * To trigger dependabot to also properly fix the …

chore(github): fix dependabot config to update yarn.lock file and support monorepo structure

---

.changeset/witty-planets-exist.md
packages/bezier-react/src/components/TagBadge/TagBadgeCommon/utils.ts

- TagBadgeSize.XS font size is changed from Size12 to Size11

fix(tagbadge): make xs tagbadge more smaller

---

.changeset/stupid-meals-deliver.md
packages/bezier-react/src/components/Button/Button.styled.ts
packages/bezier-react/src/components/Icon/Icon.stories.tsx
packages/bezier-react/src/components/TagBadge/TagBadgeCommon/constants/TagBadgeVariant.ts
packages/bezier-react/src/foundation/Colors/Theme/presets/DarkTheme.ts
packages/bezier-react/src/foundation/Colors/Theme/presets/LightTheme.ts

None.
- Semantic color 업데이트에 따라 이를 `bezier-react`에 반영합니다.
- `bg-black-darkest` → black40(white40)에서 black60(white60)으로 변경
- `bg-black-darker` → black40(white40)으로 신설
- 이에 따라 `bg-black-darkest`로 적용되었던 컬러들은 `bg-black-darker`로 변경필요.
- 생략
Yes.
- `bg-black-darkest` is now `Palette.black_60` on `LightTheme`, `Palette.white_60` on `DarkTheme`.

Add `bg-black-darker` semantic color, update `bg-black-darkest` to black60(white60)

---

.changeset/good-keys-serve.md
packages/bezier-react/babel.config.js
packages/bezier-react/package.json
packages/bezier-react/rollup.config.js
packages/bezier-react/src/components/Avatars/CheckableAvatar/CheckableAvatar.styled.ts
yarn.lock

It reduce many whitespace of component style code in compiled source like this:
|:---:|:---:|
Size diff:
|:---:|:---:|
- Migrate typescript-plugin-styled-components to babel-plugin-styled-components for apply minify(for remove extra whitespace), pure(for remove dead code).
> There is minify option at typescript-plugin-styled-components, but that's not work for me. (maybe influence of FoundationStyledComponent's override)
- Hide comment on style code that's not removed automatically by minify
- No breaking change.

Reduce bundle size (apply minify for styled-components)

---

.changeset/purple-shrimps-play.md
packages/bezier-react/src/components/Banner/Banner.test.tsx
packages/bezier-react/src/components/Button/__snapshots__/Button.test.tsx.snap
packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
packages/bezier-react/src/components/Forms/FormLabel/__snapshots__/FormLabel.test.tsx.snap
packages/bezier-react/src/components/Forms/SegmentedControl/__snapshots__/SegmentedControl.test.tsx.snap
packages/bezier-react/src/components/KeyValueListItem/__snapshots__/KeyValueListItem.test.tsx.snap
packages/bezier-react/src/components/SectionLabel/SectionLabel.test.tsx
packages/bezier-react/src/components/Text/Text.styled.ts
packages/bezier-react/src/components/Text/Text.test.tsx

change the font-weight of bold text from 600 to 'bold'
BREAKING CHANGE: every bold text is changed from 'font-weight:600' to 'font-weight: bold'
Text 컴포넌트 prop으로 `bold={true}` 를 받았을 때, font-weight를 `600`이 아닌 `bold`로 설정합니다.
Bezier상 Typography의 스펙이 변경되어 대응합니다.
대표 사용처인 채널톡 Desk 어플리케이션과 이 bezier-react storybook에선 다음 폰트 정의을 가져다 쓰고 있습니다.
https://cf.channel.io/asset/font/Inter/inter.css
```css
@font-face {
font-family: 'Inter';
font-style:  normal;
font-weight: 400;
font-display: swap;
src: url("Inter-Regular.woff2?v=3.13") format("woff2"),
url("Inter-Regular.woff?v=3.13") format("woff");
}
@font-face {
font-family: 'Inter';
font-style:  italic;
font-weight: 400;
font-display: swap;
src: …
```

fix(text): change the font-weight of bold text

---

packages/bezier-react/src/components/ButtonGroup/ButtonGroup.mdx
packages/bezier-react/src/components/ButtonGroup/ButtonGroup.stories.tsx

Fixes #984  
- `ButtonGroup` 에 관한 mdx 가 잘못 작성되어 있는 부분을 수정합니다.
No

Fix typo in ButtonGroup mdx

---

.changeset/four-pugs-swim.md
packages/bezier-react/src/components/Modals/BaseModal/BaseModal.styled.ts
packages/bezier-react/src/components/Modals/BaseModal/__snapshots__/BaseModal.test.tsx.snap
packages/bezier-react/src/components/Modals/Modal/__snapshots__/Modal.test.tsx.snap

- ~~[ ] [Component] I wrote **a unit test** about the implementation.~~
- ~~[ ] [Component] I wrote **a storybook document** about the implementation.~~
- ~~[ ] [Component] I tested the implementation in **various browsers**.~~
- ~~Windows: Chrome, Edge, (Optional) Firefox~~
- ~~macOS: Chrome, Edge, Safari, (Optional) Firefox~~
- ~~[ ] [*New* Component] I added my username to the correct directory in the `CODEOWNERS` file.~~
None.
- 기존 모달(`BaseModal`)에 사용되는 appear 애니메이션을 애플리케이션의 사용성을 저해하지 않는 수준으로 개선합니다.
- 기존 모달의 애니메이션 keyframe은 다음과 같습니다.
```ts
const translateAnimation = keyframes`
from {
transform: translate(0, -122px);
}
to {
transform: translate(0, 0);
}
`
```
- 위에서 내려오는 애니메이션이 다음과 같은 이유로 모달에 적합하지 않다고 생각하였습니다:
- 컴포넌트 자체가 크게 이동하기 때문에 반복되는 모달 appear - disappear는 유저로 하여금 annoying하게 느껴질 수 …

Change `BaseModal` animation to scale-based animation

---

.changeset/witty-starfishes-shake.md
packages/bezier-react/src/components/Modals/Modal/ModalContent.tsx

Fixes #1019
Fix invalid value of `ModalTitleSize.M` from 15 to 16
`ModalTitleSize.M` should be `Typography.Size16`. Not ~`Typography.Size15`~
No
N/A

fix(ModalContent): invalid modal title size

---

.changeset/violet-ravens-help.md
packages/bezier-react/src/components/Stack/Stack/Stack.tsx
packages/bezier-react/src/components/Stack/Stack/Stack.types.ts

Fixes #996
`Stack` 의 `align` prop의 기본값을 `start` 에서 `stretch` 로 변경합니다.
#996 참고. [CSS Flexible Box Layout Module Level 1](https://drafts.csswg.org/css-flexbox-1/#align-items-property)의 스펙에 따르면, `align-items` 속성의 기본값은 `stretch` 입니다. 라이브러리를 사용하는 엔지니어들이 의도한대로 컴포넌트가 동작할 수 있도록, 기본값을 표준에 맞게 변경했습니다.
Yes
> 애플리케이션에서 대부분은 `stretch` 로 설정되어있으나, **기본값을 사용하고 있는 사용처가 몇 있어 마이그레이션이 필요합니다.**
- [CSS Flexible Box Layout Module Level 1](https://drafts.csswg.org/css-flexbox-1/#align-items-property)

Change the default value of the `Stack`'s `align` prop from `start` to `stretch`

---

.changeset/moody-tigers-relax.md
packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.styled.ts
packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.tsx

Fixes #820
베지어 디자인 시스템 시안과 동일하게 `TextField` 컴포넌트의 텍스트 스타일을 적용합니다.
- `input` 엘리먼트의 불필요한 `size` attribute를 제거합니다. ([MDN](https://developer.mozilla.org/ko/docs/Web/HTML/Element/Input#attr-size))
- 나머지는 스토리북을 참고 부탁드립니다.
No
없음

Update the font-size of `TextField`

---

packages/bezier-react/src/components/ProgressBar/ProgressBar.mdx
packages/bezier-react/src/components/ProgressBar/ProgressBar.stories.tsx
packages/bezier-react/src/components/ProgressBar/ProgressBar.test.tsx
packages/bezier-react/src/components/ProgressBar/ProgressBar.tsx
packages/bezier-react/src/components/ProgressBar/index.ts

- ~~[ ] [Component] I wrote **a unit test** about the implementation.~~
- ~~[ ] [Component] I wrote **a storybook document** about the implementation.~~
- ~~[ ] [Component] I tested the implementation in **various browsers**.~~
- ~~Windows: Chrome, Edge, (Optional) Firefox~~
- ~~macOS: Chrome, Edge, Safari, (Optional) Firefox~~
Closes #1034
- `ProgressBar` 컴포넌트에 대한 mdx documentation을 작성합니다.
- Storybook preview 확인 후 첨삭 부탁드립니다 🙏 
No.

Write mdx documentation for `ProgressBar` component

---

.changeset/serious-bags-buy.md
packages/bezier-react/src/components/Text/Text.styled.ts

Fixes #1016
`Text` component should support CSS interpolation but currently not. So I had add code to handling this `interpolation` prop.
`interpolation` prop which is declared in `StylableComponentProps` is injectable but not working because there is no handling code currently in `Text.styled.ts` style file.
So I had add some handling code to `Text.styled.ts` style file.
```typescript
const Text = styled.span<TextProps & TextStyledProps>`
${props => props.typo};
${props => props.interpolation};  /* → added */
...
`
```
I thought that it should be placed after `props.typo` because 'used-place' level injected style is worth than 'code-level' of component.
No
N/A

fix(Text): add handling code for unhandled interpolation prop

---

.changeset/tender-books-crash.md
packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.tsx

없음
#1028 에서 함께 삭제한 `input` 의 `size` 속성을 되돌립니다.
#1028 에서 TextField 컴포넌트의 사이즈별 폰트 사이즈를 업데이트하며, 내부 input 엘리먼트의 불필요한(하다고 생각한) size 속성을 제거했습니다. `TextFieldSize` enum은 input 엘리먼트를 감싸는 Wrapper(div) 스타일 컴포넌트에게 주입하여 텍스트 필드의 높이를 결정하는 데 사용하는 값이었기때문에, 잘못 설정된 속성이라고 생각해서 내린 결정이었습니다.
문제는 input 엘리먼트의 [size 속성](https://developer.mozilla.org/ko/docs/Web/HTML/Element/Input#attr-size)이 유효한 속성이라는 점입니다. 예를 들어 `TextFieldSize.M` 의 값은 36인데, 이 값을 size 에 주었을 경우 input 엘리먼트는 36개의 글자가 보일 수 있는 만큼의 너비로 설정됩니다. 이 너비는 폰트마다 달라서, Condensed 폰트의 경우와 일반적인 너비를 가진 폰트일 경우의 너비가 다르게 설정됩니다. 
이번에 데스크에 bezier-react 마이그레이션을 하면서 어플리케이션 전반적으로 일부 UI에서 input 엘리먼트의 size 속성을 통해 암묵적으로 정해진 너비(M 기준 302px)를 사용하고 있었다는 걸 알게 되었습니다. 이런 케이스가 꽤나 많아서(***Modal, …

Revert the removed `size` property of the `TextField`'s internal `input` element

---

.changeset/orange-zoos-scream.md
packages/bezier-react/src/components/Banner/Banner.test.tsx
packages/bezier-react/src/components/Button/Button.test.tsx
packages/bezier-react/src/components/Button/__snapshots__/Button.test.tsx.snap
packages/bezier-react/src/components/Forms/FormControl/FormControl.test.tsx
packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.test.tsx
packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.tsx
packages/bezier-react/src/components/Forms/FormHelperText/__snapshots__/FormHelperText.test.tsx.snap
packages/bezier-react/src/components/Forms/FormLabel/__snapshots__/FormLabel.test.tsx.snap
packages/bezier-react/src/components/Forms/Inputs/Select/Select.test.tsx
packages/bezier-react/src/components/Forms/Inputs/Select/__snapshots__/Select.test.tsx.snap
packages/bezier-react/src/components/Forms/Inputs/TextArea/__snapshots__/TextArea.test.tsx.snap
packages/bezier-react/src/components/Forms/SegmentedControl/__snapshots__/SegmentedControl.test.tsx.snap
packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.test.tsx
packages/bezier-react/src/components/KeyValueListItem/__snapshots__/KeyValueListItem.test.tsx.snap
packages/bezier-react/src/components/ListItem/__snapshots__/ListItem.test.tsx.snap
packages/bezier-react/src/components/Navigator/NavGroup/__snapshots__/NavGroup.test.tsx.snap
packages/bezier-react/src/components/Navigator/NavItem/__snapshots__/NavItem.test.tsx.snap
packages/bezier-react/src/components/SectionLabel/SectionLabel.test.tsx
packages/bezier-react/src/components/Text/Text.stories.tsx
packages/bezier-react/src/components/Text/Text.styled.ts
packages/bezier-react/src/components/Text/Text.test.tsx
packages/bezier-react/src/components/Text/Text.tsx
packages/bezier-react/src/components/Text/Text.types.ts
packages/bezier-react/src/components/Text/index.ts
packages/bezier-react/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
packages/bezier-react/src/foundation/Typography.ts

- #1066 
`Text` 컴포넌트의 마이너 개선사항들이 포함됩니다.
- 내부적으로 CSS Variable을 사용하여 스타일 컴포넌트(className)를 재생성하지 않도록 개선합니다.
- `Typography` CSS Interpolation에 심볼을 사용해 개별 스타일 속성에 접근할 수 있도록 변경합니다.
- 관련 테스트 케이스와 스냅샷을 업데이트합니다.
No
없음

Enhance the `Text` component

---

.changeset/big-penguins-compare.md
packages/bezier-react/.storybook/preview.js
packages/bezier-react/src/components/Modals/Modal/Modal.stories.tsx
packages/bezier-react/src/components/Modals/Modal/Modal.styled.ts
packages/bezier-react/src/components/Modals/Modal/ModalAnimation.styled.ts
packages/bezier-react/src/components/Modals/Modal/ModalContent.tsx

없음
`Modal` 컴포넌트를 애플리케이션에 적용하면서, 부족한 부분들을 개선합니다.
- `Modal` 내부에 Overlay 컴포넌트가 포함될 경우, Portal을 통해 동일하게 rootElement(body) 아래 렌더하는 케이스에서 Overlay 컴포넌트에 클릭이 불가능한 문제가 있었습니다. `Modal` 이 `modal={true}` 속성을 가져 외부에 이벤트가 전달되지 않기 때문입니다. 이를 해결하고자 overflow hidden 속성을 제거하고 오버레이 영역 전체가 스크롤 가능하게 변경했습니다. 애플리케이션에서는 Overlay container 속성 지정을 통해 `Modal` 내부에 그리는 방식으로 구현하게 됩니다.
- 관련해서 UI를 테스트해볼 수 있도록 스토리를 개선합니다.
어플리케이션에서 `onHide` 콜백 호출 시, 즉시 특정 상태가 변경되며 UI가 바뀌는 케이스가 있습니다. 애니메이션이 있을 경우 의도치 않은 UI가 애니메이션 실행 시간동안 노출되는 문제가 있어 우선 제거합니다.
`ModalBody` 가 다른 엘리먼트의 자식이 된 경우에도 스타일링이 잘 적용될 수 있도록 CSS 선택자를 개선합니다.
root에 css variable을 추가하여 오버레이 색상이 잘 표시되도록 합니다.
No
- https://www.radix-ui.com/docs/primitives/components/dialog#scrollable-overla …

Enhance the `Modal` component

---

.changeset/beige-rice-shout.md
packages/bezier-react/jest.setup.ts
packages/bezier-react/src/components/Forms/Slider/Slider.stories.tsx
packages/bezier-react/src/components/Forms/Slider/Slider.test.tsx
packages/bezier-react/src/components/Forms/Slider/Slider.tsx

Enhance/fix the `Slider` component
Enhancement
- It now observes the `value` prop and change the `currentValue` state.
Fix
- Render the thumbs through `currentValue` state instead of `defaultValue` prop.
- Fix: Always rerender when the `currentValue` is changed
https://user-images.githubusercontent.com/14245930/206171410-8d312826-9572-4d55-9330-407bc5d2a963.mov
No
None

Enhance the `Slider` Component

---

.changeset/orange-zoos-scream.md
.changeset/young-parrots-happen.md
packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
packages/bezier-react/src/components/Banner/Banner.test.tsx
packages/bezier-react/src/components/Button/Button.test.tsx
packages/bezier-react/src/components/Button/__snapshots__/Button.test.tsx.snap
packages/bezier-react/src/components/Forms/FormControl/FormControl.test.tsx
packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.test.tsx
packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.tsx
packages/bezier-react/src/components/Forms/FormHelperText/__snapshots__/FormHelperText.test.tsx.snap
packages/bezier-react/src/components/Forms/FormLabel/__snapshots__/FormLabel.test.tsx.snap
packages/bezier-react/src/components/Forms/Inputs/Select/Select.test.tsx
packages/bezier-react/src/components/Forms/Inputs/Select/__snapshots__/Select.test.tsx.snap
packages/bezier-react/src/components/Forms/Inputs/TextArea/__snapshots__/TextArea.test.tsx.snap
packages/bezier-react/src/components/Forms/SegmentedControl/__snapshots__/SegmentedControl.test.tsx.snap
packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.test.tsx
packages/bezier-react/src/components/KeyValueListItem/__snapshots__/KeyValueListItem.test.tsx.snap
packages/bezier-react/src/components/ListItem/__snapshots__/ListItem.test.tsx.snap
packages/bezier-react/src/components/Navigator/NavGroup/__snapshots__/NavGroup.test.tsx.snap
packages/bezier-react/src/components/Navigator/NavItem/__snapshots__/NavItem.test.tsx.snap
packages/bezier-react/src/components/SectionLabel/SectionLabel.test.tsx
packages/bezier-react/src/components/Text/Text.stories.tsx
packages/bezier-react/src/components/Text/Text.styled.ts
packages/bezier-react/src/components/Text/Text.test.tsx
packages/bezier-react/src/components/Text/Text.tsx
packages/bezier-react/src/components/Text/Text.types.ts
packages/bezier-react/src/components/Text/index.ts
packages/bezier-react/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
packages/bezier-react/src/foundation/Typography.ts

- #1066
This reverts commit 65cdafa78b5551e39f657440ac54cc833c678163.
어플리케이션의 사이드 이펙트 및 Badge 등 컴포넌트에서 케스케이딩이 예상한대로 동작하지 않는 문제가 있어 Revert하고, 추후 개선 예정입니다.
No
없음

Revert "Enhance the `Text` component (#1068)"

---

packages/bezier-react/package.json
packages/bezier-react/src/components/Toast/useToastContextValues.test.tsx
yarn.lock

- react-hooks-testing-library(`@testing-library/react-hooks`)의 사용처를 제거합니다.
- `@testing-library/react-hooks` 라이브러리를 제거합니다.
- `@testing-library/react-hooks` 대신 `@testing-library/react`의 `renderHook`을 사용하도록 합니다.
- React 18을 사용할 경우, `@testing-library/react`에서 제공하는 `renderHook`을 사용하도록 권장하고 있습니다.
> As part of the changes for React 18, it has been decided that the renderHook API provided by this library will instead be included as official additions to both react-testing-library (https://github.com/testing-library/react-testing-library/pull/991) and react-native-testing-library (https://github.com/callstack/react-native-testing-library/pull/923) with the intention being to provide a more cohesive and …

Remove `@testing-library/react-hooks` from dependencies

---

.changeset/mighty-olives-deliver.md
packages/bezier-react/src/components/Modals/Modal/Modal.styled.ts

없음.
`Modal` 컴포넌트의 스타일을 개선합니다.
`inset` CSS 속성의 경우, 몇몇 구버전 브라우저에서 지원하지 않습니다. 동일한 기능을 하는 CSS 속성으로 변경합니다.
No
- https://caniuse.com/?search=inset

refactor(modal): change from inset to top..left style to support legacy version chrome browser

---

.changeset/thick-zoos-clap.md
packages/bezier-react/src/components/Button/Button.styled.ts
packages/bezier-react/src/components/Button/__snapshots__/Button.test.tsx.snap

- Decrease horizontal padding of `ButtonSize.XS` size `Button` to 2px
No
- [Figma](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=7463%3A70383&t=xMsOVdpIvqkQCguP-4)

Decrease horizontal padding of `ButtonSize.XS` size `Button` to 2px

---

.changeset/real-vans-tie.md
packages/bezier-react/src/components/Stack/Stack/Stack.test.tsx
packages/bezier-react/src/components/Stack/Stack/Stack.tsx

Fixes #1116 
- 첫 번째 `StackItem` 이 원하지 않는 `marginBefore` 를 갖는 버그를 수정합니다.
- 기존 코드에서는 valid element (=`ReactElement`. 참고로 `string`, `boolean`, `null` 등은 `ReactElement` 가 아닌 `ReactNode` 입니다) 라면 `index > 0` 만 검사하였기 때문에 아래와 같은 상황에서 원치 않은 `marginBefore` 가 들어갔습니다.
```typescript
<Stack spacing={10}>
{ false && <FirstComponent /> }
<SecondComponent /> //  marginBefore is set to 10
<Stack>
```
- 이제 가장 첫번째 **valid** element 다음에 나오는 element 에 대해서만 `marginBefore` 를 줍니다.
- 처음으로 했던 시도는 `React.Children.toArray(children).findIndex(...)` 과 같이 `children` 을 미리 검사하는 방법으로 첫번째 valid한 element 의 index 를 찾으려고 했으나, `toArray` 자체가 valid 한 element 만 filter 하기 때문에 사용하지 못했습니다. 따라서 `useRef` 를 사용하여 로직을 만들었습니다.
- No
- …

Fix bug that first `StackItem` has `marginBefore` when preceding node is not JSX.Element

---

.changeset/modern-pants-applaud.md
packages/bezier-react/src/components/Icon/Icon.tsx

#1123
`Icon` 컴포넌트의 이벤트 핸들러 props에 default value를 할당하지 않도록 수정합니다.
- `onClick`
- `onMouseDown`
`Icon`의 `onClick` prop에 default value(`noop`, `() => {}`)가 할당됨으로 인해 문제를 일으키는 경우가 있습니다.
아래의 조건을 만족할 경우 [a 태그의 telephone number link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#linking_to_telephone_numbers)(`tel:`)가 제대로 동작하지 않습니다.
1. iPad의 Safari 브라우저일 때
2. a 태그의 하위 엘리먼트 중 `onclick` attribute가 등록된 엘리먼트가 존재할 때
예를 들어 아래와 같은 usecase가 있습니다.
```html
<a href="tel:+49.157.0156">
<div onclick="doSomething()"></div>
</a>
```
`Icon`을 활용하여 `tel:` link로 연결되는 버튼/링크를 만드는 경우 아래와 같은 구조를 가질 수 있습니다.
```jsx
<a href={telHref} target="_blank">
<Icon source={CallIcon} size={IconSize.S} />
</a>
```
이때, iPad의 …

Remove default value of event handler props in `Icon` component

---

.changeset/spicy-peas-poke.md
packages/bezier-react/package.json
yarn.lock

Skip
```bash
../node_modules/@channel.io/bezier-react/node_modules/@babel/runtime/helpers/esm/extends.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export default function _extends() {
^^^^^^
SyntaxError: Unexpected token 'export'
at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1796:14)
at Object.<anonymous> (../../node_modules/@channel.io/bezier-react/build/index.cjs.js:9:16)
```
위 에러를 해결합니다.
- Revert https://github.com/channel-io/bezier-react/commit/0cb62c0fe9968bc0110ba516755a8e1052065491
No
- 리버트 후 정상 동작 확인

Fix unexpected babel runtime error

---

.changeset/grumpy-islands-sit.md
packages/bezier-react/src/components/Forms/FormGroup/FormGroup.tsx
packages/bezier-react/src/components/Forms/Radio/Radio.tsx
packages/bezier-react/src/components/Forms/Radio/Radio.types.ts
packages/bezier-react/src/components/Forms/RadioGroup/Radio.tsx
packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.tsx
packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.types.ts

없음
`RadioGroup`, `Radio` 컴포넌트를 개선합니다.
- 컴포넌트 타입에 제네릭을 적용합니다. `string` 외 `enum` 등의 케이스에서도 타입 에러 없이 사용할 수 있도록 합니다.
- `RadioGroup` 의 `children` 타입을 `React.ReactNode` 로 변경합니다. 다양한 유즈케이스에서도 타입 에러 없이 잘 동작하도록 변경합니다. 
- `Radio` 에 children이 존재하는 케이스에만 내부 라벨을 렌더하도록 변경합니다. 라벨이 없는 유즈케이스를 커버하기 위한 변경입니다.
- chore: 레거시 라디오 컴포넌트에 deprecated 주석을 추가합니다.
No
없음

Enhance `RadioGroup` component

---

.changeset/afraid-kids-do.md
packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.stories.tsx
packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.styled.ts
packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.test.tsx
packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.types.ts

없음
value의 타입 추론이 잘 이루어지도록 개선하고, 관련 테스트(스토리)를 추가합니다.
생략
No
- #1131

Delete `RadioGroup`'s default generic parameter to fix type inferencing

---

.changeset/dull-phones-invent.md
packages/bezier-react/src/components/Forms/Inputs/Select/Select.styled.ts
packages/bezier-react/src/components/Forms/Inputs/Select/Select.tsx
packages/bezier-react/src/components/Forms/Inputs/Select/__snapshots__/Select.test.tsx.snap
packages/bezier-react/src/components/KeyValueListItem/__snapshots__/KeyValueListItem.test.tsx.snap
packages/bezier-react/src/components/KeyValueListItem/common/KeyItem/KeyItem.styled.ts
packages/bezier-react/src/components/KeyValueListItem/common/KeyItem/KeyItem.tsx
packages/bezier-react/src/components/Modals/LegacyModal/Modal.styled.ts
packages/bezier-react/src/components/Modals/LegacyModal/ModalContent.tsx
packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.styled.ts
packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.tsx
packages/bezier-react/src/components/Navigator/NavGroup/__snapshots__/NavGroup.test.tsx.snap
packages/bezier-react/src/components/Navigator/NavItem/NavItem.styled.ts
packages/bezier-react/src/components/Navigator/NavItem/NavItem.tsx
packages/bezier-react/src/components/Navigator/NavItem/__snapshots__/NavItem.test.tsx.snap
packages/bezier-react/src/components/Text/Text.stories.tsx
packages/bezier-react/src/components/Text/Text.styled.ts
packages/bezier-react/src/components/Text/Text.test.tsx
packages/bezier-react/src/components/Text/Text.tsx
packages/bezier-react/src/components/Text/Text.types.ts

Fixes #629  
- `Text` 컴포넌트에 `truncated` 속성을 추가합니다.
- 현재 베지어 Text 컴포넌트는 `span`(inline 엘리먼트)을 사용하고 있습니다. inline 엘리먼트에서는 `text-overflow` 속성을 제대로 적용할 수 없습니다.(inline 엘리먼트는 너비를 가지지 않고 컨텐츠 크기만큼 공간을 차지함)
> The text-overflow property only affects content that is overflowing a **block container element** in its inline progression direction
따라서, `truncated` 옵션을 주었을 때 `text-overflow`가 제대로 적용될 수 있도록 `display: block` 속성도 추가하였습니다.
- (고민되는 부분) `display: block` 속성을 추가하는 것에 있어 `block`이라는 prop을 하나 더 열어주고, 말줄임 속성을 적용하고 싶으면 `block`, `truncated`를 둘 다 적용하는 방식이 더 명확하게 display 속성이 block으로 변화되는 것을 알 수 있다는 생각이 들었습니다.
(#487 에서 예기치 못하게 inline -> block 속성으로 변경되어서 문제가 된 적이 있기 때문에)
하지만 사용처에서 항상 `block`, `trucated`를 같이 적용해야한다는 …

Add `truncated` prop to Text component

---

.changeset/dirty-shrimps-talk.md
packages/bezier-react/src/components/Overlay/Overlay.styled.ts
packages/bezier-react/src/components/Overlay/Overlay.tsx

없음
인터페이스에 정의되어 있으나 `Overlay` 에 제대로 전달되고 있지 않던 속성이 올바르게 전달되도록 수정합니다.
- 불필요한 타입 단언 제거
No
없음

fix(overlay): pass missing props

---

.github/workflows/prereleased.yml

없음
Prerelease가 완료되면 채널톡 데스크 어플리케이션의 릴리즈 방에 알림 메세지를 보내는 GitHub action을 구현합니다.
- 개인 private repository에서 테스트한 스크린샷으로, 위와 같은 형태로 메세지가 전달됩니다.
- 인하우스의 메세지 알림이 일반적인 릴리즈에선 정상적으로 동작하나, 프리릴리즈에 대해서는 지원하지 않고 있기 때문에 자체적으로 액션을 구현했습니다. 메세지 파싱 로직이 인하우스에 구현된 것만큼 완벽하지 않기 때문에, 릴리즈 바디 대신에 주소를 첨부하는 방식으로 대체 구현했습니다.
- **TODO: Repo 토큰을 ch-builder의 토큰으로 변경해야함.**
No
- https://docs.github.com/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=prereleased#release
- https://github.com/channel-io/ch-web-github-actions

ci(github): create an action to send notifications to the Channel Desk app

---

.changeset/quick-ravens-dance.md
packages/bezier-react/src/components/Button/Button.styled.ts
packages/bezier-react/src/components/Button/Button.tsx
packages/bezier-react/src/components/Button/__snapshots__/Button.test.tsx.snap
packages/bezier-react/src/components/Modals/Modal/Modal.styled.ts

없음
버튼에 포커스 스타일을 추가합니다.
- 기본적으로 버튼은 `focus-visible` 한 상태에서만 포커스 스타일을 가지도록 구현했습니다. 마우스 포인터로 포커스할 땐 포커스 스타일이 나타나지 않도록 하기 위해서입니다.
- 모달이 열릴 때, `focus-visible` 스타일만 적용해서는 포커스 링이 보이지 않아 임시로 모달 내부에선 버튼 컴포넌트에 `focus` 스타일을 부여하는 방식으로 구현했습니다. data attributes를 통해 구현했는데, 썩 마음에 드는 방식은 아니라서 피드백 주시면 감사하겠습니다.
No
없음

Add focused style to `Button` component

---

.changeset/hungry-islands-judge.md
.github/CODEOWNERS
packages/bezier-react/src/components/AlphaCenter/AlphaCenter.stories.tsx
packages/bezier-react/src/components/AlphaCenter/AlphaCenter.styled.ts
packages/bezier-react/src/components/AlphaCenter/AlphaCenter.test.tsx
packages/bezier-react/src/components/AlphaCenter/AlphaCenter.tsx
packages/bezier-react/src/components/AlphaCenter/AlphaCenter.types.ts
packages/bezier-react/src/components/AlphaCenter/index.ts
packages/bezier-react/src/index.ts

Fixes #638 
컨텐츠를 가운데 정렬할 때 사용되는 레이아웃 컴포넌트인 `AlphaCenter` 컴포넌트를 구현합니다.
- #638 참고.
- 디자인 시스템 리디자인이 진행되면서 내부 구현/인터페이스가 변경될 수 있으므로, `Alpha` prefix를 추가했습니다.
No
없음

Implement `AlphaCenter` component

---

.changeset/proud-countries-breathe.md
.github/CODEOWNERS
packages/bezier-react/src/components/Forms/FormLabel/FormLabel.tsx
packages/bezier-react/src/components/Modals/Modal/ModalHeader.tsx
packages/bezier-react/src/components/VisuallyHidden/VisuallyHidden.test.tsx
packages/bezier-react/src/components/VisuallyHidden/VisuallyHidden.tsx
packages/bezier-react/src/components/VisuallyHidden/VisuallyHidden.types.ts
packages/bezier-react/src/components/VisuallyHidden/index.ts
packages/bezier-react/src/index.ts
yarn.lock

Fixes #1165 
`VisuallyHidden` 컴포넌트를 구현합니다.
- `VisuallyHidden` 컴포넌트 구현: 이슈 참고
- `ModalHeader` 에서 내부 `VisuallyHidden` 컴포넌트를 import해서 사용하도록 리팩토링
- 주로 내부에서 사용하는 유틸성 컴포넌트라, 스토리북은 큰 의미가 없다고 판단하여 추가하지 않았습니다.
No
- https://www.radix-ui.com/docs/primitives/utilities/visually-hidden

Implement `VisuallyHidden` component

---

CONTRIBUTING.md

None
`yarn global add` 스크립트는 yarn berry 이후 deprecated되어 이를 대체하는 `yarn dlx` 커맨드로 수정합니다.
https://yarnpkg.com/getting-started/migration#use-yarn-dlx-instead-of-yarn-global

docs(contributing): change yarn global add to dlx

---

.github/workflows/chromatic.yml
.github/workflows/prerelease.yml

None
Migrate legacy set-output syntax
See Reference
No
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

chore(github): migrate legacy set-output syntax

---

.changeset/heavy-rivers-punch.md
packages/bezier-react/src/foundation/Colors/Palette/index.ts
packages/bezier-react/src/foundation/Colors/Theme/presets/DarkTheme.ts
packages/bezier-react/src/foundation/Colors/Theme/presets/LightTheme.ts
packages/bezier-react/src/foundation/Colors/Theme/types/SemanticNames.ts
packages/bezier-react/src/foundation/Typography.ts

add new foundation specs for meet feature
add 2 color palette
- grey50_80
- grey850_80
add 2 text specs
- size30
- size36
add 3 semantic colors
- bg-grey-dim-lightest
- light: grey50_80
- dark: grey850_80
No
[desk thread](https://desk.channel.io/root/threads/groups/Bezier-62019/6419ace441e99b8c4fa0/6419ace441e99b8c4fa0)
[figma](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=1711%3A2160&t=CxTXratExzVN1YC9-1)

Add new palette & text specs

---

.changeset/thirty-birds-develop.md
packages/bezier-react/src/components/Avatars/Avatar/Avatar.tsx

없음
`Avatar` 의  default avatar asset 경로를 상대 경로로 변경합니다.
라이브러리 사용처에서 아래와 같이 module resolve error가 발생하는 케이스를 수정합니다. (#1109 이전으로 롤백)
```
Uncaught Error: Cannot find module '~/src/components/Avatars/assets/defaultAvatar.svg'
at webpackMissingModule (Avatar.js:12:50)
at eval (Avatar.js:12:174)
at ./node_modules/@channel.io/bezier-react/build/src/components/Avatars/Avatar/Avatar.js (bundle.js:6767:1)
at options.factory (bundle.js:86921:31)
at __webpack_require__ (bundle.js:86275:33)
at fn (bundle.js:86563:21)
at eval (ManagerAvatar.tsx:12:83)
at ./src/components/ManagerAvatar/ManagerAvatar.tsx (bundle.js:22051:1)
at options.factory (bundle.js:86921:31)
at __webpack_require__ (bundle.js:86275:33)
```
No …

Fix module resolve error in library usage

---

.changeset/silent-mayflies-change.md
packages/bezier-react/src/components/Forms/Checkbox/Checkbox.stories.tsx
packages/bezier-react/src/components/Forms/Checkbox/Checkbox.styled.ts
packages/bezier-react/src/components/Forms/Checkbox/Checkbox.test.tsx
packages/bezier-react/src/components/Forms/Checkbox/Checkbox.tsx
packages/bezier-react/src/components/Forms/Checkbox/Checkbox.types.ts

None
`Checkbox` 컴포넌트의 `checked` prop에 제네릭 타입을 적용합니다.
`checked` 의 타입, `CheckedState` 는 `boolean | 'indeterminate'` 입니다. 여기서 `'indeterminate'` 타입은 체크박스 유즈 케이스상 사용처가 거의 없고, 대부분은 `boolean` 으로만 상태를 컨트롤합니다. 이러한 대부분의 케이스에서 불필요한 `'indeterminate'` 타입이 에러를 발생시키는 불편함을 해소하기위해 `checked` prop에 제네릭 타입을 적용합니다.
No
None

feat(checkbox): apply a generic type to the checked type of Checkbox

---

.changeset/friendly-spoons-enjoy.md
packages/bezier-react/src/components/Forms/Checkbox/Checkbox.test.tsx
packages/bezier-react/src/components/Forms/Checkbox/Checkbox.tsx

None
`FormControl` 컨텍스트 아래 있을 때, 해당 컨텍스트의 id가 `Checkbox` 컴포넌트에 직접 주입한 id를 덮어씌우는 문제를 해결합니다.
Skip
No
None

fix(checkbox): fix FormControl's id always overrides Checkbox's id prop

---

package.json
packages/bezier-figma-plugin/.lintstagedrc.json
packages/bezier-react/.lintstagedrc.json
packages/bezier-react/package.json
yarn.lock

None
Precommit 관련 개발 환경을 개선합니다.
- Husky 최신 버전 업데이트
- Yarn 2+ 에서 지원하지 않는 `prepare` script을 `postinstall` 스크립트로 전환 ([#](https://typicode.github.io/husky/#/?id=install))
- `jest --onlyChanged` 추가: 의존성을 파악하여 변경된 모듈에 해당하는 부분만 테스트 케이스가 실행되도록 개선
- lintstaged의 path가 lint 스크립트의 path와 동일하게 개선 
No
None

Enhance pre-commit related configuration

---

.changeset/popular-gifts-sparkle.md
.github/CODEOWNERS
packages/bezier-react/package.json
packages/bezier-react/src/components/AutoFocus/AutoFocus.test.tsx
packages/bezier-react/src/components/AutoFocus/AutoFocus.tsx
packages/bezier-react/src/components/AutoFocus/AutoFocus.types.ts
packages/bezier-react/src/components/AutoFocus/index.ts
packages/bezier-react/src/components/Modals/Modal/Modal.test.tsx
packages/bezier-react/src/index.ts
yarn.lock

None
`AutoFocus` 컴포넌트를 추가합니다.
`AutoFocus` 컴포넌트는 autoFocus 기능을 사용처에서 선언적으로 사용할 수 있도록 만들어진 컴포넌트입니다. 하위 Children의 노드가 도큐먼트에 추가될 때, 포커스가 해당 노드로 이동하도록 합니다.
`Modal` 이 마운트될 때 특정 버튼 등에 포커스가 이동하도록 구현하고 싶은 경우 사용하기 적합합니다.
```tsx
<AutoFocus>
<button>Close</button>
</AutoFocus>
```
- 구현을 위해 Radix UI의 Slot 패키지 추가
No
- https://www.radix-ui.com/docs/primitives/utilities/slot

Introduce `AutoFocus` component

---

.changeset/new-pots-brake.md
packages/bezier-react/src/components/Tooltip/Tooltip.stories.tsx
packages/bezier-react/src/components/Tooltip/Tooltip.tsx
packages/bezier-react/src/components/Tooltip/Tooltip.types.ts
packages/bezier-react/src/components/Tooltip/TooltipContent.tsx
packages/bezier-react/src/components/Tooltip/utils.ts

None
`Tooltip` 에 `container` 속성을 추가합니다.
`Overlay` 와 동일하게, 별도의 `container` 속성을 지정하면 해당 노드 아래에 렌더되도록 할 수 있습니다.
No. container를 지정하지 않을 경우 기본값은 `getRootElement()` 의 반환값으로 동일합니다.
None

feat(tooltip): add container prop

---

.circleci/config.yml
package.json
packages/bezier-react/package.json
turbo.json

None
#1251 의 사이드 이펙트 해소. 4449f8f 에서 `--onlyChanged` flag가 추가되면서 테스트 커버리지가 제대로 수집되고 있지 않던 문제를 해결합니다.
`test:ci` 워크스페이스 공용 커맨드를 추가하여, precommit용 테스트 커맨드와 ci용 테스트 커버리지 수집을 위한 커맨드를 구분하는 방식으로 수정합니다.
No
None

Fix an issue with code coverage not being collected properly

---

.changeset/sour-pears-type.md
packages/bezier-react/src/components/AlphaStack/AlphaStack.styled.ts
packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
packages/bezier-react/src/components/Forms/FormGroup/__snapshots__/FormGroup.test.tsx.snap

- #1249 
Remove the 100% width, 100% height style from AlphaStack component
> `FormGroup` 스타일링이 틀어짐. 우측 참고
- `FormGroup` 에서 `height: 100%` 스타일이 `flex-wrap` 과 결합 시 의도치 않게 스타일링이 됩니다. 이를 해결합니다.
- 또한 width, height 100% 스타일은 `Stack` 컴포넌트의 정책으로 정해진 스타일이기때문에, `AlphaStack` 컴포넌트에 그대로 옮겨올 필요는 없다고 판단했습니다. (레퍼런스 참고)
- See #698
No
- https://chakra-ui.com/docs/components/stack
- https://polaris.shopify.com/components/layout-and-structure/alpha-stack

Remove the 100% width, 100% height style from `AlphaStack` component

---

.changeset/metal-ways-beg.md
packages/bezier-react/src/components/Forms/FormControl/FormControl.stories.tsx
packages/bezier-react/src/components/Forms/FormControl/FormControl.styled.ts
packages/bezier-react/src/components/Forms/FormControl/FormControl.test.tsx
packages/bezier-react/src/components/Forms/FormControl/FormControl.tsx
packages/bezier-react/src/components/Forms/FormControl/FormControl.types.ts
packages/bezier-react/src/components/Forms/FormControl/FormControlContext.ts
packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
packages/bezier-react/src/components/Forms/FormControl/index.ts
packages/bezier-react/src/components/Forms/FormGroup/FormGroup.tsx
packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.tsx

None
`FormControl` 컴포넌트를 개선합니다.
- forwardRef를 추가합니다.
- `useEffect` 를 통해 마운트 여부를 체크하던 로직을 Callback ref를 사용한 방식으로 리팩토링합니다. 컨텍스트 사용처에서 더 깔끔한 방식으로 마운트 여부를 체크할 수 있도록 합니다.
- 정확히 말하면 리팩토링은 아닙니다. 기존의 마운트 여부를 React Component 라이프사이클에서 DOM Node의 라이프사이클(렌더링 여부)로 체크하도록 변경했기때문에 더 의도에 맞는 코드가 되었습니다.
- TODO Resolve: labelPosition top일 때, Wrapper에 `AlphaStack` 을 사용하도록 리팩토링합니다.
- labelPosition left일 때, styled prop을 통해 leftLabelHeight를 전달받던 것을 CSS Variable로 리팩토링합니다.
- 기타 스타일 수정
No
None

Enhance `FormControl` component

---

.changeset/sixty-meals-drum.md
packages/bezier-react/src/components/AutoFocus/AutoFocus.tsx
packages/bezier-react/src/hooks/useMergeRefs.ts

None
state가 변할 때마다 `AutoFocus` 의 `HTMLElement.focus()` 메서드가 실행되는 버그를 수정합니다.
기존의 ref callback을 사용한 구현을 `useState`, `useLayoutEffect` 를 사용한 구현으로 변경했습니다. 
> _Unless you pass the same function reference for the ref callback on every render_, the callback will get temporarily detached and re-attached during ever re-render of the component.
리액트 공식 문서를 참고해봤을 때, 함수의 참조가 동일하다면 함수가 매 렌더마다 detach - attach 되면 안되는 거로 예상했지만 실제 동작은 달랐습니다. 상태 변경 시 함수가 계속 실행되어 `focus` 메서드가 매 렌더마다 실행되었습니다(re-attach).
`useState` 의 `setState` 함수를 ref callback으로 사용했을 경우엔 DOMNode가 Document에 attach 되었을 때 1번, detach 되었을 때 1번. 즉, 예상한 대로 동작하여 `useLayoutEffect` 와 함께 사용하는 방식으로 수정했습니다. 플리커링 방지를 위해(브라우저 Paint 시점 이전에 메서드를 실행함을 보장) `useEffect` …

Fixes an issue that causes the focus to move whenever the state changes when using `AutoFocus` component

---

.changeset/kind-grapes-rescue.md
packages/bezier-react/src/components/Forms/FormControl/FormControl.styled.ts
packages/bezier-react/src/components/Forms/FormControl/FormControl.tsx
packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap

No
Fix no spacing between form fields and `FormLabel` and `FormHelperText` when `labelPosition="left"`.
Skip
No
No

Fix no spacing between form fields and `FormLabel` and `FormHelperText` when `labelPosition="left"`

---

.changeset/shy-bulldogs-brush.md
packages/bezier-react/src/components/Tooltip/Tooltip.stories.tsx
packages/bezier-react/src/components/Tooltip/Tooltip.tsx
packages/bezier-react/src/components/Tooltip/Tooltip.types.ts
packages/bezier-react/src/components/Tooltip/TooltipContent.tsx
packages/bezier-react/src/components/Tooltip/utils.ts

None
- `Tooltip` 에 `container` 속성을 제거합니다.
- `Tooltip` 에 `contentWrapperStyle` 속성을 추가합니다.
- 외부 container 속성을 지정했을 때 해당 노드 아래에 렌더되도록 할 수 있게 수정하였으나 Tooltip의 로직은 container를 고려해 작성이 되지 않았습니다.
- 따라서 별도의 contentWrapperStyle 속성을 지정하여 필요에 따라 zIndex 등의 스타일을 설정할 수 있게 수정합니다. (이는 임시방편이며 현재 새로운 Tooltip 컴포넌트를 재구현중에 있습니다.)
- #1254 
- #1291

remove container prop to `Tooltip` components and add contentWrapperStyle prop

---

.changeset/gold-cows-impress.md
packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.test.tsx
packages/bezier-react/src/components/KeyValueListItem/KeyValueMultiLineListItem.styled.ts

Fixes #0000 
So remove padding property from `ValueItemContainer` in order to fix it.
현재 `ValueItemContainer`의 패딩은 `0 6px`인데, 이것은 피그마의 패딩과 다릅니다.
이로 인해 [데스크에서 MultiIine 컴포넌트가 한줄일때 이상해보이는 문제점](https://github.com/channel-io/ch-desk-web/issues/12666)이 있었습니다. 
현재 스타일은 기존의 padding인 `4px 6px`를 오버라이드하므로, 이를 삭제하여 원래 패딩을 사용하도록합니다.
[Figma](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=1164-12605&t=3W14fNTlqUQg8UwA-4)

remove overrided padding from valueItemContainer

---

.github/workflows/prerelease.yml

None
https://github.com/channel-io/bezier-react/actions/runs/4750676059/jobs/8439079642
```bash
YN0000: │ The current Node version 18.16.0 does not satisfy the required version 18.15.0.
```
Prerelease에서 발생하는 위 에러를 해결합니다.
> The node-version input is optional. If not supplied, the node version from PATH will be used. However, it is recommended to always specify Node.js version and don't rely on the system one.
> The action will first check the local cache for a semver match. If unable to find a specific version in the cache, the action will attempt to download a version of Node.js. It will pull LTS versions from [node-versions releases](https://github.com/actions/node-versions/releases) and on miss …

chore(prerelease): fix the node version to be the same as the package settings

---

.changeset/wet-wasps-work.md
packages/bezier-react/src/components/Avatars/Avatar/Avatar.styled.ts
packages/bezier-react/src/components/Avatars/Avatar/Avatar.tsx
packages/bezier-react/src/components/Avatars/Avatar/Avatar.types.ts
packages/bezier-react/src/components/Avatars/Avatar/__snapshots__/Avatar.test.tsx.snap
packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
packages/bezier-react/src/components/Avatars/CheckableAvatar/CheckableAvatar.styled.ts

None
`Avatar` 의 스타일링이 이전과 같은 방식으로 동작하도록 수정합니다.
- #1317 의 side effect. 스타일 우선순위가 변경되어 `Avatar` 의 스타일 오버라이드가 잘 되지 않는 문제가 발생했습니다.
- `Wrapper` 에 `className` 속성을 주입하여 이전과 같은 방식으로 스타일링이 잘 되도록 변경합니다.
- 불필요한 `wrapper*` 추가 스타일 속성을 제거합니다.
Yes
- Delete `wrapperStyle` prop of `AvatarProps`.
- Delete `wrapperClassName` prop of `AvatarProps`.
- Delete `wrapperInterpolation` prop of `AvatarProps`.
None

Fix `Avatar`'s style overrides to work the same way as before

---

.changeset/yellow-flies-complain.md
packages/bezier-react/src/components/Avatars/Avatar/Avatar.styled.ts
packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap

None
Add missing `display` property of `Avatar`.
#1335 에서 `all: unset` 이 추가되었습니다. `as` 속성을 통해 엘리먼트를 변경 시 기본 스타일시트가 적용되게 하지 않도록 하기 위해서였는데, HTMLDivElement의 기본 속성 `display: block` 또한 마찬가지로 초기화되고 있었습니다. 이를 수정합니다.
No
None

Add missing `display` property of `Avatar`

---

.changeset/ninety-books-behave.md
packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.tsx

None
Fix passing a number to the `width` prop of a `SegmentedControl` to work correctly
None
No
None

Fix passing a number to the `width` prop of a `SegmentedControl` to work correctly

---

.changeset/fast-bottles-judge.md
packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControlItem.tsx

None
`SegmentedControlItem` 컴포넌트 내부의 HTMLButtonElement 의 타입을 button으로 변경합니다.
- 원래는 Radix UI에 의해서 런타임에 `type: button` 이 주입되어야합니다. 
- **하지만 `type` 속성을 `SegmentedControl` 에서 이미 정의하고 사용하고 있어, 오버라이드가 제대로 되지 않은 문제가 있었습니다.**
- `type` 속성을 명시적으로 button으로 주입하여 해결합니다.
- HTMLAttributes로 사용될 수 있는 Key의 경우, 컴포넌트의 속성으로 사용하지 않도록 예방책이 필요할 거 같습니다 🤔
No
No

fix(segmented-control): fix incorrect button type of `SegmentedControlItem`

---

.changeset/dull-melons-buy.md
packages/bezier-react/src/components/Avatars/Avatar/Avatar.styled.ts
packages/bezier-react/src/components/Avatars/Avatar/__snapshots__/Avatar.test.tsx.snap

None
Fix status wrapper to grow in size to fit its children
- Change the status wrapper to flexbox
No
No

fix(avatar): fix status wrapper to grow in size to fit its children

---

.changeset/slimy-queens-remember.md
packages/bezier-codemod/src/transforms/icons-to-bezier-icons.ts
packages/bezier-codemod/src/transforms/tests/icons-to-bezier-icons/fixtures/input.tsx
packages/bezier-codemod/src/transforms/tests/icons-to-bezier-icons/fixtures/output.tsx

None
Exclude `LegacyIcon` from `iconSourceNamePattern`
- `LegacyIcon` 은 '@channel.io/bezier-react' 에서 import 를 유지하도록 합니다. 
No
None

fix(bezier-codemod): exclude `LegacyIcon` from `iconSourceNamePattern`

---

.changeset/late-moose-camp.md
packages/bezier-icons/rollup.config.mjs

- #1375 
Change rollup's cjs namespace helper to follow TypeScript's behavior
- jest가 rollup interop defaultOnly로 설정된 cjs 모듈을 제대로 해석하지 못해, auto로 변경합니다.
- 아이콘 cjs 모듈의 사이즈는 헬퍼 함수로 인해 소폭 증가하게 됩니다.
- 번들 사이즈에 가장 크리티컬한 채널 프론트에서는 esm 모듈을 사용하므로 번들 사이즈 변경에 큰 문제는 없을 거로 판단했습니다.
No
- https://rollupjs.org/configuration-options/#output-interop

build(bezier-icons): change rollup's cjs namespace helper to follow TypeScript's behavior

---

yarn.lock

This reverts commit 55b5d3e899e4905be0172e1addf6a3bb538a649c.
```bash
@channel.io/bezier-react:build: [!] (plugin babel) SyntaxError: /Users/edchoi/Desktop/Channel/bezier-react/node_modules/@radix-ui/react-slot/dist/index.d.mts: Support for the experimental syntax 'flow' isn't currently enabled (2:8):
@channel.io/bezier-react:build: 
@channel.io/bezier-react:build:   1 | import * as React from "react";
@channel.io/bezier-react:build: > 2 | export interface SlotProps extends React.HTMLAttributes<HTMLElement> {
@channel.io/bezier-react:build:     |        ^
@channel.io/bezier-react:build:   3 |     children?: React.ReactNode;
@channel.io/bezier-react:build:   4 | }
@channel.io/bezier-react:build:   5 | export const Slot: React.ForwardRefExoticComponent<SlotProps & …
```

Revert "fix(deps): update dependency @radix-ui/react-checkbox to v1.0.4 (#1394)"

---

.changeset/slow-nails-fix.md
packages/bezier-react/src/components/OutlineItem/OutlineItem.styled.ts
packages/bezier-react/src/components/OutlineItem/OutlineItem.test.tsx
packages/bezier-react/src/components/OutlineItem/OutlineItem.tsx
packages/bezier-react/src/components/SectionLabel/SectionLabel.styled.ts
packages/bezier-react/src/components/SectionLabel/SectionLabel.tsx

None
jest 에서 발생하는 `console.error` 를 제거하여 테스트 결과의 가독성을 증가시킵니다.
- boolean value를 non-boolean value로 변경합니다 (`boolean` -> `true | undefined`)
- `active` 속성은 존재하는 DOM Attribute이기 때문에 Icon(svg)등에 필터링없이 주입될 경우 에러가 발생합니다. styled prop 대신, 클래스네임을 통한 스타일링으로 이를 해결합니다.
- `Checkbox` : 체크박스 아이콘의 ref에 접근할 수 없어 에러가 발생합니다. 이는 Icon에 forwardRef를 추가하는 별도 PR에서 해결하려고 합니다.
- `ListItem` : 동일하게 `active` 속성의 문제가 있으나, 스타일링이 복잡하고 사이즈가 커서 별도 PR에서 해결하려고 합니다.
No
없음

Remove console.error from the test and change some styling to classname based

---

.changeset/afraid-pumas-agree.md
packages/bezier-icons/rollup.config.mjs
packages/bezier-icons/utils/index.ts

None
아이콘 컴포넌트의 식별자를 심볼에서 문자열 리터럴로 변경합니다.
식별자가 심볼일 경우 아래와 같은 문제가 발생할 수 있습니다. (했습니다...)
- A 패키지의 의존성 bezier-icons / A 패키지 내부의 B 패키지의 의존성 bezier-icons
- A 패키지에서 import한 IconSource를, B 패키지 내부에서 import한 isBezierIcon 을 통해 아이콘의 고유성을 체크하는 경우
- A 패키지와 B 패키지의 bezier-icons 모듈이 각기 다르기 때문에, Symbol이 2번 선언되고 아이콘 고유성 체크가 실패하게 됩니다.
bezier-react에 peer dependency로 bezier-icons를 추가하는 방식으로 문제를 해결할 수도 있습니다. 하지만 bezier-icons는 bezier-react와 꼭 쌍으로 사용해야하는 패키지가 아니고, bezier-react를 사용하는 사용처에서도 아이콘을 사용하지 않음에도 bezier-icons를 설치해야하는 불편함이 발생하게 됩니다. 또한 굳이 Symbol을 사용할 정도로 엄격하게 고유성 체크를 할 필요는 없다고 판단하여 이 PR의 해결 방식을 적용했습니다.
No. (bezier-react에선 Breaking Change입니다)
- [채널 데스크 관련 버그 제보 …

fix: change the identifier of the bezier icon to a string literal instead of a symbol

---

.circleci/config.yml
.github/workflows/chromatic.yml
.yarnrc.yml
packages/bezier-react/.ts-prunerc
yarn.lock

- #1375 
- enableTransparentWorkspaces 옵션을 기본값 true로 변경합니다.
- #1375 에서 ts-prune 관련 문제로 인해 enableTransparentWorkspaces 옵션을 false로 변경했습니다.
- version packages 시, install 과정에서 버전 업된 패키지(npm publish는 되지 않은)를 workspace 내부 링크된 패키지를 참조하지 않고, 실제 배포된 패키지를 찾으면서 설치 에러가 발생하는 문제가 있었습니다.
- 이를 롤백하고, ts-morph가 workspace 내부 모듈은 무시하는 설정을 추가하여 해결합니다.
- yarn install 이후 아이콘 패키지를 빌드하는 설정을 추가합니다.
No
None

build(yarn): change the enableTransparentWorkspaces option to the default of true

---

.changeset/config.json

없음
peer dependency에 해당하는 내부 패키지의 버전 범위가 벗어났을 경우에만, changeset이 버전을 자동으로 업데이트하도록 변경합니다.
예) bezier-icons >= 0.2.0 를 Peer dependency로 가지고 있을 경우, bezier-icons의 버전이 0.3.0이 되더라도 bezier-icons >= 0.3.0 으로 Peer dependency를 변경하지 않습니다. 기존 동작은 변경합니다.
레퍼런스 참고
No
- https://github.com/changesets/changesets/blob/main/docs/experimental-options.md

chore(changeset): change to only update when version of peer deps is out of range

---

.changeset/pink-actors-own.md
packages/bezier-react/src/components/Modals/Modal/Modal.types.ts
packages/bezier-react/src/components/Tooltip/Tooltip.types.ts
packages/bezier-react/src/components/VisuallyHidden/VisuallyHidden.types.ts

None
컴포넌트의 `children` prop을 통해, 내부의 radix-ui `Slot` 컴포넌트의 children에 직접 전달하는 경우 타입을 올바르게 수정합니다.
https://github.com/radix-ui/primitives/blob/eca6babd188df465f64f23f3584738b85dba610e/packages/react/slot/src/Slot.tsx#L60-L71
```tsx
const SlotClone = React.forwardRef<any, SlotCloneProps>((props, forwardedRef) => {
const { children, ...slotProps } = props;
if (React.isValidElement(children)) {
return React.cloneElement(children, {
...mergeProps(slotProps, children.props),
ref: forwardedRef ? composeRefs(forwardedRef, (children as any).ref) : (children as any).ref,
});
}
return React.Children.count(children) > 1 ? React.Children.only(null) : null;
});
```
- `Slot` 내부 구현을 보면, children이 …

fix: correctly change children prop in components that pass children prop directly to radix-ui `Slot`

---

.changeset/famous-comics-double.md
packages/bezier-react/src/foundation/FoundationStyledComponent.tsx

- #1424 
- #1424 의 사이드 이펙트
- Next.js 환경에서 mjs 모듈을 해석할 때, styled-components의 `styled` function이 cjs 모듈로 잘못 해석되어 `TypeError: styled is not function` 에러가 발생하는 문제를 해결합니다.
- #513 과 같은 접근방식으로 우회하여 해결합니다.
- https://github.com/rollup/rollup/issues/4438#issuecomment-1602030517
No
- https://github.com/rollup/rollup/issues/4438

fix(styled): fix styled function not being interpreted correctly in the Next.js environment

---

.changeset/eleven-jobs-invite.md
packages/bezier-react/src/components/Help/Help.styled.ts
packages/bezier-react/src/components/Help/Help.tsx
packages/bezier-react/src/components/Help/Help.types.ts
packages/bezier-react/src/components/KeyValueListItem/KeyValueListItem.test.tsx
packages/bezier-react/src/components/KeyValueListItem/common/ItemActions/ItemAction.styled.ts
packages/bezier-react/src/components/KeyValueListItem/common/ItemActions/ItemAction.tsx
packages/bezier-react/src/components/KeyValueListItem/common/ItemActions/ItemAction.types.ts
packages/bezier-react/src/components/SectionLabel/SectionLabel.stories.tsx
packages/bezier-react/src/components/SectionLabel/SectionLabel.styled.ts
packages/bezier-react/src/components/SectionLabel/SectionLabel.test.tsx
packages/bezier-react/src/components/SectionLabel/SectionLabel.tsx
packages/bezier-react/src/components/SectionLabel/SectionLabel.types.ts
packages/bezier-react/src/components/Tooltip/Tooltip.tsx

- #1291 
#1291 의 새로운 `Tooltip` 컴포넌트를 `Tooltip` 을 사용하는 아래 디자인 시스템 컴포넌트에 적용합니다.
- `Help`
- `KeyValueListItem`
- `SectionLabel` (`Help`)
- 새로운 Tooltip 컴포넌트의 스펙에 맞게 스타일링 수정
- 실패하는 테스크 케이스 수정
Yes
`help` type of `SectionLabelProps` is changed to `React.ReactNode`.
없음

Apply the reimplemented `Tooltip` to internal components

---

.changeset/brown-bottles-protect.md
packages/bezier-react/src/components/KeyValueListItem/common/ItemActions/ItemAction.styled.ts
packages/bezier-react/src/components/KeyValueListItem/common/ItemActions/ItemAction.tsx
packages/bezier-react/src/components/KeyValueListItem/common/ItemActions/ItemAction.types.ts
packages/bezier-react/src/components/KeyValueListItem/common/KeyItem/KeyItem.types.ts
packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.stories.tsx
packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.test.tsx
packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.tsx
packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.types.ts
packages/bezier-react/src/components/Navigator/NavItem/NavItem.test.tsx
packages/bezier-react/src/components/Navigator/NavItem/NavItem.tsx
packages/bezier-react/src/components/Navigator/NavItem/NavItem.types.ts
packages/bezier-react/src/components/TagBadge/Badge/Badge.stories.tsx
packages/bezier-react/src/components/TagBadge/Badge/Badge.tsx
packages/bezier-react/src/components/TagBadge/Badge/Badge.types.ts
packages/bezier-react/src/components/TagBadge/TagBadge.mdx
packages/bezier-react/src/components/TagBadge/TagBadge.stories.tsx
packages/bezier-react/src/components/Toast/Toast.stories.tsx
packages/bezier-react/src/components/Toast/Toast.types.ts
packages/bezier-react/src/components/Toast/ToastElement.tsx
packages/bezier-react/src/components/Toast/ToastProvider.tsx
packages/bezier-react/src/components/Toast/ToastService.test.ts
packages/bezier-react/src/components/Toast/useToastContextValues.test.tsx
packages/bezier-react/src/components/Toast/utils.ts

Partial fix of https://github.com/channel-io/bezier-react/issues/762
- 아래 컴포넌트들에 대하여 `iconName` 을 `BezierIcon`으로 마이그레이션 합니다.
- 해당 컴포넌트들은 이전에 마이그레이션 했던 `Select`, `KeyValueListItem` 등과 달리 `IconName`을 서버에서 받고 있지 않고 모두 클라이언트에서 들고 있어서 바로 breaking change 를 일으켜도 무방하다고 생각하여 `IconName` 을 제거했습니다.
- `KeyItem` 과 `ItemAction` 에 남아있는 `IconName` 을 지웠습니다.
- 이 pr 이 머지되면 이제 `Button` 관련된 컴포넌트(`Button` 과 `SectionLabel`) 가 남습니다.
- Yes, components in summary do support `BezierIcon` type instead of `IconName` type for icon.
- https://github.com/channel-io/bezier-react/issues/762

Remove `IconName` type from `icon` prop (`Badge`, `NavGroup`, `NavItem`, `Toast`)

---

.changeset/shiny-snakes-provide.md
packages/bezier-react/src/components/Help/Help.tsx
packages/bezier-react/src/components/ListMenuTitle/ListMenuTitle.tsx
packages/bezier-react/src/components/ListMenuTitle/ListMenuTitle.types.ts
packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.tsx
packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.types.ts
packages/bezier-react/src/components/Navigator/NavItem/NavItem.tsx
packages/bezier-react/src/components/Navigator/NavItem/NavItem.types.ts
packages/bezier-react/src/components/SectionLabel/SectionLabel.tsx
packages/bezier-react/src/components/SectionLabel/SectionLabel.types.ts
packages/bezier-react/src/components/Spinner/Spinner.tsx
packages/bezier-react/src/components/Spinner/Spinner.types.ts
packages/bezier-react/src/components/TagBadge/Badge/Badge.tsx
packages/bezier-react/src/components/TagBadge/Tag/Tag.tsx

- #1448
Add `forwardRef` to all components (except `Select`, `TextField`)
- Issue 참고
- ImperativeHandle을 사용하는 경우 ref forwarding이 어려움. 여러 방식을 시도해보았지만, ImperatvieHandle을 사용하지 않아도 괜찮은 방향으로 인터페이스를 재설계하는 편이 이후 다양한 유즈 케이스에서도 의도한대로 동작할 거 같습니다.
No
- https://github.com/radix-ui/primitives/issues/711

Add `forwardRef` to all components (except `Select`, `TextField`)

---

packages/bezier-react/src/components/Tooltip/Tooltip.styled.ts
packages/bezier-react/src/components/Tooltip/Tooltip.tsx

None
`Tootlip` 컨텐츠가 띄어 쓰기가 없는 텍스트더라도 말줄임 처리가 잘 되도록 수정합니다.
텍스트 컨테이너에 `overflow: hidden` 을 추가합니다.
No
없음

fix(tooltip): fix to show ellipsis even when no spaces are present

---

.changeset/cyan-seas-jam.md
packages/bezier-react/src/components/Forms/Slider/Slider.stories.tsx
packages/bezier-react/src/components/Forms/Slider/Slider.styled.ts
packages/bezier-react/src/components/Forms/Slider/Slider.test.tsx
packages/bezier-react/src/components/Forms/Slider/Slider.tsx
packages/bezier-react/src/components/Forms/Slider/Slider.types.ts
packages/bezier-react/src/components/Forms/Slider/__snapshots__/Slider.test.tsx.snap
packages/bezier-react/src/components/Tooltip/Tooltip.types.ts

- Fixes #1089
- #871 
`Slider` 컴포넌트의 Thumb에 툴팁을 추가하고, 기타 개선사항들을 적용합니다.
- `Slider` 컴포넌트의 Thumb에 툴팁을 추가합니다. 드래그하는 동안 툴팁이 가려지지 않도록, 툴팁에 `onPointerDownOutside` 속성을 추가하여 외부 클릭 시 툴팁이 닫히지 않도록 했습니다.
- 내부에 불필요한 로컬 상태를 제거합니다. `value` 값을 주더라도, `onValueChange` 핸들러를 넘기지 않으면 이전과 같이 툴팁이 비제어형 컴포넌트처럼 동작하지 않습니다. 제어형 컴포넌트로 동작하게 하기 위해선 사용처에서 명시적으로 상태와 그를 변경하는 핸들러를 넘겨주어야 합니다.
- 최대한 `asChild` 없이 단순하게 스타일링할 수 있도록(only className) 개선합니다.
- 가이드 눈금 위치를 결정하는 로직을 단순하게 변경하고, CSS variable을 사용하여 런타임 오버헤드가 생기지 않도록 개선합니다.
- `defaultValue` 속성의 기본값을 `5` 에서 `0` 으로 변경합니다. 더 예측하기 쉬운 기본값이라고 판단했습니다.
- 타입 선언에서 radix-ui `SliderProps` 과의 의존성을 제거합니다. 외부 인터페이스를 우리 라이브러리의 설계 의도에 맞게 관리하기 위해서, 내부 구현은 거의 동일하더라도 별도로 분리하는 게 좋다고 판단했습니다. (다른 컴포넌트들도 …

Add `Tooltip` to `Slider` and other enhancements

---

.changeset/beige-lies-sparkle.md
packages/bezier-react/babel.config.js
packages/bezier-react/package.json
packages/bezier-react/rollup.config.mjs
yarn.lock

Fixes #1458 
바벨 헬퍼 함수를 번들에 포함하도록 변경합니다.
#1458 의 근본적인 원인은 해결하기 어려웠습니다. 대신, 바벨 헬퍼를 external 모듈에서 제거하고 번들에 포함함으로써 내부 의존성이 사용하는 ESM 버전의 바벨 헬퍼를 CJS용으로 트랜스파일링하도록 변경했습니다.
아래와 같은 방식으로 변경되어, 사용처에서 모듈 시스템 충돌로 인한 문제는 발생하지 않게 됩니다.
```js
/* dist/cjs/node_modules/@radix-ui/react-tooltip/dist/index.js */
'use strict';
var _extends = require('../node_modules/@babel/runtime/helpers/esm/extends.js');
```
```js
/* ../node_modules/@babel/runtime/helpers/esm/extends.js */
'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
function _extends() {
_extends = Object.assign ? Object.assign.bind() : function (target) {
for (var i = 1; i < arguments.length; i++) {
var source = arguments[i];
for (var …
```

fix(rollup): change to include babel helper functions in the bundle

---

.changeset/pre.json
.github/workflows/chromatic.yml
.github/workflows/codeql-analysis.yml
.github/workflows/release.yml

None
2.0.0 alpha 버전을 위한 배포 환경을 설정합니다.
- enter prerelease mode (alpha)
- ci branch rule에 `alpha` branch 추가
No
- https://github.com/changesets/changesets/blob/main/docs/prereleases.md

Set up deployment environment for 2.0.0 alpha version

---

.changeset/five-jars-love.md
packages/bezier-react/src/components/Toast/ToastProvider.tsx
packages/bezier-react/src/hooks/useIsMounted.ts

Fixes #1481 
`ssr-window`에서 제공하는 fake DOM이 `React.createPortal`과 호환되지 않아 발생한 이슈를 해결하는 PR입니다.
issue 내용 참조
No

fix(toast): change portal target element in ToastProvider

---

.changeset/cuddly-cows-hammer.md
packages/bezier-react/src/components/Tabs/TabAction.tsx

Fixes #1126
- `TabAction`은 `href` 를 받으면 `a` 로, 그렇지 않으면 `button` 으로 동작하지만 event handler 에 대한 타입은 항상 `button` 에 대한 event handler 로 정의되어 있습니다. 이것을 수정합니다.
- typescript 에서는 higher order function에 대해 제네릭 타입의 추론이 가능하지만, `forwardRef`처럼 반환타입이 추가로 속성(`displayName`, `defaultProps`)을 가지게 되면 이것이 제대로 동작하지 않습니다. 참고: https://stackoverflow.com/a/58473012/22224797
- 위에서 제시한 assertion 을 하지 않고 `myRef` 같이 custom 한 ref prop 을 열거나 글로벌하게 `forwardRef` 타입을 변경하는 것은 베지어에 적용할 수 없다고 생각하여, assertion 을 해서 아래처럼 타입이 제대로 잡히게 했습니다. 
- As-is
[href 있을 때]
[href 없을 때]
- To-be
[href 있을 때]
[href 없을 때]
- No
- https://github.com/microsoft/TypeScript/pull/30215 
- https://stackoverflow.com/a/58473012/22224797

Fix wrong typing of `TabAction` prop

---

.changeset/tidy-scissors-melt.md
packages/bezier-react/src/foundation/Colors/Palette/index.ts
packages/bezier-react/src/foundation/Colors/Theme/presets/DarkTheme.ts
packages/bezier-react/src/foundation/Colors/Theme/presets/LightTheme.ts
packages/bezier-react/src/foundation/Colors/Theme/types/SemanticNames.ts

없음
1. 시멘틱에 `txt-black-pure` 추가 (black ↔ white)
2. 팔레트에 `grey800_90` 추가 후 `bg-lounge` 다크테마 색상을 해당 컬러로 변경
생략
No
- [관련 채널톡 스레드](https://desk.channel.io/root/threads/groups/Bezier-62019/64af7310073d29db5905/64af7310073d29db5905)

feat(foundation): update theme

---

.changeset/cyan-trains-unite.md
packages/bezier-react/src/components/Button/__snapshots__/Button.test.tsx.snap
packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
packages/bezier-react/src/components/Tooltip/Tooltip.tsx

- #1472 
`Tootlip` 이 `Modal` 안에 위치할 경우, 포커스 이동을 방해하는 버그를 수정합니다.
- #1472 의 사이드 이펙트. 컨테이너가 모달 컨테이너로 지정돼있을 경우 포커스가 트랩핑되는 현상이 발생했습니다.
- 원래 동작, 컨테이너를 루트 엘리먼트(`document.body`)로 되돌립니다.
No
- [관련 버그 제보(Channel private)](https://desk.channel.io/root/threads/groups/AllAboutUserChat-27227/64d5a2973ceb2abb6771/64d5a2973ceb2abb6771)

Fixed a bug where tooltips prevented focus from moving inside a modal

---

.changeset/spotty-elephants-give.md
packages/bezier-react/src/components/Forms/Slider/__snapshots__/Slider.test.tsx.snap
packages/bezier-react/src/components/Tooltip/Tooltip.test.tsx
packages/bezier-react/src/components/Tooltip/Tooltip.tsx
packages/bezier-react/src/components/Tooltip/Tooltip.types.ts

- https://github.com/channel-io/ch-desk-web/issues/13798 (Private)
`content` 속성이 nil 값일때, 툴팁을 렌더하지 않도록 조건부 렌더링 로직을 추가합니다.
- 이전 `LegacyTootlip` 의 로직을 되돌립니다.
- `disabled` 속성의 경우에도 조건부 렌더링을 적용하여 불필요한 코드 실행을 방지하도록 개선합니다.
No
없음

Enhance conditional rendering logic for `Tooltip` based on `content` prop

---

.changeset/orange-pillows-pay.md
packages/bezier-react/src/components/Forms/Slider/__snapshots__/Slider.test.tsx.snap
packages/bezier-react/src/components/Tooltip/Tooltip.tsx
packages/bezier-react/src/components/Tooltip/Tooltip.types.ts

- #1552 
#1552 에서 `disabled` 와 `isEmpty(content)` 조건에 따라 적용한 조건부 렌더링 로직을 제거합니다. 
- `Tooltip` children의 mount 여부(node의 width가 N이하면... 등)로 `Tooltip` 의 disabled 여부를 결정하는 로직에서 잠재적으로 [무한 루프](https://legacy.reactjs.org/docs/error-decoder.html/?invariant=185)가 발생할 위험이 있습니다. 이를 제거하고자 #1552 이전과 동일하게 로직을 변경합니다. 동일한 렌더링 결과를 반환하되, show/hide 동작만 막는 방식입니다.
- `Tooltip` 이 동작하지 않아야 하는 경우에 열려있다면 즉시 가리는 사이드 이펙트를 추가합니다.
No
- [에러 발생 유저챗 (Private)](https://desk.channel.io/root/user-chats/이재준-64e80077c11d5c1d610b)

fix(tooltip): remove conditional rendering logic based on disabled prop

---

.changeset/angry-emus-repeat.md
packages/bezier-react/src/components/Divider/Divider.styled.ts
packages/bezier-react/src/components/Divider/index.ts
packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.styled.ts
packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.test.tsx
packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.tsx
packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControlContext.ts
packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControlIndicator.tsx
packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControlItem.tsx

Resolves #1573
Resolves #1351 
#1573 에서 서술한 버그를 수정하고 `SegmentedControlIndicator`의 애니메이션 구현 방식을 변경합니다.
- #1573 에서 설명하는 것처럼 `SegmentedControl` 의 무한 렌더링 버그를 고치려면 `react-resize-detector`의 버전을 낮추거나 구현 방법을 `react-resize-detector` 를 사용안하는 방식으로 변경해야 합니다.
- 그런데 애초에 `react-resize-detector` 를 사용하고 있었던 이유를 보면,  `Indicator`의 애니메이션을 구현하기 위해 현재 선택된 아이템과 다음에 선택하는 아이템의 [`DOMRect`](https://developer.mozilla.org/en-US/docs/Web/API/DOMRect) 기준으로 `Indicator`가 움직이는 좌표값을 계산하고 있어서, `SegmentedControl` 를 담고있는 컨테이너의 `width` 가 변경될때마다 이 계산 로직을 업데이트 해줘야 했습니다.
- 이렇게 `width`가 변경될 때마다 이펙트를 걸어줘서 렌더링을 다시하는 것은 불필요하게 복잡한 계산 로직이 필요하고 성능에도 좋지 않기 때문에 `react-resize-detector`를 가능하면 없애는 방식이 좋겠다고 판단했습니다. 비슷한 애니메이션을 구현한 …

Remove `react-resize-detector` used in `SegmentedControl`

---

packages/bezier-react/src/utils/assertUtils.ts
packages/bezier-react/src/utils/reactUtils.ts

개발자들의 디버깅 용이성, deprecated된 속성 등을 잘 파악할 수 있는 유틸 함수들을 추가합니다.
- `process.env.NODE_ENV !== 'production'` 인 케이스를 개발 환경으로 정의하고, 이 케이스에서만 에러를 보여주도록 합니다.
- `createContext` 유틸에 assert 함수를 적용합니다.
No
- https://github.com/chakra-ui/chakra-ui/blob/63431c1ef3b7e8ac9b97c94ca025dd54b9aa3338/packages/utilities/shared-utils/src/index.ts#L23

Add assertion utility function

---

.github/workflows/generate-icon-files.yml

Fixes #1627 
- 아이콘 업데이트 없이 이전과 동일한 상태로 플러그인을 동작시키면 깃헙 액션이 에러를 뱉는 것을 수정합니다. 
- 베지어 플러그인에 의해 아이콘 변경점이 없을 경우에 커밋할 내용이 없어 github action 에서 에러가 나고 있는 것을 fallback 을 넣어서 수정합니다.
- changeset 은 추가하지 않았습니다.
- https://github.com/yangwooseong/bezier-react/actions/runs/6184421871/job/16788047266 여기서 잘 동작하는 것을 확인했습니다.
No
- https://stackoverflow.com/questions/74157458/git-throws-error-if-nothing-to-commit-how-to-surpress

Add fallback login when there is no icon update with figma plugin 

---

.changeset/kind-cars-perform.md
packages/bezier-react/rollup.config.mjs

- rollup `plugin-node-resolve` 의 옵션에 `browser: true` 를 추가하여, package.json의 exports 필드 중 `browser` 를 함께 확인하도록 수정합니다. 
- 이 변경으로 `TextArea` 컴포넌트의 높이가 올바르게 지정되지 않는 문제를 수정합니다.
`react-textarea-autosize@8.5.0` 버전에서 https://github.com/Andarist/react-textarea-autosize/pull/373 변경사항이 적용되었습니다. 라이브러리의 빌드 최적화 전략이 변경되며 package.json의 exports 필드가 수정되었는데, 기존 브라우저 API를 사용하는 빌드 아티팩트는 `browsers` 필드 하위에 포함되도록 변경되었습니다. 마찬가지로 여기서 브레이킹 체인지가 발생했는데, 기존 `main`, `module` 필드가 가르키는 아티팩트들에서는 브라우저 API를 사용하지 않는 버전으로 변경되었습니다.
rollup의 `plugin-node-resolve`는 기본값으로 `exports` 필드를 확인할 때, `default`, `module`, `import` 3가지의 조건 필드만을 확인합니다. 여기에 `browser` 필드가 없으므로, 번들 시 브라우저 API를 사용하지 않는 버전의 react-textarea-autosize가 포함되게 됩니다.
플러그인의 …

build(rollup): add browser exports condition to module resolve

---

.changeset/heavy-bikes-clap.md
packages/bezier-react/src/features/Feature.ts
packages/bezier-react/src/features/SmoothCornersFeature/SmoothCornersFeature.ts
packages/bezier-react/src/features/SmoothCornersFeature/SmoothCornersFeatures.test.ts
packages/bezier-react/src/foundation/Mixins.ts

`SmoothCornersFeature.activate` 메서드에 매개변수로 globalObject를 추가합니다. 필요한 경우 FeatureProvider를 사용하지 않고`activate` 함수를 manually하게 실행하여 새로운 window에 smooth corner 스크립트를 추가할 수 있도록 합니다.
- 채널 데스크 앱에서 새 창을 이용해 만들어질 새로운 기능에 대한 대응 작업입니다.
- activate 함수의 재실행 조건을 변경합니다. 기존에 `activated === true` 조건 체크를 globalObject가 이전에 함수가 실행되었을 때 globalObject 인자와 같은지 체크하는 로직으로 변경합니다. 새로운 globalObject를 주입 시 다시 스크립트를 실행할 수 있도록 하고, 같은 globalObject라면 같은 PaintWorklet 글로벌 영역을 가지고 있을 것이기 때문에 기존 로직보다 더 명시적인 조건이라고 판단했습니다.
- 리팩토링: 클래스 상속을 인터페이스 기반으로 변경합니다.
- 리팩토링: 타입 단언을 타입 선언 오버로딩으로 변경합니다. 타입은 공식 스펙 문서를 참고했습니다.
- 유닛 테스트 추가
No
- Type: https://html.spec.whatwg.org/multipage/worklets.html#worklets-worklet

feat(smooth-corners): enhance to inject window as argument when activating smooth corners feature

---

.changeset/tiny-countries-deliver.md
packages/bezier-react/src/components/Tooltip/Tooltip.stories.tsx
packages/bezier-react/src/components/Tooltip/Tooltip.styled.ts
packages/bezier-react/src/components/Tooltip/Tooltip.tsx
packages/bezier-react/src/components/Tooltip/Tooltip.types.ts

- **macOS: Chrome**
Added `title` props on tooltip component
As this PR, I added `title` element at tooltip component.
It should be shows title of this tooltip.
No
No

Added `title` props on tooltip component

---

.changeset/purple-tips-invent.md
packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.types.ts

TextField의 `TextFieldRef.getDOMNode()` 의 반환 타입을 올바르게 변경합니다.
-  `getDOMNode()` 이 실제로 반환하는(추론되는) 타입으로 변경합니다: `HTMLInputElement | null`
- `value` 등 프로퍼티에 타입 에러없이 접근할 수 있도록 수정합니다.
No

fix(text-field): fix type of `TextFieldRef.getDOMNode`

---

.changeset/tasty-buckets-buy.md
.github/workflows/generate-icon-files.yml
packages/bezier-icons/scripts/generate-changeset.js
packages/bezier-icons/scripts/utils/getChangeLog.js
packages/bezier-icons/scripts/utils/getChangeLog.test.js
packages/bezier-icons/scripts/utils/getIconNamesByStatus.js
packages/bezier-icons/scripts/utils/getPrDescription.js

Fixes #863 
- 피그마 플러그인이 생성하는 아이콘 업데이트 pr에 아이콘 변경 내역을 바탕으로 changeset를 생성합니다.
- changeset 내부 코드를 보면, 파일의 경로와 확장자를 보고 파일이 changeset 인지를 [확인](https://github.com/changesets/changesets/blob/main/packages/read/src/index.ts)하고, 파일안에 yaml front matter 가 있다면 거기서 version 을 [파싱](https://github.com/changesets/changesets/blob/main/packages/parse/README.md)하고 있습니다. 따라서 changeset cli 를 통하지 않더라도, changeset이 기대하는 형태로 파일을 만든다면 인식이 잘 될 것으로 생각됩니다.
- changeset 양식은 다음과 같습니다. 기존에 만들고 있는 형태를 유지했습니다. 
```typescript
// .changeset/icon-update-1697341995107.md (update 뒤에 오는 값은 Date.valueOf())
---
"@channel.io/bezier-icons": minor
---
Icon Update
**CHANGE**
- all.svg
**DELETE**
- home.svg
**ADD**
- people.svg
- …
```

add changeset auto generate job to workflow

---

.changeset/gentle-chefs-arrive.md
packages/bezier-react/package.json
packages/bezier-react/rollup.config.mjs
yarn.lock

Fixes #1687 
- react-textarea-autosize의 버전을 `8.3.4` 로 다운그레이드하고, 버전을 고정합니다.
- revert #1637
#1637 에서 react-textarea-autosize의 변경으로 인해 rollup의 node module resolve 방식을 변경했습니다. SSR 환경에서도 browser용 번들을 바라보게되면서, `document` 관련 에러가 발생하여 빌드가 실패하는 문제가 발생했습니다.
이를 해결하고자 여러 방법을 고려해봤는데,
1. main module은 SSR용 모듈로 두고, browser용 exports field를 추가: 빌드 시 browser exports field를 고려하지 않고 있는 다른 사용처에서의 사이드 이펙트가 우려되어서 선택하지 않았습니다.
2. external dependency로 명시하여 peer dependency로 변경: Breaking change를 발생시키고 싶지 않았습니다. TextArea 컴포넌트를 사용하지 않는 사용처에서도 라이브러리 사용이 강제됩니다. peerDependenciesMeta.optional를 사용하는 방법으로 우회하더라도 매력적인 선택지는 아니라고 생각했습니다.
3. 런타임에 document 체크를 하는 로직 추가: 로직을 추가하고 테스트 해보았으나 여전히 에러가 발생했습니다. 자세히 빌드 과정(Next.js)을 뜯어보진 않았지만, …

Downgrade react-textarea-autosize version to 8.3.4 to fix SSR document error

---

.changeset/shiny-walls-kick.md
packages/bezier-react/src/components/Toast/Toast.types.ts
packages/bezier-react/src/components/Toast/ToastProvider.tsx

Fixes #1689
ToastProvider에서 container(givenContainer)를 주입바다 portal target으로 사용하도록 지정합니다
Overlay에서 사용하는 컨벤션을 그대로 적용합니다
window.open과 react.portal을 사용해 팝업창에서 React를 구동하고자 하는 니즈가 있습니다
이에 ToastProvider를 새 창에 렌더해야하고, 이 때 js context상에서는 기존 window 객체에만 접근할 수 있기에
기존 ToastProvider에서는 새 window 객체에 접근할 수 없고, 따라서 새 창에 portal을 만들 수 없었습니다
이에 prop을 추가하여 portal target container를 지정할 수 있도록 합니다
지정하지 않는다면 기존처럼 fallback(getRootElement())에 붙습니다
No. 신규 Props가 추가되었으며 기존 동작 및 코드에는 영향이 가지 않습니다

Add container prop to ToastProvider 

---

.changeset/lazy-bikes-allow.md
packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.test.tsx
packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.tsx

Fixes #502 
input에 값이 채워져있고, focus되거나 hover되었을 때만 내용 삭제 버튼이 나오도록 변경합니다.
```tsx
// TextField.tsx
// before
const activeClear = activeInput && allowClear
// after
const activeClear = activeInput && allowClear && !!normalizedValue
return (
...
{ activeClear && ClearComponent }
...
)
```
기존에 `ClearComponent` 의 렌더링 조건에는 `value`에 대한 것이 없었습니다. 그래서 `!!normalizedValue`를 통해 input 태그에 값이 있어야지만 내용 삭제 버튼이 렌더링되도록 하였습니다.
No

fix(text-field): Show clear button in TextField only when it is filled and hovered/focused

---

packages/bezier-tokens/package.json

bezier-tokens 패키지의 초기 버전을 0.0.0 으로 설정하고, changeset에 의해서 0.1.0 으로 버전업되도록 합니다.

chore(bezier-tokens): set initial version to 0.0.0

---

.changeset/wicked-months-sparkle.md
packages/bezier-tokens/scripts/build-tokens.ts
packages/bezier-tokens/scripts/lib/transform.ts
packages/bezier-tokens/scripts/lib/utils.ts
packages/bezier-tokens/src/global/font.json

design token의 잘못된 설정을 몇 수정하고, 리팩토링을 적용합니다.
- font-familiy 토큰을 올바른 포맷으로 수정합니다. 불필요해진 system-font 토큰은 제거합니다.
- radius 토큰에 누락된 px 유닛을 추가합니다.
- cjs/esm 빌드에서 basePxFontSize가 누락되어 rem이 16px 기준으로 계산되고 있었던 걸 수정합니다.
- 리팩토링: 변수명 수정 및 함수 분리
Yes (alpha version)

fix invalid design token config

---

.changeset/wicked-pugs-build.md
packages/bezier-react/src/components/Modals/Modal/Modal.styled.ts
packages/bezier-react/src/components/Modals/Modal/Modal.types.ts
packages/bezier-react/src/components/Modals/Modal/ModalContent.tsx

- Modal에서 사용되는 radix overlay의 padding은 '40px 0'으로 고정되어 있었습니다.
- 미트 새 창 프로덕트에서 해당 padding을 40px보다 더 작게 주어야 할 니즈가 생겨 이를 위한 prop을 추가합니다.
- MdoalContent에서 collisionPadding prop을 받도록 합니다. ([Radix Popper](https://github.com/radix-ui/primitives/blob/main/packages/react/popper/src/Popper.tsx) 참고)
- collisionPadding은 숫자 혹은 각 사이드별 크기를 담은 객체입니다.
```ts
type CollisionPadding = number | Partial<Record<'top' | 'right' | 'bottom' | 'left', number>>
```
- collisionPadding을 실제 padding string으로 변환해 overlay에 주입합니다.
no
- [Radix Popper](https://github.com/radix-ui/primitives/blob/main/packages/react/popper/src/Popper.tsx)

ModalContent의 overlay padding에 임의의 값을 줄 수 있도록 수정

---

.changeset/thin-carpets-remain.md
packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.tsx
packages/bezier-react/src/components/LegacyTooltip/LegacyTooltip.tsx
packages/bezier-react/src/components/LegacyTooltip/LegacyTooltip.types.ts
packages/bezier-react/src/components/LegacyTooltip/LegacyTooltipContent.tsx
packages/bezier-react/src/components/LegacyTooltip/utils.ts
packages/bezier-react/src/components/Modals/Modal/ModalContent.tsx
packages/bezier-react/src/components/Overlay/Overlay.tsx
packages/bezier-react/src/components/Toast/ToastController.tsx
packages/bezier-react/src/components/Toast/ToastProvider.tsx
packages/bezier-react/src/components/Tooltip/Tooltip.tsx
packages/bezier-react/src/index.ts
packages/bezier-react/src/providers/BezierProvider.tsx
packages/bezier-react/src/providers/WindowProvider.tsx

close #1763 
- 베지어 provider에 외부 window 객체를 주입할 수 있도록 합니다.
- WindowContext를 생성하고 베지어에서 사용할 window객체를 관리하도록 합니다.
- BezierProvider를 통해 external window를 WindowContext로 전달할 수 있습니다.
- 기존 utils/dom의 window, document를 사용하던 사용처를 우선으로 마이그레이션 했습니다.(context value의 window와 docuement를 사용하도록)
- 추후 getRootElement도 마이그레이션되어야 합니다.
no

Allow external window for bezier

---

.changeset/metal-planets-peel.md
.changeset/silent-falcons-behave.md
packages/bezier-tokens/scripts/lib/format.ts
packages/bezier-tokens/src/global/opacity.json
packages/bezier-tokens/src/global/z-index.json

- z-index와 opacity 디자인 토큰을 추가합니다. 
- 모든 플랫폼을 위한 토큰은 아니고, bezier-react에서만 사용하기 위한 임시 토큰으로 추가했습니다. (기존 `Constants/` 디렉터리 하위)
- JS 빌드 아티팩트에 토큰별 카테고리를 추가합니다. json 파일명이 토큰의 카테고리가 됩니다. 기존 `SemanticNames` 과 같이 카테고리별타입스크립트 타입을 쉽게 뽑아내기 위한 변경입니다.
토큰별 카테고리에 대해: 아래와 같이 타입을 추출하여 사용할 수 있습니다.
```tsx
// AS-IS
color: SemanticNames
// TO-BE
color: keyof typeof tokens.lightTheme.color
```
JS 빌드 아티팩트가 아래와 같은 형식으로 변경됩니다.
```tsx
// AS-IS 모두 1-depth로 flat한 구조
// TO-BE
export default {
"color": { ... }
"typography": { ... } 
...
}
```
> 생각들:
> 색상 토큰에 color prefix를 붙이는 걸 고민했으나, 기존 팀의 컨벤션과 마이그레이션 비용을 고려하여 작업하지 않았음.
Yes

Add z-index and opacity tokens, Add token category to js build artifacts

---

.github/workflows/release.yml

- GitHub Action의 'Release' workflow가 fork된 레포 등에서 돌지 않도록 합니다.
- `release` job에 조건문을 추가합니다.
- Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif
- No.

Run release workflow only on upstream repo

---

.changeset/mighty-hornets-promise.md
packages/bezier-tokens/scripts/build-tokens.ts
packages/bezier-tokens/scripts/lib/transform.ts
packages/bezier-tokens/scripts/lib/utils.ts
packages/bezier-tokens/src/global/font.json
packages/bezier-tokens/src/global/transition.json
packages/bezier-tokens/src/semantic/elevation.json
packages/bezier-tokens/src/semantic/input.json

- Composition token의 스펙을 DTCG format과 비슷하게 정의하고, 커스텀 Transformer를 구현합니다.
- 공통 Semantic token이 불필요하게 라이트 테마, 다크 테마에 중복해서 들어가던 문제를 수정합니다.
- Composition token이 CSS spec에 의존하지 않도록 [DTCG format](https://design-tokens.github.io/community-group/format/#composite-types)을 참고하여 수정했습니다. shadow와 transition 타입에 적용했습니다.
- letter-spacing에도 rem 단위를 적용합니다. dimension type을 만들어서 기존 font-size와 line-height에 적용하던 custom Transformer를 적용했습니다.
- 공통 Semantic token이 불필요하게 들어가는 문제를 해결하기 위해서는 기존 defineConfig 함수를 해체하는 것이 불가피했습니다. CSS/JS 빌드를 구분하는 플래그 등을 만들어서 기존 defineConfig를 재사용하는 것도 가능했으나, 오히려 가독성이 떨어진다고 판단했습니다. 기존에 global, light theme, dark theme 빌드를 3번 진행했다면 이제는 global, light theme로 묶어서 빌드를 1번 진행하고, dark theme로 따로 한번 더 …

feat(bezier-tokens): Implementing composition tokens and removing duplicate CSS

---

.changeset/two-adults-pay.md
packages/bezier-codemod/README.md
packages/bezier-codemod/src/App.tsx
packages/bezier-codemod/src/transforms/mixin-to-css-variable.ts
packages/bezier-codemod/src/transforms/tests/mixin-to-css-variable.ts/fixtures/mixin1.input.tsx
packages/bezier-codemod/src/transforms/tests/mixin-to-css-variable.ts/fixtures/mixin1.output.tsx
packages/bezier-codemod/src/transforms/tests/mixin-to-css-variable.ts/mixin-to-css-variable.test.ts
packages/bezier-codemod/src/utils/import.ts

- FIxes https://github.com/channel-io/bezier-react/issues/1778
- Mixin interpolation 을 css variable 을 사용한 스타일 코드로 변환하는 codemod 를 추가합니다.
- As-is
```typescript
import { 
styled, 
inputWrapperStyle, 
focusedInputWrapperStyle, 
erroredInputWrapperStyle,
} from '@channel.io/bezier-react'
const Wrapper = styled.div`
position: relative;
background-color: ${({ foundation }) =>
foundation?.theme?.['bg-grey-lightest']};
border-radius: 12px;
${inputWrapperStyle};
${({ focus }) => focus && focusedInputWrapperStyle};
${({ focus, whisper }) => focus && whisper && erroredInputWrapperStyle};
`
```
- To-be
```typescript
import {
styled, css
} from '@channel.io/bezier-react'
const Wrapper = styled.div`
position: …
```

Add codemod for mixin interpolation

---

packages/bezier-react/src/components/Avatars/Avatar/Avatar.styled.ts
packages/bezier-react/src/components/Avatars/Avatar/Avatar.test.tsx
packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
packages/bezier-react/src/components/Button/Button.styled.ts
packages/bezier-react/src/components/Button/Button.test.tsx
packages/bezier-react/src/components/Button/__snapshots__/Button.test.tsx.snap
packages/bezier-react/src/components/Forms/Checkbox/Checkbox.styled.ts
packages/bezier-react/src/components/Forms/Inputs/Select/Select.styled.ts
packages/bezier-react/src/components/Forms/Inputs/Select/Select.test.tsx
packages/bezier-react/src/components/Forms/Inputs/Select/__snapshots__/Select.test.tsx.snap
packages/bezier-react/src/components/Forms/Inputs/TextArea/TextArea.styled.ts
packages/bezier-react/src/components/Forms/Inputs/TextArea/TextArea.test.tsx
packages/bezier-react/src/components/Forms/Inputs/TextField/TextField.styled.ts
packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.styled.ts
packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.styled.ts
packages/bezier-react/src/components/Forms/Slider/Slider.styled.ts
packages/bezier-react/src/components/Forms/Slider/__snapshots__/Slider.test.tsx.snap
packages/bezier-react/src/components/Forms/Switch/Switch.styled.ts
packages/bezier-react/src/components/Forms/Switch/Switch.test.tsx
packages/bezier-react/src/components/LegacyRadio/LegacyRadio.styled.ts
packages/bezier-react/src/components/LegacyRadio/LegacyRadio.test.tsx
packages/bezier-react/src/components/ListItem/ListItem.styled.ts
packages/bezier-react/src/constants/DisabledOpacity.ts

- #1106
Migrate `DisabledOpacity` constant to CSS variable
`DiabledOpacity` 상수를 `--opacity-disabled` CSS variable로 변경합니다.
No
- #1106

Migrate `DisabledOpacity` constant

---

.changeset/purple-dodos-move.md
packages/bezier-tokens/scripts/lib/transform.ts
packages/bezier-tokens/scripts/lib/utils.ts

letter spacing 관련 토큰 값이 잘못 변환되던 문제를 수정합니다.
기존 `extractNumber` 정규식이 숫자만 매칭했기 때문에, 소숫점이 포함된 letter spacing 토큰이 소숫점을 무시한채로 필터링되었습니다.
예컨대 `0.1` 이 `01` 로 필터링이 되면서, parseFloat에 의해 `1` 로 변환이 되었고 결과적으로 10배 높은 값으로 변환되었습니다.
올바르게 동작할 수 있도록 정규식을 개선합니다. 이제 부호와 소숫점 모두 포함하여 필터링할 수 있게 됩니다. 
No

fix(bezier-tokens): fix invalid letter spacing token values

---

packages/bezier-react/src/components/AlphaSmoothCornersBox/AlphaSmoothCornersBox.tsx
packages/bezier-react/src/components/AlphaStack/AlphaStack.tsx
packages/bezier-react/src/components/Avatars/Avatar/Avatar.tsx
packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.tsx
packages/bezier-react/src/components/Forms/Checkbox/Checkbox.tsx
packages/bezier-react/src/components/Forms/FormControl/FormControl.tsx
packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.tsx
packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControlIndicator.tsx
packages/bezier-react/src/components/Forms/Slider/Slider.tsx
packages/bezier-react/src/components/Modals/Modal/ModalContent.tsx
packages/bezier-react/src/components/Spinner/Spinner.tsx
packages/bezier-react/src/components/Status/Status.tsx
packages/bezier-react/src/components/Tabs/TabList.tsx
packages/bezier-react/src/utils/props.ts
packages/bezier-react/src/utils/style.ts

Remove runtime overhead related with css variables
- 단순 문자열을 반환하는 함수인데 불필요하게 함수로 분리할 필요가 없다고 판단하여 제거합니다
- 오버헤드를 없애자면 빌드 타임에 cv() -> 해당하는 문자열로 변경해줘도 되지만, 굳이 필요한가 싶어서 기존처럼 단순 string으로 변경했습니다
- cssVarValue -> cssVar로 이름 단순화
No
없음

Remove runtime overhead related with css variables

---

.changeset/tender-donkeys-promise.md
packages/bezier-react/src/components/Overlay/Overlay.stories.tsx

closes #1799 
Overlay Storybook 에서 container 크기 조절을 위한 containerProps가 동작하지 않던 문제를 해결하고, target의 위치를 위한 targetProps를 추가합니다.
문제 원인은 props를 containerWidth, containerHeight로 넘겨주는데, 받는 쪽에서 width, height로 받고 있어서 동작하지 않았습니다. conatinerWidth, containerHeight로 받도록 수정하였습니다.
targetProps는 containerProps와 동일한 방법으로 조절하도록 추가하였습니다.
없습니다.
[채널톡](https://desk.channel.io/root/groups/WebBezier-124831/657bef5ea1193bf10d53)

feat(Overlay.stories): fix not working containerWidth/Height and add targetProps to control target's position in Overlay Storybook

---

.changeset/hot-parrots-shop.md
packages/bezier-tokens/src/semantic/dark-theme/color.json
packages/bezier-tokens/src/semantic/light-theme/color.json

- #1820
add the missing `bg-header-float` semantic color token
- #1820 변경사항 중 일부를 cherry-pick 합니다.
No

fix(bezier-tokens): add the missing `bg-header-float` semantic color token

---

.changeset/quick-peaches-fail.md
packages/bezier-react/src/components/Stack/Stack.module.scss
packages/bezier-react/src/components/Text/Text.module.scss
packages/bezier-react/src/components/shared.module.scss
packages/bezier-react/src/utils/props.ts

#1837 에서 이어집니다. d074178e534101ad1abea5b1ade258760d94c1fa 부터
CSS variable을 사용할 때 명시적으로 Rule 안에서 초깃값을 지정하도록 합니다.
- CSS variable(CSS Custom property)의 값은 상속의 대상이 되기 때문에, 명시적으로 값을 초기화해두지 않으면 부모의 값을 상속하게 됩니다. 
- 이전 Box 등의 레이아웃 컴포넌트를 구현할 때, 공용 margin 속성 및 layout 속성에 초기화 대신 fallback 값으로만 기본값을 정의해두었습니다.
- 이렇게 구현할 경우, 부모에 같은 스타일이 있으면(e.g. `--b-margin: 10px`) 자식 엘리먼트가 fallback 값을 적용하지 않고 **부모의 스타일을 적용하게됩니다.**
- 이를 명시적으로 기본값을 부여하여 해결했습니다. 기본적으로 `initial` 키워드로 브라우저 기본값을 따랐고, margin/padding 등 shorthand property에서는 shorthand property로 initial 키워드를 사용할 수 없으므로(`margin: initial initial initial initial => invalid`) MDN 문서를 참고하여 속성의 기본값을 직접 지정해주었습니다. 
- border-style의 경우 기본값이 `none` 이므로, border-width가 있을 때 별도의 style …

fix(styles): fix to explicitly initialize CSS variables

---

.changeset/tough-rats-drive.md
packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
packages/bezier-react/src/components/Box/Box.tsx
packages/bezier-react/src/components/Button/__snapshots__/Button.test.tsx.snap
packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
packages/bezier-react/src/components/Forms/FormGroup/__snapshots__/FormGroup.test.tsx.snap
packages/bezier-react/src/components/Forms/FormHelperText/__snapshots__/FormHelperText.test.tsx.snap
packages/bezier-react/src/components/Forms/FormLabel/__snapshots__/FormLabel.test.tsx.snap
packages/bezier-react/src/components/Forms/Inputs/Select/__snapshots__/Select.test.tsx.snap
packages/bezier-react/src/components/KeyValueListItem/__snapshots__/KeyValueListItem.test.tsx.snap
packages/bezier-react/src/components/LegacyTooltip/__snapshots__/LegacyTooltip.test.tsx.snap
packages/bezier-react/src/components/ListItem/__snapshots__/ListItem.test.tsx.snap
packages/bezier-react/src/components/Navigator/NavGroup/__snapshots__/NavGroup.test.tsx.snap
packages/bezier-react/src/components/Navigator/NavItem/__snapshots__/NavItem.test.tsx.snap
packages/bezier-react/src/components/Stack/Stack.tsx
packages/bezier-react/src/components/Text/Text.tsx
packages/bezier-react/src/styles/components/layout.module.scss
packages/bezier-react/src/styles/components/margin.module.scss
packages/bezier-react/src/types/ComponentProps.ts
packages/bezier-react/src/utils/props.ts

공용 Margin css module과 Layout 컴포넌트 공용 css module을 개선합니다.
1.디자인 토큰을 사용하지 않고 2. dimension value를 사용하지 않는, 적은 수의 키워드만 값으로 사용할 수 있는 CSS 속성들의 타입을 명확하게 좁히고 이를 inline style 대신 class로 스타일링하도록 개선했습니다. 불필요한 스타일 계산을 최소화하기 위함입니다.
- 디자인 토큰도 갯수가 정해져있으므로 모두 class를 정의해둘 수 있지만(`.color-txt-black-darkest { color: var(--txt-black-darkest')}`), 이렇게 되면 토큰 스펙 변경에 따라 클래스명도 함께 변경해주어여하니 사람이 직접 추적해야하는 곳이 너무 많아지므로... 약간의 성능을 잃더라도 중앙 집중식 관리(bezier-tokens를 통한)의 이점을 챙기는 편이 더 좋다고 판단했습니다. CSS 파일 용량도 무시 못하게 올라가기도 합니다.
- 이 방식을 채택하자면 차라리 지금이라도 tailwind 처럼 utility class 기반 + 사용처에서 CSS를 build하는 방향으로 가는 게 맞는데, 디자인 시스템 라이브러리에서 이런 방향이 맞는지 모르겠습니다. 라이브러리 사용처에 특정 기술의 사용을 강요하다보면 또 styled-components와 같은 전철을 밟게 될 거 같다는 두려움이 있어요.
- radix UI …

Enhance margin, layout common css module

---

.changeset/slimy-lobsters-sparkle.md
packages/bezier-codemod/README.md
packages/bezier-codemod/src/App.tsx
packages/bezier-codemod/src/shared/enum.ts
packages/bezier-codemod/src/transforms/enum-member-to-string-literal/transform.ts
packages/bezier-codemod/src/transforms/v2-z-index-interpolation-to-css-variable/fixtures/z-index-enum-as-prop.input.tsx
packages/bezier-codemod/src/transforms/v2-z-index-interpolation-to-css-variable/fixtures/z-index-enum-as-prop.output.tsx
packages/bezier-codemod/src/transforms/v2-z-index-interpolation-to-css-variable/fixtures/z-index-enum-not-from-bezier-react.input.tsx
packages/bezier-codemod/src/transforms/v2-z-index-interpolation-to-css-variable/fixtures/z-index-enum-not-from-bezier-react.output.tsx
packages/bezier-codemod/src/transforms/v2-z-index-interpolation-to-css-variable/fixtures/z-index-enum.input.tsx
packages/bezier-codemod/src/transforms/v2-z-index-interpolation-to-css-variable/fixtures/z-index-enum.output.tsx
packages/bezier-codemod/src/transforms/v2-z-index-interpolation-to-css-variable/fixtures/z-index-interpolation-in-styled-component.input.tsx
packages/bezier-codemod/src/transforms/v2-z-index-interpolation-to-css-variable/fixtures/z-index-interpolation-in-styled-component.output.tsx
packages/bezier-codemod/src/transforms/v2-z-index-interpolation-to-css-variable/transform.test.ts
packages/bezier-codemod/src/transforms/v2-z-index-interpolation-to-css-variable/transform.ts
packages/bezier-codemod/src/utils/enum.ts
packages/bezier-codemod/src/utils/import.ts

- Fixes #1793
- https://github.com/channel-io/bezier-react/pull/1844 머지 후 rebase 예정 (from [252c358](https://github.com/channel-io/bezier-react/pull/1845/commits/252c358029a138102e96f04328dc8671945598ec))
- z-index interpolation 을 위한 codemod 를 추가합니다. 변환을 고려해야 하는 상황은 다음과 같이 2가지가 있습니다.
1. styled-component 내에서 interpolation 으로 사용될 때
```tsx 
// As-is
export const Box = styled.div`
z-index: ${ZIndex.Hide};
`
// To-be
export const Box = styled.div`
z-index: var(--z-index-hidden);
`
```
2. .tsx 파일에서 객체로 사용될 때
```tsx
// As-is
const overlayStyle = {
zIndex: ZIndex.Tooltip,
}
// To-be
const overlayStyle = {
zIndex: 'var(--z-index-tooltip)',
}
```
-  2가지 모두 기존에 만들어 놓았던 codemod 를 사용해서 구현가능하기 때문에 특별히 어려운 점은 …

Add codemod for z-index interpolation

---

.changeset/early-tables-taste.md
packages/bezier-codemod/README.md
packages/bezier-codemod/src/App.tsx
packages/bezier-codemod/src/shared/enum.ts
packages/bezier-codemod/src/transforms/enum-member-to-string-literal/transform.ts
packages/bezier-codemod/src/transforms/v2-text-component-interface/fixtures/text-component-attrs.input.tsx
packages/bezier-codemod/src/transforms/v2-text-component-interface/fixtures/text-component-attrs.output.tsx
packages/bezier-codemod/src/transforms/v2-text-component-interface/fixtures/text-component-props.input.tsx
packages/bezier-codemod/src/transforms/v2-text-component-interface/fixtures/text-component-props.output.tsx
packages/bezier-codemod/src/transforms/v2-text-component-interface/fixtures/text-component-with-interpolation.input.tsx
packages/bezier-codemod/src/transforms/v2-text-component-interface/fixtures/text-component-with-interpolation.output.tsx
packages/bezier-codemod/src/transforms/v2-text-component-interface/transform.test.ts
packages/bezier-codemod/src/transforms/v2-text-component-interface/transform.ts
packages/bezier-codemod/src/transforms/v2-z-index-interpolation-to-css-variable/transform.ts
packages/bezier-codemod/src/utils/component.ts

- Fixes https://github.com/channel-io/bezier-react/issues/1816
- `Text` 컴포넌트의 인터페이스를 변경하기 위한 codemod 를 추가합니다. 아래와 같이 변환됩니다.
- https://github.com/channel-io/bezier-react/pull/1844 base, from a1f267f17a8d6fced227575d6f39c60914ee9896 
```tsx
// As-is
import { Text, Typography } from '@channel.io/bezier-react'
<Text 
typo={Typography.Size14}
marginHorizontal={6}
>
some text
</Text>
// To-be
import { Text } from '@channel.io/bezier-react'
<Text 
typo="14"
mx={6}
>
some text
</Text>
// As-is
import { Text, styled, Typography } from '@channel.io/bezier-react'
const Title = styled(Text).attrs({
typo: Typography.Size11,
marginHorizontal: 6,
})``
// To-be
import { Text, styled } from …
```

Add codemod for `Text` component interface

---

packages/bezier-react/src/components/Stack/Stack.module.scss
packages/bezier-react/src/components/Stack/Stack.stories.tsx
packages/bezier-react/src/components/Text/Text.module.scss
packages/bezier-react/src/components/Text/Text.stories.tsx
packages/bezier-react/src/stories/ComponentConvention/PropsInterface.stories.mdx

- https://github.com/channel-io/bezier-react/issues/1865
- `Text`, `Stack` 컴포넌트 스타일링의 css 우선순위를 낮추기 위해 :where 셀렉터를 사용합니다.
- 컴포넌트 스토리북에 args 를 추가합니다. 
- No

Use `:where` pseudo class to `Text`, `Stack` components

---

packages/bezier-react/rollup.config.mjs

Make CSS module scope names more unique
CSS modules scope name을 더 유니크하게 변경합니다.
- postcss-modules의 [해시 생성 로직](https://github.com/madyankin/postcss-modules/blob/325f0b33f1b746eae7aa827504a5efd0949022ef/src/scoping.js#L36-L42)을 보면 해시가 겹칠 일은 거의 없겠지만, 클래스명이 겹치는 가능성을 최대한 줄이기 위해 CSS 파일이 위치한 폴더명을 클래스명에 추가하도록 했습니다.
- 임의의 `hashPrefix` 를 추가하여 다른 라이브러리와 클래스명이 겹칠 가능성을 더 낮췄습니다.
No
없음

Make CSS module scope names more unique

---

packages/bezier-react/package.json
packages/bezier-react/postcss-auto-layer.mjs
packages/bezier-react/rollup.config.mjs
packages/bezier-react/src/components/Avatars/Avatar/Avatar.module.scss
packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.module.scss
packages/bezier-react/src/components/Box/Box.module.scss
packages/bezier-react/src/components/Center/Center.module.scss
packages/bezier-react/src/components/Divider/Divider.module.scss
packages/bezier-react/src/components/Emoji/Emoji.module.scss
packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.module.scss
packages/bezier-react/src/components/Forms/Slider/Slider.module.scss
packages/bezier-react/src/components/Forms/Switch/Switch.module.scss
packages/bezier-react/src/components/Help/Help.module.scss
packages/bezier-react/src/components/Icon/Icon.module.scss
packages/bezier-react/src/components/Spinner/Spinner.module.scss
packages/bezier-react/src/components/Stack/Stack.module.scss
packages/bezier-react/src/components/Status/Status.module.scss
packages/bezier-react/src/components/TagBadge/Badge/Badge.module.scss
packages/bezier-react/src/components/TagBadge/Tag/Tag.module.scss
packages/bezier-react/src/components/TagBadge/TagBadgeCommon/TagBadge.module.scss
packages/bezier-react/src/components/Text/Text.module.scss
packages/bezier-react/src/components/Tooltip/Tooltip.module.scss
packages/bezier-react/src/styles/components/layout.module.scss
packages/bezier-react/src/styles/components/margin.module.scss
yarn.lock

- Fixes #1884
Enchance to add `@layer components` at-rule in CSS post-processing
- 커스텀 PostCSS plugin을 통해 CSS를 갈아끼우는 방식으로 구현했습니다. 구현은 단순합니다.
- 불필요해진 *.module.scss의 `@layer components` at-rule을 제거했습니다.
- `*.module.scss` + `components` 디렉토리 내부에 위치한 파일만 처리하도록 구현했습니다. 여기엔 layout, margin props도 포함되니 이후 디렉터리명 변경에 유의해야합니다.
- 이전/이후 빌드된 CSS 파일이 동일한 것을 확인했습니다.
No
- https://postcss.org/docs/writing-a-postcss-plugin
- 공식 홈페이지는 CJS인데, ESM으로 만들기 위해 참고: https://github.com/postcss/postcss/issues/1771

Enchance to add `@layer components` at-rule in CSS post-processing

---

packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.tsx
packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.tsx
packages/bezier-react/src/components/Forms/Switch/Switch.tsx
packages/bezier-react/src/features/FeatureProvider.tsx

- #1877 
- `yarn test`실행 시 테스트 코드에서 나오는 warning message의 일부를 resolve합니다.
- https://app.circleci.com/pipelines/github/channel-io/bezier-react/5804/workflows/c0aae4cd-38de-4423-a3fc-9480443ef7f9/jobs/22311 여기서 실행 결과를 보면, 성공한 테스트임에도 불구하고 굉장히 많은 경고 메시지가 테스트 결과에 포함되는 것을 볼 수 있습니다. 이런 불필요한 메시지가 로그에 포함되면 테스트 코드 결과를 파악하기도 어렵고, 경고 메시지 자체가 잠재적인 버그의 원인이기 때문에 결코 무시할 수 없습니다.
- 이번 작업으로 95%이상 경고 메시지를 줄였고, scss 마이그레이션 작업을 하면서 완전히 없애면 좋을 것 같습니다
- 에러 메시지의 원인은 아래와 같았습니다.
- jest test callback 함수 안에서 비동기 작업이 수행됨 -> 대부분의 로그를 차지하고 있는 문제로, FeatureProvider 안에서 오타 수정하면 Promise 실행 안하게 됨
- active="false" -> 정확한 원인은 아직 파악 안된 상태..
- Icon컴포넌트의 forwardRef -> 아마 styled(Icon) 으로 감싸고 나서 asChild로 인한 ref forwarding이 안되는 이슈인 듯하여 scss로 …

Resolve some warning message during test

---

.changeset/tender-years-camp.md
packages/bezier-react/src/components/Box/Box.types.ts
packages/bezier-react/src/components/Button/Button.tsx
packages/bezier-react/src/components/Button/Button.types.ts
packages/bezier-react/src/components/Modals/Modal/Modal.test.tsx
packages/bezier-react/src/components/Stack/Stack.types.ts
packages/bezier-react/src/components/Text/Text.types.ts
packages/bezier-react/src/types/ComponentProps.ts

- #1106
Change the `as` prop to allow all element types and button to allow `as` prop
- as 속성이 모든 엘리먼트 타입을 지원하도록 변경합니다. 단순 HTML element type 외에도, Link 컴포넌트를 as 속성에 주입하는 등의 케이스가 있습니다. 이를 지원하여 breaking change를 줄이기 위한 변경입니다.
- `Button` 또한 마찬가지로 Link, a 태그 등으로 사용되는 케이스들이 있습니다. as 속성을 지원하도록 개선했습니다.
No

Change the `as` prop to allow all element types and button to allow `as` prop

---

packages/bezier-react/src/components/Banner/Banner.module.scss

`flex-start` 대신 `start` 를 사용하여 발생한 빌드 경고를 수정합니다.

refactor(banner): remove postcss build warning

---

.changeset/famous-trees-wash.md
packages/bezier-codemod/src/transforms/v2-foundation-to-css-variable/fixtures/transition1.input.tsx
packages/bezier-codemod/src/transforms/v2-foundation-to-css-variable/fixtures/transition1.output.tsx
packages/bezier-codemod/src/transforms/v2-foundation-to-css-variable/transition.ts

- Transition codemod에서 TransitionDuration 을 css variable 로 변환 후 import 에서 제거하지 않는 버그가 있어서 이를 수정합니다. 코드 변환이 일어났을 때 `sourceFile.fixUnusedIdentifiers()`를 실행하면 됩니다. 
- No
- None

Fix unused import in transition codemod

---

.changeset/funny-peaches-report.md
packages/bezier-react/src/components/Forms/FormControl/FormControl.module.scss
packages/bezier-react/src/components/Forms/FormControl/FormControl.styled.ts
packages/bezier-react/src/components/Forms/FormControl/FormControl.tsx
packages/bezier-react/src/components/Forms/FormControl/FormControl.types.ts
packages/bezier-react/src/components/Forms/FormControl/__snapshots__/FormControl.test.tsx.snap
packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.module.scss
packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.styled.ts
packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.tsx
packages/bezier-react/src/components/Forms/FormHelperText/FormHelperText.types.ts
packages/bezier-react/src/components/Forms/FormHelperText/__snapshots__/FormHelperText.test.tsx.snap
packages/bezier-react/src/components/Forms/FormLabel/FormLabel.module.scss
packages/bezier-react/src/components/Forms/FormLabel/FormLabel.stories.tsx
packages/bezier-react/src/components/Forms/FormLabel/FormLabel.styled.ts
packages/bezier-react/src/components/Forms/FormLabel/FormLabel.test.tsx
packages/bezier-react/src/components/Forms/FormLabel/FormLabel.tsx
packages/bezier-react/src/components/Forms/FormLabel/FormLabel.types.ts
packages/bezier-react/src/components/Forms/FormLabel/__snapshots__/FormLabel.test.tsx.snap
packages/bezier-react/src/components/Forms/FormLabel/index.ts

- #1733 
- `FormHelperText`, `FormErrorMessage`, `FormLabel`컴포넌트를 scss로 마이그레이션 하고 `as`, `interpolation`속성을 인터페이스에서 제거합니다. 
- 각각의 컴포넌트를 scss로 마이그레이션할 때, `FormControl.styled.ts`에 있던 스타일 코드를 각 컴포넌트의 .module.scss로 이동시켰습니다. 또한 context로서 Wrapper컴포넌트를 주던 것을 `labelPosition`만 주고 각 컴포넌트의 .module.scss에서 스타일링 하도록 변경했습니다. `FornControl.module.scss`에서 스타일링 코드를 작성하고 각 컴포넌트에서는 여기에 있는 className을 사용하게 할 수도 있었는데, 컴포넌트간의 의존성을 만드는 것이 좋지 않아보여서 이렇게 했습니다.
- Ref타입으로 deprecated된 HTMLParamElement을 쓰던 것을 적절한 타입으로 변경합니다.
- 컴포넌트의 레이아웃이 `labelPosition`에 영향을 받기 때문에 일부러 `MarginProps`는 인터페이스로 노출하지 않았습니다. 
- 지금은 `Text`의 속성을 그대로 노출하고 있는데, 사실상 고정된 스타일(color, typo)를 사용하고 있기 때문에 이런 속성역시 제거해야되나 고민됩니다. 어떻게 생각하시는지 궁금합니다 @sungik-choi 
- …

Migrate `FormHelperText`, `FormErrorMessage`, and `FormLabel` component with scss

---

.changeset/thick-actors-kneel.md
packages/bezier-react/src/components/Toast/Toast.stories.tsx
packages/bezier-react/src/components/Toast/Toast.styled.ts
packages/bezier-react/src/components/Toast/Toast.types.ts
packages/bezier-react/src/components/Toast/ToastProvider.tsx
packages/bezier-react/src/components/Toast/utils.ts

toastContainer가 web-desk의 GNB 만큼의 좌측 여백을 확보하던 스타일링을 제거합니다
이제 toast의 표시 위치가 toastContainer (default: document.body)의 좌/우 하단에 위치하게 됩니다
`ToastProvider`에 enableLeftSpacing props를 추가합니다
- 기본값은 true (기존처럼 좌측에 GNB_WIDTH만큼의 offset을 추가
- false시 container의 `left:0` 포지셔닝을 잡습니다
|as-is|to-be|
|---|---|
|![asis](https://github.com/channel-io/bezier-react/assets/55074799/9433631e-22d0-47af-a9ce-516b68c1da58)|![tobe](https://github.com/channel-io/bezier-react/assets/55074799/135b6354-e9b7-45f3-979a-434087ff9503)|
Yes
만약 좌하단의 여백을 기존 동작처럼 유지하고 싶다면
1. document.body 하위에 container를 위치하고
2. container의 position을 원하는 만큼 변경해야 합니다 (as-is left:68px)

Remove constant for toastContainer positioning for ch-web-desk

---

.changeset/sour-dogs-sin.md
packages/bezier-codemod/README.md
packages/bezier-codemod/src/transforms/v2-input-interpolation-to-css-variable/fixtures/input-interpolation.input.tsx
packages/bezier-codemod/src/transforms/v2-input-interpolation-to-css-variable/fixtures/input-interpolation.output.tsx
packages/bezier-codemod/src/transforms/v2-input-interpolation-to-css-variable/transform.ts

- https://github.com/channel-io/bezier-react/issues/1778
- `inputPlaceholderStyle` mixin 에 대한 변환 로직을 codemod 에 추가하고 README를 업데이트 했습니다. 
- No
- None

Add missed `inputPlaceholderStyle` migration logic to codemod

---

.changeset/gentle-shirts-grow.md
packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.stories.tsx
packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.test.tsx
packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.tsx
packages/bezier-react/src/components/Navigator/NavGroup/NavGroup.types.ts
packages/bezier-react/src/components/Navigator/NavItem/NavItem.stories.tsx
packages/bezier-react/src/components/Navigator/NavItem/NavItem.test.tsx
packages/bezier-react/src/components/Navigator/NavItem/NavItem.tsx
packages/bezier-react/src/components/Navigator/NavItem/NavItem.types.ts

- Fixes #1929
Rename `leftIcon` property of `NavItem` and `NavGroup` to `leftContent`
이슈로 갈음합니다.
Yes

feat(navigators): rename `leftIcon` property of `NavItem` and `NavGroup` to `leftContent`

---

.changeset/bright-zoos-attend.md
packages/bezier-codemod/src/shared/enum.ts
packages/bezier-codemod/src/transforms/v2-foundation-to-css-variable/transition.ts
packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/fixtures/z-index-enum.output.tsx
packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/input.ts
packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/typography.ts
packages/bezier-codemod/src/transforms/v2-interpolation-to-css-variable/zIndex.ts
packages/bezier-codemod/src/transforms/v2-text-component-interface/fixtures/other-text-component-props.input.tsx
packages/bezier-codemod/src/transforms/v2-text-component-interface/fixtures/other-text-component-props.output.tsx
packages/bezier-codemod/src/transforms/v2-text-component-interface/transform.test.ts
packages/bezier-codemod/src/transforms/v2-text-component-interface/transform.ts
packages/bezier-codemod/src/utils/component.ts
packages/bezier-codemod/src/utils/import.ts

- https://github.com/channel-io/bezier-react/issues/1816
- `v2-text-component-interface` codemod 가 속성 값의 이름을 변경할 때(e.g. typo={Typography.Size14} -> typo='14'), 컴포넌트 이름을 확인하지 않고 속성의 이름만 확인하도록 변경합니다. 
- `sourceFile.fixUnusedImports()` 를 제거합니다.
- 기존의 변환 로직에서는 컴포넌트 이름이 정확히 `Text`이어야 하기 때문에 아래와 같은 경우를 변환할 수 없었습니다. Text 컴포넌트는 사용처가 워낙 많아서 이름을 바꿔서 사용하는 곳도 많았습니다. 데스크 코드 기준으로 이런 경우가 100 여개 정도는 되었기 때문에 변환에 포함시키도록 합니다. `Text` 말고는 typo={Typography} 를 props 로 가지는 컴포넌트가 없기 때문에 이렇게 해도 문제가 없을 것으로 생각됩니다. 
```tsx
import * as Styled from './some.styled.ts'
import { Typography } from '@channel.io/bezier-react'
<Styled.Title typo={Typography.Size14}>
channel
</Styled.Title>
```
- `Typography` enum 을 제거하면서 사용처가 없어질 때, …

Modify `v2-text-component-interface` codemod to cover more case

---

packages/bezier-react/src/components/AlphaSmoothCornersBox/AlphaSmoothCornersBox.module.scss
packages/bezier-react/src/features/SmoothCornersFeature/smoothCornersScript.ts

Fixes #1955
Add a separator(,) to the shadow custom property
- shadow 커스텀 속성에 `,` 구분자를 추가합니다.
- shadow 커스텀 속성에서 그림자 속성들을 추출하는 로직을 수정합니다. 쉼표와 그 이후 0개 이상의 공백을 기준으로 속성들을 나눕니다.
No

fix(smooth-corners): add a separator(,) to the shadow custom property

---

packages/bezier-react/src/components/FormHelperText/FormHelperText.tsx

FormHelperText: Fix invalid object key of get form context props
간단한 변경사항이므로 Summary로 대체합니다.
No

refactor(form-helper-text): fix invalid object key of get form context props

---

.changeset/curvy-dragons-rest.md
packages/bezier-react/src/components/AppProvider/AppProvider.tsx
packages/bezier-react/src/components/Tooltip/Tooltip.test.tsx
packages/bezier-react/src/components/Tooltip/Tooltip.tsx
packages/bezier-react/src/components/Tooltip/Tooltip.types.ts
packages/bezier-react/src/components/Tooltip/index.ts

- Fixes #1732
Improve performance of `Tooltip` and remove `TooltipProvider`
- #1732 를 참고해주세요.
- 초기에 floating-ui를 사용하여 구현했으나, radix-ui floating element간의 사용성(예 - esc키를 눌렀을 경우 가장 상위에 floating element만 사라짐) & 적은 Breaking change를 고려하여 TooltipProvider를 내부에 위치시키는 방식으로 변경했습니다. 생각보다 floating-ui로 구현했을 때와 성능상 차이는 거의 없었습니다.
- JSDoc을 업데이트했습니다. 기존 문의가 많았던 radix 관련 ref forwarding, spread props에 대한 내용을 추가했습니다.
- 툴팁 바깥을 눌렀을 때 툴팁이 dismiss되는 케이스에 대한 단위 테스트를 추가했습니다.
**AS-IS:** production 기준
**TO-BE:** 채널 데스크 앱에 bezier-react@2.0.0-alpha.7 + 해당 PR 변경 사항 적용. local + production target 기준
Tooltip이 굉장히 많이 존재하는 고객 태그 관리 페이지에서, 마우스가 호버되고나서 툴팁이 렌더되기 전까지 퍼포먼스를 측정했습니다.
**Scripting 소요 시간(노란색)이 크게 감소한 걸 확인할 수 있습니다.**
| AS-IS | …

Improve performance of `Tooltip` and remove `TooltipProvider`

---

.changeset/strange-colts-beg.md
packages/bezier-react/src/components/Banner/Banner.tsx

- Fixes #1486 
feat(banner): enhance to render link even when content is not a string
- content의 조건부 렌더링 로직을 제거합니다. 이제 content가 무엇이든(ReactNode) 상관없이 content와 하위 링크를 렌더하도록 합니다.
- Banner 컴포넌트 특성 상 대체로 내용이 변하지 않는 텍스트가 들어갈 거로 가정했습니다. content에 빈 문자열을 넣거나 하는 케이스(empty check)를 고려할 필요가 없다고 판단했습니다.
No

feat(banner): enhance to render link even when content is not a string

---

.changeset/sixty-cows-fetch.md
packages/bezier-react/src/components/Overlay/Overlay.test.tsx
packages/bezier-react/src/components/Overlay/Overlay.tsx
packages/bezier-react/src/features/SmoothCornersFeature/smoothCornersScript.ts

- None
- 오버레이 안의 요소를 클릭했을 때 오버레이가 닫히는 버그가 있어서 이를 수정합니다. 
- target.closest 안에 적절한 선택자가 아니어서 발생한 문제입니다. 
- event의 any 타입을 수정하여 타입 체크를 강화합니다. 
- smoothcorners 스크립트에 불필요하게 들어가있었던 로그를 제거합니다. 
- No
- None

Fix bug where overlay would close when clicking inside it

---

packages/bezier-react/rollup.config.mjs

Shorten css module's scope name
- folder, local명이 모두 클래스명에 포함되면서 디버깅이 용이해졌지만, 생각보다 유의미하게 CSS 사이즈가 증가했습니다. (전체 사이즈 대비)
- 디버깅 용이성보단 용량을 줄이는 것이 프로덕션 환경에선 더 중요하다고 판단하여 `b-` prefix와 해시를 제외한 folder, local명을 클래스명에서 제외합니다.
- bezier-react의 CSS임을 확인할 수는 있도록 `b-` prefix는 유지하도록 했습니다.
- 해시와 prefix, 그리고 hashPrefix를 사용하므로 해시 충돌이 일어날 일은 거의 없다고 봐도 무방할 거 같습니다.
**용량 차이**
- 모두 작성할 경우: 104KB
- local만 제거할 경우: 89KB (-15KB, -14.42%)
- hash를 제외하고 모두 제거할 경우: 75KB (-29KB, -27.88%)
- hash + `b-` prefix: 78KB (-26KB, -25%)
No
- https://github.com/madyankin/postcss-modules

build(rollup): shorten css module's scope name

---

packages/bezier-react/src/components/AvatarGroup/AvatarGroup.tsx
packages/bezier-react/src/components/Modal/Modal.tsx
packages/bezier-react/src/components/Modal/Modal.types.ts
packages/bezier-react/src/components/NavGroup/NavGroup.tsx
packages/bezier-react/src/components/NavItem/NavItem.tsx

Fixes #1122
Remove default value of event handler props
#1122 를 참고해주세요.
No

refactor: remove default value of event handler props

---

.changeset/witty-kids-tie.md
packages/bezier-react/src/components/LegacyTooltip/LegacyTooltipContent.tsx
packages/bezier-react/src/components/Modal/Modal.tsx
packages/bezier-react/src/components/Overlay/Overlay.tsx
packages/bezier-react/src/components/Toast/Toast.tsx
packages/bezier-react/src/components/Tooltip/Tooltip.tsx
packages/bezier-react/src/components/WindowProvider/WindowProvider.tsx
packages/bezier-react/src/components/WindowProvider/WindowProvider.types.ts
packages/bezier-react/src/components/WindowProvider/index.ts

feat(window-provider): Add `useRootElement` and JSDoc
- 사용처에서 useWindow 훅에 대한 학습 없이도 rootElement에 쉽게 접근할 수 있도록 useRootElement 훅을 추가합니다. useWindow().rootElement와 동일합니다.
- JSDoc을 추가합니다.
- 리팩토링: 변수 인라인 등
No

feat(window-provider): Add `useRootElement` and JSDoc

---

.changeset/friendly-avocados-love.md
packages/bezier-react/package.json

fix(deps): move bezier-tokens from dev-deps to deps
- bezier-tokens가 bezier-react의 dev dependency에 포함되어있어, 사용처에서 bezier-tokens를 install 하지 않습니다.
- bezier-tokens의 타입 정의를 사용하고 있고, 토큰 데이터를 bezier-react 런타임에 사용하고 있으므로 dependency에 명시해야합니다.
- 번외: bezier-icons가 peer dependency인데, 마찬가지로 '만약' bezier-react만 사용하고, bezier-icons를 사용하지 않는 프로젝트가 있다면 BezierIcon 타입을 찾을 수 없어 any로 추론되는 문제가 발생할 수 있겠다는 생각이 듭니다. 큰 문제가 될 거 같진 않지만요..
No

fix(deps): move bezier-tokens from dev-deps to deps

---

.changeset/giant-terms-impress.md
packages/bezier-codemod/src/transforms/v2-import-from-bezier-to-styled-components/fixtures/only-named-import.input.tsx
packages/bezier-codemod/src/transforms/v2-import-from-bezier-to-styled-components/fixtures/only-named-import.output.tsx
packages/bezier-codemod/src/transforms/v2-import-from-bezier-to-styled-components/transform.test.ts
packages/bezier-codemod/src/transforms/v2-import-from-bezier-to-styled-components/transform.ts

- None
- `v2-import-from-bezier-to-styled-components` 에서 다음과 같이 잘못 변환되는 케이스를 수정합니다.
```tsx
// As-is
import { css } from '@channel.io/bezier-react'
// To-be
import styled from 'styled-components'
```
- named import 를 추가할 때 default import 여부에 상관 없이 import styled from 'styled-components' 를 추가해서 생긴 버그입니다. named import 일 때 올바른 import 문을 추가하여 바로잡습니다. 
- No

Fix bug in `v2-import-from-bezier-to-styled-components`

---

.changeset/tame-news-yawn.md
packages/bezier-react/src/components/ThemeProvider/ThemeProvider.tsx
packages/bezier-react/src/components/ThemeProvider/ThemeProvider.types.ts
packages/bezier-react/src/components/Tooltip/Tooltip.tsx

feat(theme-provider): spread props
- 누락된 ThemeProvider의 prop을 spread합니다. 
- 예를 들어, Tooltip -> ThemeProvider -> Button 식으로 감쌌을 때 이 변경사항 이후로 Button이 Tooltip의 트리거 역할을 잘 수행하게 됩니다.
No

feat(theme-provider): spread props

---

packages/bezier-react/src/components/KeyValueItem/KeyValueItem.tsx

- None
-  test 도중 아래 메시지가 뜨는 것을 막습니다. 
- React.Fragment 일 때 content={undefined} 형식으로 props가 들어가서 뜨는 로그입니다. props 주입을 조건부로 변경해서 로그가 안뜨도록 했습니다. 
- No
- None

Resolve warning message of `KeyValueItem` component during test

---

.changeset/eighty-steaks-play.md
.changeset/plenty-planes-sniff.md
packages/bezier-react/src/components/Avatar/Avatar.tsx
packages/bezier-react/src/components/Icon/Icon.stories.tsx
packages/bezier-react/src/components/ThemeProvider/ThemeProvider.tsx
packages/bezier-react/src/components/ThemeProvider/index.ts
packages/bezier-react/src/components/TokenProvider/TokenProvider.tsx
packages/bezier-react/src/components/TokenProvider/TokenProvider.types.ts
packages/bezier-react/src/index.ts
packages/bezier-tokens/scripts/lib/format.ts

Exports the tokens object from bezier-tokens
bezier-react에서 `tokens` 객체를 export 하도록 변경하고, 몇가지 개선사항들을 적용합니다.
- 변경 이유: `useToken` 훅은 현재 테마에 해당하는 토큰만을 가져올 수 있습니다. 하지만 마이그레이션 하다보니 현재 테마 외에도 다른 테마에 해당하는 토큰 값을 가져오는 유즈 케이스가 꽤 많이 있었습니다. 이 부분은 커버하기 위해, `tokens` 객체를 외부로 내보냅니다.
- `subTheme` 를 일부만 사용하는 경우, 프론트 다크모드의 경우가 이에 해당합니다.
- `tokens` 객체에 deep freeze를 적용하여 내부 객체의 내용도 불변하도록 개선했습니다.
- 소소한 개선: 타입스크립트에서 Readonly 타입으로 추론되므로, 타입만으로 해당 토큰의 실제 값을 알 수 있습니다.
- `useToken` 훅의 이름을 `useTokens` 로 변경합니다. `useThemeName` 과 마찬가지로 context value와 훅의 이름을 통일하는 편이 좋다고 생각했습니다(themeName, tokens). 또한 `useToken` 이라는 이름은 개별 토큰을 반환하는 훅일거 같은 뉘앙스를 풍기며, bezier-tokens 패키지의 이름과도 맞지 않는다고 판단했습니다.
No (alpha)

Exports the tokens object from bezier-tokens

---

.changeset/early-deers-attend.md
packages/bezier-figma-plugin/package.json
packages/bezier-figma-plugin/src/ui/components/ExtractSuccess.tsx
packages/bezier-figma-plugin/src/ui/components/Home.tsx
packages/bezier-figma-plugin/src/ui/components/IconExtract.tsx
packages/bezier-figma-plugin/src/ui/index.tsx
yarn.lock

bezier-figma-plugin에 최신 버전의 bezier-react를 적용합니다.
styled-components를 제거합니다.
No

refactor(bezier-figma-plugin): migrate to use bezier-react v2 alpha

---

.changeset/chilled-oranges-drum.md
packages/bezier-react/src/components/Icon/Icon.module.scss
packages/bezier-react/src/components/ListItem/ListItem.module.scss
packages/bezier-react/src/components/Spinner/Spinner.module.scss
packages/bezier-react/src/components/Status/Status.module.scss
packages/bezier-react/src/components/Tabs/Tabs.module.scss
packages/bezier-react/src/components/Tag/Tag.module.scss
packages/bezier-react/src/components/Text/Text.module.scss

- Fixes #2006
Change incorrect default value of css variable 'inherit' to 'initial'
잘못된 마이그레이션을 수정합니다. 기존에는 아래와 같은 사고 흐름으로 마이그레이션을 진행했었습니다.
```
// AS-IS
color: colorProp ? colorProp : inherit
// TO-BE
// 스타일 외부에서 --color를 조건부 주입하면 되겠다.
--color: inherit;
color: var(--color)
```
하지만 CSS variable의 초기 키워드로 `inherit` 을 설정하는 것과 해당 속성에 직접적으로 `inherit` 을 설정하는 건 동작이 아예 다릅니다.
위의 예를 들어, `--color: inherit` 은 color 속성에 상위 속성을 적용하는 게 아니라, 접근 가능한 가장 가까운 곳에 위치하는 `--color` 의 값을 상속하게됩니다. 한번 더 자세히 풀어보자면 아래와 같습니다.
```
<div style={{ '--color': 'red' }}>
<div style={{ 'color': 'blue: }}>
<Foo />
</div>
</div>
```
맨 위 예제의 스타일이 적용된 컴포넌트를 `Foo` 라고 했을 때 `Foo` 의 color는 `red` 가 됩니다. **`--color` 는 color가 아니라 상위 `--color` 의 …

fix(components): change incorrect default value of css variable 'inherit' to 'initial'

---

.changeset/eight-hounds-smoke.md
packages/bezier-react/src/components/LegacyStack/LegacyStackItem/LegacyStackItem.module.scss

Add missing default margin styles of LegacyStackItem
정상적인 경우라면, `Stack` 이 자식 `StackItem` 에 direction 속성을 주입하는 형태가 되어야 합니다. `StackItem` 의 direction은 undefined가 되면 안됩니다. 하지만 어플리케이션에서 `StackItem` 에 direction 속성을 제대로 주입하지 않은 채로 margin 속성에만 기대어 스타일링 하는 케이스들이 있었습니다(고객 연락처). 이를 수정하기 위해 이전 코드를 참고하여 기본 margin 스타일을 추가하였습니다.
https://github.com/channel-io/bezier-react/blob/898f221836c9c7ec8ea1ec7894d2c9b00b4e2f96/packages/bezier-react/src/components/Stack/StackItem/StackItem.styled.ts#L33-L43
No

fix(legacy-stack): add missing default margin style

---

.changeset/modern-days-cross.md
packages/bezier-react/src/components/FeatureProvider/SmoothCornersFeature/smoothCornersScript.ts

- fixes #2002 
Add `try catch` block to mute the error when `smoothCornerScript` is called twice.
According to the [MDN documentation on `registerPaint()`](https://developer.mozilla.org/en-US/docs/Web/API/PaintWorkletGlobalScope/registerPaint#exceptions), this function only throws two errors. One when the parameters aren't met, throwing `TypeError` and the other when a worklet already exists with the given name, throwing `DOMException`. I thought that any of those two case won't happen in this particular case, so I just no-oped the `catch` statement. If it is not a good approach, I can narrow the error down to the later one, `DOMException`.
No. …

fix(component): make `smoothCornerScript` not throw error when called twice

---

.changeset/five-plants-rescue.md
packages/bezier-react/src/components/ListItem/ListItem.module.scss

- resolves https://github.com/channel-io/bezier-react/issues/2008
- 기존의 ListItem 컴포넌트에는 overflow: hidden 속성이 있었는데 scss 마이그레이션 과정에서 이게 없어지면서 생긴 스타일 차이입니다. 
- overflow: hidden 을 추가합니다. 
- None
- https://github.com/channel-io/bezier-react/pull/1925/files#diff-0c1f9928eb5f00ee455ed0cacd8ed51386570711f0502c324ea1fc6d97189970

Add overflow: hidden to `ListItem` component 

---

.changeset/empty-jars-shop.md
packages/bezier-react/src/components/Modal/Modal.module.scss

`Modal` 내부의 `ModalBody`가 `ModalHeader` 없이 사용될 때 혹은 `ModalFooter`가 `ModalBody` 없이 사용될 때 간격이 조절되지 않던 문제를 수정합니다.
일반적인 케이스에선 문제가 없었으나, 내부 컴포넌트들이 서로 인접해있지 않고 사이에 다른 요소를 두고 있는 경우. 예를 들어,
```html
<ModalHeader />
<div>
<ModalBody />
</div>
<ModalFooter />
```
위와 같은 경우에 스타일이 제대로 적용되지 않던 문제를 수정했습니다.
`ModalContent` 에서 `:has()` 를 사용하는 방식으로 선택자를 단순화했습니다.
No

fix(modal): fix styling issues when subcomponents are used alone

---

.changeset/thin-games-add.md
packages/bezier-react/src/components/ListItem/ListItem.module.scss
packages/bezier-react/src/components/ListItem/ListItem.stories.tsx

- #2009 
Fix `ListItem`'s left icon color specificity issue
#2009 에서 불필요하다고 판단되어 제거된 LeftIcon을 타겟으로 하는 color 스타일을 원상복구합니다.
```scss
&:where(.variant-monochrome) {
color: var(--txt-black-darkest);
& :where(.ListItemLeftIcon) {
color: var(--txt-black-dark);
}
}
```
- 기존 코드의 LeftIcon을 타겟으로 하는 color 스타일이 active 상태의 아이콘 색상보다 우선하여 적용되는 문제가 발생했고, 이를 수정합니다.
- 스토리북의 args에 variant를 추가합니다.
No

fix(list-item): fix left icon color specificity issue

---

packages/bezier-icons/package.json
packages/bezier-react/package.json
yarn.lock

Fixes #1674 
Rollup 버전을 v3에서 v4로 업데이트합니다.
현재 동작에 영향을 끼치는 변경사항은 없습니다.
No
- https://rollupjs.org/migration/
- https://github.com/rollup/rollup/blob/master/CHANGELOG.md#400
- https://ko.vitejs.dev/guide/migration.html#rollup-4

Upgrade to Rollup 4

---

packages/bezier-icons/README.md
packages/bezier-react/.storybook/preview-head.html
packages/bezier-react/README.md

- #1800 
Update README.md
- 다음 버전의 내용에 맞게 문서 내용을 업데이트합니다.
- Chore: bezier-icons 기존 문서의 잘못된 예제 수정
- Chore: storybook preload 잘못된 코드 수정
No

docs: Update README

---

.changeset/grumpy-flowers-trade.md
packages/bezier-react/src/components/Checkbox/Checkbox.module.scss
packages/bezier-react/src/components/Checkbox/Checkbox.tsx
packages/bezier-react/src/components/OutlineItem/OutlineItem.module.scss
packages/bezier-react/src/components/Tabs/Tabs.module.scss
packages/bezier-react/src/components/Tabs/Tabs.tsx

TabAction의 타이포그래피가 13이 아닌 14로 지정돼있던 문제를 수정합니다.
- 리팩토링: 불필요하게 import되던 typography mixin 제거
- 리팩토링: Checkbox의 Label을 Text로 변경 (styled-components 제거 이후 제대로 동작하게 됨)
No
- 피그마 Tab 참고

Fix TabAction typography style for Tab size M

---

.changeset/selfish-turkeys-boil.md
packages/bezier-react/src/components/KeyValueItem/KeyValueItem.module.scss

fix(key-value-item): add overflow hidden style to item wrapper element
scss 마이그레이션 과정에서 `overflow: hidden` 스타일이 제거되어 사용처(채널 데스크)에서 위와 같은 오버플로우 현상이 발생하는 문제를 수정합니다.
No

fix(key-value-item): add overflow hidden style to item wrapper element

---

.changeset/six-humans-occur.md
packages/bezier-react/src/components/Overlay/Overlay.tsx

Fixes `Overlay` not closing in other windows
#1977 에서 타입 강화를 위해 event.target의 인스턴스 체크 로직이 추가되었습니다. `instanceof HTMLElement` 의 `HTMLElement` 는 globalThis(window).HTMLElement와 동일한데, 다른 창에서는 globalThis(window)가 다르므로 HTMLElement의 참조값이 달라 타입 체크가 무조건 실패하는 문제가 있었습니다. 따라서, 오버레이 바깥을 클릭해도 닫히지 않는 문제가 발생했습니다.
타입 단언으로 변경하여 런타임 타입 체크를 제거해 문제를 해결합니다.
No
- https://github.com/channel-io/ch-desk-web/pull/15992

Fixes `Overlay` not closing in other windows

---

.changeset/smart-owls-reply.md
packages/bezier-react/src/components/Toast/Toast.tsx

- Fixes #2116 
Remove the default offset value in Toast
Toast 컴포넌트에서 기본값으로 가지고 있던, 채널 데스크 애플리케이션 종속적인 left offset 상수를 기본값에서 제거합니다.
Yes. 필요한 경우 사용처에서 직접 `left: 68` 값을 주어 사용해야합니다.

fix(toast): remove the default offset(GNB_OFFSET, 68)

---

packages/bezier-react/src/components/Toast/Toast.test.tsx

왜인지 자주 실패하는 Toast의 autoDismiss 관련 비동기 테스트 케이스의 타이밍을 수정해봅니다.
dismiss 되는 딜레이를 줄이고, 테스트 케이스의 timeout을 100에서 1000으로 늘렸습니다.

fix(toast): fix timeout for frequently failing asynchronous test cases

---

packages/bezier-react/src/components/Toast/Toast.tsx

사용성을 위해 Toast에 offset에 특정 값을 하나만 지정해도(예: `{ left: 20 }`) 다른 속성값들에 기본값이 지정되도록 개선합니다.
생략
No

feat(toast): assign default value to each property of Toast offset

---

.circleci/config.yml
package.json
turbo.json

- https://github.com/channel-io/bezier-react/issues/1684
- CI에서 lint, typecheck, test job 이 항상 cache miss 인 것을 수정합니다. 
- job마다 --dry-run=json 옵션을 주고 실행해보니 이전 결과와 hash가 같음에도 불구하고 cache miss가 나고 있었고, 하나의 job 안에서 step(e.g. yarn lint)을 2번 연속으로 실행시키면 cache hit 이 되는 것을 확인했습니다.
- node_modules/.cache/turbo 에 캐시가 저장이 안된다면 2번을 실행시켜도 cache miss가 되어야하기 때문에, 캐시는 잘 저장되는데 워크플로우마다 이것을 공유하지 못하는 상태라고 추측했습니다. 그래서 build 와는 다르게 cache_path가 설정되어 있는 것이 원인으로 추정했고, build와 동일하게 node_modules/.cache/turbo를 cache_path로 설정해서 cache hit 이 되도록 변경했습니다.
- [이전과](https://app.circleci.com/pipelines/github/channel-io/bezier-react/6773/workflows/80dfad03-243e-4060-8951-391d0f1a28c7) 비교해서 FULL TURBO 가 되면 …

Fix cache miss during lint, typecheck, test job in ci

---

.changeset/serious-bottles-film.md
packages/bezier-react/src/components/Modal/Modal.tsx
packages/bezier-react/src/components/Tooltip/Tooltip.tsx
packages/bezier-react/src/stories/alpha-color.mdx
packages/bezier-react/src/stories/alpha-shadow.mdx
packages/bezier-tokens/src/alpha/functional/dark-theme/color.json
packages/bezier-tokens/src/alpha/functional/gradient.json
packages/bezier-tokens/src/alpha/functional/light-theme/color.json
packages/bezier-tokens/src/alpha/functional/shadow.json
packages/bezier-tokens/src/alpha/global/color.json
packages/bezier-tokens/src/alpha/global/font.json
packages/bezier-tokens/src/alpha/global/gradient.json
packages/bezier-tokens/src/alpha/global/typography.json
packages/bezier-tokens/src/alpha/semantic/color.json
packages/bezier-tokens/src/alpha/semantic/shadow.json

Add "color" prefix to color tokens and fix misnaming of typography tokens
- 논의된 구조에 맞게 색상 토큰 앞에 "color" prefix를 추가합니다.
- font, typography 토큰의 위계가 잘못되어 몇몇 토큰의 이름에 "font", "typography" prefix가 없던 걸 수정합니다.
- style: prettier format
No
- [Notion (Internal)](https://www.notion.so/channelio/token-f44d981d3eb04493b1cc527335f89fdd?pvs=4)

Add "color" prefix to color tokens and fix misnaming of typography tokens

---

.changeset/witty-icons-beg.md
packages/bezier-react/src/components/FormHelperText/FormHelperText.tsx
packages/bezier-react/src/components/FormLabel/FormLabel.tsx

FormControl 내부에 위치한 FormLabel, FormHelperText(ErrorMessage)에 className 오버라이드가 잘 적용되지 않는 문제를 수정합니다.
베지어 마이그레이션 과정에서 FormControl이 FormLabel, FormHelperText에게 래퍼 스타일을 전달하는 과정이 변경되었습니다.
변경 과정에서 `get***Props` 함수가 반환하는 `className` 과 인자로 받는 `className` 의 속성명이 서로 겹치게 되었는데, 이 때 두 className이 모두 적용되는 게 아니라 인자로 받는 `className` 이 우선순위를 가지고 적용되면서 FormControl이 전달하는 래퍼 스타일이 무시되는 버그가 있었습니다. 이를 수정합니다.
No
- [Channel Desk](https://desk.channel.io/root/threads/groups/Bug-10/6617adea666db15cf58f/6617adea666db15cf58f)

fix(form-label/helper-text): fix merging of classname not working properly when inside a `FormControl`

---

.github/workflows/ci.yml

- Fixes https://github.com/channel-io/bezier-react/issues/2159
- Fixes https://github.com/channel-io/bezier-react/issues/1684
- GitHub Action 기반의 CI 워크플로우를 추가합니다.
- 워크플로우에서 secrets.TURBO_SERVER_TOKEN 를 사용하고 있기 때문에 이 pr이 머지되기 전에 레포지토리 시크릿으로 설정해야 합니다. Settings > Secrets and Variables > Actions > Repository Secrets 에서 설정 가능합니다. 값은 아무거나 해도 되기 때문에 적당한 해시값으로 하면 될 것 같습니다. 제가 권한이 없어서 설정 부탁드립니다 @sungik-choi 
- pr 이 머지되고 ci가 잘 도는 것을 확인하면 Circle CI 설정 파일(config.yml)을 제거하면 될 것 같습니다.
- https://github.com/channel-io/bezier-react/issues/1684 에서 제안한 것처럼 build, lint, typecheck, test 를 하나의 job 안에서 실행합니다. 
- 깃헙 artifact 를 리모트 캐시로 저장하는 action 을 사용하여 리모트 캐시를 활성화합니다. 
- 현재 …

Add CI pipeline by GitHub Action

---

.github/workflows/ci.yml

- #2159 
- 레포지토리의 시크릿 토큰을 가져오지 않는 이슈가 있어서 uuidV4 해시로 하드코딩합니다. 기본적으로 어떤 값이든 올 수 있기 때문에 하드코딩해도 상관없을 것으로 보입니다. 
- https://github.com/channel-io/bezier-react/actions/runs/8734661989/job/23966571547?pr=2165 
- 생략
- No
- https://github.com/felixmosh/turborepo-gh-artifacts/issues/1

Fix Turborepo server token to uuid

---

.changeset/forty-days-cry.md
.changeset/olive-ants-explode.md
packages/bezier-react/src/components/AlphaButton/AlphaButton.stories.tsx
packages/bezier-react/src/components/AlphaButton/Button.module.scss
packages/bezier-react/src/components/AlphaButton/Button.tsx
packages/bezier-react/src/components/AlphaButton/Button.types.ts
packages/bezier-react/src/components/AlphaButton/index.ts
packages/bezier-react/src/components/BaseButton/BaseButton.tsx
packages/bezier-react/src/components/Button/Button.module.scss
packages/bezier-react/src/components/Button/Button.tsx
packages/bezier-react/src/index.ts

- Fixes #2178
- V2 토큰을 사용하여 버튼 컴포넌트를 구현합니다. 
- 디자인 상으로 Icon 유무와 Floating 여부에 의해서 4가지로 컴포넌트가 나눠져 있어서 버튼 컴포넌트를 non-floating & not-icon-only 인 경우로 제한했습니다. 다만 (Floating)IconButton 처럼 아이콘만 있는 버튼을 분리하는게 좋을지는 아직 고민중입니다. 디자인 스펙에 맞추려면 분리하는게 좋을듯한데, 분리하게 되면 꽤나 겹치는 부분이 있어서 코드적으로 관리 포인트가 2가지 생기는게 우려됩니다. 
- hover or active 상태인 경우에 대해서는 v2 토큰을 사용한 디자인이 나와있지 않아서 v1 토큰으로 구현하고 버튼 안에 있는 텍스트나 스피너도 기존의 컴포넌트를 사용했습니다. 그런데 기존의 hover 디자인을 확인하니 primary&blue 버튼인 경우에 디자인 스펙과 다른 부분이 있어서 Button 컴포넌트를 수정했습니다. 
- 스토리북은 우선순위가 높지 않아 보여서 최대한 간단한 형태로 만들었습니다. 
- No
- [버튼(internal)](https://www.figma.com/file/8J76noM3T1Sp5cNPhnYQiG/Action?type=design&node-id=0%3A1&mode=design&t=L4yIeScuZnOADvDx-1)

Add `AlphaButton` component

---

.github/workflows/generate-icon-files.yml
.github/workflows/release.yml

- None
- actions/checkout@v4 에서 persist-credentials: false 로 하지 않으면 깃 로컬 config 에 GITHUB_TOKEN 을 저장하고, 이거 때문에 이어지는 워크 플로우가 트리거 되지 않는 다고 합니다. persist-credentials: false 설정을 추가합니다. 
- 생략
- No
- https://github.com/orgs/community/discussions/26220
- https://github.com/marketplace/actions/github-push#example-workflow-file

Fix CI not triggering in icon update PR (2)

---

.changeset/six-dots-check.md
packages/bezier-react/src/components/AlphaAvatar/Avatar.tsx
packages/bezier-react/src/components/AlphaAvatar/__snapshots__/Avatar.test.tsx.snap
packages/bezier-react/src/components/AlphaAvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
packages/bezier-react/src/components/Avatar/Avatar.tsx
packages/bezier-react/src/components/Avatar/__snapshots__/Avatar.test.tsx.snap
packages/bezier-react/src/components/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
packages/bezier-react/src/components/Emoji/Emoji.tsx
packages/bezier-react/src/components/Emoji/__snapshots__/Emoji.test.tsx.snap

- `Avatar`, `Emoji` 컴포넌트의 `aria-label` 속성을 `aria-description` 속성으로 대체합니다.
- `aria-label` 속성은 Interactive한 element에 부여하는 것이 의도입니다. 
> Note: aria-label is intended for interactive elements or for elements made interactive via other ARIA declarations when there's no visible text in the DOM to serve as a label.
> Note: While aria-label can be used on any element that can have an accessible name, in practice however, it is supported only on interactive elements, [widgets](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles#2._widget_roles), [landmarks](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles#3._landmark_roles), images, and iframes.
- No.
- …

Replace `aria-label` of non-interactive elements

---

.github/workflows/chromatic.yml

- Fixes https://github.com/channel-io/bezier-react/issues/2185
- Chromatic의 turbosnap기능을 활성화하고, trigger되는 조건을 push, pull_request에서 push로 변경합니다.
- turbosnap은 webpack의 디펜던시 그래프를 이용해서 변화가 있는 스토리만 스냅샷을 찍는 기능입니다. 베지어 스토리 갯수가 100개 정도 되서 사용량 제한 5000개를 초과하지 않기 위해 필요한 기능입니다. 자세한 설명은 이슈를 첨고해주세요.
- `Help`컴포넌트를 바꾸는 경우: 디펜던시 그래프에서 Help와 연결된 부분 (Help, FormLabel, FormControl, Modal, Button 등)이 변화가 있다고 판단하고 관련된 스토리 22개만 스냅샷으로 찍습니다([#](https://github.com/yangwooseong/bezier-react/actions/runs/8933306731/job/24538487220)). Modal이나 Button이 연결되어 있다고 판단하는 것은 스토리에서 FormLabel, FormControl을 사용하고 있어서 그렇습니다. 
- `AlphaButton` 컴포넌트를 바꾸는 경우: `AlphaButton`에 의존하는 컴포넌트가 없기 때문에 스냅샷 하나만 찍게 됩니다 …

Enable chromatic turbosnap

---

.changeset/quick-seals-sin.md
packages/bezier-react/src/components/Icon/Icon.types.ts

- None
- Icon 컴포넌트의 `source` 속성에 있는 jsdoc의 오타를 수정합니다. 
| As-is | To-be |
|--------|--------|
| <img width="514" alt="image" src="https://github.com/channel-io/bezier-react/assets/28595102/469db30b-5ce1-44e8-a585-a31948cb4662"> |  <img width="516" alt="image" src="https://github.com/channel-io/bezier-react/assets/28595102/249993c6-3e28-486c-a0a4-56a071fff5b0"> |
- No
- None

Fix typo in `IconProps` jsdoc

---

.changeset/brown-lies-shop.md
packages/bezier-react/src/components/Toast/Toast.module.scss

- None
https://github.com/channel-io/bezier-react/assets/28595102/97005c58-9602-4066-b398-2200a574848f
(강제로 body의 height를 늘려서 스크롤했을 때 토스트가 이동하는 모습)
스크롤을 하면 토스트 위치가 바뀌는 버그가 있어서 이를 수정합니다. 
- `ToastProvider`의 container를 스크롤하면 `ToastContainer`의 위치가 바뀔 수 있어서 생긴 버그입니다.  `ToastContainer`의 position 을 absolute가 아닌 fixed로 변경합니다. 
- No
- None

Fix Toast moving up and down when window is scrolled

---

.changeset/red-worms-argue.md
packages/bezier-react/src/components/AutoFocus/AutoFocus.tsx
packages/bezier-react/src/components/BaseTagBadge/BaseTagBadge.tsx
packages/bezier-react/src/components/FeatureProvider/FeatureProvider.tsx
packages/bezier-react/src/components/Overlay/Overlay.tsx
packages/bezier-react/src/components/TextArea/TextArea.tsx
packages/bezier-react/src/components/Toast/Toast.tsx
packages/bezier-react/src/hooks/useIsomorphicLayoutEffect.ts

None
bezier-react 를 사용할 때 뜨는 리액트 경고를 해결합니다.
이 이슈는 다음의 원인으로 인해 발생하는 이슈입니다.
`packages/bezier-react/src/components/Toast/Toast.tsx` 내 `createContainer` 함수에서 InvertedThemeProvider를 사용하게 되는데, 이때 해당 컴포넌트에 key값이 들어가지 않아 생기는 에러입니다.
이를 InvertedThemeProvider 내에 넣도록 변경함으로써, 문제를 해결하고자 합니다.
이 이슈는 다음 원인으로 인해 발생됨이 추정됩니다.
stack trace를 따라가다보면, 최종 끝에 다다르는 파일이 `BaseTagBadge.mjs` 에 위치하게 되는데, 여기서 유일하게 ref parameter를 사용하지 않는 컴포넌트는 `BaseTagBadgeText` 컴포넌트가 유일합니다.
따라서 해당 컴포넌트에 forwardRef를 사용하게 함으로써 이 문제를 해결하고자 합니다.
```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and …
```

fix console errors from bezier-react

---

.changeset/long-mugs-count.md
packages/bezier-icons/scripts/utils/getChangeLog.js
packages/bezier-icons/scripts/utils/getChangeLog.test.js
packages/bezier-icons/scripts/utils/getPrDescription.js
packages/bezier-icons/scripts/utils/getPrDescription.test.js
packages/bezier-icons/scripts/utils/getRenamedIconMap.js

None
- https://github.com/channel-io/bezier-react/pull/2251 에서 PR본문과 changeset에 undefined가 뜨는 버그를 해결합니다. 
- 아이콘 이름이 변경되었을 때를 `getPrDescription` 함수에서 다루지 않아서 생기는 버그였습니다. 깃 로그를 직접 찍어보니 R100 으로 뜨기 때문에 이 경우를 추가했습니다. 테스트 코드에서 어떤식으로 PR과 changeset에 rename 기록이 추가되는지 확인할 수 있습니다. 
- No
- [What does R100 mean?](https://stackoverflow.com/questions/53056942/git-diff-name-status-what-does-r100-mean)

Fix bug in icon generating action when icon is renamed 

---

.changeset/blue-frogs-destroy.md
.changeset/sixty-trains-relate.md
packages/bezier-react/src/components/AlphaButton/Button.module.scss
packages/bezier-react/src/components/AlphaButton/Button.types.ts
packages/bezier-react/src/components/AlphaIconButton/IconButton.module.scss
packages/bezier-react/src/components/AlphaIconButton/IconButton.types.ts
packages/bezier-tokens/src/alpha/functional/light-theme/color.json

- None
- 새롭게 디자인 스펙에 추가된 transparent 토큰을 bezier-tokens에 추가하고, tertiary 버튼에 이를 사용합니다. 
- 버튼의 color속성 중에서 `white`를 `white-absolute`로 변경합니다. 
- [디자인 스펙 변경사항(internal)](https://desk.channel.io/root/groups/v2_BezierRelease-364583/6656c24932354c6650e6)

Add token for transparent color

---

.changeset/fluffy-donuts-matter.md
packages/bezier-react/src/components/AlphaAvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
packages/bezier-react/src/components/AlphaButton/Button.module.scss
packages/bezier-react/src/components/AlphaButton/Button.tsx
packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.module.scss
packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.tsx
packages/bezier-react/src/components/AlphaFloatingIconButton/FloatingIconButton.module.scss
packages/bezier-react/src/components/AlphaFloatingIconButton/FloatingIconButton.tsx
packages/bezier-react/src/components/AlphaIconButton/IconButton.module.scss
packages/bezier-react/src/components/AlphaIconButton/IconButton.tsx
packages/bezier-react/src/components/AlphaSpinner/Spinner.module.scss
packages/bezier-react/src/components/AlphaSpinner/Spinner.tsx
packages/bezier-react/src/components/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
packages/bezier-react/src/components/Help/__snapshots__/Help.test.tsx.snap
packages/bezier-react/src/components/Icon/Icon.module.scss
packages/bezier-react/src/components/Icon/Icon.tsx
packages/bezier-react/src/components/NavGroup/__snapshots__/NavGroup.test.tsx.snap
packages/bezier-react/src/components/NavItem/__snapshots__/NavItem.test.tsx.snap

- None
- `AlphaButton`안에 있는 로더 컴포넌트를 새로 만든 `AlphaSpinner`로 교체합니다. 
- 디자인 스펙에 의하면, 버튼안에 있는 `AlphaSpinner`의 사이즈는 아이콘 사이즈와 일치해야합니다. 따라서 버튼의 스타일 코드가 아이콘의 사이즈 맵(e.g. s - 20, m -24, ...) 을 알 필요가 있습니다. 이런 비슷한 경우가 SegmentedControl - Divider 컴포넌트에서 variables classname을 사용한 경우가 있었는데, 이 PR에서는 스타일 코드를 직접 `@include`로 가져와서 그 안에 있는 변수에 접근하는 방향으로 해결해봤습니다. 내보내는 쪽과 사용하는 쪽에서 불필요하게 variables classname을 사용하지 않아도 되는 장점이 있어서 이렇게 시도해봤습니다. 
- 이에 따라 아이콘 사이즈를 js로 결정하던 것에서 scss 안에서 맵을 들고 있는 형태로 변경했습니다. 
- Spinner 쪽에서는 vectorEffect="non-scaling-stroke"를 지웠습니다. vectorEffect="non-scaling-stroke"가 없으면, stroke-width=2px로 고정해도 svg 사이즈에 맞게 바뀌기 때문에 사이즈마다 4px, 6px로 지정했던 의도였습니다. 그런데 버튼아래에서 사용하게 되면, 버튼의 아이콘 사이즈마다 다른 storke-width 를 …

Use `AlphaSpinner` in `AlphaButton` component set

---

.changeset/chatty-hounds-bow.md
packages/bezier-tokens/src/alpha/semantic/shadow.json

- None
- `alpha-shadow-input-default` 토큰이 참조하고 있는 값을 수정합니다. 
- 생략
- No
- [디자인 스펙(internal)](https://www.figma.com/design/LIxRAsKKyGx3fdgvm2knL9/%F0%9F%93%8C-Foundation?node-id=40221-32519&t=SFSQo9D9XFaNipko-4)

Fix `alpha-shadow-input-default` token

---

.changeset/giant-kangaroos-ring.md
packages/bezier-react/src/components/AlphaButton/Button.module.scss
packages/bezier-react/src/components/AlphaButton/Button.types.ts
packages/bezier-react/src/components/AlphaIconButton/IconButton.module.scss
packages/bezier-react/src/components/AlphaIconButton/IconButton.types.ts

- None
- white (absolute) 처럼 괄호에 있는 것은 개발단에서 생략하는 것으로 합의한 것을 반영합니다.
- 생략
- Yes
- [스레드 (internal)](https://desk.channel.io/root/threads/groups/v2_BezierRelease-364583/666957ba4acbecf950a6/666957ba4acbecf950a6)

Change `white-absolute` to `white` in `AlphaButton` and `AlphaIconButton` color

---

package.json
packages/bezier-react/src/components/Help/Help.module.scss

- None
- https://github.com/channel-io/bezier-react/pull/2260 에서 chromatic에서 사용하는 노드 버전이 engine.node 와 달라져서 에러가 뜬 이슈가 있었습니다 ([#](https://github.com/channel-io/bezier-react/actions/runs/9343590910/job/25713414442)). 그 때는 크로마틱 버그로 인식을 못해서 package.json.engine.node 버전을 18.20.3 에서 >=18.20.3으로 바꿔서 해결했는데, 크로마틱의 최신 버전에서 이 이슈가 해결되어서 .nvmrc 버전과 동일한 버전으로 돌립니다.
- None
- No
- https://github.com/chromaui/chromatic-cli/blob/HEAD/CHANGELOG.md#v1154-wed-jun-12-2024 (PR1006이 수정PR)

Set required node version as .nvmrc's version

---

.changeset/nice-ducks-judge.md
packages/bezier-icons/rollup.config.mjs
packages/bezier-icons/utils/index.ts

- #1313 
- bezier-icons를 빌드할 때 만들어지는 리액트 컴포넌트에 ref를 forwarding 하도록 svgr template 코드를 수정합니다. 
- forwardRef로 감싸면 함수가 아닌 객체가 만들어지기 때문에 isBezierIcon가 체크하는 타입도 object로 변경했습니다. 
- 스토리북으로 테스트 했을 때 툴팁의 children 으로 아이콘이 와도 툴팁이 잘 뜨는 것을 확인했습니다. 데스크에서는 bezier-icons의 dist 폴더를 교체해서 테스트 해봤을 때 잘 작동하는 것을 확인했습니다.
- 엄밀히 말하면 IconSource 타입이 변경되서 breaking change가 맞으나, IconSource 타입에 의존하는 사용처가 없어 보여서 minor 버전 업으로 진행합니다. 
- https://react-svgr.com/docs/options/#ref

Forward ref to Icon component generated by svgr

---

packages/bezier-icons/utils/utils.test.tsx

- #1313 
- isBezierIcon 에서 타입 체크하는 것을 바꾸면서 테스트 코드가 실패하는 것을 수정합니다. 
- https://github.com/channel-io/bezier-react/pull/2329 에서 CI가 통과했던 것은 isBezierIcon 함수가 있는 bezier-icons/utils/index.ts 경로가 turbo.json의 test.inputs 에 없기 때문에 터보 캐시가 힛되서 그런 것 같습니다. 
- https://github.com/channel-io/bezier-react/pull/2328 에서는 이유는 잘 모르겠지만 터보 캐시가 미스되서 테스트를 다시 돌려서 fail 이 뜬 것으로 보입니다. 
- 단순히 bezier-icons에서 코드가 바뀌어도 테스트의 터보 캐시가 힛되는 문제를 수정하려면 turbo.json 에 utils/**/*.ts 경로를 넣으면 되지만, 이렇게 하기보다 bezier-icons나 bezier-tokens같은 패키지도 패키지 디렉토리 바로 밑에 src/ 를 둬서 디렉토리 구조를 통일하는 게 좋아보이긴 합니다. 이거는 논의 후 별도 PR로 작업하는게 좋을 것 같네요. 
- No
- https://turbo.build/repo/docs/reference/configuration#inputs

Resolve test fail in bezier-icons package

---

.changeset/nervous-days-push.md
packages/bezier-react/src/components/Icon/Icon.types.ts

- #1313 
- bezier-icons 의 type declaration 에서 선언되는 타입을 수정하면서 Icon 컴포넌트가 받는 source 타입을 수정하지 않아 사용처에서 타입 에러가 뜹니다. 베지어에서는 타입 체크가 통과되고 있는 것은 아마 @types/react@18.2.61 버전에서 breaking change가 생긴 것에 의한 영향인 것 같습니다. 
- Icon 의 인터페이스를 BezierIcon 을 바라보도록 수정합니다. Button types 의 LeftContent에서도 BezierIcon 을 직접 바라보고 있어서 일관성 측면에서도 이렇게 하는 게 나아보입니다. 
- No
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68720/files#diff-32cfd8cb197872bcba371f5018185d2e75fa540b52cda2dd7d8ac12dcc021299L246

Change `source` props type of `Icon` component

---

.changeset/wicked-lies-appear.md
packages/bezier-icons/utils/index.ts

- None
아래 함수에서 생길 수 있는 버그를 수정합니다. arg가 null 일 때 typeof arg === 'object' 이기 때문에 런타임 에러가 납니다. 
```tsx
export function isBezierIcon(arg: any) {
return typeof arg === 'object' && arg[BEZIER_ICON_ID] === true
}
```
- undefined 일 떄는 typeof arg === 'undefined` 이어서 Button 의 leftContent 속성에 아무것도 넣지 않는 경우에는 에러가 뜨지 않고 있었습니다. 
- No
- https://github.com/channel-io/bezier-react/pull/2329/files#diff-7045a70c57f70692f95240783652cbbeb87e13a5528a8c45c69f530e4d62e130

Fix runtime error in `isBezierIcon` function

---

.changeset/twelve-crews-visit.md
packages/bezier-figma-plugin/src/config.ts
packages/bezier-figma-plugin/src/ui/hooks/useCreatePRWithSvgMap.ts

- #2229 
- figma plugin이 PR을 생성하는 레포를 bezier-react에서 bezier-asset으로 변경합니다. 
- base branch를 main에서 exp로 변경합니다. 
- iconExtractPath를 packages/bezier-icons/icons에서 asset/icons로 변경합니다. 
- 개발 모드로 실행해봤을 때 bezier-asset레포에 [PR](https://github.com/channel-io/bezier-asset/pull/30)이 잘 생성되는 것을 확인했습니다. 
-  No

Change repository to `bezier-asset` where figma plugin creates PR 

---

packages/bezier-react/src/components/Checkbox/Checkbox.module.scss
packages/bezier-react/src/components/RadioGroup/RadioGroup.module.scss

#2360
Fixes #2360 
Prepare for Sass breaking change by migrating deprecated nested-to-unnested rule syntax.
Changing the order of the properties in `RadioGroup.module.scss` and `Checkbox.module.scss`
No

Prepare for Sass breaking change

---

.github/workflows/generate-icon-changeset.yml

- None
- https://github.com/channel-io/bezier-react/pull/2378 에서 아이콘 변경 내역이 PR 본문에 잘못 나오고 changeset push 가 안되고 있는 것을 수정합니다. 
- PR본문을 추가하는 워크플로우에서 checkout 액션의 fetch-depth가 default(=1) 이라서 파일이 변경된 것으로 인식하지 않고 추가된것으로 인식해서 모두 Add로 나왔습니다. 0으로 바꿔서 모든 커밋 히스토리를 가져오도록 수정했습니다. 
- 누락된 changeset commit push 를 추가합니다. 
- No
- fork한 레포에서 테스트했을 때 잘 나오는 것을 확인했습니다 -> https://github.com/yangwooseong/bezier-react/pull/168

Fix wrong pr description in icon update PR

---

.husky/commit-msg

- https://github.com/typicode/husky/issues/1472
- https://github.com/channel-io/bezier-react/actions/runs/10088650857/job/27894755203
- pre-commit 이 제대로 동작하지 않아 changeset 액션이 실패하고 있습니다. 
- husky 에서 9.1.1 에서 버그를 일으키고 있어서 이에 대응합니다. 
> There's a bug with this release which prevents the deprecation notice to appear and requires to remove #!/usr/bin/env sh and . "$(dirname -- "$0")/_/husky.sh" (which are deprecated by the way). I'll publish a new version to fix that. Sorry about any inconvenience.
- commit-msg의 2라인을 제거합니다. 9.1.1에서 제거됐어야 하는데 버그가 있어서 제거가 안되었나 봅니다. 
- No
- https://github.com/channel-io/bezier-react/pull/2371
- https://github.com/typicode/husky/releases/tag/v9.1.1

Fix pre-commit bug with husky

---

.changeset/short-ads-ring.md
packages/bezier-react/src/components/AlphaFloatingIconButton/FloatingIconButton.module.scss

- resolves #2382
- `AlphaFloatingIconButton`의 아이콘 수직 정렬이 틀어지는 버그를 수정합니다. 
- ButtonContent에 display: flex 속성을 넣어서 svg와 높이가 같아지도록 합니다. 
- No

Fix wrong vertical align with icon in `AlphaFloatingIconButton`

---

.changeset/dry-icons-search.md
packages/bezier-react/src/components/Emoji/Emoji.stories.tsx
packages/bezier-react/src/components/Emoji/Emoji.test.tsx
packages/bezier-react/src/components/Emoji/Emoji.tsx
packages/bezier-react/src/components/Emoji/Emoji.types.ts

- resolves #2335 
- `Emoji` 컴포넌트에서 url 을 직접 받는 로직을 제거하고 컴포넌트 내부에서 `name`, `size` 속성으로부터 url 을 만드는 것으로 변경합니다.
- breaking change를 발생시키지 않기 위해 imageUrl 만 optional 로 변경하고 `name` 타입을 아이콘 이름의 union type(e.g. 'smiley' | 'grinning' | ... )으로 좁히지 않았습니다. 
- 채널톡 데스크에서 자이언트 이모지를 보여주는 경우는 size=60 일 때이고, 이때는 asset size가 160인 url 을 넣어주고 있습니다. 이 기조에 맞춰서 size >= 60일 떄는 asset size 160으로 url 을 만들었습니다. 
- No 
- None

Deprecate `imageUrl` props in `Emoji` component

---

.changeset/gold-otters-shop.md
packages/bezier-react/src/components/OutlineItem/OutlineItem.module.scss
packages/bezier-react/src/components/OutlineItem/OutlineItem.tsx

- None
- OutlineItem 컴포넌트의 아이콘 사이즈와 아이콘의 right margin 을 디자인 스펙에 맞게 변경합니다. 
- 생략 
- No
- [디자인 스펙(internal)](https://www.figma.com/design/99k33ZxchcPKTz2tzJlZeE/Components?node-id=1164-12605&m=dev)
- [UI Change](https://www.chromatic.com/test?appId=62bead1508281287d3c94d25&id=66ac2aea3a39ce91f17bab5a)

Fix `OutlineItem`'s icon size and gap between icon and leftContent

---

.changeset/strange-spies-provide.md
packages/bezier-react/src/components/Button/Button.module.scss

- Fixes #2364 
- 디자인스펙에 따르면 tertiary 버튼은 호버할 때 텍스트의 색깔이 변경되지 않도록 합니다. 지금은 바꾸고 있어서 이를 수정합니다. 
- V2 버튼은 잘 적용되어 있는 상태입니다. 
- No
- [스레드 (internal)](https://www.notion.so/channelio/Hover-fg-bezier2-ecf379e359344352bc570255e5b27e96)

Keep the color of text when hovering over the tertiary `Button` 

---

.changeset/little-llamas-attend.md
packages/bezier-react/src/components/TextField/TextField.module.scss

- resolves https://github.com/channel-io/bezier-react/issues/2280
- `TextField`의 rightContent로 오는 컴포넌트의 width 가 고정되는 버그를 수정합니다. 
| As-is| To-be |
|--------|--------|
| <img width="356" alt="image" src="https://github.com/user-attachments/assets/7b0ee373-d3bd-4c9e-91bb-afdd148691a2"> | <img width="364" alt="image" src="https://github.com/user-attachments/assets/680339fd-5214-4128-ab00-487582763fce"> |
-  No
- None

Fix right button of `TextField` component shrinking bug

---

renovate.json

- resolves https://github.com/channel-io/bezier-react/issues/1217
- 파싱 에러가 나서 cron 문법으로 다시 시도합니다. 
- `0 10-19 1-7 * MON`-> 매 달 1일에서 7일까지 월요일에 10시에서 19시까지 0분에 실행입니다. 
- No
- https://docs.renovatebot.com/configuration-options/#schedule
- https://stackoverflow.com/questions/51669973/how-to-fire-the-job-on-first-monday-of-month-using-cron-expresssion-in-spring-s
- https://crontab.guru/#0_10-19_1-7_*_MON

Fix renovate schedule to cron syntax

---

.changeset/orange-eggs-wait.md
packages/stylelint-bezier/src/plugins/validate-token/index.ts

- None
- styled-componets에서 template literal 을 사용하는 경우가 꽤 많아서, 그럴때는 disable 하지 않아도 되게끔 통과시킵니다. 
- None
- No
- None

Allow template literal for validate-token stylelint rule

---

.changeset/dull-falcons-compete.md
packages/bezier-react/src/stories/alpha-color.mdx
packages/bezier-tokens/package.json
packages/bezier-tokens/scripts/build-tokens.ts
packages/bezier-tokens/scripts/lib/constants.ts
packages/bezier-tokens/scripts/lib/transform.ts
packages/bezier-tokens/scripts/lib/utils.ts
yarn.lock

- resolves #2413 
- alpha functional 토큰에 대해서 정해진 공식에 따라 hovered color 토큰을 만들기 위해 style dictionary 에 transform 을 추가합니다. 
- 스토리북 > Alpha-foundation > Color 에 hovered color 토큰을 추가합니다. 
- mergeCSS, mergeJsIndex 함수가 이미 있기 때문에, hovered color 토큰을 만들기 위해 builder를 하나 더 만들기만 하면 merge 함수가 알아서 파일을 합쳐줍니다. 
- 변환 공식은 이슈를 참조해주세요. 추후에 바뀔 여지가 있습니다.
-  No
- https://styledictionary.com/

Add transform to style dictionary to get hovered color tokens

---

.changeset/rare-chefs-remember.md
packages/bezier-react/src/components/Toast/Toast.tsx
packages/bezier-react/src/components/Toast/Toast.types.ts

Toast에 z-index가 제대로 적용되지 않아 Floating component간 위계가 맞지 않았던 부분을 수정합니다.
Toast의 conatiner가 `position: fixed` 스타일을 가지기에 stacking context를 만들어냅니다. 따라서 자식 요소인 Toast가 z-index를 가지더라도 container 외부에 영향을 미치지 못하기 때문에 의도한대로 올바르게 z-index가 적용되지 않았습니다. container에 z-index 스타일을 추가하여 해결합니다.
No, Toast의 `zIndex` prop을 deprecate 처리했습니다. 
- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index/Stacking_context

Fix z-index not being applied correctly in `Toast`

---

packages/bezier-tokens/src/alpha/global/color.json

- None
- 색상을 변경하고 transparent 컬러를 추가합니다. transparent 컬러는 tertiary 버튼의 hovered color 를 얻기 위해 사용됩니다.
blue 
300 7D9EFA
cobalt
300 71B9F5
200 8DCAFC
100 A1D5FF
green
300 68CC7F
200 84E09A
orange 200 FFB070
- No
- [피그마(internal)](https://www.figma.com/design/LIxRAsKKyGx3fdgvm2knL9/%F0%9F%93%8C-Foundation?m=auto&node-id=981-467&t=NKB71bZ9tzcclVBS-1)

Update tokens value and add transparent color

---

.changeset/shy-flies-provide.md

None
#2452 에서 누락된 changeset 을 추가합니다. 이 PR이 머지되서 changesets PR이 생성되면 Changelog 안에 있는 PR 번호를 직접 수정할 예정입니다. 
None
No
None

Add missed changesets for #2452

---

.changeset/honest-snakes-hug.md
packages/bezier-react/src/components/AlphaButton/Button.tsx
packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.tsx
packages/bezier-react/src/components/AlphaFloatingIconButton/FloatingIconButton.tsx
packages/bezier-react/src/components/AlphaIconButton/IconButton.tsx
packages/bezier-react/src/components/AlphaLoader/AlphaLoader.stories.tsx
packages/bezier-react/src/components/AlphaLoader/Loader.test.tsx
packages/bezier-react/src/components/AlphaLoader/Loader.types.ts
packages/bezier-react/src/components/AlphaToggleButton/ToggleButton.tsx

- None
- AlphaLoader size 속성의 초기값이 없기 때문에 optional 이 아닌 required로 수정합니다. 
- 생략 
- No
- [컴포넌트 스펙(internal)](https://www.notion.so/channelio/Loader-e1e30e3fdcb14a3ba94b900d24e0d58e?pvs=4#9141d935a26b4dcea55b108f0bd3e466)

Fix `size` props of `AlphaLoader` component to be required

---

.changeset/cold-adults-thank.md
packages/bezier-react/src/components/AlphaButton/Button.tsx
packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.tsx
packages/bezier-react/src/components/AlphaFloatingIconButton/FloatingIconButton.tsx
packages/bezier-react/src/components/AlphaIconButton/IconButton.tsx

- 버튼 안에서 사용되는 로더 컴포넌트의 스타일을 버튼 컴포넌트 스펙에 맞게 수정했습니다. primary 버튼일 때는 on-overlay,  아닐 때는 secondary 여야 합니다. 
- 생략 
- No
- [컴포넌트 스펙(internal)](https://www.notion.so/Button-95e7964c1e174aaa9923abc8ecc193b3?d=12874b55ec7c80dc9732001c0b74a23b&pvs=4#043567a82b2f4b5a9da4abd656d7ce08)

Fix `variant` props of `AlphaLoader` component used in buttons

---

.changeset/tricky-hounds-do.md
packages/bezier-tokens/scripts/build-tokens.ts
packages/bezier-tokens/scripts/lib/constants.ts
packages/bezier-tokens/scripts/lib/format.ts
packages/bezier-tokens/scripts/lib/transform.ts
packages/bezier-tokens/scripts/lib/utils.ts

- https://github.com/channel-io/bezier-react/pull/2422#discussion_r1772647894
- 기존에 hovered token를 만들기 위해 CustomTransform, HoveredTransform 두 벌로 transform 을 만들고 머지 했던 것을 CustomFormat 에서 hovered token 를 생성하는 것으로 구현을 변경합니다. 이 과정에서 alphaCustomCss 포맷을 추가 구현했습니다. 
- semantic 토큰에도 hovered token을 추가했습니다.
- hovered color 생성 공식을 업데이트 합니다. (alpha = 0.2 포함 여부, alpha = 0일 때 saturation, lightness 유지)
- 이렇게 구현 방법을 바꾸면 transform 을 여러개 만들어야 할 필요가 없어집니다. 또한 js 로 생성되는 빌드 결과에서 darkThemeHovered 값들이 darkTheme 안으로 들어가게 되서 깔끔해지고 styles.css 안에서 선택자가 중복되고 있던 문제가 해결됩니다. 
- hoveredToken 이 tokens 로 들어가게 되면서 storybook 에도 hovered color 가 추가되었습니다. -> color 토큰이 달라질 때 or hovered color공식이 달라질 때 어떻게 달라지는지 크로마틱 UI test 에서 명시적으로 …

Implement hovered color with customFormat of SD

---

.changeset/stale-spoons-guess.md
packages/bezier-react/src/components/Emoji/Emoji.tsx

- Fixes #2449 
- "+1"(👍) 이모지가 렌더링 되지 않은 버그를 수정합니다. 
- emoji 이름으로 부터 url 을 계산할 때 인코딩 처리가 누락되어 있던 것이 원인이었습니다. 
- No
- None

Fix bug of "+1" emoji not rendering

---

.changeset/chatty-singers-grab.md
packages/bezier-react/src/components/AlphaButton/Button.module.scss
packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.module.scss

- 없음 
- `s` 사이즈의 `AlphaButton`, `AlphaFloatingButton`에 있는 1px 갭을 제거합니다. 
- 생략 
- No
- https://desk.channel.io/root/groups/v2BezierRelease-364583/67246bd9e9aa76c8de5d

Remove 1px gap in `s` size `AlphaButton`

---

.changeset/sixty-horses-care.md
packages/bezier-vscode/src/server.ts

- https://github.com/channel-io/bezier-react/issues/2485
- `bezier-vscode` 익스텐션의 자동완성 로직을 아래와 같이 변경합니다. 
- 바꾸는 이유는 이슈를 참고해주세요. 
As-is 
https://github.com/user-attachments/assets/617d5872-ef8d-4613-aad4-3f6f5471d480
To-be
https://github.com/user-attachments/assets/fe146de3-2aa5-47b1-88b7-f4b03b23a9e1
- No
- None

Change autocomplete logic of `bezier-vscode` 

---

packages/bezier-react/src/components/AlphaAvatar/Avatar.figma.tsx
packages/bezier-react/src/components/AlphaAvatarGroup/AvatarGroup.figma.tsx
packages/bezier-react/src/components/AlphaStatusBadge/StatusBadge.figma.tsx

AlphaAvatar, AlphaAvatarGroup, AlphaStatusBadge에 대한 Code Connect 추가
- Avatar의 status를 처리하는 방식이 굉장히 까다로웠습니다. example 문에서 props 변환외에 조건식을 평가하거나 하지 않기 때문에 모든 enum 경우의 수에서 같은 객체를 반환하도록 처리해야했습니다.
- nestedProps의 첫번째 인자는 피그마의 레이어명과 동일해야하는데, 피그마 내부의 사소한 결정에도 구현 의존성이 생기는 점이 아쉬웠습니다. 똑똑하게 처리해주면 좋을텐데요...
- StatusBadge의 `'lock'` 에 해당하는 구현이 추가되어야합니다.
No
- https://github.com/figma/code-connect/blob/main/docs/react.md#nested-properties

code connects for Avatar, AvatarGroup and StatusBadge

---

.changeset/good-colts-clean.md
packages/bezier-react/src/components/Slider/Slider.stories.tsx

close #2312 
- I processed value props to prevent type error.
<details>
<summary>First commit</summary>
- I don't like it, but using a `Template` was the solution I thought of.
- The control that inputs the `array` in storybook requires `object` input.
- Maybe, I can create a custom control using a `decorator`. I'm not sure because I haven't tried it yet. We also need to discuss how to use this to receive input.
```typescript
const Template: StoryFn<SliderProps> = (args) => {
const processedArgs = getProcessedArgs(args)
return <Slider {...processedArgs} />
}
export const Primary = Template.bind({})
Primary.args = {
width: 285,
defaultValue: [5],
value: undefined,
disabled: false,
guide: [5],
min: …
```

Fix runtime error in Slider storybook

---

.changeset/selfish-ladybugs-reply.md
packages/bezier-vscode/src/server.ts
packages/bezier-vscode/src/utils.ts

- https://github.com/channel-io/bezier-react/issues/2485
- alpha 토큰도 자동완성 추천에 나오도록 합니다. 
- legacy token, alpha token 별로 `{ category: { [name]: value }` 객체를  assignToTokenMap 함수를 통해 만든 다음에 딥 머지를 했습니다. 이 때 alpha token의 "dimension" category 는 바뀔 예정이라 제외했습니다. 
https://github.com/user-attachments/assets/6c14d51c-9e44-4de7-92c9-419cf933959e
- No
- None

Add `alpha` token to autocomplete suggestion of `bezier-vscode`

---

.changeset/long-hornets-grin.md
packages/bezier-react/src/components/ListItem/ListItem.module.scss
packages/bezier-react/src/components/ListItem/ListItem.tsx

Improves the styling of the `ListItem` component based on whether it is interactive or not
- `onClick` 여부에 따라 커서, 호버 스타일을 차등 적용합니다.
- `disabled` 상태의 커서를 기본값이 아니라, 다른 컴포넌트와 마찬가지로 `not-allowed` 를 사용하도록 변경합니다.
No

Improves the styling of the `ListItem` component based on whether it is interactive or not

---

.github/workflows/release.yml
package.json
packages/bezier-vscode/LICENSE.md
packages/bezier-vscode/package.json

- https://github.com/channel-io/bezier-react/issues/2485
- `bezier-vscode` 배포를 release.yml 에 추가해서 changesets PR을 머지하면 자동으로 배포되도록 합니다. 
- 누락된 LICENSE 파일을 추가합니다. 이게 없으니 `vsce publish`실행시키면 `그대로 진행하시곘습니까? [y/N]` 을 물어보네요. 
- `VSCE_PAT`: VSCode 퍼블리셔의 [토큰입니다](https://www.notion.so/channelio/42644061d7f542a9bf5684f2807128e4?pvs=4#c7f90fd0ef95446c84bf25f335cb97cc). 레포 시크릿에 추가헀습니다. 
- `--no-dependencies`: yarn 버전 이슈때문에 안넣어주면 에러가 뜹니다 (https://github.com/microsoft/vscode-vsce/issues/517)
- `continue-on-error`: changesets PR 에 VSCode 관련 변경 사항이 없을 경우에 현재 배포된 버전과 같은 버전으로 배포하게 되는데 이때 워닝이 아니라 에러를 뱉기 떄문에 true 로 했습니다. 
- https://github.com/channel-io/bezier-react/pull/2496/files 이 PR이 머지되면 0.3.0 으로 버전이 올라간채로 …

Integrate VSCode extension release to GH Action

---

.changeset/chilly-masks-battle.md
packages/bezier-react/src/components/ListItem/ListItem.tsx
packages/bezier-react/src/components/ListItem/ListItem.types.ts
packages/bezier-react/src/components/OutlineItem/OutlineItem.module.scss
packages/bezier-react/src/components/OutlineItem/OutlineItem.tsx
packages/bezier-react/src/components/OutlineItem/OutlineItem.types.ts
packages/bezier-react/src/types/props.ts

Add `clickable` property to `ListItem` and `OutlineItem`
- `ListItem` 의 경우 실제 사용처에서 링크 역할을 하는 컴포넌트 등 상호작용 가능한 요소의 자식 요소로 사용되는 경우가 많습니다. 이 경우 `onClick` 의 여부만으로 클릭 가능한 스타일을 적용하기가 애매합니다. `clickable` 속성을 추가하여 이런 케이스를 사용처에서 핸들링할 수 있도록 했습니다.
- [Material UI](https://mui.com/material-ui/react-list/)처럼 `ListItemButton` 같은 컴포넌트를 따로 제공하는 방법이 이상적으로 보여지나, 당장 적용하기에는 브레이킹 체인지가 되어야 해서(ListItem은 아예 호버 스타일 등을 지원하지 않는 방향이 되어야겠죠) 적용하기 어렵다고 판단했습니다. 새로운 디자인 시스템 컴포넌트를 구현하고 있는 상황이니 최대한 변경이 적은 방향을 선택했습니다.
- `OutlineItem` 도 `ListItem` 과 비슷한 류로 활용되는 경우가 많아 `clickable` 속성을 추가했습니다.
- 클릭 가능 여부를 판단할 때 각 컴포넌트의 링크 존재 여부를 고려하도록 했습니다.
- (p.s. 링크로 사용하는 사용처가 데스크에 전혀 없어서, 추후에는 제거하고 링크를 더 잘 사용할 수 있는 방안을 찾아봐야할듯)
- `focused`, …

Add `clickable` property to `ListItem` and `OutlineItem`

---

.changeset/few-jokes-worry.md
packages/bezier-react/src/components/AlphaButton/Button.tsx
packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.tsx
packages/bezier-react/src/components/AlphaFloatingIconButton/FloatingIconButton.module.scss
packages/bezier-react/src/components/AlphaFloatingIconButton/FloatingIconButton.tsx
packages/bezier-react/src/components/AlphaIconButton/IconButton.module.scss
packages/bezier-react/src/components/AlphaIconButton/IconButton.tsx

- None
- xs 버튼의 아이콘 사이즈를 xxs에서 xs로 조절합니다. IconButton 에서는 패딩도 같이 조절합니다. 
- 없음 
- No

Fix icon size of xs `AlphaButton`

---

.changeset/dry-chairs-vanish.md
packages/bezier-react/src/components/AlphaButton/Button.tsx
packages/bezier-react/src/components/AlphaButton/Button.types.ts
packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.tsx
packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.types.ts
packages/bezier-react/src/components/AlphaFloatingIconButton/FloatingIconButton.tsx
packages/bezier-react/src/components/AlphaFloatingIconButton/FloatingIconButton.types.ts
packages/bezier-react/src/components/AlphaIconButton/IconButton.tsx
packages/bezier-react/src/components/AlphaIconButton/IconButton.types.ts
packages/bezier-react/src/components/Button/Button.tsx
packages/bezier-react/src/components/Button/Button.types.ts

#2299 
- Button 의 disabled 의 기본값을 false 에서 loading 을 따라가도록 수정합니다. 
- loading: true, disabled: undefined -> disabled: true
- loading: true, disabled: false -> disabled: false
https://github.com/user-attachments/assets/c05e5848-91c5-46bc-bf0e-c7cfdab2002b
No

modify default value of Button's disabled props to follow loading props

---

.changeset/old-oranges-wink.md
packages/bezier-react/src/components/AlphaTokenProvider/TokenProvider.tsx
packages/bezier-react/src/components/AlphaTokenProvider/TokenProvider.types.ts
packages/bezier-react/src/components/AlphaTokenProvider/index.ts
packages/bezier-react/src/components/AppProvider/AppProvider.tsx
packages/bezier-react/src/components/ThemeProvider/ThemeProvider.tsx
packages/bezier-react/src/components/ThemeProvider/index.ts
packages/bezier-react/src/index.ts
packages/bezier-react/src/types/alpha-tokens.ts
packages/bezier-react/src/types/tokens.ts
packages/bezier-react/src/types/utils.ts

- #2148 
- 알파 버전의 디자인 토큰 타입을 추가합니다
- 알파 버전의 디자인 토큰 프로바이더와 관련 훅, 토큰 객체를 export 합니다.
- `alphaTokens` 로 토큰 객체에, `AlphaTokens` 네임스페이스로 토큰 타입에 접근할 수 있도록 합니다.
- `useAlphaTokens` 훅으로 자바스크립트에서 현재 테마명에 맞는 알파 버전 디자인 토큰에 접근할 수 있습니다.
- `ThemeProvider` 도 `AlphaThemeProvider` 를 별도로 두어야하나 고민했지만, 이미 알파 디자인 토큰이 스타일 시트에 말려들어가있어서 `ThemeProvider` 하나만(= `AppProvider` 하나만) 사용하더라도 `useAlphaTokens` 훅을 사용할 수 있도록 해도 괜찮겠다고 생각했습니다.
- 현재 토큰 객체 구조상, 타이핑할 때 Functional Semantic 토큰을 묶어서 지칭할 수 있는 용어가 필요한데 현재 디자인 시스템에는 따로 정의가 없습니다. 임시로 학습 비용이 최대한 적은 방향으로, 기존과 동일하게 SemanticToken 이라고 칭했습니다.
No
없음

Add alpha design token types

---

.changeset/rotten-numbers-explain.md
packages/bezier-react/src/styles/components/elevation.module.scss
packages/bezier-react/src/styles/components/radius.module.scss
packages/bezier-react/src/styles/components/z-index.module.scss
packages/bezier-tokens/README.md
packages/bezier-tokens/package.json
packages/bezier-tokens/scripts/build-scss-index.ts
packages/bezier-tokens/scripts/build-tokens.ts
packages/bezier-tokens/scripts/lib/utils.ts

bezier-tokens에서 scss 파일을 내보냅니다.
- 일부 유틸 클래스를 만드는 CSS 모듈에서 토큰에 대한 종류를 모두 알고있어야하는 불편함이 있었습니다. 이번에 #2566 PR 작업을 진행하면서 동일한 작업이 반복되는걸 느껴 이를 함께 수정합니다.
- bezier-tokens에서 [map-deep](https://styledictionary.com/reference/hooks/formats/predefined/#scssmap-deep) 포맷으로 scss output을 만들도록 합니다. 자바스크립트 케이스처럼 `index.scss` 를 만드는 과정을 추가했습니다.
- bezier-token의 `sideEffects` 필드에 scss 파일을 추가합니다.
- scss의 `pkg:` Importer 규칙에 따라 bezier-tokens의 conditional export field를 수정했습니다. bezier-react에선 storybook & build 과정 모두 상대 경로로 지정하는 게 잘 동작해서 pkg 프로토콜은 이 PR에서 사용하지 않았습니다 (시간이 좀 더 걸릴듯함)
No
- ev-inner, ev-base 에 대한 유틸 클래스가 추가로 생기지만 사용처 영향은 없습니다 (매우 미미한 스타일 시트 파일 크기 상승)
- https://sass-lang.com/documentation/js-api/classes/nodepackageim …

Support for SCSS output in bezier-tokens

---

.changeset/few-singers-end.md
packages/bezier-react/src/components/Banner/Banner.tsx

- resolves #2574
- 배너의 iconColor 속성을 할당해도 variant 에 의해 정해지는 색깔을 오버라이딩하지 않는 버그를 수정합니다. 
- iconColor 가 없을 때만 Icon classname 을 엘리먼트에 추가하도록 했습니다. 
- No
- None

Modify the `iconColor` property of the `Banner` component to override the color.

---

.changeset/sharp-tools-approve.md
packages/bezier-react/src/components/Banner/Banner.module.scss

Add `text-align: left` style to `Banner` component
사용처 부모 요소의 텍스트 정렬 속성이 의도치 않게 오버라이드되지 않도록 기본 스타일 속성을 추가합니다.
No

Add `text-align: left` style to `Banner` component

---

.changeset/pre.json
.github/workflows/chromatic.yml
.github/workflows/ci.yml
.github/workflows/code-connect.yml

컬러 토큰 마이그레이션을 위해 프리릴리즈 모드로 진입합니다.
- main 브랜치 헤드 커밋 기준으로 alpha 브랜치를 생성
- changeset prerelease mode 진입
- CI 브랜치 필터에 alpha 브랜치 필터 추가
이 PR 이후 bezier-react의 기존 컴포넌트들에서 alpha 컬러 토큰 지원 작업을 진행할 예정입니다.
No

Enter prerelease mode

---

.changeset/good-cheetahs-study.md
packages/bezier-react/.storybook/main.ts

close web-7689
Enable JSDoc-based argument controls in development mode
This PR removes the production-only restriction for the react-docgen-typescript-plugin that generates Storybook documentation from JSDoc comments. As tested, enabling this feature in development mode doesn't seem to cause significant performance issues that were initially concerns. This change will provide a consistent documentation experience across both development and production environments.
Related to PR #931 which originally introduced the JSDoc-based documentation generation but limited it to production builds due to performance concerns.
- No

feat: add functionality to control arguments based on JSDoc in dev mode

---

.changeset/serious-donuts-hug.md
packages/bezier-react/src/components/Overlay/Overlay.module.scss
packages/bezier-react/src/components/Overlay/Overlay.tsx
packages/bezier-react/src/components/Overlay/Overlay.types.ts
packages/bezier-react/src/components/Select/Select.tsx

resolves #2615 
- Applied getZIndexClassName to ensure correct z-index stacking.
- Verified that dropdownZIndex now correctly overrides the default z-index in Overlay.
- Checked for similar issues in related components to prevent future conflicts.
No

fix(Overlay): Ensure dropdownZIndex properly overrides Overlay z-index

---

packages/bezier-react/src/components/Modal/Modal.test.tsx

- None
2개의 콘솔 warning과 error 메시지를 제거합니다. 
```Warning: Missing `Description` or `aria-describedby={undefined}` for {DialogContent}.```
``` 
`DialogContent` requires a `DialogTitle` for the component to be accessible for screen reader users.        
If you want to hide the `DialogTitle`, you can wrap it with our VisuallyHidden component.
```
- DialogContent 와 연결된 described-by 가 있기를 기대하는데 ModalHeaderProps에 description 을 주지 않아서 워닝이 뜨고 있었습니다. DialogContent에 described-by={undefined} 를 추가했습니다. 
- ModalHeader 가 필요없더라도 VisuallyHidden 을 써야 접근성을 해치지 않기 때문에 명시적으로 hidden 속성을 줬습니다. 
- No
- https://www.radix-ui.com/primitives/docs/components/dialog#description

Silence aria-descriedby warning in test

---

.github/workflows/chromatic.yml

- None
- 아이콘 업데이트 PR에서 크로마틱 액션을 실행하도록 변경합니다. 
- 기존에는 author=ch-builder 로 필터링을 하고 있어서 changesets PR, icon update PR 에서는 크로마틱 액션을 실행하지 않았습니다. icon update PR 같은 경우 files changed 에서 달라진 점을 볼 수 있으니 시각 테스트가 필요하지 않다고 생각했으나, 이번처럼 속성이 변경되서 예상치 못한 사이드 이펙트를 낼 수 있어서 시각 테스트를 넣으면 좋을 것 같습니다. 이번에 달라진 것도 다른 PR에 있는 시각 테스트 결과를 보고 알아차렸기 때문에 효용성이 있을 거라 생각합니다. 
- icon update PR을 changesets PR 과 구별하는 방법을 PR 제목 말고는 떠오르지 않아서 "ci(changesets)" 포함 여부로 판단했습니다. 
- No
- No

Let chromatic action run with icon update PR

---

.changeset/upset-candles-grab.md
packages/bezier-react/src/components/Checkbox/Checkbox.tsx
packages/bezier-react/src/components/SegmentedControl/SegmentedControl.stories.tsx

- [v] I wrote a PR title in **English** and added an appropriate **label** to the PR.
- [v] I wrote the commit message in **English** and to follow [**the Conventional Commits specification**](https://www.conventionalcommits.org/en/v1.0.0/).
- [v] I [added the **changeset**](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md) about the changes that needed to be released. (or didn't have to)
- [v] I wrote or updated **documentation** related to the changes. (or didn't have to)
- [v] I wrote or updated **tests** related to the changes. (or didn't have to)
- [v] I tested the changes in various browsers. (or didn't have to)
With TS 5.6+, type inferencing of Checkbox …

Fix possible infinite type recursion during inferencing typeof Checkbox on TS 5.6+
