src/components/Avatars/Avatar/Avatar.tsx, src/components/Avatars/Avatar/Avatar.types.ts, src/components/Checkbox/Checkbox.tsx, src/components/Checkbox/Checkbox.types.ts, src/components/Icon/Icon.tsx, src/components/Icon/Icon.types.ts, src/components/ListItem/ListItem.tsx, src/components/ListItem/ListItem.types.ts, src/components/OutlineItem/OutlineItem.types.ts, src/components/SegmentedControl/SegmentedControl.tsx, src/components/TabAction/TabAction.tsx, src/components/TabAction/TabAction.types.ts, src/components/Tabs/Tabs.tsx, src/layout/Client/Client.types.ts, src/types/OptionItem.ts, src/types/OptionItemHost.ts
#373 이후로 확인된 잘못 작성된 type 을 수정합니다.
#373
=> Extendable 제거 이후로 타입 문제 수정

.circleci/config.yml, jest.config.js
Codecov 로 test coverage 를 관리하도록 설정합니다.
* jest coverage collection enable
* codecov CircleCI Orb 추가
* 이슈 없음.
=> Codecov integration

.circleci/config.yml
codecov coverage 가 exp branch 에 대해 쌓이지 않는 문제 수정
* exp branch 에서 CI test job 이 실행되도록 변경
* 이슈 없음.
=> exp branch 에서 coverage report 하도록 변경

.circleci/config.yml
master branch 에서 codecov report 를 올리도록 수정합니다.
* install, test job 을 master branch 에서도 하도록 변경
* 이슈 없음.
=> master branch 에서 coverage report 하도록 수정

src/worklets/smoothCorners/SmoothCorners.stories.tsx
SmoothCorners.stories.tsx에서의 불필요한 export로 인해 storybook이 고장난 것을 고칩니다.
* 이슈 없음.
=> storybook 버그 수정: SmoothCorner 불필요한 export 제거

src/components/ListItem/ListItem.tsx, src/components/ListItem/ListItem.types.ts
누락된 `ref={forwardedRef}`를 추가합니다.
* 이슈 없음.
=> ListItem forward Ref 안되는 문제 수정

.github/workflows/codeql-analysis.yml
Github 의 CodeQL 을 통해 코드에 내재하는 위험성을 체크합니다.
* CodeQL action 을 추가합니다.
* 어느 정도 효용성이 있는지 테스트가 필요합니다. 추이를 지켜보고 존속 여부를 결정할 예정입니다.
See also: https://codeql.github.com/docs/codeql-overview/about-codeql/
=> CodeQL Github Action 추가

src/components/Button/Button.tsx, src/components/Button/Button.types.ts
Button 컴포넌트가 HTMLButtonElement 의 type attribute 를 받도록 수정합니다.
* type prop 추가
* 이슈 없음.
=> Button type prop 추가

src/components/TagBadge/Badge/Badge.tsx, src/components/TagBadge/Badge/Badge.types.ts, src/components/TagBadge/Tag/Tag.tsx, src/components/TagBadge/Tag/Tag.types.ts
태그와 뱃지를 HTMLAttr를 받게 추가하여 onClick, onMouseEnter등이 타입이 깨지지 않게 합니다
=> Tag Badge 에 HTMLAttr를  타입으로 추가

.circleci/config.yml, .releaserc, package-lock.json, package.json
semantic-release ci 를 연동합니다.
* semantic-release ci, config(.releaserc) 추가
* commitizen 지원 추가
=> Add semantic-release configuration

.circleci/config.yml, .releaserc, package-lock.json, package.json, src/components/Button/Button.tsx
semantic-release 관련 누락된 설정을 추가합니다.
* @semantic-release/git 플러그인을 추가하여 버전 수정을 push 하도록 설정
* prepublish 커맨드 추가
* CircleCI build job 제거
=> ci(semantic): semantic-release 관련 설정 추가

src/components/Input/TextArea/TextArea.stories.tsx, src/components/Input/TextArea/TextArea.styled.ts, src/components/Input/TextArea/TextArea.test.tsx, src/components/Input/TextArea/TextArea.tsx, src/components/Input/TextArea/TextArea.types.ts, src/components/Input/TextArea/__snapshots__/TextArea.test.tsx.snap, src/components/Input/TextArea/index.ts, src/components/Input/TextArea/utils.ts, src/components/Input/TextField/TextField.styled.ts, src/components/Input/TextField/TextField.test.tsx, src/components/Input/TextField/TextField.tsx, src/index.ts, src/utils/storyUtils.test.ts
TextArea 컴포넌트를 작성합니다. 
ch-desk-web에서 UserChat Description, Tag Description 등의 컴포넌트에 사용됩니다.
* 이슈 없음.
=> feat(textarea): TextArea 컴포넌트 작성

src/components/ListItem/index.ts
ListItem의 ListItemSize를 export 하도록 변경합니다
* fix #503
=> ListItem의 ListItemSize를 export 하도록 변경

src/components/Input/Select/Select.styled.ts, src/components/Input/Select/Select.test.tsx
z-index 가 존재하지 않아, z-index 가 존재하는 다른 element 보다 아래 표시되는 문제 수정
=> fix(select): dropdown z-index 10 추가

src/components/Avatars/CheckableAvatar/CheckableAvatar.stories.tsx, src/components/Avatars/CheckableAvatar/CheckableAvatar.styled.ts, src/components/Avatars/CheckableAvatar/CheckableAvatar.tsx, src/types/InjectedInterpolation.ts
=> fix(checkableavatar): 체크 스타일이 children 내부 Avatar에도 적용되는 문제 수정

src/components/Text/Text.tsx
Text컴포넌트에 forwardedRef를 추가하였습니다.
사용처에서 ref 주입시에 정상적으로 동작하기는 하지만 ts error가 발생함
=> feat(text): text 컴포넌트에서 ref를 받을 수 있도록 forwardedRef추가

src/components/Overlay/Overlay.tsx
|:---:|:---:|
|<video src="https://user-images.githubusercontent.com/55433950/123283503-6a226c80-d546-11eb-8776-69f4cfe80b9f.mov"></video>|<video src="https://user-images.githubusercontent.com/55433950/123283519-6e4e8a00-d546-11eb-9759-60bb57f79890.mov"></video>|
1. children이 변경
2. targetRect, containerRect가 변경
3. Overlay컴포넌트가 변경된 children을 가지고 렌더링까지 완료
4. useEffect내에서 Overlay의 스타일 계산하여 주입
1. children이 변경
2. 이 시점에 Overlay가 위치재계산이 됨
3. 2번에서는 아직 Overlay가 변경된 children을 가지고 실제 dom으로 마운트 되기 전이라 children이 변경되기 이전의 Overlay를 기반으로 dom의 위치가 계산됨
4. 위치가 예상하지 않은곳에 뜸
children이 변경될 경우 Overlay컴포넌트를 강제로 update시켜 정상적인 위치로 계산
> children이 변경되었을때 Overlay의 위치를 올바르게 계산하기 위해서는 Overlay가 변경된 children을 가지고 실제 dom에 마운트가 되어야 해당 dom의 width, …
=> fix(overlay): children이 변해도 새로 위치계산이 적용되지 않는문제 수정

src/components/Button/Button.tsx, src/components/Button/Button.types.ts
Instagram 메신저 연동 작업에서 추가 핸들러가 필요하여 이를 등록합니다
- onMouseEnter 추가
- onMouseLeave 추가
- onBlur 추가
* 이슈 없음.
=> Button Component에 핸들러 추가

src/components/Banner/Banner.const.ts, src/components/Banner/Banner.stories.tsx, src/components/Banner/Banner.styled.ts, src/components/Banner/Banner.test.tsx, src/components/Banner/Banner.tsx, src/components/Banner/Banner.types.ts, src/components/Banner/index.ts, src/index.ts
Banner 컴포넌트 구현.
[컴포넌트 스펙](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=1164%3A1500)에 맞춰 구현합니다.
* 이슈 없음.
=> feat(banner): add Banner component

src/foundation/Typography.ts
Typography 에 Size22 스펙 추가했습니다.
- Typo: 22
- LineHeight: 28
=> Typography Size22 추가

src/components/Forms/Inputs/TextField/TextField.types.ts
Textfield 컴포넌트의 잘못된 rightContent 타입을 수정합니다.
없음
없음
=> fix(textfield): 잘못된 rightContent의 타입 수정

src/index.ts
외부에서 커스텀한 폼을 만들 때, `FormControlContext` 에 접근할 수 있도록 관련된 hook들을 export 합니다.
없음
없음
=> feat(forms): export form-related hook

src/components/Forms/FormControl/FormControl.styled.ts, src/components/Forms/index.ts, src/index.ts
사용처에서 폼 공통 인터페이스를 확장할 수 있도록 export 목록에 추가합니다.
없음
없음
=> feat: export common form interface

.storybook/main.js, src/stories/Intro.stories.mdx
V1 런칭을 위해, 개요, 문서작성, 컴포넌트 작성 컨벤션 등이 들어갈 문서입니다.
없음.
=> 인트로 페이지 템플릿 생성

src/components/Navigator/NavGroup/__snapshots__/NavGroup.test.tsx.snap, src/components/Navigator/NavItem/__snapshots__/NavItem.test.tsx.snap
https://github.com/channel-io/bezier-react/pull/715 를 머지했으나, https://github.com/channel-io/bezier-react/pull/665 의 변경사항으로 머지 후 돌아간 테스트의 에러 발생, 해당 에러를 수정하는 PR 입니다.
Snapshot 업데이트 진행
=> Snap shot conflict 수정

src/components/Status/Status.styled.ts, src/components/Status/Status.tsx
This reverts commit f97fa8d905306f72676042afb50dc0ee52da22d5.
PR이 아닌 형태로 direct merge 되었기에 이를 revert합니다.
=> Revert "fix(status): remove dependency on legacy icon"

apps/bezier-react/src/components/Emoji/Emoji.stories.tsx, apps/bezier-react/src/components/Emoji/Emoji.types.ts
이모지 사이즈를 최신 디자인에 맞게 업데이트합니다.
- 스토리북에서 size를 조절할 수 있도록 argType 업데이트
- Fix #782
=> feat(emoji): update EmojiSize specification

apps/bezier-react/src/components/Forms/Inputs/Select/Select.tsx
- 폼의 접근성 관련 속성이 div 컨테이너로 잘못 전달되어 label과 button이 연결되지 않는 문제를 수정합니다.
- 불필요한 주석을 제거합니다.
없음
없음
=> fix(select): fix invalid property passing to the container

package-lock.json, package.json
Peer dependency 이슈로 자동 릴리즈가 제대로 이루어지지 않는 점을 해결합니다.
- `@semantic-release/git` 최신 버전 업데이트로 버전 맞춤.
- #822 에서 peer deps 문제를 파악하지 못한 것이 원인.
=> fix(package): update @semantic-release/git to fix peer deps issue

packages/bezier-react/src/components/Stack/Stack.stories.mdx, packages/bezier-react/src/components/Stack/Stack.stories.tsx
- #705 에서 추가한 컴포넌트 documentation 작성 가이드에 따라, `Stack` 컴포넌트의 documentation을 추가합니다.
- 스토리북 실행 후 확인하여 첨삭 부탁드립니다!
- #705
=> Write mdx documentation for Stack components

package-lock.json, package.json
#834, #822를 revert합니다.
빌드 시 특정 라이브러리들이 누락되어서 들어가는 문제가 있어 의심가는 PR들을 revert합니다
=> 의심 가는 PR들 리버트 - #834, #822

packages/bezier-react/src/components/Forms/Switch/Switch.test.tsx, packages/bezier-react/src/components/Forms/Switch/Switch.tsx, packages/bezier-react/src/components/Forms/Switch/Switch.types.ts
- [Figma Switch](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=3263%3A131)
=> Forms/Switch 테스트 작성

packages/bezier-react/src/components/Banner/Banner.stories.mdx, packages/bezier-react/src/components/Banner/Banner.stories.tsx, packages/bezier-react/src/components/Banner/Banner.types.ts
- #705 에서 추가한 컴포넌트 documentation 작성 가이드에 따라, `Banner` 컴포넌트의 documentation을 추가합니다.
- `BannerOptions` interface에 jsdoc을 추가합니다.
- 스토리북 실행 후 확인하여 첨삭 부탁드립니다!
- #705
=> Write mdx documentation for Banner component

README.md, packages/bezier-figma-plugin/README.md, packages/bezier-figma-plugin/package.json, packages/bezier-react/README.md, packages/bezier-react/package.json
루트 workspace와 각 패키지의 `README.md` 파일의 내용을 최신화하고 보강합니다.
- 루트 workspace의 README를 적절한 내용으로 변경하고, 여러 Status Badge 들을 추가
- 각 패키지의 README를 적절한 내용으로 변경하고, 그에 맞게 package description 변경
없음. 다른 오픈소스 라이브러리들의 README를 참고하여 작성.
=> Enhance the README

.github/workflows/prerelease.yml
`prerelease` workflow에 yarn cache를 적용합니다.
없음
- https://github.com/chakra-ui/chakra-ui/blob/main/.github/workflows/release.yml
=> ci(changesets): apply yarn cache

.changeset/curly-swans-greet.md
#872 에서 누락된 Changeset을 추가합니다.
- `ButtonGroup` 추가에 대한 changeset 추가
팀원들이 사용 방식에 익숙해지기 전까지, 같은 실수가 재발하지 않도록 changeset을 추가하지 않으면 머지하지 못하도록 하는 설정을 추가할지 고민입니다. (변경사항이 없는 경우, empty 옵션으로 changeset을 추가할 수 있음)
없음
=> chore(changeset): add changeset

.github/workflows/chromatic.yml
워크플로우 테스트를 위한 PR입니다.
[repository_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch) 이벤트가 default branch에 워크플로우 파일이 있을 때만 트리거되기 때문에 원활한 테스트를 위해 미리 머지합니다.
Details 참고
=> ci(chromatic): change trigger event to repository_dispatch

.github/workflows/chromatic-report.yml
#887 워크플로우를 테스트하기 위한 PR입니다.
`workflow_run` 이벤트는 워크플로우 파일이 기본 브랜치에 존재하는 경우에만 동작하기 때문에 미리 머지해서 테스트합니다.
- #887 
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
=> ci(chromatic-report): add chromatic report workflow

.github/workflows/chromatic-report.yml
#887 워크플로우를 테스트하기 위한 PR입니다.
- `workflow_run` 이벤트는 워크플로우 파일이 기본 브랜치에 존재하는 경우에만 동작하기 때문에 미리 머지해서 테스트합니다.
- rest api 스펙과 다른 부분을 맞춥니다.
- #888
- #887 
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
=> ci(chromatic-report): fix to fit api spec

.github/workflows/chromatic-report.yml
#887 워크플로우를 테스트하기 위한 PR입니다.
- `workflow_run` 이벤트는 워크플로우 파일이 기본 브랜치에 존재하는 경우에만 동작하기 때문에 미리 머지해서 테스트합니다.
- 잘못 설정된 인코딩 옵션을 올바르게 변경합니다.
- #889
- #888
- #887 
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
=> ci(chromatic-report): fix invalid result-encoding value

.github/workflows/chromatic-report.yml
Chromatic report 워크플로우가 작동하지 않던 부분을 수정합니다.
- [예제](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run)에서 예상하던 동작과 다르게 GITHUB_WORKSPACE 환경 변수가 제대로 전달되지 않아 동작하지 않던 오류를 수정합니다.
- #897 에서 누락되었던 변경사항을 추가합니다.
- #888
=> ci(chromatic-report): fix not working github workspace env

.github/workflows/chromatic-report.yml
=> ci(chromatic-report): fix typo

.github/workflows/chromatic-report.yml, .github/workflows/chromatic.yml
- Chromatic 워크플로우 동작을 개선합니다.
- Chromatic Report 워크플로우가 올바르게 동작하도록 수정합니다.
- Chromatic 워크플로우가 `master`, `next*` 브랜치에 푸시되는 경우에만 push 이벤트를 통해 트리거되도록 개선합니다.
- Chromatic Report 워크플로우의 실행 조건문이 제대로 동작하도록 수정합니다.
- Chromatic Report에 Checkout step을 추가하여 Template 스텝에서 파일을 찾지 못하는 문제를 해결합니다.
- Chromatic 워크플로우에서 output을 저장하는 커맨드에 `"` 를 추가하여 빈 아티팩트가 생성되는 문제를 해결합니다.
- [Forked Repository](https://github.com/sungik-choi/bezier-react/actions/runs/2731326945)에서 템플릿까지 정상적으로 생성되는 것 확인
- https://github.com/chuhlomin/render-template/issues/6
=> ci: fix and enhance chromatic(report) workflow

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/pull_request_template.md
GitHub PR과 이슈 템플릿을 개선합니다.
- 오픈소스임을 감안하여 모두 영문으로 변경했습니다.
- PR 템플릿에 셀프 체크리스트를 추가했습니다. 명시적으로 작성되지 않던 규칙들을 추가했습니다 (TODO: Contribute 문서에도 추가 필요)
- Chakra UI, Shopify Polaris 참고
- [prosemirror-toolkit의 PR 템플릿 셀프 체크리스트](https://github.com/channel-io/prosemirror-toolkit/blob/main/.github/pull_request_template.md) 참고
=> chore: enhance the pr/issue templates

.changeset/silver-chefs-raise.md
Add the missing breaking change of #892 to changeset
=> chore(changeset): reword silver-chefs-raise changeset

packages/bezier-react/src/components/Icon/Icon.mdx, packages/bezier-react/src/components/Icon/Icon.stories.tsx
`Icon` 컴포넌트에 대한 Storybook MDX documentation을 작성합니다.
생각해보니.. chromatic build가 있어서 스크린샷을 올려볼 필요가 없군요 😁 
None
None
=> Write mdx documentation for Icon component

packages/bezier-react/src/foundation/Typography.mdx, packages/bezier-react/src/foundation/Typography.stories.tsx
Write documentation for `Typography` in `@channel.io/bezier-react`
(None)
(None)
(None)
=> Write mdx documentation for Typography

packages/bezier-react/src/components/TagBadge/TagBadge.mdx, packages/bezier-react/src/components/TagBadge/TagBadge.stories.tsx, packages/bezier-react/src/stories/Intro.stories.mdx
Add documentation for components in `Components/TagBadge`: `Tag` and `Badge`.
Refer to the Chromatic deployment for preview.
(None)
=> Write mdx document for TagBadge component group

.changeset/pretty-tools-sneeze.md, packages/bezier-react/src/foundation/Colors/Palette/index.ts, packages/bezier-react/src/foundation/Colors/Theme/presets/DarkTheme.ts, packages/bezier-react/src/foundation/Colors/Theme/presets/LightTheme.ts, packages/bezier-react/src/foundation/Colors/Theme/types/SemanticNames.ts
새 semantic color 'bg-gnb'를 추가합니다.
'bg-gnb'와 함께 palette도 추가됩니다.
- grey900_90
- grey100_90
- [Figma](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?node-id=1711%3A2160)
=> feat(color): add semantic color 'bg-lounge' and its pallete color

.github/workflows/chromatic-report.yml
No
Add if check condition to prevent a job from running by dependabot
Skip
No
- [GitHub Actions - Ignore or exclude Dependabot Pull Requests](https://stackoverflow.com/questions/71679568/github-actions-ignore-or-exclude-dependabot-pull-requests)
- https://github.com/orgs/community/discussions/25067
- https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
=> fix(chromatic-report): add if check condition to prevent a job from running by dependabot

.github/CODEOWNERS, .github/dependabot.yml, .github/pull_request_template.md
Fixes #998
코드 오너 설정을 추가합니다.
- `CODEOWNER` 파일을 추가하고, 각 디렉터리의 코드 오너를 지정합니다.
- 컴포넌트를 처음 구현한 멤버를 코드 오너로 지정했습니다.
- 현재 유지 보수를 할 수 없는 멤버는 코드 오너를 저(@sungik-choi)로 지정했습니다.
- 코드 오너에 관련된 부분을 PR Template에 추가합니다.
- 코드 오너를 자동으로 리뷰어에 할당하므로, dependabot의 불필요한 reviewers 설정을 제거합니다.
- 이 PR이 머지된 이후, next-v1 branch의 리뷰어 수를 3에서 2로 변경합니다.
No
- #998
=> Add code owner

package.json, turbo.json, yarn.lock
Skip
Bump turbo from 1.2.6 to 1.6.3
- Delete the unused config option of `turbo.json`
No
Skip
=> Bump turbo from 1.2.6 to 1.6.3

package.json, packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.tsx, yarn.lock
Skip
Bump typescript from v4.6.4 to v4.8.4
Skip
No
- #960
=> Bump typescript from 4.6.4 to 4.8.4

.eslintrc.js, packages/bezier-react/src/components/Avatars/Avatars.stories.tsx, packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.stories.tsx, packages/bezier-react/src/components/SectionLabel/SectionLabel.test.tsx, packages/bezier-react/src/components/Tabs/Tabs/Tabs.stories.tsx, packages/bezier-react/src/foundation/Colors/Palette/Palette.stories.tsx, packages/bezier-react/src/layout/components/Navigations/Navigations.stories.tsx, packages/bezier-react/src/layout/stories/LayoutPlayground/LayoutPlayGround.stories.tsx
Skip
> #965 base, starts from 04f6b41b64ae7377d15c3e325dcc130c5ee4f3bf
Update eslint config rules
- Delete the unused rule (Resolve FIXME)
- Add `'react/no-array-index-key'` rule to prevent missing react component's key prop
No
Skip
=> Update eslint config rules

.changeset/fifty-boats-retire.md, packages/bezier-react/src/foundation/FoundationStyledComponent.tsx
Fixes #1013 
Export ServerStyleSheet Functions for SSR Support
Added logic to export ServerStyleSheet function
With/without the above function, the following differences are observed:
|as-is|to-be|
|:---:|:---:|
|<img width="500" alt="스크린샷 2022-11-14 오후 1 36 11" src="https://user-images.githubusercontent.com/55074799/201578055-b9f36771-315d-4093-9637-f278e061efd5.png">|<img width="510" alt="스크린샷 2022-11-14 오후 1 35 33" src="https://user-images.githubusercontent.com/55074799/201578059-6b38507e-bd67-460f-b1da-ccb975c18fa7.png">|
No
https://styled-components.com/docs/advanced#server-side-rendering
=> Export ServerStyleSheet Function for SSR Support

.changeset/chilly-ladybugs-laugh.md, packages/bezier-react/src/components/ButtonGroup/ButtonGroup.tsx, packages/bezier-react/src/components/ButtonGroup/ButtonGroup.types.ts
Fixes #940 
`ButtonGroup` 에 justify prop을 추가합니다.
#940 이슈를 참고해주세요.
No
생략
=> Enhance `ButtonGroup`'s `justify` property from fixed to non-fixed property

.changeset/kind-chairs-hide.md, packages/bezier-react/.storybook/preview.js, packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.stories.tsx, packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.styled.ts, packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.test.tsx, packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.tsx, packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.types.ts, packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap, packages/bezier-react/src/components/Avatars/AvatarGroup/index.ts
- #1064 
- #1066 
`AvatarGroup` 의 마이너 개선사항들이 포함됩니다.
- `AvatarGroup` 전체 래퍼에 쌓임 맥락을 생성하여 내부의 쌓임 맥락이 외부의 맥락과 비교되지 않도록 합니다.
- 전체 래퍼에 `group` role을 추가합니다.
- 내부적으로 CSS Variable을 사용하여 스타일 컴포넌트(className)를 재생성하지 않도록 개선합니다.
- Ellipsis 관련 동작에 대한 테스트를 추가합니다.
- 기타 오타 수정
- CSS Variable을 테마 스코프별로 생성하여 스토리북 환경에서 잘 동작하도록 합니다.
No
없음
=> Enhance the `AvatarGroup` component

packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
- AvatarGroup 관련 snapshot 업데이트를 통해 ci test 에러를 해결합니다.
=> Update snapshot test AvatarGroup

.github/workflows/prereleased.yml
Fixes #1147
prereleased 워크플로우가 올바르게 작동하도록 수정합니다.
- 이슈 참고. 태그가 푸시될 때로 워크플로우 트리거 조건을 변경합니다. 
- 다른 패키지에서도 사용될 수 있는 가능성을 고려하여 특정 패키지명에 대한 패턴은 제외했습니다.
No
- [Filter Pattern](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet)
- [Stack overflow](https://stackoverflow.com/questions/58862864/github-actions-ci-conditional-regex)
=> ci(github): fix prereleased action to work correctly

.github/workflows/chromatic-report.yml, .github/workflows/chromatic.yml
없음
Chromatic 워크플로우가 renovate 봇이 생성한 의존성 업데이트 PR에는 실행되지 않도록 합니다.
요약에 더해서, 기존엔 chromatic-report 워크 플로우에 해당 조건이 걸려있었는데, chromatic 워크 플로우는 조건에 무방하게 실행되고 있었으므로 동일하게 해당 조건을 추가합니다. 
No
없음
=> ci(github): enhance github actor filter of the chromatic actions

supports/eslint-config-bezier/package.json, supports/tsconfig/package.json
없음
#1114 에서 추가된 내부 설정 패키지들에 버전 정보와 내부 패키지로 사용된다는 점을 명시합니다.
- `changeset` 을 사용할 경우, 버전을 지정해주어야합니다.
- 또한 배포하지 않을 패키지엔 `private: true` 를 명시적으로 지정해주어야 합니다.
No
> # Managing applications or non-npm packages
> 
> Changesets can also be used to manage application versions or non-npm packages (ie dotnet NuGet packages, ruby gems, docker images etc).
> 
> The only requirement is that the project has a package.json file to manage the versions and dependencies within the repo.
> 
> To enable this feature set `privatePackages` to `{ version: true, tag: true }` in your `.changesets/config.json` file. By default changesets will only update the changelog and version (ie `{ version: true, tag: false }`).
> 
> > …
=> chore(supports): add version, private and description value to package.json

renovate.json
없음
renovate 설정을 추가합니다.
- 잘못된 timezone 설정을 올바르게 수정
- 매주 월요일, 10am ~ 6pm 사이에 동작하도록 수정합니다.
No
- https://docs.renovatebot.com/key-concepts/scheduling/
- https://docs.renovatebot.com/presets-schedule/#scheduleearlymondays
=> chore(renovate): add timezone and schedule configuration

yarn.lock
=> chore(deps): fix yarn.lock

renovate.json
=> chore(renovate): fix schedule config

.github/create-ch-desk-bullets-blocks.sh, .github/workflows/prerelease.yml
None
Fix prerelease workflow to ensure JSON transform
=> chore(github): fix prerelease workflow to ensure JSON transform

.github/workflows/prerelease.yml
References
- https://docs.github.com/en/actions/learn-github-actions/expressions#example-returning-a-json-object
- https://github.com/actions/runner/issues/2245
=> ci(github): test the JSON array conversion process of gha

.github/workflows/prerelease.yml
- #1257 
이슈가 해결되기 전까지 임시로 해당 스텝을 비활성화합니다.
None
No
None
=> ci(prerelease): disable sending channel desk message steps

packages/bezier-react/rollup.config.js
`tsconfigDefaults`의 `noEmit`, `exclude` 옵션을 `tsconfigOverride`로 이동합니다.
tsconfigDefaults에 존재하는 옵션들의 경우 로딩되는 `tsconfig`에 들어있는 옵션과 중복된다면 덮어씌워져 사라집니다. Rollup에서 로딩되는 tsconfig에는 noEmit, exclude 옵션이 존재하기에 작성된 `tsconfigDefaults`에 존재하는 옵션들은 사용되지 않고 있었습니다.
이로 인해 현재 빌드 시에 stories.tsx에 대한 타입들이 같이 빌드되고 있는 상황이었기에 이를 수정합니다. 
`tsconfig.build.json`을 그냥 새로 만드는게 가독성 면이나 실수 면에서나 개선될거 같아서 그걸 추가하는것에 대해서는 어떻게 생각하시는지 궁금합니다.
https://github.com/ezolenko/rollup-plugin-typescript2#plugin-options
=> Change some tsconfigDefaults options to tsconfigOverride

.github/workflows/chromatic.yml
None
https://github.com/channel-io/bezier-react/actions/runs/4751055201
위 이슈를 해결합니다.
- See #1297
No
None
=> chore(chromatic): specify the node version

.changeset/giant-paws-check.md, packages/bezier-react/src/components/Forms/SegmentedControl/index.ts
None
Add the missing `SegmentedControlSize` enum export
Skip
No
None
=> Add the missing `SegmentedControlSize` enum export

.changeset/nine-crews-complain.md, packages/bezier-react/src/components/Avatars/Avatar/Avatar.styled.ts, packages/bezier-react/src/components/Avatars/AvatarGroup/__snapshots__/AvatarGroup.test.tsx.snap
None
Fix `Avatar` not resizing under flex layout.
- Add `flex: none` style to avatar wrapper component
No
None
=> Fix `Avatar` not resizing under flex layout

README.md
- #1367 
`main` 으로 변경된 브랜치에 맞게 뱃지 링크를 업데이트합니다.
생략
No
No
=> docs: change the badge link to match the changed branch

.changeset/cuddly-tips-smoke.md
Fixes #1367 
> 🦋  error an error occurred while publishing @channel.io/bezier-react: E400 400 Bad Request - PUT https://registry.npmjs.org/@channel.io%2fbezier-react - Cannot publish over previously published version "1.0.0". 
https://github.com/channel-io/bezier-react/actions/runs/5117661702/jobs/9201032175#step:7:533
이전에 잘못 v1.0.0 버전을 퍼블리시한 적이 있어, 해당 버전으로 퍼블리시가 불가능합니다.
v1.1.0 버전으로 강제 업데이트합니다.
생략
No
> Note: package-name@version is unique, and cannot be reused by unpublishing and re-publishing it. **We recommend publishing a minor version update instead.**
- https://docs.npmjs.com/unpublishing-packages-from-the-registry
=> Release v1.1.0

README.md, packages/bezier-figma-plugin/README.md, packages/bezier-figma-plugin/package.json, packages/bezier-icons/README.md, packages/bezier-icons/package.json, packages/bezier-react/README.md, packages/bezier-react/package.json
None
문서상의 `The Bezier Design System` 을 `Bezier design system` 으로 모두 통일합니다.
None
No
None
=> docs: bezier design system syntax unification

.changeset/sweet-carrots-vanish.md
- #1411 
#1411 에 대한 패치노트를 생성합니다.
=> chore(changeset): add a changeset to force a minor update

.github/workflows/release.yml, package.json
None
`changeset version` 시, 내부 의존성의 yarn.lock 충돌을 피하기 위해 yarn.lock 재생성 과정을 포함합니다.
Skip
No
https://github.com/emotion-js/emotion/blob/fef1ea086fbec998caaa016a5ecdace4bbb9d749/package.json#L26
emotion의 예시를 참고했습니다.
=> chore(changeset): add custom version package script

.changeset/sour-cameras-shave.md
- #1383 
- Breaking Change가 존재하므로, patch에서 minor 버전으로 변경합니다.
- (Breaking Change가 있다면 major 버전을 올리는 것이 맞으나, 현재 bezier-react의 경우 실수로 major 버전이 1이 되어 아직 안정화 상태가 아님을 고려)
- 패치 노트의 가독성을 올립니다.
=> chore(changeset): change versioning of #1383 from patch to minor

.github/ISSUE_TEMPLATE/epic.md, .github/ISSUE_TEMPLATE/feature-request.yml
Add template for epic issue and update changing of label name
=> chore(github): add template for epic issue and update changing of label name

packages/bezier-react/src/components/Help/Help.types.ts
- #1293 
- #1293 에서 #1434 의 변경사항이 적용되지 않아 타입 에러가 발생하는 부분을 해결합니다.
No
=> fix(help): fix type error

.changeset/tidy-scissors-melt.md
=> docs(changeset): modify changeset of #1506

.changeset/swift-pets-rhyme.md, packages/bezier-react/src/foundation/Colors/Theme/presets/DarkTheme.ts
- DarkTheme에 누락된 `bg-black-darkest` color를 추가합니다. Figma 상으로 해당 색상은 `grey900` / `white`입니다.
- <img width="327" alt="image" src="https://github.com/channel-io/bezier-react/assets/6940439/dc18dbab-d777-4797-822e-1956919833bf">
- No
=> Add bg-black-darkest color to DarkTheme

.changeset/cyan-poems-bow.md, packages/bezier-react/src/components/ProgressBar/ProgressBar.mdx, packages/bezier-react/src/components/ProgressBar/ProgressBar.stories.tsx, packages/bezier-react/src/components/ProgressBar/ProgressBar.styled.ts, packages/bezier-react/src/components/ProgressBar/ProgressBar.test.tsx, packages/bezier-react/src/components/ProgressBar/ProgressBar.tsx, packages/bezier-react/src/components/ProgressBar/ProgressBar.types.ts
- ProgressBar 컴포넌트에 새 Variant `GreenAlt`를 추가합니다.
- `GreenAlt` variant는 `Green`과 거의 동일하지만, wrapper 배경색으로 `bgtxt-absolute-white-normal`을 가집니다.
- <img width="925" alt="image" src="https://github.com/channel-io/bezier-react/assets/6940439/2227efc4-40b0-429b-bfd3-4a906d32bf45">
- No
- [Figma](https://www.figma.com/file/99k33ZxchcPKTz2tzJlZeE/Components?type=design&node-id=23846-206096&mode=design&t=bdsS24BO6w7gLlol-4)
=> Add ProgressBar `GreenAlt` variant

.changeset/khaki-mugs-applaud.md, packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.styled.ts
Fixes #1454
`SegmentedControl` 의 각 아이템 텍스트 라벨에 말줄임 표시를 추가합니다.
디자인 스펙 업데이트
No
이슈 참고
=> Add text ellipsis to the each item label of `SegmentedControl`

.github/pull_request_template.md
PR Template을 업데이트합니다.
- 체크리스트를 단순화했습니다. PR/Commit 등 특정 컨텍스트에 관련된 항목을 하나의 리스트로 합쳤습니다.
- 변경 사항의 종류에 따라 체크하지 않아도 되는 항목들에서 `[Component]` 를 제거했습니다. 대신 `(or didn't have to)` 문구를 추가하여 체크리스트를 모두 체크할 수 있도록 했습니다. 체크리스트가 항상 모두 체크된 상태가 되는걸 목표로 했습니다.
- 작동하지 않는 링크를 업데이트했습니다.
- 문서화에 대한 체크리스트를 추가했습니다.
- 코드 오너에 대한 체크리스트를 제거했습니다. (#1585)
- 주석 어투를 통일했습니다.
- TODO: 문서화 / 브라우저 테스트에 대한 내용은 별도 문서로 분리하고, 문서 링크를 추가하는 방향으로 개선 필요
=> chore(github): update pr template

.changeset/shaggy-months-hammer.md, packages/bezier-react/README.md
설치할 의존성의 목록을 업데이트 했습니다.
`@types/styled-components` 라이브러리가 설치되어 있지 않은 경우, styled 를 import 하는 경우에 타입이 any로 추론되는 문제가 발생합니다.
본 PR은 이 문제를 해결하는 방법중 하나를 제시합니다.
장기적으로는, 해당 의존성을 설치하지 않아도 되도록 install 과정에서 자동으로 의존성을 추가하도록 하여야 합니다.
No
=> docs(bezier-react): update installation section

.changeset/nice-melons-joke.md, packages/bezier-react/src/components/TagBadge/Tag/Tag.stories.tsx, packages/bezier-react/src/components/TagBadge/Tag/Tag.test.tsx, packages/bezier-react/src/components/TagBadge/Tag/Tag.tsx
resolves #501 
- x 버튼을 눌렀을 때 onClick이 동작하지 않도록 했습니다
- 클릭에 대한 테스트코드를 추가했습니다.
- x 버튼을 눌렀을 때 `onClick` 함수가 동작하지 않도록 `stopPropagation`을 이용하여 `onDelete`만 동작하도록 만들었습니다.
-  태그를 클릭했을 때 `onClick`, x 버튼을 클릭했을 때 `onDelete` 함수가 동작하는지에 대한 테스트 코드를 추가하였습니다.
No, 특별히 기능에 대한 변경사항이 없습니다.
=> test(react-bezier): Add test code for click event in Tag Component

packages/bezier-tokens/README.md
=> docs(bezier-tokens): apply changes from #1766

packages/bezier-react/src/hooks/useIsMounted.test.ts
=> test(bezier-react): add test to useIsMounted

.changeset/tricky-geese-lick.md, packages/bezier-codemod/README.md, packages/bezier-codemod/src/App.tsx, packages/bezier-codemod/src/transforms/import-styled-from-styled-component.ts, packages/bezier-codemod/src/transforms/tests/import-styled-from-styled-components/fixtures/styled1.input.tsx, packages/bezier-codemod/src/transforms/tests/import-styled-from-styled-components/fixtures/styled1.output.tsx, packages/bezier-codemod/src/transforms/tests/import-styled-from-styled-components/fixtures/styled2.input.tsx, packages/bezier-codemod/src/transforms/tests/import-styled-from-styled-components/fixtures/styled2.output.tsx, packages/bezier-codemod/src/transforms/tests/import-styled-from-styled-components/fixtures/styled3.input.tsx, packages/bezier-codemod/src/transforms/tests/import-styled-from-styled-components/fixtures/styled3.output.tsx, packages/bezier-codemod/src/transforms/tests/import-styled-from-styled-components/fixtures/styled4.input.tsx, packages/bezier-codemod/src/transforms/tests/import-styled-from-styled-components/fixtures/styled4.output.tsx, packages/bezier-codemod/src/transforms/tests/import-styled-from-styled-components/import-styled-from-styled-components.test.ts, packages/bezier-codemod/src/utils/import.ts
- Fixes #1782
- https://github.com/channel-io/bezier-react/pull/1787 베이스이기 때문에 앞선 pr이 머지되면 rebase 후 오픈 예정입니다. 
- `@channel.io/bezier-react`에서 `styled` 객체를 import 하던 것을 `styled-components`에서 import 하는 것으로 변경하도록 하는 codemod 를 추가합니다. 
As-is
```tsx
import { styled, Button } from "@channel.io/bezier-react";
export const Wrapper = styled(Button)``;
```
To-be
```tsx
import styled from "styled-components";
import { Button } from "@channel.io/bezier-react";
export const Wrapper = styled(Button)``;
```
- `styled` 만 import 하고 있는 경우에는 import 문 자체를 없애야 합니다. 이를 위해 `ImportDeclaration.remove()` 함수를 호출하면 뒤에 있는 개행을 제거하는 이슈가 있습니다. ts-morph 레포에 이슈를 남겨둔 상황인데, 원인을 파악하기 못한다면 어플리케이션 쪽에서 대응해야 할 것 같습니다.
No
- …
=> Add codemod for import of `styled` object

packages/bezier-react/.storybook/WithFoundationProvider.jsx, packages/bezier-react/src/providers/BezierProvider.tsx
스토리북에 `AlphaAppProvider` 를 적용합니다.
- CSS variable 테스트를 할 수 있도록 환경을 구축합니다. #1733 마이그레이션이 완료되면, BezierProvider를 제거할 수 있습니다.
- 중복되거나 불필요한 글로벌 스타일, Provider를 제거했습니다.
적용된 모습
No
=> chore(storybook): setting up AlphaAppProvider

.changeset/strange-toes-tap.md, packages/bezier-react/.storybook/WithFoundationProvider.jsx, packages/bezier-react/src/index.ts, packages/bezier-react/src/providers/AppProvider.tsx
Rename `AlphaAppProvider` to `AppProvider`
alpha 버전에서 구현 이후, 별도 컴포넌트 상태 변경 없이 바로 v2에 Stable로 적용할 예정이기때문에 alpha prefix를 제거했습니다.
No
=> Rename `AlphaAppProvider` to `AppProvider`

packages/bezier-react/package.json
package.json의 스타일 파일 경로를 올바르게 바꿉니다.
=> fix(package): change the CSS file path

.changeset/cuddly-chairs-warn.md
- #1866
Fix invalid changelog in #1866
- Breaking change를 제대로 명시합니다.
- minor -> major version bump로 변경합니다.
Yes
=> chore(changeset): fix invalid changelog in #1866

.changeset/stale-nails-study.md, packages/bezier-react/src/components/ButtonGroup/ButtonGroup.stories.tsx, packages/bezier-react/src/components/ButtonGroup/ButtonGroup.test.tsx, packages/bezier-react/src/components/ButtonGroup/ButtonGroup.tsx, packages/bezier-react/src/components/ButtonGroup/ButtonGroup.types.ts, packages/bezier-react/src/components/ButtonGroup/index.ts
- #1733 
Update `ButtonGroup` interface
- margin prop을 지원하도록 합니다.
- named export, jsdoc 추가 등
No
=> feat(button-group): update interface

.changeset/hot-bobcats-develop.md, .changeset/sweet-suits-smoke.md
- #1906 
#1906 에서 누락된 변경 사항 적용
=> chore(changeset): apply missing changes

packages/bezier-tokens/scripts/build-tokens.ts
- #1779 
Fix scoping issues with common semantic tokens
> 우측 라이트 테마의 box-shadow가 다크 테마의 box-shadow(shdw 컬러) 토큰을 참조한 모습
- #1779 에서 공용 시맨틱 토큰을 줄이고자, CSS의 경우 전체 루트 선택자 하위에만 variable을 선언했습니다. 
- 예상과 다르게 실제는 가장 가까운 테마의 시맨틱 토큰을 참조하는 게 아니라, 루트에 적용된 시맨틱 토큰을 참조하는 방식으로 동작했습니다.
- #1779 이전으로 되돌려, 각 테마별 스코프에 공용 시맨틱 토큰을 (중복되더라도) 각각 선언하여 참조가 올바르게 되도록 변경했습니다.
No (alpha)
=> fix(bezier-tokens): fix scoping issues with common semantic tokens

.stylelintrc, .stylelintrc.mjs, package.json, packages/bezier-react/package.json, packages/bezier-react/src/components/AlphaSmoothCornersBox/AlphaSmoothCornersBox.module.scss, packages/bezier-react/src/components/Avatars/Avatar/Avatar.module.scss, packages/bezier-react/src/components/Avatars/AvatarGroup/AvatarGroup.module.scss, packages/bezier-react/src/components/Banner/Banner.module.scss, packages/bezier-react/src/components/Button/Button.module.scss, packages/bezier-react/src/components/Divider/Divider.module.scss, packages/bezier-react/src/components/Emoji/Emoji.module.scss, packages/bezier-react/src/components/Forms/SegmentedControl/SegmentedControl.module.scss, packages/bezier-react/src/components/Forms/Slider/Slider.module.scss, packages/bezier-react/src/components/Forms/Switch/Switch.module.scss, packages/bezier-react/src/components/Help/Help.module.scss, packages/bezier-react/src/components/Modal/Modal.module.scss, packages/bezier-react/src/components/Spinner/Spinner.module.scss, packages/bezier-react/src/components/Status/Status.module.scss, packages/bezier-react/src/components/TagBadge/Badge/Badge.module.scss, packages/bezier-react/src/components/TagBadge/TagBadgeCommon/TagBadge.module.scss, packages/bezier-react/src/components/Text/Text.module.scss, packages/bezier-react/src/components/Tooltip/Tooltip.module.scss, packages/bezier-react/src/styles/_base.scss, packages/bezier-react/src/styles/components/layout.module.scss, packages/bezier-react/src/styles/index.scss, yarn.lock
Apply stylelint for scss
styled-components(js)에 적용되고 있었던 이전 stylelint 설정을 scss에 적용되도록 변경합니다.
- `@channel.io/stylelint-config` 를 의존성에서 제거합니다. styled-components 관련 설정을 대부분 포함하고 있고, scss 설정도 일부 있으나 레거시라 굳이 이 설정을 확장해서 사용할 필요는 없다고 판단했습니다.
- 위 패키지를 의존성에서 제거하며 stylelint를 최신 버전으로 업데이트합니다.
- 확장들을 설치합니다.
-  stylelint-config-standard-scss : 일반적인 scss 규칙
- stylelint-config-clean-order : 순서 규칙 용도로 추가했습니다. 타 순서 규칙을 다루는 확장들에 비해 최근까지 관리되는 것으로 보였고, 개인적인 선호로 규칙의 그룹핑이 명확해 스타일을 파악하기 가장 용이해보였습니다. Adobe spectrum 에서도 사용하는 걸 보고 프로덕션에서 사용해도 무방하다고 생각했습니다.
- 몇 규칙들을 변경하거나 추가합니다. ([.stylelintrc.mjs](https://github.com/channel-io/bezier-react/compare/alpha...sungik-choi:style/scss-stylelint?expand=1#diff-d2da74f7aad24697674a9c …
=> Apply stylelint for scss

.changeset/thick-actors-kneel.md
- #1915
fix bump type and format changelog
=> chore(changeset): fix bump type and format changelog

README.md
- None 
- Readme 에 bezier-tokens 라이브러리를 추가합니다
- No
- None
=> Add bezier-tokens to Readme

packages/bezier-react/src/components/Forms/RadioGroup/RadioGroup.module.scss
```bash
@channel.io/bezier-react:build: DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
@channel.io/bezier-react:build: 
@channel.io/bezier-react:build: Recommendation: math.div($outer-indicator-size, 2) or calc($outer-indicator-size / 2)
@channel.io/bezier-react:build: 
@channel.io/bezier-react:build: More info and automated migrator: https://sass-lang.com/d/slash-div
@channel.io/bezier-react:build: 
@channel.io/bezier-react:build:    ╷
@channel.io/bezier-react:build: 63 │     left: calc(#{$outer-indicator-size / 2} + #{$outer-indicator-margin});
@channel.io/bezier-react:build:    │                  ^^^^^^^^^^^^^^^^^^^^^^^^^ …
```
=> refactor(radio-group): change to do division outside of calc()

.changeset/long-birds-attend.md, packages/bezier-react/src/index.ts, packages/bezier-react/src/types/Utils.ts
- Fixes #1798
Deprecate internal use modules
from [1926041](https://github.com/channel-io/bezier-react/pull/1963/commits/192604101948ba062a8c820b9d0d2983a15eafaf)
Yes
=> Deprecate internal use modules

.changeset/violet-queens-explain.md, packages/bezier-react/src/components/Text/Text.module.scss, packages/bezier-react/src/components/Text/Text.stories.tsx, packages/bezier-react/src/styles/mixins/_typography.scss
Fixes an issue where multi line truncated in `Text` was not being applied
- typography size mixin 마이그레이션을 잘못하여 multi-line truncated가 제대로 동작하지 않는 문제를 수정합니다. mixin에 매개변수를 추가하여 css variable을 지정할 수 있는 기능을 추가했습니다.
- 해당 케이스에 대한 스토리북을 강화합니다.
No
=> Fixes an issue where multi line truncated in `Text` was not being applied

.changeset/smart-geese-provide.md, packages/bezier-react/src/components/Tabs/Tabs.module.scss, packages/bezier-react/src/components/Tabs/Tabs.tsx
Fix invalid style migrations of Tabs component
- TabList에 className 속성이 전달되고 있지 않던 문제를 수정
- 사용하지 않는 CSS variable 제거
No
=> fix(tabs): fix invalid migration

.changeset/many-shrimps-float.md, packages/bezier-react/src/components/TextField/TextField.module.scss
- Fixes #2015
feat(text-field): update background color of secondary varient
피그마와 동일한 색상으로 업데이트합니다.
No
=> feat(text-field): update background color of secondary varient

packages/bezier-react/package.json, supports/eslint-config-bezier/package.json, yarn.lock
- Close #1832
#1832 에 더해 Breaking change가 없는 lint package들을 업데이트합니다.
=> fix(deps): update style

.changeset/fluffy-comics-grin.md, packages/bezier-react/src/components/Modal/Modal.tsx
fix(modal): fix invalid aria-modal value
`aria-modal` 의 값은 `"true"` 혹은 `"false"` 가 되어야합니다.
No
-https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-modal
=> fix(modal): fix invalid aria-modal value

.changeset/tricky-forks-marry.md, packages/bezier-react/src/components/Badge/Badge.module.scss
- Variant 를 enum 에서 string literal 로 바꾸면서 클래스네임이 달라지면서 생긴 Badge 의 스타일 버그를 수정합니다. variant 에 맞게 PascalCase 에서 kebab-case 로 변경합니다.
- 다른 컴포넌트들도 한번씩 확인했습니다. 
- 생략  
- No
- None
=> Change classname of `Badge` component for style issue

.changeset/soft-parents-work.md, packages/bezier-figma-plugin/src/plugin/index.ts
- None
- 피그마 플러그인에서 선택한 영역안에 있는 컴포넌트를 svg string로 추출할 때 에러 처리가 되어 있지 않았습니다. 
- svg 추출이 안되는 컴포넌트가 있다면 Promise.all 의 특성상 모든 promise 의 resolve 값이 무시되어서 아이콘 추출에 실패하게 됩니다. 에러가 있을 때 undefined 를 resolve 하도록 하되, github rest API에 담아보낼 svgByName json 객체를 만들 때는 포함하지 않도록 합니다. 이렇게 하면 svg 추출에 실패한 경우를 무시하고 성공한 경우만 담아서 보내게 됩니다. 
- No
- [Promise.all vs Promise.allSettled](https://inpa.tistory.com/entry/JS-%F0%9F%93%9A-%EB%8D%94%EC%9D%B4%EC%83%81-Promiseall-%EC%93%B0%EC%A7%80%EB%A7%90%EA%B3%A0-PromiseallSettled-%EC%82%AC%EC%9A%A9%ED%95%98%EC%9E%90)
=> Add error catch logic on figma plugin

packages/bezier-react/src/components/LegacyStack/LegacyStack.mdx
Add deprecation warning to LegacyStack storybook docs
스토리북 문서에 사용 금지 경고 문구를 추가합니다.
No
- https://storybook.js.org/docs/writing-docs/mdx#linking-to-other-stories-and-pages
=> docs(legacy-stack): add deprecation warning

packages/bezier-react/tsconfig.build.json
2ff4dd1c29c5fd701174c01b6571bf8f545a2679 커밋만 봐주시면 됩니다.
bezier-react의 타입 빌드 설정을 개선합니다.
`include` 옵션에 필요한 엔트리 포인트 파일만을 지정해서, 접근 가능한 코드가 아니라면 타입 선언을 생성하지 않도록 했습니다. 불필요해진 `exclude` 옵션을 제거합니다.
No
=> build(bezier-react): improve type build settings

README.md, packages/bezier-vscode/package.json
- None
- bezier-vscode 는 vsce 라는 툴로 publish 하기 때문에 npm registry 에 등록될 필요가 없습니다. 따라서 private 속성을 true 로 합니다. 
- README 에 bezier-vscode 를 추가합니다. 
- No 
- https://code.visualstudio.com/api/working-with-extensions/publishing-extension#publishing-extensions
=> Set `private` true in bezier-vscode package.jon

.stylelintignore, package.json, yarn.lock
rm unnecessary stylelintignore & upgrade stylelint
생략
=> chore(deps): rm unnecessary stylelintignore & upgrade stylelint

packages/bezier-vscode/package.json
- #774 
- extension 을 출판하기 위해 필요한 필드를 추가합니다. 
- 생략 
- No
- https://code.visualstudio.com/api/working-with-extensions/publishing-extension#create-a-publisher
=> Add publisher name to `bezier-vscode` package.json

packages/bezier-react/.storybook/preview.tsx, packages/bezier-react/src/stories/alpha-color.mdx, packages/bezier-react/src/stories/alpha-shadow.mdx, packages/bezier-react/src/stories/color.mdx
- Closes #2076
문서화를 위해 알파 버전의 Color, Shadow 토큰에 대한 스토리북을 작성합니다.
- dcd4a7cf8ecb1d055983dfc5bc8c2b548c933f2c 커밋부터
- 디자인은 피그마를 참고하여 임의로 구현했습니다. 현재 작업이 어느정도 완료된 거로 보이는 Color, Shadow 토큰만 우선으로 작업했습니다.
- 스토리북에서 Alpha-foundation 하위에 보이도록 했고, 해당 카테고리가 상위에 보이도록 설정을 조절했습니다.
No
=> Add documentation about alpha version color & shadow design tokens

.changeset/cyan-steaks-fail.md, packages/bezier-tokens/src/alpha/functional/dark-theme/color.json, packages/bezier-tokens/src/alpha/functional/light-theme/color.json, packages/bezier-tokens/src/alpha/semantic/color.json
- #2125 
- 피그마 디자인의 변경사항을 반영합니다. 
- functional/fg/*/darkest 삭제
- semantic/fg/*/darkest -> semantic/fg/*/black
- 생략
- No
- [figma](https://www.figma.com/file/LIxRAsKKyGx3fdgvm2knL9/%F0%9F%93%8C-Foundation?type=design&node-id=39348-25854&mode=design&t=42bYtvFe4RUOtj0J-4) (internal link)
=> Reflect figma design change in alpha design tokens

packages/bezier-vscode/CHANGELOG.md
- None
- #2153 에서 버전이 롤백되었기 때문에 #2091 이 changelog 에 들어가있지 않습니다. 이것을 직접 추가합니다. 
- 생략
- No
- https://github.com/channel-io/bezier-react/pull/2153#discussion_r1560699591
=> Add first commit of `bezier-vscode` to changelog.md

.changeset/many-icons-look.md, packages/bezier-tokens/src/alpha/global/color.json
Fix value of color.cobalt.300
생략
No
- [채널톡](https://desk.channel.io/root/threads/groups/(CT)BezierRedesign-244958/661ce512d034ebfe3a26/661ce512d034ebfe3a26)
=> fix(alpha/color): fix value of color.cobalt.300

README.md
- #2164 
- Codecov 리포트를 테스트하기 위한 pr 입니다.
=> codecov test PR

.github/workflows/ci.yml
- None
- pr이 머지되서 메인 브랜치에 푸쉬되면 CI가 트리거 되도록 합니다. 
- main branch push 이벤트를 추가합니다. 
- No
- https://github.com/yangwooseong/bezier-react/actions/runs/8827598462
=> Add push event on main branch to CI config

packages/bezier-react/src/components/Button/Button.stories.tsx, packages/bezier-react/src/components/LegacyStack/LegacyStack.stories.tsx
- https://github.com/channel-io/bezier-react/issues/1000
- 시각회귀테스트가 잘 동작하려면 스토리북에서 랜덤한 이미지나 값을 사용하지 않아야 합니다. 고정된 값을 사용하는 것으로 변경합니다. 
- 생략
- No
- None
=> Remove random value in storybook 

.github/workflows/release.yml
- Fixes https://github.com/channel-io/bezier-react/issues/2189 
- 이슈를 참조해주세요
- 이슈를 참조해주세요.
- 레토 설정에서 `CHANGESET_TOKEN` 시크릿을 추가했습니다.
- No
- None
=> use PAT(Personal Access Token) for CI trigger of changeset PR

.github/workflows/chromatic.yml
- changeset PR에서 CI가 잘 작동하도록 PAT를 활용했는데, 사이드 이펙트로 불필요하게 크로마틱이 돌기 시작해서 이를 수정합니다. Codecov나 Codeql 등은 사용량 제한이 없기 때문에 그대로 두어도 괜찮을 것 같습니다.
- actor 에 github-actions[bot] 필터를 추가합니다. 
- No
- https://github.com/channel-io/bezier-react/pull/2188
=> Do not trigger chromatic with changeset pr

.github/workflows/generate-icon-files.yml, .github/workflows/release.yml
- None
- https://github.com/channel-io/bezier-react/pull/2202 에서 CI가 돌지 않는 이슈를 해결합니다. 
- 어떤 워크플로우에서 `${{ secrets.GITHUB_TOKEN }}` 을 사용하면 다른 워크플로우를 트리거 하지 않기 때문에 personal access token 을 임의로 만들어서 대체합니다. (https://github.com/channel-io/bezier-react/pull/2190 와 동일한 문제입니다.)
- `PERSONAL_ACCESS_TOKEN` 을 레포 시크릿으로 만들고 이전에 만들었던 `CHANGESET_TOKEN` 까지 이걸로 대체합니다.
- No
- https://github.com/orgs/community/discussions/25702
- https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
=> Fix CI not triggering in icon update PR

.github/workflows/generate-icon-files.yml, .github/workflows/release.yml
- None
- checkout action 에서 있었던 오타를 수정합니다.
- https://github.com/channel-io/bezier-react/actions?query=workflow%3ARelease++ 을 보면 changeset pr이 올라가야 하는데 Release 가 돌지 않아서 올라가지 않은 pr (#2193) 이 하나 있습니다. 이거는 추후에 changeset pr 이 생성되면 디스크립션을 수정해서 pr 을 넣어야할 것 같네요..
- None
- https://github.com/actions/checkout?tab=readme-ov-file#usage
=> Fix typo with token setting in checkout action

.changeset/happy-pears-tan.md, packages/bezier-tokens/src/alpha/functional/dark-theme/color.json, packages/bezier-tokens/src/alpha/functional/light-theme/color.json
Add missing `fg-{color}-dark` alpha version tokens
생략
No
=> feat(bezier-tokens): add missing `fg-{color}-dark` alpha version tokens

.github/workflows/chromatic.yml
- None
- autoAcceptChanges 옵션을 true 로 둬서 chromatic UI test 에 의해 checks가 pending 으로 되는 것을 막습니다.
- 테스트 pr: https://github.com/yangwooseong/bezier-react/pull/150
- autoAcceptChanges: true 로 changes를 항상 승인해서 checks 가 통과되게 되지만 checks 에서 visual test나 UI review 가 안보이게 되는 단점은 있습니다. 다만 커멘트로 나오는 chromatic build 링크를 타고 들어가면 승인된 visual test 를 확인할 수 있어서 괜찮을 것 같기도 합니다. 
- No
- https://www.chromatic.com/docs/cli/#configuration-options
=> Set `autoAcceptChanges` true in chromatic

.github/workflows/generate-icon-files.yml
- None
- icon update workflow가 제대로 돌지 않는 것을 수정합니다. 
- 테스트 PR: https://github.com/channel-io/bezier-react/pull/2211
- `GITHUB_TOKEN`을 사용하는 워크플로우에 의해 트리거 되는 이벤트는 다른 워크플로우를 트리거하지 못합니다. 그래서 아이콘 pr 에서 CI 가 돌지 않았고, CI가 돌지 않는 문제를 수정하려고 `GITHUB_TOKEN` 을 쓰는 곳을 지우고 `PERSONAL_ACCESS_TOKEN` 을 제 계정에서 만들고 레포 시크릿에 추가한 뒤 이를 사용했습니다. 이렇게 하니 CI는 잘 돌지만, icons.json 을 만들때 뿐만아니라 지울때 역시 Generate Icon Files 워크플로우가 도는 문제가 생겼습니다 (아마 이런 재귀적인 실행을 막으려고 `GITHUB_TOKEN`을 사용할 때 다른 워크플로우가 돌지 않게 막아놓은 것이 아닌가 싶습니다). 그래서 icons.json 파일이 있는지 확인하는 잡을 하나 더 추가해서, 없다면 Generate Icon Files 워크플로우가 실행되지 않도록 했습니다. 
- 별도로 잡을 추가하지 않고 이벤트를 `pull_request` - `opened` 로 하는 방법도 시도했으나, 그렇게 하면 checkout 을 할 떄 merge commit 에 체크아웃을 해버리는 문제가 생겨서 적용하지 않았습니다 …
=> Fix icon update workflow not triggering

.changeset/brown-schools-tap.md, packages/bezier-figma-plugin/tsconfig.json
-  None
- 피그마 플러그인을 개발 모드로 실행할 때 unexpected token 에러가 떠서 실행이 안되고 있는 상태입니다. tsconfig를 @channel.io/shared-configs 를 사용하는 과정에서 설정에 변경이 있었어서 https://www.figma.com/plugin-docs/libraries-and-bundling/ 를 참고해서 target: es6를 추가합니다. 
- 생략
- No
- None
=> Fix type error of figma plugin in development mode

.github/workflows/chromatic.yml
- https://github.com/channel-io/bezier-react/issues/2246 와 관련있어보입니다. 
- main branch 푸쉬할 떄 크로마틱 빌드가 되지 않고 있습니다. https://github.com/channel-io/bezier-react/pull/2198 에서 잘못 삭제된 push 트리거를 되살립니다. 
- None
- No
- None
=> Add push trigger on main for chromatic

package.json, packages/bezier-react/src/components/AlphaAvatar/Avatar.tsx, packages/bezier-react/src/components/AlphaAvatar/AvatarSizeContext.ts, packages/bezier-react/src/components/AlphaAvatarGroup/AvatarGroup.tsx, packages/bezier-react/src/components/AlphaAvatarGroup/AvatarGroup.types.ts, packages/bezier-react/src/components/AlphaButton/Button.module.scss, packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.module.scss, packages/bezier-react/src/components/AlphaFloatingIconButton/FloatingIconButton.module.scss, packages/bezier-react/src/components/AlphaIconButton/IconButton.module.scss
- Resolves #2249 
- build 했을 때 나오는 css warning과 circular dependency warning을 제거합니다.
- 순환 참조를 해결하기 위해 AvatarGroup에 있는 컨텍스트를 Avatar로 이동해서 Avatar -> AvatarGroup으로의 참조를 끊었습니다. 
- No
- None
=> Remove build warning

.vscode/settings.json
- eslint에만 validate & autofix 가 적용되어 있어서 stylelint도 추가했습니다.
- 생략
- No 
- None
=> Support stylelint validate and autofix

yarn.lock
This reverts commit 46276b83b766d15ba3cda4a1facec0160578e603.
- turborepo를 버전업 한 이후로 yarn script 를 실행할 때마다 빈 파일이 생기고 있어서 버전업을 리버트 합니다. 
- 생략
- No
- https://github.com/vercel/turbo/issues/7671
=> Revert "chore(deps): update dependency turbo to v1.13.4 (#2288)"

.changeset/perfect-laws-melt.md, packages/bezier-react/src/components/Select/Select.tsx, packages/bezier-react/src/components/Select/Select.types.ts
Fixes #2322 
`Select` 컴포넌트에 `OverlayProps`인 `keepInContainer` prop을 받도록 합니다.
- No
=> Add `dropdownKeepInContainer` prop in `<Select />`

.changeset/pretty-balloons-visit.md, packages/bezier-react/src/components/TextField/TextField.module.scss, packages/bezier-react/src/components/TextField/TextField.test.tsx, packages/bezier-react/src/components/TextField/TextField.tsx
Fixes #2267 
In TextField Component, focus on the clear button when tab key is pressed.
The style in scss is not applied in test code.
No
=> fix(TextField): focus on clear button when tab pressed

yarn.lock
- None
- yarn dedupe 명령어로 중복된 의존성을 제거합니다. 
- None
- No
- None
=> Dedupe dependency

.changeset/cold-clocks-rescue.md, packages/bezier-tokens/src/alpha/global/color.json
- alpha 토큰의 토큰값을 변경합니다. 
- 생략 
- No
- [디자인 스펙](https://desk.channel.io/root/groups/v2BezierRelease-364583/6697d1bb340525b9b57d)
=> Change alpha token `global/green/300`

packages/bezier-react/.storybook/main.ts, packages/bezier-react/package.json, packages/bezier-react/src/components/AlphaAvatar/AlphaAvatar.stories.tsx, packages/bezier-react/src/components/AlphaAvatarGroup/AlphaAvatarGroup.stories.tsx, packages/bezier-react/src/components/AlphaButton/AlphaButton.stories.tsx, packages/bezier-react/src/components/AlphaFloatingButton/AlphaFloatingButton.stories.tsx, packages/bezier-react/src/components/AlphaFloatingIconButton/AlphaFloatingIconButton.stories.tsx, packages/bezier-react/src/components/AlphaLoader/AlphaLoader.stories.tsx, packages/bezier-react/src/components/AlphaToggleButton/AlphaToggleButton.stories.tsx, packages/bezier-react/src/components/AlphaToggleButtonGroup/AlphaToggleButtonGroup.stories.tsx, yarn.lock
- Fixes #2317 
- V2 컴포넌트 피그마 파일은 V1와 달리 컴포넌트마다 분리되어 있어서 한번에 찾기 어려운 불편함이 있었습니다. 스토리북에서 링크가 있으면 편할 것 같아서 넣어봤습니다.
- 생략
- No
=> Add storybook design addon

.github/workflows/chromatic.yml
- resolves #2275
- bezier-tokens 가 바뀔 때 크로마틱을 실행해서 달라진 점을 확인할 수 있도록 합니다. 
- 크로마틱 사용량을 보면 6,7월 기준으로 4000 snapshot 정도이고, 토큰이 바뀔 때는 대부분 turbosnap으로 되서 20%로 계산되기 때문에 괜찮지 않을까 합니다.
추가) bezier-icons까지 paths 추가합니다. 아이콘 업데이트가 있을 때 크로마틱이 돌지 않아서 업데이트 이후 올라오는 PR의 visual diff에 아이콘이 잡히는 현상이 있어서 추가하는 게 좋을 것 같습니다.
참고) https://www.chromatic.com/review?appId=62bead1508281287d3c94d25&number=2387&type=linked)
- 생략 
- No
- https://www.chromatic.com/billing?accountId=65fd0a9579d4f3f850e2c4c4
=> Trigger chromatic action with changes in bezier-tokens

renovate.json
- None
- renovate 주기를 1달 단위로 조정합니다. 
- 파싱이 잘 되는지 안되는지 로컬에서 테스트하기가 어려워서, 이렇게 해보고 다음주 월요일에 잘 되는지 봐야할 것 같습니다. [@breejs/later](https://breejs.github.io/later/parsers.html#text) 파싱 로직에 **대부분** 의존한다고 하는데, 막상 매주 월요일로 잘 설정된 현재 값을 넣고 파싱하면 에러를 뱉습니다. 잘 안되면 cron syntax로 해야할 것 같네요. 
- No
- https://docs.renovatebot.com/configuration-options/#schedule
=> Set renovate schedule to monthly

renovate.json
- https://github.com/channel-io/bezier-react/issues/1217
- renovate schedule에서 minute을 * 으로 변경합니다. 
- 위 이슈에서 `Invalid schedule: "0 10-19 1-7 * MON" has cron syntax, but doesn't have * as minutes` 에러를 뱉고 있습니다. 
소스를 뒤져보면 
```tsx
if (
parsedCron.fields.minute.length !== 60 ||
scheduleText.indexOf(minutesChar) !== 0 // (const minutesChar = "*")
) {
message = `Invalid schedule: "${scheduleText}" has cron syntax, but doesn't have * as minutes`;
return true;
}
```
cron syntax에서는 minute 이 * 이어야 하는 것 같습니다. 
- No
- https://github.com/renovatebot/renovate/blob/64b0555ce303f83a566765a0fa092a1ea4c22a48/lib/workers/repository/update/branch/schedule.ts#L61-L67
=> Set minute to wildcard in renovate schedule

packages/bezier-react/src/components/Banner/Banner.stories.tsx, packages/bezier-react/src/components/Icon/Icon.stories.tsx
- None
- 더이상 사용되지 않는 아이콘을 대체합니다. 
- 생략
- No
- [스레드(internal)](https://desk.channel.io/root/threads/groups/(CT)BezierRedesign-244958/66badf423c3f6d27e23f/66badf423c3f6d27e23f)
=> Replace deprecated icon

.changeset/olive-flowers-pump.md, .changeset/sour-planets-burn.md, packages/bezier-react/src/components/AlphaButton/Button.module.scss, packages/bezier-react/src/components/AlphaIconButton/IconButton.module.scss, packages/bezier-tokens/src/alpha/functional/dark-theme/color.json, packages/bezier-tokens/src/alpha/functional/light-theme/color.json
- 없음
- bg/absolute/white,black/transparent 토큰을 추가합니다. 
- bg/white/white-alpha/transparent 다크테마값을 white/0에서 black/0로 수정합니다. 
- Alpha(Icon)Button 의 tertiary 배경색을 수정합니다. 
- 생략  
- No
- [스레드(internal)](https://desk.channel.io/root/groups/v2BezierRelease-364583/6715ed6a8c9efb2632fe)
- [피그마(internal)](https://www.figma.com/design/8J76noM3T1Sp5cNPhnYQiG/Action?node-id=0-1&t=GPYPLyyOBg3Oml6g-1)
=> Add absolute transparent tokens, modify AlphaButton bg color

.github/ISSUE_TEMPLATE/rfc.yml
RFC 문서에 대한 깃허브 이슈 템플릿을 작성합니다.
주로 새로운 디자인 시스템 컴포넌트 구현 전에 문서를 작성하고 공유하기 위해 활용할 계획입니다.
아래와 같은 목차로 구성했습니다. 굵게 표시된 항목은 필수 항목입니다. 컴포넌트 외에도 사용되길 기대하고 작성했습니다.
1. **요약**
2. **목표와 요구사항**
3. **설계 상세**: 컴포넌트의 경우 API와 속성의 기본값 등을 상세히 설명하길 기대합니다.
4. **사용례**: 사용처에서 어떤 방식으로 사용되는지 설명
5. 접근성: 어떤 접근성 요구사항들을 고려했으며, 어떻게 준수했는지
6. 대안: 고려한 다른 방안이 있다면 어떤 것들이 있는지
7. 테스트 계획: 테스트가 필요하다면 테스트의 진행 방식 (단위 테스트, 스냅샷 테스트 등)
8. 레퍼런스: 피그마, 참고 문서 링크 등
No
=> Add an RFC documentation template

.changeset/few-cars-explain.md, packages/bezier-tokens/src/alpha/functional/dark-theme/color.json, packages/bezier-tokens/src/alpha/functional/light-theme/color.json
- 토큰 이름을 변경합니다. 
- Yes
- [스레드 (internal)](https://desk.channel.io/root/groups/v2BezierRelease-364583/67203d26cd0c3abcf715)
=> Rename `bg-*-shade-light` to `bg-*-shade-lighter`

.github/workflows/code-connect.yml, package.json, packages/bezier-react/figma.config.json, packages/bezier-react/jest.config.js, packages/bezier-react/package.json, packages/bezier-react/src/components/AlphaButton/Button.figma.tsx, packages/bezier-react/src/components/AlphaFloatingButton/FloatingButton.figma.tsx, packages/bezier-react/src/components/AlphaFloatingIconButton/FloatingIconButton.figma.tsx, packages/bezier-react/src/components/AlphaIconButton/IconButton.figma.tsx, yarn.lock
- Fixes #2268 
Figma Code Connect를 도입/검증합니다. 
- figma code connect cli를 사용하여 설정 파일과 AlphaButton 컴포넌트 군을 code connect 합니다.
- code connect 파일이 변경된 커밋이 main 브랜치에 푸시되었을 경우 퍼블리시를 트리거하는 GitHub Action을 추가합니다. (토큰 환경변수로 추가함)
- 릴리즈 시점에 퍼블리시 워크플로우를 트리거하여야 불일치가 발생하지 않겠으나, 불일치가 문제가 될 케이스가 많지 않을 것이며 테스트 용이성을 고려해봤을 때 이 편이 좋겠다고 판단했습니다.
- 피그마 내의 GitHub 링크가 제 fork repository로 이동하는 문제가 있습니다. 제 PAT를 사용해서 그런건지, remote origin(fork repository)을 바라보는 건지 모르겠어서 CI 트리거된 이후 체크해봐야할 거 같습니다.
- Icon의 경우 제대로 보이지 않는데, [아이콘별 Code Connect를 만드는 별도 처리](https://github.com/figma/code-connect/blob/main/docs/react.md#icons)가 필요합니다. 이는 추후에 별도 이슈로 다룹니다.
No
- https://github.com/figma/code-connect/blob/main/docs/react.md
=> Figma Code Connect PoC

.github/workflows/code-connect.yml
없음
Code Connect CI가 잘 동작하도록 수정합니다.
- 누락된 checkout 과정을 추가하여 파일에 접근할 수 있도록 수정
- yarn 인스톨 과정 추가. 처음엔 전체 yarn 의존성 설치 과정 없이 bezier-react로 `cd` 후 npx를 사용하여 개별 패키지만 설치&실행해보려고 했으나, 테스트 시 로컬에 패키지가 설치되지 않은 상태에선 실행이 안되어 불가피하게 전체 의존성 설치 과정을 추가했습니다
No
=> ci(code-connect): fix to work

packages/stylelint-bezier/README.md
- None
- `stylelint-bezier` 패키지에 version matchup 을 추가합니다. `bezier-tokens@0.2.10`에서 토큰 이름이 바뀌는 breaking change가 있었습니다.  `bezier-tokens@0.2.10`를 처음으로 사용하는 `stylelint-bezier@0.2.4`와 `bezier-react@2.3.3`을 테이블에 추가했습니다. 
- None
- no
- https://github.com/channel-io/bezier-react/releases
=> Add version matchup to `stylelint-bezier`

.changeset/clever-humans-hang.md, packages/bezier-react/src/components/LegacyIcon/utils.ts
- Fixes #2493
레거시 아이콘을 지원하는 컴포넌트들의 렌더링 성능을 개선합니다.
- `isIconName` 이 포함된 모듈이 처음 평가되는 시점에 한번만 아이콘 이름 객체를 생성합니다.
- `Set` 을 사용하여 빠르게 탐색할 수 있도록 합니다.
No
=> perf(legacy-icon): create the iconNames object only when the module is first evaluated

.changeset/fair-timers-jog.md, packages/bezier-vscode/src/server.ts
- None
- bezier-vscode 0.2.0 으로 설치했을 때 자동완성이 안되는 버그를 수정합니다. 
- 개발 모드에서 실행했을 때 자동완성을 보여줄 때 아래 에러가 떴었습니다. 동작에 문제는 없어서 그대로 배포했으나 배포 환경에서는 자동완성이 안되서 아래 에러와 관련이 있으리라 생각됩니다. 
- 추측하건대 resolveProvider: true 로 해놓고 connection.onCompletionResolve 핸들러를 붙이지 않아서 뜨는 에러 같습니다. onCompletionResolve 는 completion 을 완성했을 때 세부 정보를 붙이는 핸들러라 불필요하다고 판단해서 resolveProvider 자체를 지웠습니다. 
- resolveProvider: true 를 넣은 것은 resolveProvider: true 로 해야 자동완성 기능을 지원하는 줄 알았는데 다시 테스트 해보니 completionProvider 가 not null 이면 지원을 하나 봅니다.
- No
- https://github.com/microsoft/vscode-extension-samples/blob/727cb7ea42a9258e58b3b919efd8c725a6f8f1e4/lsp-sample/server/src/server.ts#L233-L246
=> Fix `bezier-vscode` bug

.github/workflows/code-connect.yml
Bind the Figma access token to an environment variable
Code Connect CI 정상화를 위해 시크릿을 잡의 환경 변수에 바인딩합니다.
No
- https://docs.github.com/ko/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow
=> Bind the Figma access token to an environment variable

.changeset/odd-bags-unite.md, packages/bezier-tokens/src/alpha/functional/dark-theme/color.json, packages/bezier-tokens/src/alpha/functional/light-theme/color.json
- None
- `color-fg(bg)-grey-grey-alpha-*` 토큰을 `color-fg(bg)-grey-alpha-*` 으로 변경합니다. 
- 누락된 `color-fg-grey-darkest` 토큰을 추가합니다. 
- 생략 
- Yes, bezier-stylelint 버전 업과 동시에 적용되어야 합니다. 
- [스레드](https://desk.channel.io/root/groups/v2BezierRelease-364583/6735b3e076a4b1c18516)
=> Rename `color-fg-grey-grey-alpha-*` tokens

packages/bezier-vscode/package.json
https://github.com/channel-io/bezier-react/actions/runs/12310900865/job/34360202023
```bash
Error: @types/vscode ^1.96.0 greater than engines.vscode ^1.75.0. Consider upgrade engines.vscode or use an older @types/vscode version
Error: Process completed with exit code 1.
```
위 에러를 수정합니다.
상위 버전 명시
No
- https://code.visualstudio.com/api/working-with-extensions/publishing-extension#visual-studio-code-compatibility
=> fix(vscode): update vscode engine version to 1.96.0

.github/workflows/release.yml, package.json
- resolves #2572 
- bezier vscode 익스텐션 배포를 changeset PR이 머지될 때 수행하도록 합니다. 
- changesets액션은 changeset이 있다면 changeset PR을 만들고, 없다면 publish 옵션으로 준 yarn release 커맨드를 실행합니다. yarn release 커맨드 시점에 익스텐션 배포까지 넣어버리는게 좋을 것 같아서 이렇게 했습니다. 
- No
- None
=> Integrate bezier-vscode publish to changeset publish

.changeset/icon-update-1740117935671.md, packages/bezier-icons/icons/bounce.svg, packages/bezier-icons/icons/one-way.svg
- 2 icon(s) added
| Name | Status |
|--|--|
| bounce.svg | 🆕 |
| one-way.svg | 🆕 |
=> Icon update PR made by bezier-asset main

packages/bezier-react/src/components/Toast/Toast.test.tsx
- resolves https://github.com/channel-io/bezier-react/issues/2624
- Toast 테스트 코드 실행시 뜨는 "not wrapped in act(...)" 워닝을 해결합니다. 
- [이슈](https://github.com/channel-io/bezier-react/issues/2624)를 참고해주세요. 
- No
- https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#wrapping-things-in-act-unnecessarily
- https://github.com/channel-io/bezier-react/actions/runs/14612928065/job/40994513998#step:9:611
=> Resolves "not wrapped in act(...)" warning in `Toast` component test

packages/bezier-react/src/components/TextArea/TextArea.test.tsx, packages/bezier-react/src/components/TextField/TextField.test.tsx, packages/bezier-react/src/components/Toast/useToastContextValues.test.tsx
- None
- 테스트 코드에서 불필요하게 사용하고 있는 act 랩핑을 제거합니다.
- 상태 변화가 일어나지 않는 코드에서 `act` 사용을 제거합니다. 
- `waitFor` 함수로 대체합니다. 
- `getByTestId` 를 `getByRole` 로 변경합니다. 
- None
- https://testing-library.com/docs/queries/about#priority
=> Remove unnecessary `act` wrapping in test code

.changeset/wet-swans-report.md, packages/bezier-tokens/src/alpha/functional/dark-theme/color.json, packages/bezier-tokens/src/alpha/global/color.json
변경된 요구사항에 맞게 알파 컬러 토큰을 업데이트합니다
생략
NO
=> Update Alpha Color Tokens

yarn.lock
- None
- 685MB -> 525MB 로 줄어들었습니다. (-24%)
- 생략 
- No
=> chore(deps): yarn dedupe
